//=========================================================
//File name    : csr_ctrl_agent_agent_monitor.sv
//Author       : OpenAI_Codex
//Module name  : csr_ctrl_agent_agent_monitor
//Discribution : csr_ctrl_agent_agent_monitor : monitor
//Date         : 2026-04-12
//=========================================================
`ifndef CSR_CTRL_AGENT_AGENT_MONITOR__SV
`define CSR_CTRL_AGENT_AGENT_MONITOR__SV

class csr_ctrl_agent_agent_monitor  extends tcnt_monitor_base#(virtual csr_ctrl_agent_agent_interface,csr_ctrl_agent_agent_cfg,csr_ctrl_agent_agent_xaction);

    `uvm_component_utils(csr_ctrl_agent_agent_monitor)

    extern function new(string name, uvm_component parent);
    extern virtual function void build_phase(uvm_phase phase);
    extern task run_phase(uvm_phase phase);
    extern task mon_data();
endclass:csr_ctrl_agent_agent_monitor

function csr_ctrl_agent_agent_monitor::new(string name, uvm_component parent);
    super.new(name,parent);
endfunction:new

function void csr_ctrl_agent_agent_monitor::build_phase(uvm_phase phase);
    super.build_phase(phase);
endfunction:build_phase

task csr_ctrl_agent_agent_monitor::run_phase(uvm_phase phase);
    super.run_phase(phase);
    this.mon_data();
endtask:run_phase

task csr_ctrl_agent_agent_monitor::mon_data();

    logic [3:0] io_ooo_to_mem_tlbCsr_satp_mode;
    logic [15:0] io_ooo_to_mem_tlbCsr_satp_asid;
    logic [43:0] io_ooo_to_mem_tlbCsr_satp_ppn;
    logic io_ooo_to_mem_tlbCsr_satp_changed;
    logic [3:0] io_ooo_to_mem_tlbCsr_vsatp_mode;
    logic [15:0] io_ooo_to_mem_tlbCsr_vsatp_asid;
    logic [43:0] io_ooo_to_mem_tlbCsr_vsatp_ppn;
    logic io_ooo_to_mem_tlbCsr_vsatp_changed;
    logic [3:0] io_ooo_to_mem_tlbCsr_hgatp_mode;
    logic [15:0] io_ooo_to_mem_tlbCsr_hgatp_vmid;
    logic [43:0] io_ooo_to_mem_tlbCsr_hgatp_ppn;
    logic io_ooo_to_mem_tlbCsr_hgatp_changed;
    logic io_ooo_to_mem_tlbCsr_mbmc_BME;
    logic io_ooo_to_mem_tlbCsr_mbmc_CMODE;
    logic io_ooo_to_mem_tlbCsr_mbmc_BCLEAR;
    logic [57:0] io_ooo_to_mem_tlbCsr_mbmc_BMA;
    logic io_ooo_to_mem_tlbCsr_priv_mxr;
    logic io_ooo_to_mem_tlbCsr_priv_sum;
    logic io_ooo_to_mem_tlbCsr_priv_vmxr;
    logic io_ooo_to_mem_tlbCsr_priv_vsum;
    logic io_ooo_to_mem_tlbCsr_priv_virt;
    logic io_ooo_to_mem_tlbCsr_priv_virt_changed;
    logic io_ooo_to_mem_tlbCsr_priv_spvp;
    logic [1:0] io_ooo_to_mem_tlbCsr_priv_imode;
    logic [1:0] io_ooo_to_mem_tlbCsr_priv_dmode;
    logic io_ooo_to_mem_tlbCsr_mPBMTE  ;
    logic io_ooo_to_mem_tlbCsr_hPBMTE  ;
    logic [1:0] io_ooo_to_mem_tlbCsr_pmm_mseccfg;
    logic [1:0] io_ooo_to_mem_tlbCsr_pmm_menvcfg;
    logic [1:0] io_ooo_to_mem_tlbCsr_pmm_henvcfg;
    logic [1:0] io_ooo_to_mem_tlbCsr_pmm_hstatus;
    logic [1:0] io_ooo_to_mem_tlbCsr_pmm_senvcfg;
    logic io_ooo_to_mem_csrCtrl_pf_ctrl_l1I_pf_enable;
    logic io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_enable;
    logic io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_enable;
    logic io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_train_on_hit;
    logic io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_enable_agt;
    logic io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_enable_pht;
    logic [3:0] io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_active_threshold;
    logic [5:0] io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_active_stride;
    logic io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_enable_stride;
    logic io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_store_only;
    logic io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_recv_enable;
    logic io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_pbop_enable;
    logic io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_vbop_enable;
    logic io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_tp_enable;
    logic [9:0] io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_delay_latency;
    logic io_ooo_to_mem_csrCtrl_bp_ctrl_ubtbEnable;
    logic io_ooo_to_mem_csrCtrl_bp_ctrl_abtbEnable;
    logic io_ooo_to_mem_csrCtrl_bp_ctrl_mbtbEnable;
    logic io_ooo_to_mem_csrCtrl_bp_ctrl_tageEnable;
    logic io_ooo_to_mem_csrCtrl_bp_ctrl_scEnable;
    logic io_ooo_to_mem_csrCtrl_bp_ctrl_ittageEnable;
    logic [21:0] io_ooo_to_mem_csrCtrl_sbuffer_timeout;
    logic io_ooo_to_mem_csrCtrl_ldld_vio_check_enable;
    logic io_ooo_to_mem_csrCtrl_cache_error_enable;
    logic io_ooo_to_mem_csrCtrl_uncache_write_outstanding_enable;
    logic io_ooo_to_mem_csrCtrl_power_down_enable;
    logic io_ooo_to_mem_csrCtrl_flush_l2_enable;
    logic io_ooo_to_mem_csrCtrl_distribute_csr_w_valid;
    logic [11:0] io_ooo_to_mem_csrCtrl_distribute_csr_w_bits_addr;
    logic [63:0] io_ooo_to_mem_csrCtrl_distribute_csr_w_bits_data;
    logic io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_valid;
    logic [1:0] io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_addr;
    logic [1:0] io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_matchType;
    logic io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_select;
    logic io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_timing;
    logic [3:0] io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_action;
    logic io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_chain;
    logic io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_execute;
    logic io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_store;
    logic io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_load;
    logic [63:0] io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_tdata2;
    logic io_ooo_to_mem_csrCtrl_frontend_trigger_tEnableVec_0;
    logic io_ooo_to_mem_csrCtrl_frontend_trigger_tEnableVec_1;
    logic io_ooo_to_mem_csrCtrl_frontend_trigger_tEnableVec_2;
    logic io_ooo_to_mem_csrCtrl_frontend_trigger_tEnableVec_3;
    logic io_ooo_to_mem_csrCtrl_frontend_trigger_triggerCanRaiseBpExp;
    logic io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_valid;
    logic [1:0] io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_addr;
    logic [1:0] io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_matchType;
    logic io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_select;
    logic io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_timing;
    logic [3:0] io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_action;
    logic io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_chain;
    logic io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_store;
    logic io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_load;
    logic [63:0] io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_tdata2;
    logic io_ooo_to_mem_csrCtrl_mem_trigger_tEnableVec_0;
    logic io_ooo_to_mem_csrCtrl_mem_trigger_tEnableVec_1;
    logic io_ooo_to_mem_csrCtrl_mem_trigger_tEnableVec_2;
    logic io_ooo_to_mem_csrCtrl_mem_trigger_tEnableVec_3;
    logic io_ooo_to_mem_csrCtrl_mem_trigger_triggerCanRaiseBpExp;
    logic io_ooo_to_mem_csrCtrl_fsIsOff;

    csr_ctrl_agent_agent_xaction  mon_tr;
    memblock_sync_pkg::dispatch_raw_csr_t raw_csr;
    memblock_sync_pkg::dispatch_raw_csr_t last_raw_csr;
    bit has_last_raw_csr;
    bit last_capture_en;

    last_raw_csr = memblock_sync_pkg::make_empty_raw_csr();
    has_last_raw_csr = 1'b0;
    last_capture_en = 1'b0;
    while(1) begin
        @this.vif.mon_mp.mon_cb;
        io_ooo_to_mem_tlbCsr_satp_mode = this.vif.mon_mp.mon_cb.io_ooo_to_mem_tlbCsr_satp_mode;
        io_ooo_to_mem_tlbCsr_satp_asid = this.vif.mon_mp.mon_cb.io_ooo_to_mem_tlbCsr_satp_asid;
        io_ooo_to_mem_tlbCsr_satp_ppn = this.vif.mon_mp.mon_cb.io_ooo_to_mem_tlbCsr_satp_ppn;
        io_ooo_to_mem_tlbCsr_satp_changed = this.vif.mon_mp.mon_cb.io_ooo_to_mem_tlbCsr_satp_changed;
        io_ooo_to_mem_tlbCsr_vsatp_mode = this.vif.mon_mp.mon_cb.io_ooo_to_mem_tlbCsr_vsatp_mode;
        io_ooo_to_mem_tlbCsr_vsatp_asid = this.vif.mon_mp.mon_cb.io_ooo_to_mem_tlbCsr_vsatp_asid;
        io_ooo_to_mem_tlbCsr_vsatp_ppn = this.vif.mon_mp.mon_cb.io_ooo_to_mem_tlbCsr_vsatp_ppn;
        io_ooo_to_mem_tlbCsr_vsatp_changed = this.vif.mon_mp.mon_cb.io_ooo_to_mem_tlbCsr_vsatp_changed;
        io_ooo_to_mem_tlbCsr_hgatp_mode = this.vif.mon_mp.mon_cb.io_ooo_to_mem_tlbCsr_hgatp_mode;
        io_ooo_to_mem_tlbCsr_hgatp_vmid = this.vif.mon_mp.mon_cb.io_ooo_to_mem_tlbCsr_hgatp_vmid;
        io_ooo_to_mem_tlbCsr_hgatp_ppn = this.vif.mon_mp.mon_cb.io_ooo_to_mem_tlbCsr_hgatp_ppn;
        io_ooo_to_mem_tlbCsr_hgatp_changed = this.vif.mon_mp.mon_cb.io_ooo_to_mem_tlbCsr_hgatp_changed;
        io_ooo_to_mem_tlbCsr_mbmc_BME = this.vif.mon_mp.mon_cb.io_ooo_to_mem_tlbCsr_mbmc_BME;
        io_ooo_to_mem_tlbCsr_mbmc_CMODE = this.vif.mon_mp.mon_cb.io_ooo_to_mem_tlbCsr_mbmc_CMODE;
        io_ooo_to_mem_tlbCsr_mbmc_BCLEAR = this.vif.mon_mp.mon_cb.io_ooo_to_mem_tlbCsr_mbmc_BCLEAR;
        io_ooo_to_mem_tlbCsr_mbmc_BMA = this.vif.mon_mp.mon_cb.io_ooo_to_mem_tlbCsr_mbmc_BMA;
        io_ooo_to_mem_tlbCsr_priv_mxr = this.vif.mon_mp.mon_cb.io_ooo_to_mem_tlbCsr_priv_mxr;
        io_ooo_to_mem_tlbCsr_priv_sum = this.vif.mon_mp.mon_cb.io_ooo_to_mem_tlbCsr_priv_sum;
        io_ooo_to_mem_tlbCsr_priv_vmxr = this.vif.mon_mp.mon_cb.io_ooo_to_mem_tlbCsr_priv_vmxr;
        io_ooo_to_mem_tlbCsr_priv_vsum = this.vif.mon_mp.mon_cb.io_ooo_to_mem_tlbCsr_priv_vsum;
        io_ooo_to_mem_tlbCsr_priv_virt = this.vif.mon_mp.mon_cb.io_ooo_to_mem_tlbCsr_priv_virt;
        io_ooo_to_mem_tlbCsr_priv_virt_changed = this.vif.mon_mp.mon_cb.io_ooo_to_mem_tlbCsr_priv_virt_changed;
        io_ooo_to_mem_tlbCsr_priv_spvp = this.vif.mon_mp.mon_cb.io_ooo_to_mem_tlbCsr_priv_spvp;
        io_ooo_to_mem_tlbCsr_priv_imode = this.vif.mon_mp.mon_cb.io_ooo_to_mem_tlbCsr_priv_imode;
        io_ooo_to_mem_tlbCsr_priv_dmode = this.vif.mon_mp.mon_cb.io_ooo_to_mem_tlbCsr_priv_dmode;
        io_ooo_to_mem_tlbCsr_mPBMTE = this.vif.mon_mp.mon_cb.io_ooo_to_mem_tlbCsr_mPBMTE;
        io_ooo_to_mem_tlbCsr_hPBMTE = this.vif.mon_mp.mon_cb.io_ooo_to_mem_tlbCsr_hPBMTE;
        io_ooo_to_mem_tlbCsr_pmm_mseccfg = this.vif.mon_mp.mon_cb.io_ooo_to_mem_tlbCsr_pmm_mseccfg;
        io_ooo_to_mem_tlbCsr_pmm_menvcfg = this.vif.mon_mp.mon_cb.io_ooo_to_mem_tlbCsr_pmm_menvcfg;
        io_ooo_to_mem_tlbCsr_pmm_henvcfg = this.vif.mon_mp.mon_cb.io_ooo_to_mem_tlbCsr_pmm_henvcfg;
        io_ooo_to_mem_tlbCsr_pmm_hstatus = this.vif.mon_mp.mon_cb.io_ooo_to_mem_tlbCsr_pmm_hstatus;
        io_ooo_to_mem_tlbCsr_pmm_senvcfg = this.vif.mon_mp.mon_cb.io_ooo_to_mem_tlbCsr_pmm_senvcfg;
        io_ooo_to_mem_csrCtrl_pf_ctrl_l1I_pf_enable = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_pf_ctrl_l1I_pf_enable;
        io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_enable = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_enable;
        io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_enable = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_enable;
        io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_train_on_hit = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_train_on_hit;
        io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_enable_agt = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_enable_agt;
        io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_enable_pht = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_enable_pht;
        io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_active_threshold = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_active_threshold;
        io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_active_stride = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_active_stride;
        io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_enable_stride = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_enable_stride;
        io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_store_only = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_store_only;
        io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_recv_enable = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_recv_enable;
        io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_pbop_enable = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_pbop_enable;
        io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_vbop_enable = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_vbop_enable;
        io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_tp_enable = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_tp_enable;
        io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_delay_latency = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_delay_latency;
        io_ooo_to_mem_csrCtrl_bp_ctrl_ubtbEnable = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_bp_ctrl_ubtbEnable;
        io_ooo_to_mem_csrCtrl_bp_ctrl_abtbEnable = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_bp_ctrl_abtbEnable;
        io_ooo_to_mem_csrCtrl_bp_ctrl_mbtbEnable = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_bp_ctrl_mbtbEnable;
        io_ooo_to_mem_csrCtrl_bp_ctrl_tageEnable = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_bp_ctrl_tageEnable;
        io_ooo_to_mem_csrCtrl_bp_ctrl_scEnable = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_bp_ctrl_scEnable;
        io_ooo_to_mem_csrCtrl_bp_ctrl_ittageEnable = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_bp_ctrl_ittageEnable;
        io_ooo_to_mem_csrCtrl_sbuffer_timeout = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_sbuffer_timeout;
        io_ooo_to_mem_csrCtrl_ldld_vio_check_enable = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_ldld_vio_check_enable;
        io_ooo_to_mem_csrCtrl_cache_error_enable = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_cache_error_enable;
        io_ooo_to_mem_csrCtrl_uncache_write_outstanding_enable = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_uncache_write_outstanding_enable;
        io_ooo_to_mem_csrCtrl_power_down_enable = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_power_down_enable;
        io_ooo_to_mem_csrCtrl_flush_l2_enable = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_flush_l2_enable;
        io_ooo_to_mem_csrCtrl_distribute_csr_w_valid = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_distribute_csr_w_valid;
        io_ooo_to_mem_csrCtrl_distribute_csr_w_bits_addr = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_distribute_csr_w_bits_addr;
        io_ooo_to_mem_csrCtrl_distribute_csr_w_bits_data = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_distribute_csr_w_bits_data;
        io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_valid = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_valid;
        io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_addr = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_addr;
        io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_matchType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_matchType;
        io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_select = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_select;
        io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_timing = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_timing;
        io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_action = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_action;
        io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_chain = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_chain;
        io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_execute = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_execute;
        io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_store = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_store;
        io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_load = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_load;
        io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_tdata2 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_tdata2;
        io_ooo_to_mem_csrCtrl_frontend_trigger_tEnableVec_0 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_frontend_trigger_tEnableVec_0;
        io_ooo_to_mem_csrCtrl_frontend_trigger_tEnableVec_1 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_frontend_trigger_tEnableVec_1;
        io_ooo_to_mem_csrCtrl_frontend_trigger_tEnableVec_2 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_frontend_trigger_tEnableVec_2;
        io_ooo_to_mem_csrCtrl_frontend_trigger_tEnableVec_3 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_frontend_trigger_tEnableVec_3;
        io_ooo_to_mem_csrCtrl_frontend_trigger_triggerCanRaiseBpExp = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_frontend_trigger_triggerCanRaiseBpExp;
        io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_valid = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_valid;
        io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_addr = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_addr;
        io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_matchType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_matchType;
        io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_select = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_select;
        io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_timing = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_timing;
        io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_action = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_action;
        io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_chain = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_chain;
        io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_store = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_store;
        io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_load = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_load;
        io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_tdata2 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_tdata2;
        io_ooo_to_mem_csrCtrl_mem_trigger_tEnableVec_0 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_mem_trigger_tEnableVec_0;
        io_ooo_to_mem_csrCtrl_mem_trigger_tEnableVec_1 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_mem_trigger_tEnableVec_1;
        io_ooo_to_mem_csrCtrl_mem_trigger_tEnableVec_2 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_mem_trigger_tEnableVec_2;
        io_ooo_to_mem_csrCtrl_mem_trigger_tEnableVec_3 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_mem_trigger_tEnableVec_3;
        io_ooo_to_mem_csrCtrl_mem_trigger_triggerCanRaiseBpExp = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_mem_trigger_triggerCanRaiseBpExp;
        io_ooo_to_mem_csrCtrl_fsIsOff = this.vif.mon_mp.mon_cb.io_ooo_to_mem_csrCtrl_fsIsOff;

        if(this.cfg.xz_sw==tcnt_dec_base::ON && this.vif.rst_n==1'b1 && memblock_sync_pkg::reset_backend_done==1'b1) begin
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_tlbCsr_satp_mode,io_ooo_to_mem_tlbCsr_satp_mode,4);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_tlbCsr_satp_asid,io_ooo_to_mem_tlbCsr_satp_asid,16);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_tlbCsr_satp_ppn,io_ooo_to_mem_tlbCsr_satp_ppn,44);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_tlbCsr_satp_changed,io_ooo_to_mem_tlbCsr_satp_changed,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_tlbCsr_vsatp_mode,io_ooo_to_mem_tlbCsr_vsatp_mode,4);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_tlbCsr_vsatp_asid,io_ooo_to_mem_tlbCsr_vsatp_asid,16);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_tlbCsr_vsatp_ppn,io_ooo_to_mem_tlbCsr_vsatp_ppn,44);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_tlbCsr_vsatp_changed,io_ooo_to_mem_tlbCsr_vsatp_changed,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_tlbCsr_hgatp_mode,io_ooo_to_mem_tlbCsr_hgatp_mode,4);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_tlbCsr_hgatp_vmid,io_ooo_to_mem_tlbCsr_hgatp_vmid,16);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_tlbCsr_hgatp_ppn,io_ooo_to_mem_tlbCsr_hgatp_ppn,44);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_tlbCsr_hgatp_changed,io_ooo_to_mem_tlbCsr_hgatp_changed,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_tlbCsr_mbmc_BME,io_ooo_to_mem_tlbCsr_mbmc_BME,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_tlbCsr_mbmc_CMODE,io_ooo_to_mem_tlbCsr_mbmc_CMODE,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_tlbCsr_mbmc_BCLEAR,io_ooo_to_mem_tlbCsr_mbmc_BCLEAR,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_tlbCsr_mbmc_BMA,io_ooo_to_mem_tlbCsr_mbmc_BMA,58);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_tlbCsr_priv_mxr,io_ooo_to_mem_tlbCsr_priv_mxr,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_tlbCsr_priv_sum,io_ooo_to_mem_tlbCsr_priv_sum,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_tlbCsr_priv_vmxr,io_ooo_to_mem_tlbCsr_priv_vmxr,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_tlbCsr_priv_vsum,io_ooo_to_mem_tlbCsr_priv_vsum,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_tlbCsr_priv_virt,io_ooo_to_mem_tlbCsr_priv_virt,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_tlbCsr_priv_virt_changed,io_ooo_to_mem_tlbCsr_priv_virt_changed,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_tlbCsr_priv_spvp,io_ooo_to_mem_tlbCsr_priv_spvp,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_tlbCsr_priv_imode,io_ooo_to_mem_tlbCsr_priv_imode,2);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_tlbCsr_priv_dmode,io_ooo_to_mem_tlbCsr_priv_dmode,2);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_tlbCsr_mPBMTE,io_ooo_to_mem_tlbCsr_mPBMTE,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_tlbCsr_hPBMTE,io_ooo_to_mem_tlbCsr_hPBMTE,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_tlbCsr_pmm_mseccfg,io_ooo_to_mem_tlbCsr_pmm_mseccfg,2);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_tlbCsr_pmm_menvcfg,io_ooo_to_mem_tlbCsr_pmm_menvcfg,2);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_tlbCsr_pmm_henvcfg,io_ooo_to_mem_tlbCsr_pmm_henvcfg,2);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_tlbCsr_pmm_hstatus,io_ooo_to_mem_tlbCsr_pmm_hstatus,2);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_tlbCsr_pmm_senvcfg,io_ooo_to_mem_tlbCsr_pmm_senvcfg,2);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_pf_ctrl_l1I_pf_enable,io_ooo_to_mem_csrCtrl_pf_ctrl_l1I_pf_enable,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_enable,io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_enable,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_enable,io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_enable,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_train_on_hit,io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_train_on_hit,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_enable_agt,io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_enable_agt,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_enable_pht,io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_enable_pht,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_active_threshold,io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_active_threshold,4);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_active_stride,io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_active_stride,6);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_enable_stride,io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_enable_stride,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_store_only,io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_store_only,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_recv_enable,io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_recv_enable,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_pbop_enable,io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_pbop_enable,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_vbop_enable,io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_vbop_enable,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_tp_enable,io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_tp_enable,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_delay_latency,io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_delay_latency,10);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_bp_ctrl_ubtbEnable,io_ooo_to_mem_csrCtrl_bp_ctrl_ubtbEnable,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_bp_ctrl_abtbEnable,io_ooo_to_mem_csrCtrl_bp_ctrl_abtbEnable,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_bp_ctrl_mbtbEnable,io_ooo_to_mem_csrCtrl_bp_ctrl_mbtbEnable,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_bp_ctrl_tageEnable,io_ooo_to_mem_csrCtrl_bp_ctrl_tageEnable,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_bp_ctrl_scEnable,io_ooo_to_mem_csrCtrl_bp_ctrl_scEnable,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_bp_ctrl_ittageEnable,io_ooo_to_mem_csrCtrl_bp_ctrl_ittageEnable,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_sbuffer_timeout,io_ooo_to_mem_csrCtrl_sbuffer_timeout,22);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_ldld_vio_check_enable,io_ooo_to_mem_csrCtrl_ldld_vio_check_enable,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_cache_error_enable,io_ooo_to_mem_csrCtrl_cache_error_enable,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_uncache_write_outstanding_enable,io_ooo_to_mem_csrCtrl_uncache_write_outstanding_enable,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_power_down_enable,io_ooo_to_mem_csrCtrl_power_down_enable,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_flush_l2_enable,io_ooo_to_mem_csrCtrl_flush_l2_enable,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_distribute_csr_w_valid,io_ooo_to_mem_csrCtrl_distribute_csr_w_valid,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_distribute_csr_w_bits_addr,io_ooo_to_mem_csrCtrl_distribute_csr_w_bits_addr,12);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_distribute_csr_w_bits_data,io_ooo_to_mem_csrCtrl_distribute_csr_w_bits_data,64);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_valid,io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_valid,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_addr,io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_addr,2);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_matchType,io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_matchType,2);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_select,io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_select,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_timing,io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_timing,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_action,io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_action,4);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_chain,io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_chain,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_execute,io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_execute,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_store,io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_store,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_load,io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_load,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_tdata2,io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_tdata2,64);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_frontend_trigger_tEnableVec_0,io_ooo_to_mem_csrCtrl_frontend_trigger_tEnableVec_0,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_frontend_trigger_tEnableVec_1,io_ooo_to_mem_csrCtrl_frontend_trigger_tEnableVec_1,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_frontend_trigger_tEnableVec_2,io_ooo_to_mem_csrCtrl_frontend_trigger_tEnableVec_2,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_frontend_trigger_tEnableVec_3,io_ooo_to_mem_csrCtrl_frontend_trigger_tEnableVec_3,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_frontend_trigger_triggerCanRaiseBpExp,io_ooo_to_mem_csrCtrl_frontend_trigger_triggerCanRaiseBpExp,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_valid,io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_valid,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_addr,io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_addr,2);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_matchType,io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_matchType,2);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_select,io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_select,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_timing,io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_timing,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_action,io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_action,4);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_chain,io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_chain,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_store,io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_store,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_load,io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_load,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_tdata2,io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_tdata2,64);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_mem_trigger_tEnableVec_0,io_ooo_to_mem_csrCtrl_mem_trigger_tEnableVec_0,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_mem_trigger_tEnableVec_1,io_ooo_to_mem_csrCtrl_mem_trigger_tEnableVec_1,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_mem_trigger_tEnableVec_2,io_ooo_to_mem_csrCtrl_mem_trigger_tEnableVec_2,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_mem_trigger_tEnableVec_3,io_ooo_to_mem_csrCtrl_mem_trigger_tEnableVec_3,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_mem_trigger_triggerCanRaiseBpExp,io_ooo_to_mem_csrCtrl_mem_trigger_triggerCanRaiseBpExp,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_csrCtrl_fsIsOff,io_ooo_to_mem_csrCtrl_fsIsOff,1);

        end
        if (memblock_sync_pkg::dispatch_monitor_capture_en != last_capture_en) begin
            has_last_raw_csr = 1'b0;
            last_capture_en = memblock_sync_pkg::dispatch_monitor_capture_en;
        end
        if (this.vif.rst_n!=1'b1 || memblock_sync_pkg::reset_backend_done!=1'b1) begin
            has_last_raw_csr = 1'b0;
        end
        if(this.vif.rst_n==1'b1 && memblock_sync_pkg::reset_backend_done==1'b1 &&
           memblock_sync_pkg::dispatch_monitor_capture_en==1'b1) begin
            raw_csr = memblock_sync_pkg::make_empty_raw_csr();
            raw_csr.valid             = 1'b1;
            raw_csr.satp_mode         = io_ooo_to_mem_tlbCsr_satp_mode;
            raw_csr.satp_asid         = io_ooo_to_mem_tlbCsr_satp_asid;
            raw_csr.satp_ppn          = io_ooo_to_mem_tlbCsr_satp_ppn;
            raw_csr.satp_changed      = io_ooo_to_mem_tlbCsr_satp_changed;
            raw_csr.vsatp_mode        = io_ooo_to_mem_tlbCsr_vsatp_mode;
            raw_csr.vsatp_asid        = io_ooo_to_mem_tlbCsr_vsatp_asid;
            raw_csr.vsatp_ppn         = io_ooo_to_mem_tlbCsr_vsatp_ppn;
            raw_csr.vsatp_changed     = io_ooo_to_mem_tlbCsr_vsatp_changed;
            raw_csr.hgatp_mode        = io_ooo_to_mem_tlbCsr_hgatp_mode;
            raw_csr.hgatp_vmid        = io_ooo_to_mem_tlbCsr_hgatp_vmid;
            raw_csr.hgatp_ppn         = io_ooo_to_mem_tlbCsr_hgatp_ppn;
            raw_csr.hgatp_changed     = io_ooo_to_mem_tlbCsr_hgatp_changed;
            raw_csr.priv_mxr          = io_ooo_to_mem_tlbCsr_priv_mxr;
            raw_csr.priv_sum          = io_ooo_to_mem_tlbCsr_priv_sum;
            raw_csr.priv_vmxr         = io_ooo_to_mem_tlbCsr_priv_vmxr;
            raw_csr.priv_vsum         = io_ooo_to_mem_tlbCsr_priv_vsum;
            raw_csr.priv_virt         = io_ooo_to_mem_tlbCsr_priv_virt;
            raw_csr.priv_virt_changed = io_ooo_to_mem_tlbCsr_priv_virt_changed;
            raw_csr.priv_spvp         = io_ooo_to_mem_tlbCsr_priv_spvp;
            raw_csr.priv_imode        = io_ooo_to_mem_tlbCsr_priv_imode;
            raw_csr.priv_dmode        = io_ooo_to_mem_tlbCsr_priv_dmode;
            raw_csr.m_pbmt_en         = io_ooo_to_mem_tlbCsr_mPBMTE;
            raw_csr.h_pbmt_en         = io_ooo_to_mem_tlbCsr_hPBMTE;
            raw_csr.cycle             = $time;
            if (!has_last_raw_csr ||
                memblock_sync_pkg::raw_csr_payload_changed(last_raw_csr, raw_csr)) begin
                memblock_sync_pkg::push_raw_csr(raw_csr);
                has_last_raw_csr = 1'b1;
            end
            last_raw_csr = raw_csr;
        end
        //if(xxxTODOxxx==1'b1) begin
        //    mon_tr = csr_ctrl_agent_agent_xaction::type_id::create("mon_tr");
        //    mon_tr.io_ooo_to_mem_tlbCsr_satp_mode = io_ooo_to_mem_tlbCsr_satp_mode;
        //    mon_tr.io_ooo_to_mem_tlbCsr_satp_asid = io_ooo_to_mem_tlbCsr_satp_asid;
        //    mon_tr.io_ooo_to_mem_tlbCsr_satp_ppn = io_ooo_to_mem_tlbCsr_satp_ppn;
        //    mon_tr.io_ooo_to_mem_tlbCsr_satp_changed = io_ooo_to_mem_tlbCsr_satp_changed;
        //    mon_tr.io_ooo_to_mem_tlbCsr_vsatp_mode = io_ooo_to_mem_tlbCsr_vsatp_mode;
        //    mon_tr.io_ooo_to_mem_tlbCsr_vsatp_asid = io_ooo_to_mem_tlbCsr_vsatp_asid;
        //    mon_tr.io_ooo_to_mem_tlbCsr_vsatp_ppn = io_ooo_to_mem_tlbCsr_vsatp_ppn;
        //    mon_tr.io_ooo_to_mem_tlbCsr_vsatp_changed = io_ooo_to_mem_tlbCsr_vsatp_changed;
        //    mon_tr.io_ooo_to_mem_tlbCsr_hgatp_mode = io_ooo_to_mem_tlbCsr_hgatp_mode;
        //    mon_tr.io_ooo_to_mem_tlbCsr_hgatp_vmid = io_ooo_to_mem_tlbCsr_hgatp_vmid;
        //    mon_tr.io_ooo_to_mem_tlbCsr_hgatp_ppn = io_ooo_to_mem_tlbCsr_hgatp_ppn;
        //    mon_tr.io_ooo_to_mem_tlbCsr_hgatp_changed = io_ooo_to_mem_tlbCsr_hgatp_changed;
        //    mon_tr.io_ooo_to_mem_tlbCsr_mbmc_BME = io_ooo_to_mem_tlbCsr_mbmc_BME;
        //    mon_tr.io_ooo_to_mem_tlbCsr_mbmc_CMODE = io_ooo_to_mem_tlbCsr_mbmc_CMODE;
        //    mon_tr.io_ooo_to_mem_tlbCsr_mbmc_BCLEAR = io_ooo_to_mem_tlbCsr_mbmc_BCLEAR;
        //    mon_tr.io_ooo_to_mem_tlbCsr_mbmc_BMA = io_ooo_to_mem_tlbCsr_mbmc_BMA;
        //    mon_tr.io_ooo_to_mem_tlbCsr_priv_mxr = io_ooo_to_mem_tlbCsr_priv_mxr;
        //    mon_tr.io_ooo_to_mem_tlbCsr_priv_sum = io_ooo_to_mem_tlbCsr_priv_sum;
        //    mon_tr.io_ooo_to_mem_tlbCsr_priv_vmxr = io_ooo_to_mem_tlbCsr_priv_vmxr;
        //    mon_tr.io_ooo_to_mem_tlbCsr_priv_vsum = io_ooo_to_mem_tlbCsr_priv_vsum;
        //    mon_tr.io_ooo_to_mem_tlbCsr_priv_virt = io_ooo_to_mem_tlbCsr_priv_virt;
        //    mon_tr.io_ooo_to_mem_tlbCsr_priv_virt_changed = io_ooo_to_mem_tlbCsr_priv_virt_changed;
        //    mon_tr.io_ooo_to_mem_tlbCsr_priv_spvp = io_ooo_to_mem_tlbCsr_priv_spvp;
        //    mon_tr.io_ooo_to_mem_tlbCsr_priv_imode = io_ooo_to_mem_tlbCsr_priv_imode;
        //    mon_tr.io_ooo_to_mem_tlbCsr_priv_dmode = io_ooo_to_mem_tlbCsr_priv_dmode;
        //    mon_tr.io_ooo_to_mem_tlbCsr_mPBMTE = io_ooo_to_mem_tlbCsr_mPBMTE;
        //    mon_tr.io_ooo_to_mem_tlbCsr_hPBMTE = io_ooo_to_mem_tlbCsr_hPBMTE;
        //    mon_tr.io_ooo_to_mem_tlbCsr_pmm_mseccfg = io_ooo_to_mem_tlbCsr_pmm_mseccfg;
        //    mon_tr.io_ooo_to_mem_tlbCsr_pmm_menvcfg = io_ooo_to_mem_tlbCsr_pmm_menvcfg;
        //    mon_tr.io_ooo_to_mem_tlbCsr_pmm_henvcfg = io_ooo_to_mem_tlbCsr_pmm_henvcfg;
        //    mon_tr.io_ooo_to_mem_tlbCsr_pmm_hstatus = io_ooo_to_mem_tlbCsr_pmm_hstatus;
        //    mon_tr.io_ooo_to_mem_tlbCsr_pmm_senvcfg = io_ooo_to_mem_tlbCsr_pmm_senvcfg;
        //    mon_tr.io_ooo_to_mem_csrCtrl_pf_ctrl_l1I_pf_enable = io_ooo_to_mem_csrCtrl_pf_ctrl_l1I_pf_enable;
        //    mon_tr.io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_enable = io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_enable;
        //    mon_tr.io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_enable = io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_enable;
        //    mon_tr.io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_train_on_hit = io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_train_on_hit;
        //    mon_tr.io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_enable_agt = io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_enable_agt;
        //    mon_tr.io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_enable_pht = io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_enable_pht;
        //    mon_tr.io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_active_threshold = io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_active_threshold;
        //    mon_tr.io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_active_stride = io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_active_stride;
        //    mon_tr.io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_enable_stride = io_ooo_to_mem_csrCtrl_pf_ctrl_l1D_pf_enable_stride;
        //    mon_tr.io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_store_only = io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_store_only;
        //    mon_tr.io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_recv_enable = io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_recv_enable;
        //    mon_tr.io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_pbop_enable = io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_pbop_enable;
        //    mon_tr.io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_vbop_enable = io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_vbop_enable;
        //    mon_tr.io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_tp_enable = io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_tp_enable;
        //    mon_tr.io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_delay_latency = io_ooo_to_mem_csrCtrl_pf_ctrl_l2_pf_delay_latency;
        //    mon_tr.io_ooo_to_mem_csrCtrl_bp_ctrl_ubtbEnable = io_ooo_to_mem_csrCtrl_bp_ctrl_ubtbEnable;
        //    mon_tr.io_ooo_to_mem_csrCtrl_bp_ctrl_abtbEnable = io_ooo_to_mem_csrCtrl_bp_ctrl_abtbEnable;
        //    mon_tr.io_ooo_to_mem_csrCtrl_bp_ctrl_mbtbEnable = io_ooo_to_mem_csrCtrl_bp_ctrl_mbtbEnable;
        //    mon_tr.io_ooo_to_mem_csrCtrl_bp_ctrl_tageEnable = io_ooo_to_mem_csrCtrl_bp_ctrl_tageEnable;
        //    mon_tr.io_ooo_to_mem_csrCtrl_bp_ctrl_scEnable = io_ooo_to_mem_csrCtrl_bp_ctrl_scEnable;
        //    mon_tr.io_ooo_to_mem_csrCtrl_bp_ctrl_ittageEnable = io_ooo_to_mem_csrCtrl_bp_ctrl_ittageEnable;
        //    mon_tr.io_ooo_to_mem_csrCtrl_sbuffer_timeout = io_ooo_to_mem_csrCtrl_sbuffer_timeout;
        //    mon_tr.io_ooo_to_mem_csrCtrl_ldld_vio_check_enable = io_ooo_to_mem_csrCtrl_ldld_vio_check_enable;
        //    mon_tr.io_ooo_to_mem_csrCtrl_cache_error_enable = io_ooo_to_mem_csrCtrl_cache_error_enable;
        //    mon_tr.io_ooo_to_mem_csrCtrl_uncache_write_outstanding_enable = io_ooo_to_mem_csrCtrl_uncache_write_outstanding_enable;
        //    mon_tr.io_ooo_to_mem_csrCtrl_power_down_enable = io_ooo_to_mem_csrCtrl_power_down_enable;
        //    mon_tr.io_ooo_to_mem_csrCtrl_flush_l2_enable = io_ooo_to_mem_csrCtrl_flush_l2_enable;
        //    mon_tr.io_ooo_to_mem_csrCtrl_distribute_csr_w_valid = io_ooo_to_mem_csrCtrl_distribute_csr_w_valid;
        //    mon_tr.io_ooo_to_mem_csrCtrl_distribute_csr_w_bits_addr = io_ooo_to_mem_csrCtrl_distribute_csr_w_bits_addr;
        //    mon_tr.io_ooo_to_mem_csrCtrl_distribute_csr_w_bits_data = io_ooo_to_mem_csrCtrl_distribute_csr_w_bits_data;
        //    mon_tr.io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_valid = io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_valid;
        //    mon_tr.io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_addr = io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_addr;
        //    mon_tr.io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_matchType = io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_matchType;
        //    mon_tr.io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_select = io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_select;
        //    mon_tr.io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_timing = io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_timing;
        //    mon_tr.io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_action = io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_action;
        //    mon_tr.io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_chain = io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_chain;
        //    mon_tr.io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_execute = io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_execute;
        //    mon_tr.io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_store = io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_store;
        //    mon_tr.io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_load = io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_load;
        //    mon_tr.io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_tdata2 = io_ooo_to_mem_csrCtrl_frontend_trigger_tUpdate_bits_tdata_tdata2;
        //    mon_tr.io_ooo_to_mem_csrCtrl_frontend_trigger_tEnableVec_0 = io_ooo_to_mem_csrCtrl_frontend_trigger_tEnableVec_0;
        //    mon_tr.io_ooo_to_mem_csrCtrl_frontend_trigger_tEnableVec_1 = io_ooo_to_mem_csrCtrl_frontend_trigger_tEnableVec_1;
        //    mon_tr.io_ooo_to_mem_csrCtrl_frontend_trigger_tEnableVec_2 = io_ooo_to_mem_csrCtrl_frontend_trigger_tEnableVec_2;
        //    mon_tr.io_ooo_to_mem_csrCtrl_frontend_trigger_tEnableVec_3 = io_ooo_to_mem_csrCtrl_frontend_trigger_tEnableVec_3;
        //    mon_tr.io_ooo_to_mem_csrCtrl_frontend_trigger_triggerCanRaiseBpExp = io_ooo_to_mem_csrCtrl_frontend_trigger_triggerCanRaiseBpExp;
        //    mon_tr.io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_valid = io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_valid;
        //    mon_tr.io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_addr = io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_addr;
        //    mon_tr.io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_matchType = io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_matchType;
        //    mon_tr.io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_select = io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_select;
        //    mon_tr.io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_timing = io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_timing;
        //    mon_tr.io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_action = io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_action;
        //    mon_tr.io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_chain = io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_chain;
        //    mon_tr.io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_store = io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_store;
        //    mon_tr.io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_load = io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_load;
        //    mon_tr.io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_tdata2 = io_ooo_to_mem_csrCtrl_mem_trigger_tUpdate_bits_tdata_tdata2;
        //    mon_tr.io_ooo_to_mem_csrCtrl_mem_trigger_tEnableVec_0 = io_ooo_to_mem_csrCtrl_mem_trigger_tEnableVec_0;
        //    mon_tr.io_ooo_to_mem_csrCtrl_mem_trigger_tEnableVec_1 = io_ooo_to_mem_csrCtrl_mem_trigger_tEnableVec_1;
        //    mon_tr.io_ooo_to_mem_csrCtrl_mem_trigger_tEnableVec_2 = io_ooo_to_mem_csrCtrl_mem_trigger_tEnableVec_2;
        //    mon_tr.io_ooo_to_mem_csrCtrl_mem_trigger_tEnableVec_3 = io_ooo_to_mem_csrCtrl_mem_trigger_tEnableVec_3;
        //    mon_tr.io_ooo_to_mem_csrCtrl_mem_trigger_triggerCanRaiseBpExp = io_ooo_to_mem_csrCtrl_mem_trigger_triggerCanRaiseBpExp;
        //    mon_tr.io_ooo_to_mem_csrCtrl_fsIsOff = io_ooo_to_mem_csrCtrl_fsIsOff;

        //    mon_tr.channel_id = this.cfg.channel_id;
        //    mon_tr.unpack();
        //    this.mon_item_port.write(mon_tr);
        //end
    end
endtask:mon_data

`endif
