//=========================================================
//File name    : lsqenq_agent_agent_interface.sv
//Author       : OpenAI_Codex
//Module name  : lsqenq_agent_agent_interface
//Discribution : lsqenq_agent_agent_interface : signal interface
//Date         : 2026-04-12
//=========================================================
`ifndef LSQENQ_AGENT_AGENT_INTERFACE__SV
`define LSQENQ_AGENT_AGENT_INTERFACE__SV

`include "memblock_compile_params.svh"

`ifndef DEF_SETUP_TIME
    `define DEF_SETUP_TIME 1
`endif
`ifndef DEF_HOLD_TIME
    `define DEF_HOLD_TIME 1
`endif

interface lsqenq_agent_agent_interface  (input bit clk,input bit rst_n);

    logic [1:0] io_ooo_to_mem_enqLsq_needAlloc_0;
    logic [1:0] io_ooo_to_mem_enqLsq_needAlloc_1;
    logic [1:0] io_ooo_to_mem_enqLsq_needAlloc_2;
    logic [1:0] io_ooo_to_mem_enqLsq_needAlloc_3;
    logic [1:0] io_ooo_to_mem_enqLsq_needAlloc_4;
    logic [1:0] io_ooo_to_mem_enqLsq_needAlloc_5;
    logic io_ooo_to_mem_enqLsq_req_0_valid;
    logic [`MEMBLOCK_DUT_FUTYPE_W-1:0] io_ooo_to_mem_enqLsq_req_0_bits_fuType;
    logic [`MEMBLOCK_DUT_UOP_IDX_W-1:0] io_ooo_to_mem_enqLsq_req_0_bits_uopIdx;
    logic io_ooo_to_mem_enqLsq_req_0_bits_robIdx_flag;
    logic [`MEMBLOCK_DUT_ROB_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_0_bits_robIdx_value;
    logic io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_flag;
    logic [`MEMBLOCK_DUT_LQ_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_flag;
    logic [`MEMBLOCK_DUT_SQ_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_value;
    logic [`MEMBLOCK_DUT_NUM_LS_ELEM_W-1:0] io_ooo_to_mem_enqLsq_req_0_bits_numLsElem;
    logic io_ooo_to_mem_enqLsq_req_1_valid;
    logic [`MEMBLOCK_DUT_FUTYPE_W-1:0] io_ooo_to_mem_enqLsq_req_1_bits_fuType;
    logic [`MEMBLOCK_DUT_UOP_IDX_W-1:0] io_ooo_to_mem_enqLsq_req_1_bits_uopIdx;
    logic io_ooo_to_mem_enqLsq_req_1_bits_robIdx_flag;
    logic [`MEMBLOCK_DUT_ROB_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_1_bits_robIdx_value;
    logic io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_flag;
    logic [`MEMBLOCK_DUT_LQ_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_flag;
    logic [`MEMBLOCK_DUT_SQ_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_value;
    logic [`MEMBLOCK_DUT_NUM_LS_ELEM_W-1:0] io_ooo_to_mem_enqLsq_req_1_bits_numLsElem;
    logic io_ooo_to_mem_enqLsq_req_2_valid;
    logic [`MEMBLOCK_DUT_FUTYPE_W-1:0] io_ooo_to_mem_enqLsq_req_2_bits_fuType;
    logic [`MEMBLOCK_DUT_UOP_IDX_W-1:0] io_ooo_to_mem_enqLsq_req_2_bits_uopIdx;
    logic io_ooo_to_mem_enqLsq_req_2_bits_robIdx_flag;
    logic [`MEMBLOCK_DUT_ROB_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_2_bits_robIdx_value;
    logic io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_flag;
    logic [`MEMBLOCK_DUT_LQ_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_flag;
    logic [`MEMBLOCK_DUT_SQ_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_value;
    logic [`MEMBLOCK_DUT_NUM_LS_ELEM_W-1:0] io_ooo_to_mem_enqLsq_req_2_bits_numLsElem;
    logic io_ooo_to_mem_enqLsq_req_3_valid;
    logic [`MEMBLOCK_DUT_FUTYPE_W-1:0] io_ooo_to_mem_enqLsq_req_3_bits_fuType;
    logic [`MEMBLOCK_DUT_UOP_IDX_W-1:0] io_ooo_to_mem_enqLsq_req_3_bits_uopIdx;
    logic io_ooo_to_mem_enqLsq_req_3_bits_robIdx_flag;
    logic [`MEMBLOCK_DUT_ROB_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_3_bits_robIdx_value;
    logic io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_flag;
    logic [`MEMBLOCK_DUT_LQ_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_flag;
    logic [`MEMBLOCK_DUT_SQ_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_value;
    logic [`MEMBLOCK_DUT_NUM_LS_ELEM_W-1:0] io_ooo_to_mem_enqLsq_req_3_bits_numLsElem;
    logic io_ooo_to_mem_enqLsq_req_4_valid;
    logic [`MEMBLOCK_DUT_FUTYPE_W-1:0] io_ooo_to_mem_enqLsq_req_4_bits_fuType;
    logic [`MEMBLOCK_DUT_UOP_IDX_W-1:0] io_ooo_to_mem_enqLsq_req_4_bits_uopIdx;
    logic io_ooo_to_mem_enqLsq_req_4_bits_robIdx_flag;
    logic [`MEMBLOCK_DUT_ROB_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_4_bits_robIdx_value;
    logic io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_flag;
    logic [`MEMBLOCK_DUT_LQ_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_flag;
    logic [`MEMBLOCK_DUT_SQ_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_value;
    logic [`MEMBLOCK_DUT_NUM_LS_ELEM_W-1:0] io_ooo_to_mem_enqLsq_req_4_bits_numLsElem;
    logic io_ooo_to_mem_enqLsq_req_5_valid;
    logic [`MEMBLOCK_DUT_FUTYPE_W-1:0] io_ooo_to_mem_enqLsq_req_5_bits_fuType;
    logic [`MEMBLOCK_DUT_UOP_IDX_W-1:0] io_ooo_to_mem_enqLsq_req_5_bits_uopIdx;
    logic io_ooo_to_mem_enqLsq_req_5_bits_robIdx_flag;
    logic [`MEMBLOCK_DUT_ROB_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_5_bits_robIdx_value;
    logic io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_flag;
    logic [`MEMBLOCK_DUT_LQ_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_flag;
    logic [`MEMBLOCK_DUT_SQ_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_value;
    logic [`MEMBLOCK_DUT_NUM_LS_ELEM_W-1:0] io_ooo_to_mem_enqLsq_req_5_bits_numLsElem;

    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_0;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_1;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_10;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_11;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_12;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_13;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_14;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_15;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_16;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_17;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_18;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_19;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_2;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_20;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_21;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_22;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_23;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_3;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_4;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_5;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_6;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_7;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_8;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_9;
    logic io_ooo_to_mem_enqLsq_req_0_bits_flushPipe;
    logic [8:0] io_ooo_to_mem_enqLsq_req_0_bits_fuOpType;
    logic io_ooo_to_mem_enqLsq_req_0_bits_lastUop;
    logic [3:0] io_ooo_to_mem_enqLsq_req_0_bits_trigger;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_0;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_1;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_10;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_11;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_12;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_13;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_14;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_15;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_16;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_17;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_18;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_19;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_2;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_20;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_21;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_22;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_23;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_3;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_4;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_5;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_6;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_7;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_8;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_9;
    logic io_ooo_to_mem_enqLsq_req_1_bits_flushPipe;
    logic [8:0] io_ooo_to_mem_enqLsq_req_1_bits_fuOpType;
    logic io_ooo_to_mem_enqLsq_req_1_bits_lastUop;
    logic [3:0] io_ooo_to_mem_enqLsq_req_1_bits_trigger;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_0;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_1;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_10;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_11;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_12;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_13;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_14;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_15;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_16;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_17;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_18;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_19;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_2;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_20;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_21;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_22;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_23;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_3;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_4;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_5;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_6;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_7;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_8;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_9;
    logic io_ooo_to_mem_enqLsq_req_2_bits_flushPipe;
    logic [8:0] io_ooo_to_mem_enqLsq_req_2_bits_fuOpType;
    logic io_ooo_to_mem_enqLsq_req_2_bits_lastUop;
    logic [3:0] io_ooo_to_mem_enqLsq_req_2_bits_trigger;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_0;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_1;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_10;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_11;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_12;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_13;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_14;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_15;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_16;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_17;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_18;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_19;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_2;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_20;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_21;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_22;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_23;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_3;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_4;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_5;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_6;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_7;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_8;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_9;
    logic io_ooo_to_mem_enqLsq_req_3_bits_flushPipe;
    logic [8:0] io_ooo_to_mem_enqLsq_req_3_bits_fuOpType;
    logic io_ooo_to_mem_enqLsq_req_3_bits_lastUop;
    logic [3:0] io_ooo_to_mem_enqLsq_req_3_bits_trigger;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_0;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_1;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_10;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_11;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_12;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_13;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_14;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_15;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_16;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_17;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_18;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_19;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_2;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_20;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_21;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_22;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_23;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_3;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_4;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_5;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_6;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_7;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_8;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_9;
    logic io_ooo_to_mem_enqLsq_req_4_bits_flushPipe;
    logic [8:0] io_ooo_to_mem_enqLsq_req_4_bits_fuOpType;
    logic io_ooo_to_mem_enqLsq_req_4_bits_lastUop;
    logic [3:0] io_ooo_to_mem_enqLsq_req_4_bits_trigger;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_0;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_1;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_10;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_11;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_12;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_13;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_14;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_15;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_16;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_17;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_18;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_19;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_2;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_20;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_21;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_22;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_23;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_3;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_4;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_5;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_6;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_7;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_8;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_9;
    logic io_ooo_to_mem_enqLsq_req_5_bits_flushPipe;
    logic [8:0] io_ooo_to_mem_enqLsq_req_5_bits_fuOpType;
    logic io_ooo_to_mem_enqLsq_req_5_bits_lastUop;
    logic [3:0] io_ooo_to_mem_enqLsq_req_5_bits_trigger;

    clocking drv_cb @(posedge clk);
        `ifdef INTERFACE_ADD_DELAY
            default input #`DEF_SETUP_TIME output #`DEF_HOLD_TIME;
        `endif
        output io_ooo_to_mem_enqLsq_needAlloc_0;
        output io_ooo_to_mem_enqLsq_needAlloc_1;
        output io_ooo_to_mem_enqLsq_needAlloc_2;
        output io_ooo_to_mem_enqLsq_needAlloc_3;
        output io_ooo_to_mem_enqLsq_needAlloc_4;
        output io_ooo_to_mem_enqLsq_needAlloc_5;
        output io_ooo_to_mem_enqLsq_req_0_valid;
        output io_ooo_to_mem_enqLsq_req_0_bits_fuType;
        output io_ooo_to_mem_enqLsq_req_0_bits_uopIdx;
        output io_ooo_to_mem_enqLsq_req_0_bits_robIdx_flag;
        output io_ooo_to_mem_enqLsq_req_0_bits_robIdx_value;
        output io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_flag;
        output io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_value;
        output io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_flag;
        output io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_value;
        output io_ooo_to_mem_enqLsq_req_0_bits_numLsElem;
        output io_ooo_to_mem_enqLsq_req_1_valid;
        output io_ooo_to_mem_enqLsq_req_1_bits_fuType;
        output io_ooo_to_mem_enqLsq_req_1_bits_uopIdx;
        output io_ooo_to_mem_enqLsq_req_1_bits_robIdx_flag;
        output io_ooo_to_mem_enqLsq_req_1_bits_robIdx_value;
        output io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_flag;
        output io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_value;
        output io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_flag;
        output io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_value;
        output io_ooo_to_mem_enqLsq_req_1_bits_numLsElem;
        output io_ooo_to_mem_enqLsq_req_2_valid;
        output io_ooo_to_mem_enqLsq_req_2_bits_fuType;
        output io_ooo_to_mem_enqLsq_req_2_bits_uopIdx;
        output io_ooo_to_mem_enqLsq_req_2_bits_robIdx_flag;
        output io_ooo_to_mem_enqLsq_req_2_bits_robIdx_value;
        output io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_flag;
        output io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_value;
        output io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_flag;
        output io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_value;
        output io_ooo_to_mem_enqLsq_req_2_bits_numLsElem;
        output io_ooo_to_mem_enqLsq_req_3_valid;
        output io_ooo_to_mem_enqLsq_req_3_bits_fuType;
        output io_ooo_to_mem_enqLsq_req_3_bits_uopIdx;
        output io_ooo_to_mem_enqLsq_req_3_bits_robIdx_flag;
        output io_ooo_to_mem_enqLsq_req_3_bits_robIdx_value;
        output io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_flag;
        output io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_value;
        output io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_flag;
        output io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_value;
        output io_ooo_to_mem_enqLsq_req_3_bits_numLsElem;
        output io_ooo_to_mem_enqLsq_req_4_valid;
        output io_ooo_to_mem_enqLsq_req_4_bits_fuType;
        output io_ooo_to_mem_enqLsq_req_4_bits_uopIdx;
        output io_ooo_to_mem_enqLsq_req_4_bits_robIdx_flag;
        output io_ooo_to_mem_enqLsq_req_4_bits_robIdx_value;
        output io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_flag;
        output io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_value;
        output io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_flag;
        output io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_value;
        output io_ooo_to_mem_enqLsq_req_4_bits_numLsElem;
        output io_ooo_to_mem_enqLsq_req_5_valid;
        output io_ooo_to_mem_enqLsq_req_5_bits_fuType;
        output io_ooo_to_mem_enqLsq_req_5_bits_uopIdx;
        output io_ooo_to_mem_enqLsq_req_5_bits_robIdx_flag;
        output io_ooo_to_mem_enqLsq_req_5_bits_robIdx_value;
        output io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_flag;
        output io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_value;
        output io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_flag;
        output io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_value;
        output io_ooo_to_mem_enqLsq_req_5_bits_numLsElem;

        output io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_0;
        output io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_1;
        output io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_10;
        output io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_11;
        output io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_12;
        output io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_13;
        output io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_14;
        output io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_15;
        output io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_16;
        output io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_17;
        output io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_18;
        output io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_19;
        output io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_2;
        output io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_20;
        output io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_21;
        output io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_22;
        output io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_23;
        output io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_3;
        output io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_4;
        output io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_5;
        output io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_6;
        output io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_7;
        output io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_8;
        output io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_9;
        output io_ooo_to_mem_enqLsq_req_0_bits_flushPipe;
        output io_ooo_to_mem_enqLsq_req_0_bits_fuOpType;
        output io_ooo_to_mem_enqLsq_req_0_bits_lastUop;
        output io_ooo_to_mem_enqLsq_req_0_bits_trigger;
        output io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_0;
        output io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_1;
        output io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_10;
        output io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_11;
        output io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_12;
        output io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_13;
        output io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_14;
        output io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_15;
        output io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_16;
        output io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_17;
        output io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_18;
        output io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_19;
        output io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_2;
        output io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_20;
        output io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_21;
        output io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_22;
        output io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_23;
        output io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_3;
        output io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_4;
        output io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_5;
        output io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_6;
        output io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_7;
        output io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_8;
        output io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_9;
        output io_ooo_to_mem_enqLsq_req_1_bits_flushPipe;
        output io_ooo_to_mem_enqLsq_req_1_bits_fuOpType;
        output io_ooo_to_mem_enqLsq_req_1_bits_lastUop;
        output io_ooo_to_mem_enqLsq_req_1_bits_trigger;
        output io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_0;
        output io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_1;
        output io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_10;
        output io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_11;
        output io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_12;
        output io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_13;
        output io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_14;
        output io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_15;
        output io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_16;
        output io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_17;
        output io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_18;
        output io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_19;
        output io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_2;
        output io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_20;
        output io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_21;
        output io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_22;
        output io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_23;
        output io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_3;
        output io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_4;
        output io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_5;
        output io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_6;
        output io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_7;
        output io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_8;
        output io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_9;
        output io_ooo_to_mem_enqLsq_req_2_bits_flushPipe;
        output io_ooo_to_mem_enqLsq_req_2_bits_fuOpType;
        output io_ooo_to_mem_enqLsq_req_2_bits_lastUop;
        output io_ooo_to_mem_enqLsq_req_2_bits_trigger;
        output io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_0;
        output io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_1;
        output io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_10;
        output io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_11;
        output io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_12;
        output io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_13;
        output io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_14;
        output io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_15;
        output io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_16;
        output io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_17;
        output io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_18;
        output io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_19;
        output io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_2;
        output io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_20;
        output io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_21;
        output io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_22;
        output io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_23;
        output io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_3;
        output io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_4;
        output io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_5;
        output io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_6;
        output io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_7;
        output io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_8;
        output io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_9;
        output io_ooo_to_mem_enqLsq_req_3_bits_flushPipe;
        output io_ooo_to_mem_enqLsq_req_3_bits_fuOpType;
        output io_ooo_to_mem_enqLsq_req_3_bits_lastUop;
        output io_ooo_to_mem_enqLsq_req_3_bits_trigger;
        output io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_0;
        output io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_1;
        output io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_10;
        output io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_11;
        output io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_12;
        output io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_13;
        output io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_14;
        output io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_15;
        output io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_16;
        output io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_17;
        output io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_18;
        output io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_19;
        output io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_2;
        output io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_20;
        output io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_21;
        output io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_22;
        output io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_23;
        output io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_3;
        output io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_4;
        output io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_5;
        output io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_6;
        output io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_7;
        output io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_8;
        output io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_9;
        output io_ooo_to_mem_enqLsq_req_4_bits_flushPipe;
        output io_ooo_to_mem_enqLsq_req_4_bits_fuOpType;
        output io_ooo_to_mem_enqLsq_req_4_bits_lastUop;
        output io_ooo_to_mem_enqLsq_req_4_bits_trigger;
        output io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_0;
        output io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_1;
        output io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_10;
        output io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_11;
        output io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_12;
        output io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_13;
        output io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_14;
        output io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_15;
        output io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_16;
        output io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_17;
        output io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_18;
        output io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_19;
        output io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_2;
        output io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_20;
        output io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_21;
        output io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_22;
        output io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_23;
        output io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_3;
        output io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_4;
        output io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_5;
        output io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_6;
        output io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_7;
        output io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_8;
        output io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_9;
        output io_ooo_to_mem_enqLsq_req_5_bits_flushPipe;
        output io_ooo_to_mem_enqLsq_req_5_bits_fuOpType;
        output io_ooo_to_mem_enqLsq_req_5_bits_lastUop;
        output io_ooo_to_mem_enqLsq_req_5_bits_trigger;
    endclocking:drv_cb

    clocking mon_cb @(posedge clk);
        `ifdef INTERFACE_ADD_DELAY
            default input #`DEF_SETUP_TIME output #`DEF_HOLD_TIME;
        `endif
        input  io_ooo_to_mem_enqLsq_needAlloc_0;
        input  io_ooo_to_mem_enqLsq_needAlloc_1;
        input  io_ooo_to_mem_enqLsq_needAlloc_2;
        input  io_ooo_to_mem_enqLsq_needAlloc_3;
        input  io_ooo_to_mem_enqLsq_needAlloc_4;
        input  io_ooo_to_mem_enqLsq_needAlloc_5;
        input  io_ooo_to_mem_enqLsq_req_0_valid;
        input  io_ooo_to_mem_enqLsq_req_0_bits_fuType;
        input  io_ooo_to_mem_enqLsq_req_0_bits_uopIdx;
        input  io_ooo_to_mem_enqLsq_req_0_bits_robIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_0_bits_robIdx_value;
        input  io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_value;
        input  io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_value;
        input  io_ooo_to_mem_enqLsq_req_0_bits_numLsElem;
        input  io_ooo_to_mem_enqLsq_req_1_valid;
        input  io_ooo_to_mem_enqLsq_req_1_bits_fuType;
        input  io_ooo_to_mem_enqLsq_req_1_bits_uopIdx;
        input  io_ooo_to_mem_enqLsq_req_1_bits_robIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_1_bits_robIdx_value;
        input  io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_value;
        input  io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_value;
        input  io_ooo_to_mem_enqLsq_req_1_bits_numLsElem;
        input  io_ooo_to_mem_enqLsq_req_2_valid;
        input  io_ooo_to_mem_enqLsq_req_2_bits_fuType;
        input  io_ooo_to_mem_enqLsq_req_2_bits_uopIdx;
        input  io_ooo_to_mem_enqLsq_req_2_bits_robIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_2_bits_robIdx_value;
        input  io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_value;
        input  io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_value;
        input  io_ooo_to_mem_enqLsq_req_2_bits_numLsElem;
        input  io_ooo_to_mem_enqLsq_req_3_valid;
        input  io_ooo_to_mem_enqLsq_req_3_bits_fuType;
        input  io_ooo_to_mem_enqLsq_req_3_bits_uopIdx;
        input  io_ooo_to_mem_enqLsq_req_3_bits_robIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_3_bits_robIdx_value;
        input  io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_value;
        input  io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_value;
        input  io_ooo_to_mem_enqLsq_req_3_bits_numLsElem;
        input  io_ooo_to_mem_enqLsq_req_4_valid;
        input  io_ooo_to_mem_enqLsq_req_4_bits_fuType;
        input  io_ooo_to_mem_enqLsq_req_4_bits_uopIdx;
        input  io_ooo_to_mem_enqLsq_req_4_bits_robIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_4_bits_robIdx_value;
        input  io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_value;
        input  io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_value;
        input  io_ooo_to_mem_enqLsq_req_4_bits_numLsElem;
        input  io_ooo_to_mem_enqLsq_req_5_valid;
        input  io_ooo_to_mem_enqLsq_req_5_bits_fuType;
        input  io_ooo_to_mem_enqLsq_req_5_bits_uopIdx;
        input  io_ooo_to_mem_enqLsq_req_5_bits_robIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_5_bits_robIdx_value;
        input  io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_value;
        input  io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_value;
        input  io_ooo_to_mem_enqLsq_req_5_bits_numLsElem;

        input  io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_0;
        input  io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_1;
        input  io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_10;
        input  io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_11;
        input  io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_12;
        input  io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_13;
        input  io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_14;
        input  io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_15;
        input  io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_16;
        input  io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_17;
        input  io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_18;
        input  io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_19;
        input  io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_2;
        input  io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_20;
        input  io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_21;
        input  io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_22;
        input  io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_23;
        input  io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_3;
        input  io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_4;
        input  io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_5;
        input  io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_6;
        input  io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_7;
        input  io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_8;
        input  io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_9;
        input  io_ooo_to_mem_enqLsq_req_0_bits_flushPipe;
        input  io_ooo_to_mem_enqLsq_req_0_bits_fuOpType;
        input  io_ooo_to_mem_enqLsq_req_0_bits_lastUop;
        input  io_ooo_to_mem_enqLsq_req_0_bits_trigger;
        input  io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_0;
        input  io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_1;
        input  io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_10;
        input  io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_11;
        input  io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_12;
        input  io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_13;
        input  io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_14;
        input  io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_15;
        input  io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_16;
        input  io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_17;
        input  io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_18;
        input  io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_19;
        input  io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_2;
        input  io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_20;
        input  io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_21;
        input  io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_22;
        input  io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_23;
        input  io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_3;
        input  io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_4;
        input  io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_5;
        input  io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_6;
        input  io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_7;
        input  io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_8;
        input  io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_9;
        input  io_ooo_to_mem_enqLsq_req_1_bits_flushPipe;
        input  io_ooo_to_mem_enqLsq_req_1_bits_fuOpType;
        input  io_ooo_to_mem_enqLsq_req_1_bits_lastUop;
        input  io_ooo_to_mem_enqLsq_req_1_bits_trigger;
        input  io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_0;
        input  io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_1;
        input  io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_10;
        input  io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_11;
        input  io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_12;
        input  io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_13;
        input  io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_14;
        input  io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_15;
        input  io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_16;
        input  io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_17;
        input  io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_18;
        input  io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_19;
        input  io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_2;
        input  io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_20;
        input  io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_21;
        input  io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_22;
        input  io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_23;
        input  io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_3;
        input  io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_4;
        input  io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_5;
        input  io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_6;
        input  io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_7;
        input  io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_8;
        input  io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_9;
        input  io_ooo_to_mem_enqLsq_req_2_bits_flushPipe;
        input  io_ooo_to_mem_enqLsq_req_2_bits_fuOpType;
        input  io_ooo_to_mem_enqLsq_req_2_bits_lastUop;
        input  io_ooo_to_mem_enqLsq_req_2_bits_trigger;
        input  io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_0;
        input  io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_1;
        input  io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_10;
        input  io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_11;
        input  io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_12;
        input  io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_13;
        input  io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_14;
        input  io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_15;
        input  io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_16;
        input  io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_17;
        input  io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_18;
        input  io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_19;
        input  io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_2;
        input  io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_20;
        input  io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_21;
        input  io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_22;
        input  io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_23;
        input  io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_3;
        input  io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_4;
        input  io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_5;
        input  io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_6;
        input  io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_7;
        input  io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_8;
        input  io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_9;
        input  io_ooo_to_mem_enqLsq_req_3_bits_flushPipe;
        input  io_ooo_to_mem_enqLsq_req_3_bits_fuOpType;
        input  io_ooo_to_mem_enqLsq_req_3_bits_lastUop;
        input  io_ooo_to_mem_enqLsq_req_3_bits_trigger;
        input  io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_0;
        input  io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_1;
        input  io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_10;
        input  io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_11;
        input  io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_12;
        input  io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_13;
        input  io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_14;
        input  io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_15;
        input  io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_16;
        input  io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_17;
        input  io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_18;
        input  io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_19;
        input  io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_2;
        input  io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_20;
        input  io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_21;
        input  io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_22;
        input  io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_23;
        input  io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_3;
        input  io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_4;
        input  io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_5;
        input  io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_6;
        input  io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_7;
        input  io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_8;
        input  io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_9;
        input  io_ooo_to_mem_enqLsq_req_4_bits_flushPipe;
        input  io_ooo_to_mem_enqLsq_req_4_bits_fuOpType;
        input  io_ooo_to_mem_enqLsq_req_4_bits_lastUop;
        input  io_ooo_to_mem_enqLsq_req_4_bits_trigger;
        input  io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_0;
        input  io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_1;
        input  io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_10;
        input  io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_11;
        input  io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_12;
        input  io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_13;
        input  io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_14;
        input  io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_15;
        input  io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_16;
        input  io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_17;
        input  io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_18;
        input  io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_19;
        input  io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_2;
        input  io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_20;
        input  io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_21;
        input  io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_22;
        input  io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_23;
        input  io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_3;
        input  io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_4;
        input  io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_5;
        input  io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_6;
        input  io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_7;
        input  io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_8;
        input  io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_9;
        input  io_ooo_to_mem_enqLsq_req_5_bits_flushPipe;
        input  io_ooo_to_mem_enqLsq_req_5_bits_fuOpType;
        input  io_ooo_to_mem_enqLsq_req_5_bits_lastUop;
        input  io_ooo_to_mem_enqLsq_req_5_bits_trigger;
    endclocking:mon_cb

    modport drv_mp (clocking drv_cb);
    modport mon_mp (clocking mon_cb);

endinterface:lsqenq_agent_agent_interface

`endif
