//=========================================================
//File name    : lsqenq_agent_agent_monitor.sv
//Author       : OpenAI_Codex
//Module name  : lsqenq_agent_agent_monitor
//Discribution : lsqenq_agent_agent_monitor : monitor
//Date         : 2026-04-12
//=========================================================
`ifndef LSQENQ_AGENT_AGENT_MONITOR__SV
`define LSQENQ_AGENT_AGENT_MONITOR__SV

class lsqenq_agent_agent_monitor  extends tcnt_monitor_base#(virtual lsqenq_agent_agent_interface,lsqenq_agent_agent_cfg,lsqenq_agent_agent_xaction);

    `uvm_component_utils(lsqenq_agent_agent_monitor)

    extern function new(string name, uvm_component parent);
    extern virtual function void build_phase(uvm_phase phase);
    extern task run_phase(uvm_phase phase);
    extern task mon_data();
endclass:lsqenq_agent_agent_monitor

function lsqenq_agent_agent_monitor::new(string name, uvm_component parent);
    super.new(name,parent);
endfunction:new

function void lsqenq_agent_agent_monitor::build_phase(uvm_phase phase);
    super.build_phase(phase);
endfunction:build_phase

task lsqenq_agent_agent_monitor::run_phase(uvm_phase phase);
    super.run_phase(phase);
    this.mon_data();
endtask:run_phase

task lsqenq_agent_agent_monitor::mon_data();

    logic io_ooo_to_mem_enqLsq_canAccept;
    logic [1:0] io_ooo_to_mem_enqLsq_needAlloc_0;
    logic [1:0] io_ooo_to_mem_enqLsq_needAlloc_1;
    logic [1:0] io_ooo_to_mem_enqLsq_needAlloc_2;
    logic [1:0] io_ooo_to_mem_enqLsq_needAlloc_3;
    logic [1:0] io_ooo_to_mem_enqLsq_needAlloc_4;
    logic [1:0] io_ooo_to_mem_enqLsq_needAlloc_5;
    logic [1:0] io_ooo_to_mem_enqLsq_needAlloc_6;
    logic [1:0] io_ooo_to_mem_enqLsq_needAlloc_7;
    logic io_ooo_to_mem_enqLsq_req_0_valid;
    logic [35:0] io_ooo_to_mem_enqLsq_req_0_bits_fuType;
    logic [6:0] io_ooo_to_mem_enqLsq_req_0_bits_uopIdx;
    logic io_ooo_to_mem_enqLsq_req_0_bits_robIdx_flag;
    logic [8:0] io_ooo_to_mem_enqLsq_req_0_bits_robIdx_value;
    logic io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_value;
    logic [4:0] io_ooo_to_mem_enqLsq_req_0_bits_numLsElem;
    logic io_ooo_to_mem_enqLsq_req_1_valid;
    logic [35:0] io_ooo_to_mem_enqLsq_req_1_bits_fuType;
    logic [6:0] io_ooo_to_mem_enqLsq_req_1_bits_uopIdx;
    logic io_ooo_to_mem_enqLsq_req_1_bits_robIdx_flag;
    logic [8:0] io_ooo_to_mem_enqLsq_req_1_bits_robIdx_value;
    logic io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_value;
    logic [4:0] io_ooo_to_mem_enqLsq_req_1_bits_numLsElem;
    logic io_ooo_to_mem_enqLsq_req_2_valid;
    logic [35:0] io_ooo_to_mem_enqLsq_req_2_bits_fuType;
    logic [6:0] io_ooo_to_mem_enqLsq_req_2_bits_uopIdx;
    logic io_ooo_to_mem_enqLsq_req_2_bits_robIdx_flag;
    logic [8:0] io_ooo_to_mem_enqLsq_req_2_bits_robIdx_value;
    logic io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_value;
    logic [4:0] io_ooo_to_mem_enqLsq_req_2_bits_numLsElem;
    logic io_ooo_to_mem_enqLsq_req_3_valid;
    logic [35:0] io_ooo_to_mem_enqLsq_req_3_bits_fuType;
    logic [6:0] io_ooo_to_mem_enqLsq_req_3_bits_uopIdx;
    logic io_ooo_to_mem_enqLsq_req_3_bits_robIdx_flag;
    logic [8:0] io_ooo_to_mem_enqLsq_req_3_bits_robIdx_value;
    logic io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_value;
    logic [4:0] io_ooo_to_mem_enqLsq_req_3_bits_numLsElem;
    logic io_ooo_to_mem_enqLsq_req_4_valid;
    logic [35:0] io_ooo_to_mem_enqLsq_req_4_bits_fuType;
    logic [6:0] io_ooo_to_mem_enqLsq_req_4_bits_uopIdx;
    logic io_ooo_to_mem_enqLsq_req_4_bits_robIdx_flag;
    logic [8:0] io_ooo_to_mem_enqLsq_req_4_bits_robIdx_value;
    logic io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_value;
    logic [4:0] io_ooo_to_mem_enqLsq_req_4_bits_numLsElem;
    logic io_ooo_to_mem_enqLsq_req_5_valid;
    logic [35:0] io_ooo_to_mem_enqLsq_req_5_bits_fuType;
    logic [6:0] io_ooo_to_mem_enqLsq_req_5_bits_uopIdx;
    logic io_ooo_to_mem_enqLsq_req_5_bits_robIdx_flag;
    logic [8:0] io_ooo_to_mem_enqLsq_req_5_bits_robIdx_value;
    logic io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_value;
    logic [4:0] io_ooo_to_mem_enqLsq_req_5_bits_numLsElem;
    logic io_ooo_to_mem_enqLsq_req_6_valid;
    logic [35:0] io_ooo_to_mem_enqLsq_req_6_bits_fuType;
    logic [6:0] io_ooo_to_mem_enqLsq_req_6_bits_uopIdx;
    logic io_ooo_to_mem_enqLsq_req_6_bits_robIdx_flag;
    logic [8:0] io_ooo_to_mem_enqLsq_req_6_bits_robIdx_value;
    logic io_ooo_to_mem_enqLsq_req_6_bits_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_enqLsq_req_6_bits_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_req_6_bits_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_enqLsq_req_6_bits_sqIdx_value;
    logic [4:0] io_ooo_to_mem_enqLsq_req_6_bits_numLsElem;
    logic io_ooo_to_mem_enqLsq_req_7_valid;
    logic [35:0] io_ooo_to_mem_enqLsq_req_7_bits_fuType;
    logic [6:0] io_ooo_to_mem_enqLsq_req_7_bits_uopIdx;
    logic io_ooo_to_mem_enqLsq_req_7_bits_robIdx_flag;
    logic [8:0] io_ooo_to_mem_enqLsq_req_7_bits_robIdx_value;
    logic io_ooo_to_mem_enqLsq_req_7_bits_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_enqLsq_req_7_bits_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_req_7_bits_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_enqLsq_req_7_bits_sqIdx_value;
    logic [4:0] io_ooo_to_mem_enqLsq_req_7_bits_numLsElem;
    logic io_ooo_to_mem_enqLsq_resp_0_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_enqLsq_resp_0_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_resp_0_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_enqLsq_resp_0_sqIdx_value;
    logic io_ooo_to_mem_enqLsq_resp_1_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_enqLsq_resp_1_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_resp_1_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_enqLsq_resp_1_sqIdx_value;
    logic io_ooo_to_mem_enqLsq_resp_2_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_enqLsq_resp_2_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_resp_2_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_enqLsq_resp_2_sqIdx_value;
    logic io_ooo_to_mem_enqLsq_resp_3_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_enqLsq_resp_3_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_resp_3_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_enqLsq_resp_3_sqIdx_value;
    logic io_ooo_to_mem_enqLsq_resp_4_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_enqLsq_resp_4_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_resp_4_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_enqLsq_resp_4_sqIdx_value;
    logic io_ooo_to_mem_enqLsq_resp_5_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_enqLsq_resp_5_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_resp_5_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_enqLsq_resp_5_sqIdx_value;
    logic io_ooo_to_mem_enqLsq_resp_6_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_enqLsq_resp_6_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_resp_6_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_enqLsq_resp_6_sqIdx_value;
    logic io_ooo_to_mem_enqLsq_resp_7_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_enqLsq_resp_7_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_resp_7_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_enqLsq_resp_7_sqIdx_value;

    lsqenq_agent_agent_xaction  mon_tr;
    while(1) begin
        @this.vif.mon_mp.mon_cb;
        io_ooo_to_mem_enqLsq_canAccept = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_canAccept;
        io_ooo_to_mem_enqLsq_needAlloc_0 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_needAlloc_0;
        io_ooo_to_mem_enqLsq_needAlloc_1 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_needAlloc_1;
        io_ooo_to_mem_enqLsq_needAlloc_2 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_needAlloc_2;
        io_ooo_to_mem_enqLsq_needAlloc_3 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_needAlloc_3;
        io_ooo_to_mem_enqLsq_needAlloc_4 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_needAlloc_4;
        io_ooo_to_mem_enqLsq_needAlloc_5 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_needAlloc_5;
        io_ooo_to_mem_enqLsq_needAlloc_6 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_needAlloc_6;
        io_ooo_to_mem_enqLsq_needAlloc_7 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_needAlloc_7;
        io_ooo_to_mem_enqLsq_req_0_valid = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_valid;
        io_ooo_to_mem_enqLsq_req_0_bits_fuType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_fuType;
        io_ooo_to_mem_enqLsq_req_0_bits_uopIdx = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_uopIdx;
        io_ooo_to_mem_enqLsq_req_0_bits_robIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_robIdx_flag;
        io_ooo_to_mem_enqLsq_req_0_bits_robIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_robIdx_value;
        io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_flag;
        io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_value;
        io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_flag;
        io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_value;
        io_ooo_to_mem_enqLsq_req_0_bits_numLsElem = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_numLsElem;
        io_ooo_to_mem_enqLsq_req_1_valid = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_valid;
        io_ooo_to_mem_enqLsq_req_1_bits_fuType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_fuType;
        io_ooo_to_mem_enqLsq_req_1_bits_uopIdx = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_uopIdx;
        io_ooo_to_mem_enqLsq_req_1_bits_robIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_robIdx_flag;
        io_ooo_to_mem_enqLsq_req_1_bits_robIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_robIdx_value;
        io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_flag;
        io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_value;
        io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_flag;
        io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_value;
        io_ooo_to_mem_enqLsq_req_1_bits_numLsElem = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_numLsElem;
        io_ooo_to_mem_enqLsq_req_2_valid = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_valid;
        io_ooo_to_mem_enqLsq_req_2_bits_fuType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_fuType;
        io_ooo_to_mem_enqLsq_req_2_bits_uopIdx = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_uopIdx;
        io_ooo_to_mem_enqLsq_req_2_bits_robIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_robIdx_flag;
        io_ooo_to_mem_enqLsq_req_2_bits_robIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_robIdx_value;
        io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_flag;
        io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_value;
        io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_flag;
        io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_value;
        io_ooo_to_mem_enqLsq_req_2_bits_numLsElem = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_numLsElem;
        io_ooo_to_mem_enqLsq_req_3_valid = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_valid;
        io_ooo_to_mem_enqLsq_req_3_bits_fuType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_fuType;
        io_ooo_to_mem_enqLsq_req_3_bits_uopIdx = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_uopIdx;
        io_ooo_to_mem_enqLsq_req_3_bits_robIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_robIdx_flag;
        io_ooo_to_mem_enqLsq_req_3_bits_robIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_robIdx_value;
        io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_flag;
        io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_value;
        io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_flag;
        io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_value;
        io_ooo_to_mem_enqLsq_req_3_bits_numLsElem = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_numLsElem;
        io_ooo_to_mem_enqLsq_req_4_valid = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_valid;
        io_ooo_to_mem_enqLsq_req_4_bits_fuType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_fuType;
        io_ooo_to_mem_enqLsq_req_4_bits_uopIdx = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_uopIdx;
        io_ooo_to_mem_enqLsq_req_4_bits_robIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_robIdx_flag;
        io_ooo_to_mem_enqLsq_req_4_bits_robIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_robIdx_value;
        io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_flag;
        io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_value;
        io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_flag;
        io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_value;
        io_ooo_to_mem_enqLsq_req_4_bits_numLsElem = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_numLsElem;
        io_ooo_to_mem_enqLsq_req_5_valid = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_valid;
        io_ooo_to_mem_enqLsq_req_5_bits_fuType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_fuType;
        io_ooo_to_mem_enqLsq_req_5_bits_uopIdx = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_uopIdx;
        io_ooo_to_mem_enqLsq_req_5_bits_robIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_robIdx_flag;
        io_ooo_to_mem_enqLsq_req_5_bits_robIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_robIdx_value;
        io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_flag;
        io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_value;
        io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_flag;
        io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_value;
        io_ooo_to_mem_enqLsq_req_5_bits_numLsElem = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_numLsElem;
        io_ooo_to_mem_enqLsq_req_6_valid = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_6_valid;
        io_ooo_to_mem_enqLsq_req_6_bits_fuType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_6_bits_fuType;
        io_ooo_to_mem_enqLsq_req_6_bits_uopIdx = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_6_bits_uopIdx;
        io_ooo_to_mem_enqLsq_req_6_bits_robIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_6_bits_robIdx_flag;
        io_ooo_to_mem_enqLsq_req_6_bits_robIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_6_bits_robIdx_value;
        io_ooo_to_mem_enqLsq_req_6_bits_lqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_6_bits_lqIdx_flag;
        io_ooo_to_mem_enqLsq_req_6_bits_lqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_6_bits_lqIdx_value;
        io_ooo_to_mem_enqLsq_req_6_bits_sqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_6_bits_sqIdx_flag;
        io_ooo_to_mem_enqLsq_req_6_bits_sqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_6_bits_sqIdx_value;
        io_ooo_to_mem_enqLsq_req_6_bits_numLsElem = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_6_bits_numLsElem;
        io_ooo_to_mem_enqLsq_req_7_valid = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_7_valid;
        io_ooo_to_mem_enqLsq_req_7_bits_fuType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_7_bits_fuType;
        io_ooo_to_mem_enqLsq_req_7_bits_uopIdx = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_7_bits_uopIdx;
        io_ooo_to_mem_enqLsq_req_7_bits_robIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_7_bits_robIdx_flag;
        io_ooo_to_mem_enqLsq_req_7_bits_robIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_7_bits_robIdx_value;
        io_ooo_to_mem_enqLsq_req_7_bits_lqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_7_bits_lqIdx_flag;
        io_ooo_to_mem_enqLsq_req_7_bits_lqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_7_bits_lqIdx_value;
        io_ooo_to_mem_enqLsq_req_7_bits_sqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_7_bits_sqIdx_flag;
        io_ooo_to_mem_enqLsq_req_7_bits_sqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_7_bits_sqIdx_value;
        io_ooo_to_mem_enqLsq_req_7_bits_numLsElem = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_7_bits_numLsElem;
        io_ooo_to_mem_enqLsq_resp_0_lqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_resp_0_lqIdx_flag;
        io_ooo_to_mem_enqLsq_resp_0_lqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_resp_0_lqIdx_value;
        io_ooo_to_mem_enqLsq_resp_0_sqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_resp_0_sqIdx_flag;
        io_ooo_to_mem_enqLsq_resp_0_sqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_resp_0_sqIdx_value;
        io_ooo_to_mem_enqLsq_resp_1_lqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_resp_1_lqIdx_flag;
        io_ooo_to_mem_enqLsq_resp_1_lqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_resp_1_lqIdx_value;
        io_ooo_to_mem_enqLsq_resp_1_sqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_resp_1_sqIdx_flag;
        io_ooo_to_mem_enqLsq_resp_1_sqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_resp_1_sqIdx_value;
        io_ooo_to_mem_enqLsq_resp_2_lqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_resp_2_lqIdx_flag;
        io_ooo_to_mem_enqLsq_resp_2_lqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_resp_2_lqIdx_value;
        io_ooo_to_mem_enqLsq_resp_2_sqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_resp_2_sqIdx_flag;
        io_ooo_to_mem_enqLsq_resp_2_sqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_resp_2_sqIdx_value;
        io_ooo_to_mem_enqLsq_resp_3_lqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_resp_3_lqIdx_flag;
        io_ooo_to_mem_enqLsq_resp_3_lqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_resp_3_lqIdx_value;
        io_ooo_to_mem_enqLsq_resp_3_sqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_resp_3_sqIdx_flag;
        io_ooo_to_mem_enqLsq_resp_3_sqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_resp_3_sqIdx_value;
        io_ooo_to_mem_enqLsq_resp_4_lqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_resp_4_lqIdx_flag;
        io_ooo_to_mem_enqLsq_resp_4_lqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_resp_4_lqIdx_value;
        io_ooo_to_mem_enqLsq_resp_4_sqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_resp_4_sqIdx_flag;
        io_ooo_to_mem_enqLsq_resp_4_sqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_resp_4_sqIdx_value;
        io_ooo_to_mem_enqLsq_resp_5_lqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_resp_5_lqIdx_flag;
        io_ooo_to_mem_enqLsq_resp_5_lqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_resp_5_lqIdx_value;
        io_ooo_to_mem_enqLsq_resp_5_sqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_resp_5_sqIdx_flag;
        io_ooo_to_mem_enqLsq_resp_5_sqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_resp_5_sqIdx_value;
        io_ooo_to_mem_enqLsq_resp_6_lqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_resp_6_lqIdx_flag;
        io_ooo_to_mem_enqLsq_resp_6_lqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_resp_6_lqIdx_value;
        io_ooo_to_mem_enqLsq_resp_6_sqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_resp_6_sqIdx_flag;
        io_ooo_to_mem_enqLsq_resp_6_sqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_resp_6_sqIdx_value;
        io_ooo_to_mem_enqLsq_resp_7_lqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_resp_7_lqIdx_flag;
        io_ooo_to_mem_enqLsq_resp_7_lqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_resp_7_lqIdx_value;
        io_ooo_to_mem_enqLsq_resp_7_sqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_resp_7_sqIdx_flag;
        io_ooo_to_mem_enqLsq_resp_7_sqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_resp_7_sqIdx_value;

        if(this.cfg.xz_sw==tcnt_dec_base::ON && this.vif.rst_n==1'b1 && memblock_sync_pkg::reset_backend_done==1'b1) begin
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_canAccept,io_ooo_to_mem_enqLsq_canAccept,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_needAlloc_0,io_ooo_to_mem_enqLsq_needAlloc_0,2);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_needAlloc_1,io_ooo_to_mem_enqLsq_needAlloc_1,2);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_needAlloc_2,io_ooo_to_mem_enqLsq_needAlloc_2,2);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_needAlloc_3,io_ooo_to_mem_enqLsq_needAlloc_3,2);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_needAlloc_4,io_ooo_to_mem_enqLsq_needAlloc_4,2);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_needAlloc_5,io_ooo_to_mem_enqLsq_needAlloc_5,2);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_needAlloc_6,io_ooo_to_mem_enqLsq_needAlloc_6,2);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_needAlloc_7,io_ooo_to_mem_enqLsq_needAlloc_7,2);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_0_valid,io_ooo_to_mem_enqLsq_req_0_valid,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_0_bits_fuType,io_ooo_to_mem_enqLsq_req_0_bits_fuType,36);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_0_bits_uopIdx,io_ooo_to_mem_enqLsq_req_0_bits_uopIdx,7);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_0_bits_robIdx_flag,io_ooo_to_mem_enqLsq_req_0_bits_robIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_0_bits_robIdx_value,io_ooo_to_mem_enqLsq_req_0_bits_robIdx_value,9);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_flag,io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_value,io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_value,7);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_flag,io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_value,io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_value,6);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_0_bits_numLsElem,io_ooo_to_mem_enqLsq_req_0_bits_numLsElem,5);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_1_valid,io_ooo_to_mem_enqLsq_req_1_valid,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_1_bits_fuType,io_ooo_to_mem_enqLsq_req_1_bits_fuType,36);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_1_bits_uopIdx,io_ooo_to_mem_enqLsq_req_1_bits_uopIdx,7);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_1_bits_robIdx_flag,io_ooo_to_mem_enqLsq_req_1_bits_robIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_1_bits_robIdx_value,io_ooo_to_mem_enqLsq_req_1_bits_robIdx_value,9);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_flag,io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_value,io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_value,7);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_flag,io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_value,io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_value,6);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_1_bits_numLsElem,io_ooo_to_mem_enqLsq_req_1_bits_numLsElem,5);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_2_valid,io_ooo_to_mem_enqLsq_req_2_valid,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_2_bits_fuType,io_ooo_to_mem_enqLsq_req_2_bits_fuType,36);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_2_bits_uopIdx,io_ooo_to_mem_enqLsq_req_2_bits_uopIdx,7);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_2_bits_robIdx_flag,io_ooo_to_mem_enqLsq_req_2_bits_robIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_2_bits_robIdx_value,io_ooo_to_mem_enqLsq_req_2_bits_robIdx_value,9);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_flag,io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_value,io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_value,7);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_flag,io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_value,io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_value,6);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_2_bits_numLsElem,io_ooo_to_mem_enqLsq_req_2_bits_numLsElem,5);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_3_valid,io_ooo_to_mem_enqLsq_req_3_valid,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_3_bits_fuType,io_ooo_to_mem_enqLsq_req_3_bits_fuType,36);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_3_bits_uopIdx,io_ooo_to_mem_enqLsq_req_3_bits_uopIdx,7);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_3_bits_robIdx_flag,io_ooo_to_mem_enqLsq_req_3_bits_robIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_3_bits_robIdx_value,io_ooo_to_mem_enqLsq_req_3_bits_robIdx_value,9);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_flag,io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_value,io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_value,7);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_flag,io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_value,io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_value,6);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_3_bits_numLsElem,io_ooo_to_mem_enqLsq_req_3_bits_numLsElem,5);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_4_valid,io_ooo_to_mem_enqLsq_req_4_valid,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_4_bits_fuType,io_ooo_to_mem_enqLsq_req_4_bits_fuType,36);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_4_bits_uopIdx,io_ooo_to_mem_enqLsq_req_4_bits_uopIdx,7);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_4_bits_robIdx_flag,io_ooo_to_mem_enqLsq_req_4_bits_robIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_4_bits_robIdx_value,io_ooo_to_mem_enqLsq_req_4_bits_robIdx_value,9);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_flag,io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_value,io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_value,7);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_flag,io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_value,io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_value,6);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_4_bits_numLsElem,io_ooo_to_mem_enqLsq_req_4_bits_numLsElem,5);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_5_valid,io_ooo_to_mem_enqLsq_req_5_valid,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_5_bits_fuType,io_ooo_to_mem_enqLsq_req_5_bits_fuType,36);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_5_bits_uopIdx,io_ooo_to_mem_enqLsq_req_5_bits_uopIdx,7);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_5_bits_robIdx_flag,io_ooo_to_mem_enqLsq_req_5_bits_robIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_5_bits_robIdx_value,io_ooo_to_mem_enqLsq_req_5_bits_robIdx_value,9);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_flag,io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_value,io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_value,7);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_flag,io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_value,io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_value,6);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_5_bits_numLsElem,io_ooo_to_mem_enqLsq_req_5_bits_numLsElem,5);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_6_valid,io_ooo_to_mem_enqLsq_req_6_valid,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_6_bits_fuType,io_ooo_to_mem_enqLsq_req_6_bits_fuType,36);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_6_bits_uopIdx,io_ooo_to_mem_enqLsq_req_6_bits_uopIdx,7);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_6_bits_robIdx_flag,io_ooo_to_mem_enqLsq_req_6_bits_robIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_6_bits_robIdx_value,io_ooo_to_mem_enqLsq_req_6_bits_robIdx_value,9);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_6_bits_lqIdx_flag,io_ooo_to_mem_enqLsq_req_6_bits_lqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_6_bits_lqIdx_value,io_ooo_to_mem_enqLsq_req_6_bits_lqIdx_value,7);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_6_bits_sqIdx_flag,io_ooo_to_mem_enqLsq_req_6_bits_sqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_6_bits_sqIdx_value,io_ooo_to_mem_enqLsq_req_6_bits_sqIdx_value,6);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_6_bits_numLsElem,io_ooo_to_mem_enqLsq_req_6_bits_numLsElem,5);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_7_valid,io_ooo_to_mem_enqLsq_req_7_valid,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_7_bits_fuType,io_ooo_to_mem_enqLsq_req_7_bits_fuType,36);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_7_bits_uopIdx,io_ooo_to_mem_enqLsq_req_7_bits_uopIdx,7);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_7_bits_robIdx_flag,io_ooo_to_mem_enqLsq_req_7_bits_robIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_7_bits_robIdx_value,io_ooo_to_mem_enqLsq_req_7_bits_robIdx_value,9);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_7_bits_lqIdx_flag,io_ooo_to_mem_enqLsq_req_7_bits_lqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_7_bits_lqIdx_value,io_ooo_to_mem_enqLsq_req_7_bits_lqIdx_value,7);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_7_bits_sqIdx_flag,io_ooo_to_mem_enqLsq_req_7_bits_sqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_7_bits_sqIdx_value,io_ooo_to_mem_enqLsq_req_7_bits_sqIdx_value,6);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_7_bits_numLsElem,io_ooo_to_mem_enqLsq_req_7_bits_numLsElem,5);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_resp_0_lqIdx_flag,io_ooo_to_mem_enqLsq_resp_0_lqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_resp_0_lqIdx_value,io_ooo_to_mem_enqLsq_resp_0_lqIdx_value,7);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_resp_0_sqIdx_flag,io_ooo_to_mem_enqLsq_resp_0_sqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_resp_0_sqIdx_value,io_ooo_to_mem_enqLsq_resp_0_sqIdx_value,6);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_resp_1_lqIdx_flag,io_ooo_to_mem_enqLsq_resp_1_lqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_resp_1_lqIdx_value,io_ooo_to_mem_enqLsq_resp_1_lqIdx_value,7);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_resp_1_sqIdx_flag,io_ooo_to_mem_enqLsq_resp_1_sqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_resp_1_sqIdx_value,io_ooo_to_mem_enqLsq_resp_1_sqIdx_value,6);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_resp_2_lqIdx_flag,io_ooo_to_mem_enqLsq_resp_2_lqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_resp_2_lqIdx_value,io_ooo_to_mem_enqLsq_resp_2_lqIdx_value,7);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_resp_2_sqIdx_flag,io_ooo_to_mem_enqLsq_resp_2_sqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_resp_2_sqIdx_value,io_ooo_to_mem_enqLsq_resp_2_sqIdx_value,6);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_resp_3_lqIdx_flag,io_ooo_to_mem_enqLsq_resp_3_lqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_resp_3_lqIdx_value,io_ooo_to_mem_enqLsq_resp_3_lqIdx_value,7);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_resp_3_sqIdx_flag,io_ooo_to_mem_enqLsq_resp_3_sqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_resp_3_sqIdx_value,io_ooo_to_mem_enqLsq_resp_3_sqIdx_value,6);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_resp_4_lqIdx_flag,io_ooo_to_mem_enqLsq_resp_4_lqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_resp_4_lqIdx_value,io_ooo_to_mem_enqLsq_resp_4_lqIdx_value,7);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_resp_4_sqIdx_flag,io_ooo_to_mem_enqLsq_resp_4_sqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_resp_4_sqIdx_value,io_ooo_to_mem_enqLsq_resp_4_sqIdx_value,6);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_resp_5_lqIdx_flag,io_ooo_to_mem_enqLsq_resp_5_lqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_resp_5_lqIdx_value,io_ooo_to_mem_enqLsq_resp_5_lqIdx_value,7);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_resp_5_sqIdx_flag,io_ooo_to_mem_enqLsq_resp_5_sqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_resp_5_sqIdx_value,io_ooo_to_mem_enqLsq_resp_5_sqIdx_value,6);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_resp_6_lqIdx_flag,io_ooo_to_mem_enqLsq_resp_6_lqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_resp_6_lqIdx_value,io_ooo_to_mem_enqLsq_resp_6_lqIdx_value,7);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_resp_6_sqIdx_flag,io_ooo_to_mem_enqLsq_resp_6_sqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_resp_6_sqIdx_value,io_ooo_to_mem_enqLsq_resp_6_sqIdx_value,6);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_resp_7_lqIdx_flag,io_ooo_to_mem_enqLsq_resp_7_lqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_resp_7_lqIdx_value,io_ooo_to_mem_enqLsq_resp_7_lqIdx_value,7);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_resp_7_sqIdx_flag,io_ooo_to_mem_enqLsq_resp_7_sqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_resp_7_sqIdx_value,io_ooo_to_mem_enqLsq_resp_7_sqIdx_value,6);

        end
        //if(xxxTODOxxx==1'b1) begin
        //    mon_tr = lsqenq_agent_agent_xaction::type_id::create("mon_tr");
        //    mon_tr.io_ooo_to_mem_enqLsq_canAccept = io_ooo_to_mem_enqLsq_canAccept;
        //    mon_tr.io_ooo_to_mem_enqLsq_needAlloc_0 = io_ooo_to_mem_enqLsq_needAlloc_0;
        //    mon_tr.io_ooo_to_mem_enqLsq_needAlloc_1 = io_ooo_to_mem_enqLsq_needAlloc_1;
        //    mon_tr.io_ooo_to_mem_enqLsq_needAlloc_2 = io_ooo_to_mem_enqLsq_needAlloc_2;
        //    mon_tr.io_ooo_to_mem_enqLsq_needAlloc_3 = io_ooo_to_mem_enqLsq_needAlloc_3;
        //    mon_tr.io_ooo_to_mem_enqLsq_needAlloc_4 = io_ooo_to_mem_enqLsq_needAlloc_4;
        //    mon_tr.io_ooo_to_mem_enqLsq_needAlloc_5 = io_ooo_to_mem_enqLsq_needAlloc_5;
        //    mon_tr.io_ooo_to_mem_enqLsq_needAlloc_6 = io_ooo_to_mem_enqLsq_needAlloc_6;
        //    mon_tr.io_ooo_to_mem_enqLsq_needAlloc_7 = io_ooo_to_mem_enqLsq_needAlloc_7;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_0_valid = io_ooo_to_mem_enqLsq_req_0_valid;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_0_bits_fuType = io_ooo_to_mem_enqLsq_req_0_bits_fuType;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_0_bits_uopIdx = io_ooo_to_mem_enqLsq_req_0_bits_uopIdx;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_0_bits_robIdx_flag = io_ooo_to_mem_enqLsq_req_0_bits_robIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_0_bits_robIdx_value = io_ooo_to_mem_enqLsq_req_0_bits_robIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_flag = io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_value = io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_flag = io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_value = io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_0_bits_numLsElem = io_ooo_to_mem_enqLsq_req_0_bits_numLsElem;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_1_valid = io_ooo_to_mem_enqLsq_req_1_valid;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_1_bits_fuType = io_ooo_to_mem_enqLsq_req_1_bits_fuType;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_1_bits_uopIdx = io_ooo_to_mem_enqLsq_req_1_bits_uopIdx;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_1_bits_robIdx_flag = io_ooo_to_mem_enqLsq_req_1_bits_robIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_1_bits_robIdx_value = io_ooo_to_mem_enqLsq_req_1_bits_robIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_flag = io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_value = io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_flag = io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_value = io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_1_bits_numLsElem = io_ooo_to_mem_enqLsq_req_1_bits_numLsElem;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_2_valid = io_ooo_to_mem_enqLsq_req_2_valid;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_2_bits_fuType = io_ooo_to_mem_enqLsq_req_2_bits_fuType;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_2_bits_uopIdx = io_ooo_to_mem_enqLsq_req_2_bits_uopIdx;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_2_bits_robIdx_flag = io_ooo_to_mem_enqLsq_req_2_bits_robIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_2_bits_robIdx_value = io_ooo_to_mem_enqLsq_req_2_bits_robIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_flag = io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_value = io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_flag = io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_value = io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_2_bits_numLsElem = io_ooo_to_mem_enqLsq_req_2_bits_numLsElem;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_3_valid = io_ooo_to_mem_enqLsq_req_3_valid;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_3_bits_fuType = io_ooo_to_mem_enqLsq_req_3_bits_fuType;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_3_bits_uopIdx = io_ooo_to_mem_enqLsq_req_3_bits_uopIdx;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_3_bits_robIdx_flag = io_ooo_to_mem_enqLsq_req_3_bits_robIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_3_bits_robIdx_value = io_ooo_to_mem_enqLsq_req_3_bits_robIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_flag = io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_value = io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_flag = io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_value = io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_3_bits_numLsElem = io_ooo_to_mem_enqLsq_req_3_bits_numLsElem;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_4_valid = io_ooo_to_mem_enqLsq_req_4_valid;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_4_bits_fuType = io_ooo_to_mem_enqLsq_req_4_bits_fuType;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_4_bits_uopIdx = io_ooo_to_mem_enqLsq_req_4_bits_uopIdx;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_4_bits_robIdx_flag = io_ooo_to_mem_enqLsq_req_4_bits_robIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_4_bits_robIdx_value = io_ooo_to_mem_enqLsq_req_4_bits_robIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_flag = io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_value = io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_flag = io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_value = io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_4_bits_numLsElem = io_ooo_to_mem_enqLsq_req_4_bits_numLsElem;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_5_valid = io_ooo_to_mem_enqLsq_req_5_valid;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_5_bits_fuType = io_ooo_to_mem_enqLsq_req_5_bits_fuType;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_5_bits_uopIdx = io_ooo_to_mem_enqLsq_req_5_bits_uopIdx;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_5_bits_robIdx_flag = io_ooo_to_mem_enqLsq_req_5_bits_robIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_5_bits_robIdx_value = io_ooo_to_mem_enqLsq_req_5_bits_robIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_flag = io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_value = io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_flag = io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_value = io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_5_bits_numLsElem = io_ooo_to_mem_enqLsq_req_5_bits_numLsElem;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_6_valid = io_ooo_to_mem_enqLsq_req_6_valid;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_6_bits_fuType = io_ooo_to_mem_enqLsq_req_6_bits_fuType;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_6_bits_uopIdx = io_ooo_to_mem_enqLsq_req_6_bits_uopIdx;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_6_bits_robIdx_flag = io_ooo_to_mem_enqLsq_req_6_bits_robIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_6_bits_robIdx_value = io_ooo_to_mem_enqLsq_req_6_bits_robIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_6_bits_lqIdx_flag = io_ooo_to_mem_enqLsq_req_6_bits_lqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_6_bits_lqIdx_value = io_ooo_to_mem_enqLsq_req_6_bits_lqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_6_bits_sqIdx_flag = io_ooo_to_mem_enqLsq_req_6_bits_sqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_6_bits_sqIdx_value = io_ooo_to_mem_enqLsq_req_6_bits_sqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_6_bits_numLsElem = io_ooo_to_mem_enqLsq_req_6_bits_numLsElem;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_7_valid = io_ooo_to_mem_enqLsq_req_7_valid;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_7_bits_fuType = io_ooo_to_mem_enqLsq_req_7_bits_fuType;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_7_bits_uopIdx = io_ooo_to_mem_enqLsq_req_7_bits_uopIdx;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_7_bits_robIdx_flag = io_ooo_to_mem_enqLsq_req_7_bits_robIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_7_bits_robIdx_value = io_ooo_to_mem_enqLsq_req_7_bits_robIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_7_bits_lqIdx_flag = io_ooo_to_mem_enqLsq_req_7_bits_lqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_7_bits_lqIdx_value = io_ooo_to_mem_enqLsq_req_7_bits_lqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_7_bits_sqIdx_flag = io_ooo_to_mem_enqLsq_req_7_bits_sqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_7_bits_sqIdx_value = io_ooo_to_mem_enqLsq_req_7_bits_sqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_7_bits_numLsElem = io_ooo_to_mem_enqLsq_req_7_bits_numLsElem;
        //    mon_tr.io_ooo_to_mem_enqLsq_resp_0_lqIdx_flag = io_ooo_to_mem_enqLsq_resp_0_lqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_resp_0_lqIdx_value = io_ooo_to_mem_enqLsq_resp_0_lqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_resp_0_sqIdx_flag = io_ooo_to_mem_enqLsq_resp_0_sqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_resp_0_sqIdx_value = io_ooo_to_mem_enqLsq_resp_0_sqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_resp_1_lqIdx_flag = io_ooo_to_mem_enqLsq_resp_1_lqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_resp_1_lqIdx_value = io_ooo_to_mem_enqLsq_resp_1_lqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_resp_1_sqIdx_flag = io_ooo_to_mem_enqLsq_resp_1_sqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_resp_1_sqIdx_value = io_ooo_to_mem_enqLsq_resp_1_sqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_resp_2_lqIdx_flag = io_ooo_to_mem_enqLsq_resp_2_lqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_resp_2_lqIdx_value = io_ooo_to_mem_enqLsq_resp_2_lqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_resp_2_sqIdx_flag = io_ooo_to_mem_enqLsq_resp_2_sqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_resp_2_sqIdx_value = io_ooo_to_mem_enqLsq_resp_2_sqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_resp_3_lqIdx_flag = io_ooo_to_mem_enqLsq_resp_3_lqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_resp_3_lqIdx_value = io_ooo_to_mem_enqLsq_resp_3_lqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_resp_3_sqIdx_flag = io_ooo_to_mem_enqLsq_resp_3_sqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_resp_3_sqIdx_value = io_ooo_to_mem_enqLsq_resp_3_sqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_resp_4_lqIdx_flag = io_ooo_to_mem_enqLsq_resp_4_lqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_resp_4_lqIdx_value = io_ooo_to_mem_enqLsq_resp_4_lqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_resp_4_sqIdx_flag = io_ooo_to_mem_enqLsq_resp_4_sqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_resp_4_sqIdx_value = io_ooo_to_mem_enqLsq_resp_4_sqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_resp_5_lqIdx_flag = io_ooo_to_mem_enqLsq_resp_5_lqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_resp_5_lqIdx_value = io_ooo_to_mem_enqLsq_resp_5_lqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_resp_5_sqIdx_flag = io_ooo_to_mem_enqLsq_resp_5_sqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_resp_5_sqIdx_value = io_ooo_to_mem_enqLsq_resp_5_sqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_resp_6_lqIdx_flag = io_ooo_to_mem_enqLsq_resp_6_lqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_resp_6_lqIdx_value = io_ooo_to_mem_enqLsq_resp_6_lqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_resp_6_sqIdx_flag = io_ooo_to_mem_enqLsq_resp_6_sqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_resp_6_sqIdx_value = io_ooo_to_mem_enqLsq_resp_6_sqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_resp_7_lqIdx_flag = io_ooo_to_mem_enqLsq_resp_7_lqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_resp_7_lqIdx_value = io_ooo_to_mem_enqLsq_resp_7_lqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_resp_7_sqIdx_flag = io_ooo_to_mem_enqLsq_resp_7_sqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_resp_7_sqIdx_value = io_ooo_to_mem_enqLsq_resp_7_sqIdx_value;

        //    mon_tr.channel_id = this.cfg.channel_id;
        //    mon_tr.unpack();
        //    this.mon_item_port.write(mon_tr);
        //end
    end
endtask:mon_data

`endif
