//=========================================================
//File name    : lsqenq_agent_agent_monitor.sv
//Author       : OpenAI_Codex
//Module name  : lsqenq_agent_agent_monitor
//Discribution : lsqenq_agent_agent_monitor : monitor
//Date         : 2026-04-12
//=========================================================
`ifndef LSQENQ_AGENT_AGENT_MONITOR__SV
`define LSQENQ_AGENT_AGENT_MONITOR__SV

`include "memblock_compile_params.svh"

class lsqenq_agent_agent_monitor  extends tcnt_monitor_base#(virtual lsqenq_agent_agent_interface,lsqenq_agent_agent_cfg,lsqenq_agent_agent_xaction);

    `uvm_component_utils(lsqenq_agent_agent_monitor)

    extern function new(string name, uvm_component parent);
    extern virtual function void build_phase(uvm_phase phase);
    extern task run_phase(uvm_phase phase);
    extern task mon_data();
endclass:lsqenq_agent_agent_monitor

function lsqenq_agent_agent_monitor::new(string name, uvm_component parent);
    super.new(name,parent);
endfunction:new

function void lsqenq_agent_agent_monitor::build_phase(uvm_phase phase);
    super.build_phase(phase);
endfunction:build_phase

task lsqenq_agent_agent_monitor::run_phase(uvm_phase phase);
    super.run_phase(phase);
    this.mon_data();
endtask:run_phase

task lsqenq_agent_agent_monitor::mon_data();

    logic [1:0] io_ooo_to_mem_enqLsq_needAlloc_0;
    logic [1:0] io_ooo_to_mem_enqLsq_needAlloc_1;
    logic [1:0] io_ooo_to_mem_enqLsq_needAlloc_2;
    logic [1:0] io_ooo_to_mem_enqLsq_needAlloc_3;
    logic [1:0] io_ooo_to_mem_enqLsq_needAlloc_4;
    logic [1:0] io_ooo_to_mem_enqLsq_needAlloc_5;
    logic io_ooo_to_mem_enqLsq_req_0_valid;
    logic [`MEMBLOCK_DUT_FUTYPE_W-1:0] io_ooo_to_mem_enqLsq_req_0_bits_fuType;
    logic [`MEMBLOCK_DUT_UOP_IDX_W-1:0] io_ooo_to_mem_enqLsq_req_0_bits_uopIdx;
    logic io_ooo_to_mem_enqLsq_req_0_bits_robIdx_flag;
    logic [`MEMBLOCK_DUT_ROB_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_0_bits_robIdx_value;
    logic io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_flag;
    logic [`MEMBLOCK_DUT_LQ_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_flag;
    logic [`MEMBLOCK_DUT_SQ_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_value;
    logic [`MEMBLOCK_DUT_NUM_LS_ELEM_W-1:0] io_ooo_to_mem_enqLsq_req_0_bits_numLsElem;
    logic io_ooo_to_mem_enqLsq_req_1_valid;
    logic [`MEMBLOCK_DUT_FUTYPE_W-1:0] io_ooo_to_mem_enqLsq_req_1_bits_fuType;
    logic [`MEMBLOCK_DUT_UOP_IDX_W-1:0] io_ooo_to_mem_enqLsq_req_1_bits_uopIdx;
    logic io_ooo_to_mem_enqLsq_req_1_bits_robIdx_flag;
    logic [`MEMBLOCK_DUT_ROB_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_1_bits_robIdx_value;
    logic io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_flag;
    logic [`MEMBLOCK_DUT_LQ_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_flag;
    logic [`MEMBLOCK_DUT_SQ_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_value;
    logic [`MEMBLOCK_DUT_NUM_LS_ELEM_W-1:0] io_ooo_to_mem_enqLsq_req_1_bits_numLsElem;
    logic io_ooo_to_mem_enqLsq_req_2_valid;
    logic [`MEMBLOCK_DUT_FUTYPE_W-1:0] io_ooo_to_mem_enqLsq_req_2_bits_fuType;
    logic [`MEMBLOCK_DUT_UOP_IDX_W-1:0] io_ooo_to_mem_enqLsq_req_2_bits_uopIdx;
    logic io_ooo_to_mem_enqLsq_req_2_bits_robIdx_flag;
    logic [`MEMBLOCK_DUT_ROB_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_2_bits_robIdx_value;
    logic io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_flag;
    logic [`MEMBLOCK_DUT_LQ_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_flag;
    logic [`MEMBLOCK_DUT_SQ_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_value;
    logic [`MEMBLOCK_DUT_NUM_LS_ELEM_W-1:0] io_ooo_to_mem_enqLsq_req_2_bits_numLsElem;
    logic io_ooo_to_mem_enqLsq_req_3_valid;
    logic [`MEMBLOCK_DUT_FUTYPE_W-1:0] io_ooo_to_mem_enqLsq_req_3_bits_fuType;
    logic [`MEMBLOCK_DUT_UOP_IDX_W-1:0] io_ooo_to_mem_enqLsq_req_3_bits_uopIdx;
    logic io_ooo_to_mem_enqLsq_req_3_bits_robIdx_flag;
    logic [`MEMBLOCK_DUT_ROB_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_3_bits_robIdx_value;
    logic io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_flag;
    logic [`MEMBLOCK_DUT_LQ_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_flag;
    logic [`MEMBLOCK_DUT_SQ_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_value;
    logic [`MEMBLOCK_DUT_NUM_LS_ELEM_W-1:0] io_ooo_to_mem_enqLsq_req_3_bits_numLsElem;
    logic io_ooo_to_mem_enqLsq_req_4_valid;
    logic [`MEMBLOCK_DUT_FUTYPE_W-1:0] io_ooo_to_mem_enqLsq_req_4_bits_fuType;
    logic [`MEMBLOCK_DUT_UOP_IDX_W-1:0] io_ooo_to_mem_enqLsq_req_4_bits_uopIdx;
    logic io_ooo_to_mem_enqLsq_req_4_bits_robIdx_flag;
    logic [`MEMBLOCK_DUT_ROB_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_4_bits_robIdx_value;
    logic io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_flag;
    logic [`MEMBLOCK_DUT_LQ_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_flag;
    logic [`MEMBLOCK_DUT_SQ_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_value;
    logic [`MEMBLOCK_DUT_NUM_LS_ELEM_W-1:0] io_ooo_to_mem_enqLsq_req_4_bits_numLsElem;
    logic io_ooo_to_mem_enqLsq_req_5_valid;
    logic [`MEMBLOCK_DUT_FUTYPE_W-1:0] io_ooo_to_mem_enqLsq_req_5_bits_fuType;
    logic [`MEMBLOCK_DUT_UOP_IDX_W-1:0] io_ooo_to_mem_enqLsq_req_5_bits_uopIdx;
    logic io_ooo_to_mem_enqLsq_req_5_bits_robIdx_flag;
    logic [`MEMBLOCK_DUT_ROB_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_5_bits_robIdx_value;
    logic io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_flag;
    logic [`MEMBLOCK_DUT_LQ_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_flag;
    logic [`MEMBLOCK_DUT_SQ_VALUE_W-1:0] io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_value;
    logic [`MEMBLOCK_DUT_NUM_LS_ELEM_W-1:0] io_ooo_to_mem_enqLsq_req_5_bits_numLsElem;

    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_0;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_1;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_10;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_11;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_12;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_13;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_14;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_15;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_16;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_17;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_18;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_19;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_2;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_20;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_21;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_22;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_23;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_3;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_4;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_5;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_6;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_7;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_8;
    logic io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_9;
    logic io_ooo_to_mem_enqLsq_req_0_bits_flushPipe;
    logic [8:0] io_ooo_to_mem_enqLsq_req_0_bits_fuOpType;
    logic io_ooo_to_mem_enqLsq_req_0_bits_lastUop;
    logic [3:0] io_ooo_to_mem_enqLsq_req_0_bits_trigger;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_0;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_1;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_10;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_11;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_12;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_13;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_14;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_15;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_16;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_17;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_18;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_19;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_2;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_20;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_21;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_22;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_23;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_3;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_4;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_5;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_6;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_7;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_8;
    logic io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_9;
    logic io_ooo_to_mem_enqLsq_req_1_bits_flushPipe;
    logic [8:0] io_ooo_to_mem_enqLsq_req_1_bits_fuOpType;
    logic io_ooo_to_mem_enqLsq_req_1_bits_lastUop;
    logic [3:0] io_ooo_to_mem_enqLsq_req_1_bits_trigger;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_0;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_1;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_10;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_11;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_12;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_13;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_14;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_15;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_16;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_17;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_18;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_19;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_2;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_20;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_21;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_22;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_23;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_3;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_4;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_5;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_6;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_7;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_8;
    logic io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_9;
    logic io_ooo_to_mem_enqLsq_req_2_bits_flushPipe;
    logic [8:0] io_ooo_to_mem_enqLsq_req_2_bits_fuOpType;
    logic io_ooo_to_mem_enqLsq_req_2_bits_lastUop;
    logic [3:0] io_ooo_to_mem_enqLsq_req_2_bits_trigger;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_0;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_1;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_10;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_11;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_12;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_13;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_14;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_15;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_16;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_17;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_18;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_19;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_2;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_20;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_21;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_22;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_23;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_3;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_4;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_5;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_6;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_7;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_8;
    logic io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_9;
    logic io_ooo_to_mem_enqLsq_req_3_bits_flushPipe;
    logic [8:0] io_ooo_to_mem_enqLsq_req_3_bits_fuOpType;
    logic io_ooo_to_mem_enqLsq_req_3_bits_lastUop;
    logic [3:0] io_ooo_to_mem_enqLsq_req_3_bits_trigger;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_0;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_1;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_10;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_11;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_12;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_13;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_14;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_15;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_16;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_17;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_18;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_19;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_2;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_20;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_21;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_22;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_23;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_3;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_4;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_5;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_6;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_7;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_8;
    logic io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_9;
    logic io_ooo_to_mem_enqLsq_req_4_bits_flushPipe;
    logic [8:0] io_ooo_to_mem_enqLsq_req_4_bits_fuOpType;
    logic io_ooo_to_mem_enqLsq_req_4_bits_lastUop;
    logic [3:0] io_ooo_to_mem_enqLsq_req_4_bits_trigger;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_0;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_1;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_10;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_11;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_12;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_13;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_14;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_15;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_16;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_17;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_18;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_19;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_2;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_20;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_21;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_22;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_23;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_3;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_4;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_5;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_6;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_7;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_8;
    logic io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_9;
    logic io_ooo_to_mem_enqLsq_req_5_bits_flushPipe;
    logic [8:0] io_ooo_to_mem_enqLsq_req_5_bits_fuOpType;
    logic io_ooo_to_mem_enqLsq_req_5_bits_lastUop;
    logic [3:0] io_ooo_to_mem_enqLsq_req_5_bits_trigger;
    lsqenq_agent_agent_xaction  mon_tr;
    while(1) begin
        @this.vif.mon_mp.mon_cb;
        io_ooo_to_mem_enqLsq_needAlloc_0 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_needAlloc_0;
        io_ooo_to_mem_enqLsq_needAlloc_1 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_needAlloc_1;
        io_ooo_to_mem_enqLsq_needAlloc_2 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_needAlloc_2;
        io_ooo_to_mem_enqLsq_needAlloc_3 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_needAlloc_3;
        io_ooo_to_mem_enqLsq_needAlloc_4 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_needAlloc_4;
        io_ooo_to_mem_enqLsq_needAlloc_5 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_needAlloc_5;
        io_ooo_to_mem_enqLsq_req_0_valid = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_valid;
        io_ooo_to_mem_enqLsq_req_0_bits_fuType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_fuType;
        io_ooo_to_mem_enqLsq_req_0_bits_uopIdx = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_uopIdx;
        io_ooo_to_mem_enqLsq_req_0_bits_robIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_robIdx_flag;
        io_ooo_to_mem_enqLsq_req_0_bits_robIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_robIdx_value;
        io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_flag;
        io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_value;
        io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_flag;
        io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_value;
        io_ooo_to_mem_enqLsq_req_0_bits_numLsElem = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_numLsElem;
        io_ooo_to_mem_enqLsq_req_1_valid = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_valid;
        io_ooo_to_mem_enqLsq_req_1_bits_fuType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_fuType;
        io_ooo_to_mem_enqLsq_req_1_bits_uopIdx = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_uopIdx;
        io_ooo_to_mem_enqLsq_req_1_bits_robIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_robIdx_flag;
        io_ooo_to_mem_enqLsq_req_1_bits_robIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_robIdx_value;
        io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_flag;
        io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_value;
        io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_flag;
        io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_value;
        io_ooo_to_mem_enqLsq_req_1_bits_numLsElem = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_numLsElem;
        io_ooo_to_mem_enqLsq_req_2_valid = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_valid;
        io_ooo_to_mem_enqLsq_req_2_bits_fuType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_fuType;
        io_ooo_to_mem_enqLsq_req_2_bits_uopIdx = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_uopIdx;
        io_ooo_to_mem_enqLsq_req_2_bits_robIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_robIdx_flag;
        io_ooo_to_mem_enqLsq_req_2_bits_robIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_robIdx_value;
        io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_flag;
        io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_value;
        io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_flag;
        io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_value;
        io_ooo_to_mem_enqLsq_req_2_bits_numLsElem = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_numLsElem;
        io_ooo_to_mem_enqLsq_req_3_valid = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_valid;
        io_ooo_to_mem_enqLsq_req_3_bits_fuType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_fuType;
        io_ooo_to_mem_enqLsq_req_3_bits_uopIdx = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_uopIdx;
        io_ooo_to_mem_enqLsq_req_3_bits_robIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_robIdx_flag;
        io_ooo_to_mem_enqLsq_req_3_bits_robIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_robIdx_value;
        io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_flag;
        io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_value;
        io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_flag;
        io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_value;
        io_ooo_to_mem_enqLsq_req_3_bits_numLsElem = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_numLsElem;
        io_ooo_to_mem_enqLsq_req_4_valid = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_valid;
        io_ooo_to_mem_enqLsq_req_4_bits_fuType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_fuType;
        io_ooo_to_mem_enqLsq_req_4_bits_uopIdx = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_uopIdx;
        io_ooo_to_mem_enqLsq_req_4_bits_robIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_robIdx_flag;
        io_ooo_to_mem_enqLsq_req_4_bits_robIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_robIdx_value;
        io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_flag;
        io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_value;
        io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_flag;
        io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_value;
        io_ooo_to_mem_enqLsq_req_4_bits_numLsElem = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_numLsElem;
        io_ooo_to_mem_enqLsq_req_5_valid = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_valid;
        io_ooo_to_mem_enqLsq_req_5_bits_fuType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_fuType;
        io_ooo_to_mem_enqLsq_req_5_bits_uopIdx = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_uopIdx;
        io_ooo_to_mem_enqLsq_req_5_bits_robIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_robIdx_flag;
        io_ooo_to_mem_enqLsq_req_5_bits_robIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_robIdx_value;
        io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_flag;
        io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_value;
        io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_flag;
        io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_value;
        io_ooo_to_mem_enqLsq_req_5_bits_numLsElem = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_numLsElem;

        io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_0 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_0;
        io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_1 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_1;
        io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_10 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_10;
        io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_11 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_11;
        io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_12 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_12;
        io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_13 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_13;
        io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_14 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_14;
        io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_15 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_15;
        io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_16 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_16;
        io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_17 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_17;
        io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_18 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_18;
        io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_19 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_19;
        io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_2 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_2;
        io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_20 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_20;
        io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_21 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_21;
        io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_22 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_22;
        io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_23 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_23;
        io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_3 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_3;
        io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_4 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_4;
        io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_5 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_5;
        io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_6 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_6;
        io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_7 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_7;
        io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_8 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_8;
        io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_9 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_exceptionVec_9;
        io_ooo_to_mem_enqLsq_req_0_bits_flushPipe = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_flushPipe;
        io_ooo_to_mem_enqLsq_req_0_bits_fuOpType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_fuOpType;
        io_ooo_to_mem_enqLsq_req_0_bits_lastUop = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_lastUop;
        io_ooo_to_mem_enqLsq_req_0_bits_trigger = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_0_bits_trigger;
        io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_0 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_0;
        io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_1 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_1;
        io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_10 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_10;
        io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_11 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_11;
        io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_12 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_12;
        io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_13 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_13;
        io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_14 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_14;
        io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_15 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_15;
        io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_16 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_16;
        io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_17 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_17;
        io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_18 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_18;
        io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_19 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_19;
        io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_2 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_2;
        io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_20 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_20;
        io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_21 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_21;
        io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_22 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_22;
        io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_23 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_23;
        io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_3 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_3;
        io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_4 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_4;
        io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_5 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_5;
        io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_6 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_6;
        io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_7 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_7;
        io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_8 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_8;
        io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_9 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_exceptionVec_9;
        io_ooo_to_mem_enqLsq_req_1_bits_flushPipe = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_flushPipe;
        io_ooo_to_mem_enqLsq_req_1_bits_fuOpType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_fuOpType;
        io_ooo_to_mem_enqLsq_req_1_bits_lastUop = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_lastUop;
        io_ooo_to_mem_enqLsq_req_1_bits_trigger = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_1_bits_trigger;
        io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_0 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_0;
        io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_1 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_1;
        io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_10 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_10;
        io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_11 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_11;
        io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_12 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_12;
        io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_13 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_13;
        io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_14 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_14;
        io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_15 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_15;
        io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_16 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_16;
        io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_17 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_17;
        io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_18 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_18;
        io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_19 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_19;
        io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_2 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_2;
        io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_20 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_20;
        io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_21 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_21;
        io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_22 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_22;
        io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_23 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_23;
        io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_3 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_3;
        io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_4 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_4;
        io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_5 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_5;
        io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_6 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_6;
        io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_7 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_7;
        io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_8 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_8;
        io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_9 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_exceptionVec_9;
        io_ooo_to_mem_enqLsq_req_2_bits_flushPipe = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_flushPipe;
        io_ooo_to_mem_enqLsq_req_2_bits_fuOpType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_fuOpType;
        io_ooo_to_mem_enqLsq_req_2_bits_lastUop = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_lastUop;
        io_ooo_to_mem_enqLsq_req_2_bits_trigger = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_2_bits_trigger;
        io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_0 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_0;
        io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_1 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_1;
        io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_10 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_10;
        io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_11 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_11;
        io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_12 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_12;
        io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_13 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_13;
        io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_14 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_14;
        io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_15 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_15;
        io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_16 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_16;
        io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_17 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_17;
        io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_18 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_18;
        io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_19 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_19;
        io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_2 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_2;
        io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_20 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_20;
        io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_21 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_21;
        io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_22 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_22;
        io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_23 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_23;
        io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_3 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_3;
        io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_4 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_4;
        io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_5 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_5;
        io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_6 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_6;
        io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_7 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_7;
        io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_8 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_8;
        io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_9 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_exceptionVec_9;
        io_ooo_to_mem_enqLsq_req_3_bits_flushPipe = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_flushPipe;
        io_ooo_to_mem_enqLsq_req_3_bits_fuOpType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_fuOpType;
        io_ooo_to_mem_enqLsq_req_3_bits_lastUop = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_lastUop;
        io_ooo_to_mem_enqLsq_req_3_bits_trigger = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_3_bits_trigger;
        io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_0 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_0;
        io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_1 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_1;
        io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_10 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_10;
        io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_11 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_11;
        io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_12 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_12;
        io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_13 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_13;
        io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_14 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_14;
        io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_15 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_15;
        io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_16 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_16;
        io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_17 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_17;
        io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_18 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_18;
        io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_19 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_19;
        io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_2 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_2;
        io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_20 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_20;
        io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_21 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_21;
        io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_22 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_22;
        io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_23 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_23;
        io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_3 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_3;
        io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_4 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_4;
        io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_5 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_5;
        io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_6 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_6;
        io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_7 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_7;
        io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_8 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_8;
        io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_9 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_exceptionVec_9;
        io_ooo_to_mem_enqLsq_req_4_bits_flushPipe = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_flushPipe;
        io_ooo_to_mem_enqLsq_req_4_bits_fuOpType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_fuOpType;
        io_ooo_to_mem_enqLsq_req_4_bits_lastUop = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_lastUop;
        io_ooo_to_mem_enqLsq_req_4_bits_trigger = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_4_bits_trigger;
        io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_0 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_0;
        io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_1 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_1;
        io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_10 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_10;
        io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_11 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_11;
        io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_12 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_12;
        io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_13 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_13;
        io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_14 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_14;
        io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_15 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_15;
        io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_16 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_16;
        io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_17 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_17;
        io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_18 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_18;
        io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_19 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_19;
        io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_2 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_2;
        io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_20 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_20;
        io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_21 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_21;
        io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_22 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_22;
        io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_23 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_23;
        io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_3 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_3;
        io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_4 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_4;
        io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_5 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_5;
        io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_6 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_6;
        io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_7 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_7;
        io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_8 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_8;
        io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_9 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_exceptionVec_9;
        io_ooo_to_mem_enqLsq_req_5_bits_flushPipe = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_flushPipe;
        io_ooo_to_mem_enqLsq_req_5_bits_fuOpType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_fuOpType;
        io_ooo_to_mem_enqLsq_req_5_bits_lastUop = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_lastUop;
        io_ooo_to_mem_enqLsq_req_5_bits_trigger = this.vif.mon_mp.mon_cb.io_ooo_to_mem_enqLsq_req_5_bits_trigger;

        if(this.cfg.xz_sw==tcnt_dec_base::ON && this.vif.rst_n==1'b1 && memblock_sync_pkg::reset_backend_done==1'b1) begin
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_needAlloc_0,io_ooo_to_mem_enqLsq_needAlloc_0,2);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_needAlloc_1,io_ooo_to_mem_enqLsq_needAlloc_1,2);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_needAlloc_2,io_ooo_to_mem_enqLsq_needAlloc_2,2);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_needAlloc_3,io_ooo_to_mem_enqLsq_needAlloc_3,2);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_needAlloc_4,io_ooo_to_mem_enqLsq_needAlloc_4,2);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_needAlloc_5,io_ooo_to_mem_enqLsq_needAlloc_5,2);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_0_valid,io_ooo_to_mem_enqLsq_req_0_valid,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_0_bits_fuType,io_ooo_to_mem_enqLsq_req_0_bits_fuType,`MEMBLOCK_DUT_FUTYPE_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_0_bits_uopIdx,io_ooo_to_mem_enqLsq_req_0_bits_uopIdx,`MEMBLOCK_DUT_UOP_IDX_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_0_bits_robIdx_flag,io_ooo_to_mem_enqLsq_req_0_bits_robIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_0_bits_robIdx_value,io_ooo_to_mem_enqLsq_req_0_bits_robIdx_value,`MEMBLOCK_DUT_ROB_VALUE_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_flag,io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_value,io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_value,`MEMBLOCK_DUT_LQ_VALUE_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_flag,io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_value,io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_value,`MEMBLOCK_DUT_SQ_VALUE_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_0_bits_numLsElem,io_ooo_to_mem_enqLsq_req_0_bits_numLsElem,`MEMBLOCK_DUT_NUM_LS_ELEM_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_1_valid,io_ooo_to_mem_enqLsq_req_1_valid,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_1_bits_fuType,io_ooo_to_mem_enqLsq_req_1_bits_fuType,`MEMBLOCK_DUT_FUTYPE_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_1_bits_uopIdx,io_ooo_to_mem_enqLsq_req_1_bits_uopIdx,`MEMBLOCK_DUT_UOP_IDX_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_1_bits_robIdx_flag,io_ooo_to_mem_enqLsq_req_1_bits_robIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_1_bits_robIdx_value,io_ooo_to_mem_enqLsq_req_1_bits_robIdx_value,`MEMBLOCK_DUT_ROB_VALUE_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_flag,io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_value,io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_value,`MEMBLOCK_DUT_LQ_VALUE_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_flag,io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_value,io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_value,`MEMBLOCK_DUT_SQ_VALUE_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_1_bits_numLsElem,io_ooo_to_mem_enqLsq_req_1_bits_numLsElem,`MEMBLOCK_DUT_NUM_LS_ELEM_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_2_valid,io_ooo_to_mem_enqLsq_req_2_valid,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_2_bits_fuType,io_ooo_to_mem_enqLsq_req_2_bits_fuType,`MEMBLOCK_DUT_FUTYPE_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_2_bits_uopIdx,io_ooo_to_mem_enqLsq_req_2_bits_uopIdx,`MEMBLOCK_DUT_UOP_IDX_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_2_bits_robIdx_flag,io_ooo_to_mem_enqLsq_req_2_bits_robIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_2_bits_robIdx_value,io_ooo_to_mem_enqLsq_req_2_bits_robIdx_value,`MEMBLOCK_DUT_ROB_VALUE_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_flag,io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_value,io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_value,`MEMBLOCK_DUT_LQ_VALUE_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_flag,io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_value,io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_value,`MEMBLOCK_DUT_SQ_VALUE_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_2_bits_numLsElem,io_ooo_to_mem_enqLsq_req_2_bits_numLsElem,`MEMBLOCK_DUT_NUM_LS_ELEM_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_3_valid,io_ooo_to_mem_enqLsq_req_3_valid,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_3_bits_fuType,io_ooo_to_mem_enqLsq_req_3_bits_fuType,`MEMBLOCK_DUT_FUTYPE_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_3_bits_uopIdx,io_ooo_to_mem_enqLsq_req_3_bits_uopIdx,`MEMBLOCK_DUT_UOP_IDX_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_3_bits_robIdx_flag,io_ooo_to_mem_enqLsq_req_3_bits_robIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_3_bits_robIdx_value,io_ooo_to_mem_enqLsq_req_3_bits_robIdx_value,`MEMBLOCK_DUT_ROB_VALUE_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_flag,io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_value,io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_value,`MEMBLOCK_DUT_LQ_VALUE_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_flag,io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_value,io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_value,`MEMBLOCK_DUT_SQ_VALUE_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_3_bits_numLsElem,io_ooo_to_mem_enqLsq_req_3_bits_numLsElem,`MEMBLOCK_DUT_NUM_LS_ELEM_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_4_valid,io_ooo_to_mem_enqLsq_req_4_valid,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_4_bits_fuType,io_ooo_to_mem_enqLsq_req_4_bits_fuType,`MEMBLOCK_DUT_FUTYPE_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_4_bits_uopIdx,io_ooo_to_mem_enqLsq_req_4_bits_uopIdx,`MEMBLOCK_DUT_UOP_IDX_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_4_bits_robIdx_flag,io_ooo_to_mem_enqLsq_req_4_bits_robIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_4_bits_robIdx_value,io_ooo_to_mem_enqLsq_req_4_bits_robIdx_value,`MEMBLOCK_DUT_ROB_VALUE_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_flag,io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_value,io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_value,`MEMBLOCK_DUT_LQ_VALUE_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_flag,io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_value,io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_value,`MEMBLOCK_DUT_SQ_VALUE_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_4_bits_numLsElem,io_ooo_to_mem_enqLsq_req_4_bits_numLsElem,`MEMBLOCK_DUT_NUM_LS_ELEM_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_5_valid,io_ooo_to_mem_enqLsq_req_5_valid,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_5_bits_fuType,io_ooo_to_mem_enqLsq_req_5_bits_fuType,`MEMBLOCK_DUT_FUTYPE_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_5_bits_uopIdx,io_ooo_to_mem_enqLsq_req_5_bits_uopIdx,`MEMBLOCK_DUT_UOP_IDX_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_5_bits_robIdx_flag,io_ooo_to_mem_enqLsq_req_5_bits_robIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_5_bits_robIdx_value,io_ooo_to_mem_enqLsq_req_5_bits_robIdx_value,`MEMBLOCK_DUT_ROB_VALUE_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_flag,io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_value,io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_value,`MEMBLOCK_DUT_LQ_VALUE_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_flag,io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_value,io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_value,`MEMBLOCK_DUT_SQ_VALUE_W);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_enqLsq_req_5_bits_numLsElem,io_ooo_to_mem_enqLsq_req_5_bits_numLsElem,`MEMBLOCK_DUT_NUM_LS_ELEM_W);

        end
        //if(xxxTODOxxx==1'b1) begin
        //    mon_tr = lsqenq_agent_agent_xaction::type_id::create("mon_tr");
        //    mon_tr.io_ooo_to_mem_enqLsq_needAlloc_0 = io_ooo_to_mem_enqLsq_needAlloc_0;
        //    mon_tr.io_ooo_to_mem_enqLsq_needAlloc_1 = io_ooo_to_mem_enqLsq_needAlloc_1;
        //    mon_tr.io_ooo_to_mem_enqLsq_needAlloc_2 = io_ooo_to_mem_enqLsq_needAlloc_2;
        //    mon_tr.io_ooo_to_mem_enqLsq_needAlloc_3 = io_ooo_to_mem_enqLsq_needAlloc_3;
        //    mon_tr.io_ooo_to_mem_enqLsq_needAlloc_4 = io_ooo_to_mem_enqLsq_needAlloc_4;
        //    mon_tr.io_ooo_to_mem_enqLsq_needAlloc_5 = io_ooo_to_mem_enqLsq_needAlloc_5;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_0_valid = io_ooo_to_mem_enqLsq_req_0_valid;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_0_bits_fuType = io_ooo_to_mem_enqLsq_req_0_bits_fuType;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_0_bits_uopIdx = io_ooo_to_mem_enqLsq_req_0_bits_uopIdx;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_0_bits_robIdx_flag = io_ooo_to_mem_enqLsq_req_0_bits_robIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_0_bits_robIdx_value = io_ooo_to_mem_enqLsq_req_0_bits_robIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_flag = io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_value = io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_flag = io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_value = io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_0_bits_numLsElem = io_ooo_to_mem_enqLsq_req_0_bits_numLsElem;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_1_valid = io_ooo_to_mem_enqLsq_req_1_valid;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_1_bits_fuType = io_ooo_to_mem_enqLsq_req_1_bits_fuType;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_1_bits_uopIdx = io_ooo_to_mem_enqLsq_req_1_bits_uopIdx;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_1_bits_robIdx_flag = io_ooo_to_mem_enqLsq_req_1_bits_robIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_1_bits_robIdx_value = io_ooo_to_mem_enqLsq_req_1_bits_robIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_flag = io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_value = io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_flag = io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_value = io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_1_bits_numLsElem = io_ooo_to_mem_enqLsq_req_1_bits_numLsElem;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_2_valid = io_ooo_to_mem_enqLsq_req_2_valid;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_2_bits_fuType = io_ooo_to_mem_enqLsq_req_2_bits_fuType;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_2_bits_uopIdx = io_ooo_to_mem_enqLsq_req_2_bits_uopIdx;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_2_bits_robIdx_flag = io_ooo_to_mem_enqLsq_req_2_bits_robIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_2_bits_robIdx_value = io_ooo_to_mem_enqLsq_req_2_bits_robIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_flag = io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_value = io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_flag = io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_value = io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_2_bits_numLsElem = io_ooo_to_mem_enqLsq_req_2_bits_numLsElem;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_3_valid = io_ooo_to_mem_enqLsq_req_3_valid;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_3_bits_fuType = io_ooo_to_mem_enqLsq_req_3_bits_fuType;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_3_bits_uopIdx = io_ooo_to_mem_enqLsq_req_3_bits_uopIdx;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_3_bits_robIdx_flag = io_ooo_to_mem_enqLsq_req_3_bits_robIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_3_bits_robIdx_value = io_ooo_to_mem_enqLsq_req_3_bits_robIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_flag = io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_value = io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_flag = io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_value = io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_3_bits_numLsElem = io_ooo_to_mem_enqLsq_req_3_bits_numLsElem;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_4_valid = io_ooo_to_mem_enqLsq_req_4_valid;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_4_bits_fuType = io_ooo_to_mem_enqLsq_req_4_bits_fuType;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_4_bits_uopIdx = io_ooo_to_mem_enqLsq_req_4_bits_uopIdx;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_4_bits_robIdx_flag = io_ooo_to_mem_enqLsq_req_4_bits_robIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_4_bits_robIdx_value = io_ooo_to_mem_enqLsq_req_4_bits_robIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_flag = io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_value = io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_flag = io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_value = io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_4_bits_numLsElem = io_ooo_to_mem_enqLsq_req_4_bits_numLsElem;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_5_valid = io_ooo_to_mem_enqLsq_req_5_valid;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_5_bits_fuType = io_ooo_to_mem_enqLsq_req_5_bits_fuType;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_5_bits_uopIdx = io_ooo_to_mem_enqLsq_req_5_bits_uopIdx;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_5_bits_robIdx_flag = io_ooo_to_mem_enqLsq_req_5_bits_robIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_5_bits_robIdx_value = io_ooo_to_mem_enqLsq_req_5_bits_robIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_flag = io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_value = io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_flag = io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_flag;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_value = io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_value;
        //    mon_tr.io_ooo_to_mem_enqLsq_req_5_bits_numLsElem = io_ooo_to_mem_enqLsq_req_5_bits_numLsElem;

        //    mon_tr.channel_id = this.cfg.channel_id;
        //    mon_tr.unpack();
        //    this.mon_item_port.write(mon_tr);
        //end
    end
endtask:mon_data

`endif
