//=========================================================
//File name    : lsqenq_agent_agent_interface.sv
//Author       : OpenAI_Codex
//Module name  : lsqenq_agent_agent_interface
//Discribution : lsqenq_agent_agent_interface : signal interface
//Date         : 2026-04-12
//=========================================================
`ifndef LSQENQ_AGENT_AGENT_INTERFACE__SV
`define LSQENQ_AGENT_AGENT_INTERFACE__SV

`ifndef DEF_SETUP_TIME
    `define DEF_SETUP_TIME 1
`endif
`ifndef DEF_HOLD_TIME
    `define DEF_HOLD_TIME 1
`endif

interface lsqenq_agent_agent_interface  (input bit clk,input bit rst_n);

    logic io_ooo_to_mem_enqLsq_canAccept;
    logic [1:0] io_ooo_to_mem_enqLsq_needAlloc_0;
    logic [1:0] io_ooo_to_mem_enqLsq_needAlloc_1;
    logic [1:0] io_ooo_to_mem_enqLsq_needAlloc_2;
    logic [1:0] io_ooo_to_mem_enqLsq_needAlloc_3;
    logic [1:0] io_ooo_to_mem_enqLsq_needAlloc_4;
    logic [1:0] io_ooo_to_mem_enqLsq_needAlloc_5;
    logic [1:0] io_ooo_to_mem_enqLsq_needAlloc_6;
    logic [1:0] io_ooo_to_mem_enqLsq_needAlloc_7;
    logic io_ooo_to_mem_enqLsq_req_0_valid;
    logic [35:0] io_ooo_to_mem_enqLsq_req_0_bits_fuType;
    logic [6:0] io_ooo_to_mem_enqLsq_req_0_bits_uopIdx;
    logic io_ooo_to_mem_enqLsq_req_0_bits_robIdx_flag;
    logic [8:0] io_ooo_to_mem_enqLsq_req_0_bits_robIdx_value;
    logic io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_value;
    logic [4:0] io_ooo_to_mem_enqLsq_req_0_bits_numLsElem;
    logic io_ooo_to_mem_enqLsq_req_1_valid;
    logic [35:0] io_ooo_to_mem_enqLsq_req_1_bits_fuType;
    logic [6:0] io_ooo_to_mem_enqLsq_req_1_bits_uopIdx;
    logic io_ooo_to_mem_enqLsq_req_1_bits_robIdx_flag;
    logic [8:0] io_ooo_to_mem_enqLsq_req_1_bits_robIdx_value;
    logic io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_value;
    logic [4:0] io_ooo_to_mem_enqLsq_req_1_bits_numLsElem;
    logic io_ooo_to_mem_enqLsq_req_2_valid;
    logic [35:0] io_ooo_to_mem_enqLsq_req_2_bits_fuType;
    logic [6:0] io_ooo_to_mem_enqLsq_req_2_bits_uopIdx;
    logic io_ooo_to_mem_enqLsq_req_2_bits_robIdx_flag;
    logic [8:0] io_ooo_to_mem_enqLsq_req_2_bits_robIdx_value;
    logic io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_value;
    logic [4:0] io_ooo_to_mem_enqLsq_req_2_bits_numLsElem;
    logic io_ooo_to_mem_enqLsq_req_3_valid;
    logic [35:0] io_ooo_to_mem_enqLsq_req_3_bits_fuType;
    logic [6:0] io_ooo_to_mem_enqLsq_req_3_bits_uopIdx;
    logic io_ooo_to_mem_enqLsq_req_3_bits_robIdx_flag;
    logic [8:0] io_ooo_to_mem_enqLsq_req_3_bits_robIdx_value;
    logic io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_value;
    logic [4:0] io_ooo_to_mem_enqLsq_req_3_bits_numLsElem;
    logic io_ooo_to_mem_enqLsq_req_4_valid;
    logic [35:0] io_ooo_to_mem_enqLsq_req_4_bits_fuType;
    logic [6:0] io_ooo_to_mem_enqLsq_req_4_bits_uopIdx;
    logic io_ooo_to_mem_enqLsq_req_4_bits_robIdx_flag;
    logic [8:0] io_ooo_to_mem_enqLsq_req_4_bits_robIdx_value;
    logic io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_value;
    logic [4:0] io_ooo_to_mem_enqLsq_req_4_bits_numLsElem;
    logic io_ooo_to_mem_enqLsq_req_5_valid;
    logic [35:0] io_ooo_to_mem_enqLsq_req_5_bits_fuType;
    logic [6:0] io_ooo_to_mem_enqLsq_req_5_bits_uopIdx;
    logic io_ooo_to_mem_enqLsq_req_5_bits_robIdx_flag;
    logic [8:0] io_ooo_to_mem_enqLsq_req_5_bits_robIdx_value;
    logic io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_value;
    logic [4:0] io_ooo_to_mem_enqLsq_req_5_bits_numLsElem;
    logic io_ooo_to_mem_enqLsq_req_6_valid;
    logic [35:0] io_ooo_to_mem_enqLsq_req_6_bits_fuType;
    logic [6:0] io_ooo_to_mem_enqLsq_req_6_bits_uopIdx;
    logic io_ooo_to_mem_enqLsq_req_6_bits_robIdx_flag;
    logic [8:0] io_ooo_to_mem_enqLsq_req_6_bits_robIdx_value;
    logic io_ooo_to_mem_enqLsq_req_6_bits_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_enqLsq_req_6_bits_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_req_6_bits_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_enqLsq_req_6_bits_sqIdx_value;
    logic [4:0] io_ooo_to_mem_enqLsq_req_6_bits_numLsElem;
    logic io_ooo_to_mem_enqLsq_req_7_valid;
    logic [35:0] io_ooo_to_mem_enqLsq_req_7_bits_fuType;
    logic [6:0] io_ooo_to_mem_enqLsq_req_7_bits_uopIdx;
    logic io_ooo_to_mem_enqLsq_req_7_bits_robIdx_flag;
    logic [8:0] io_ooo_to_mem_enqLsq_req_7_bits_robIdx_value;
    logic io_ooo_to_mem_enqLsq_req_7_bits_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_enqLsq_req_7_bits_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_req_7_bits_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_enqLsq_req_7_bits_sqIdx_value;
    logic [4:0] io_ooo_to_mem_enqLsq_req_7_bits_numLsElem;
    logic io_ooo_to_mem_enqLsq_resp_0_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_enqLsq_resp_0_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_resp_0_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_enqLsq_resp_0_sqIdx_value;
    logic io_ooo_to_mem_enqLsq_resp_1_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_enqLsq_resp_1_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_resp_1_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_enqLsq_resp_1_sqIdx_value;
    logic io_ooo_to_mem_enqLsq_resp_2_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_enqLsq_resp_2_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_resp_2_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_enqLsq_resp_2_sqIdx_value;
    logic io_ooo_to_mem_enqLsq_resp_3_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_enqLsq_resp_3_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_resp_3_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_enqLsq_resp_3_sqIdx_value;
    logic io_ooo_to_mem_enqLsq_resp_4_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_enqLsq_resp_4_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_resp_4_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_enqLsq_resp_4_sqIdx_value;
    logic io_ooo_to_mem_enqLsq_resp_5_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_enqLsq_resp_5_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_resp_5_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_enqLsq_resp_5_sqIdx_value;
    logic io_ooo_to_mem_enqLsq_resp_6_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_enqLsq_resp_6_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_resp_6_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_enqLsq_resp_6_sqIdx_value;
    logic io_ooo_to_mem_enqLsq_resp_7_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_enqLsq_resp_7_lqIdx_value;
    logic io_ooo_to_mem_enqLsq_resp_7_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_enqLsq_resp_7_sqIdx_value;

    clocking drv_cb @(posedge clk);
        `ifdef INTERFACE_ADD_DELAY
            default input #`DEF_SETUP_TIME output #`DEF_HOLD_TIME;
        `endif
        input  io_ooo_to_mem_enqLsq_canAccept;
        output io_ooo_to_mem_enqLsq_needAlloc_0;
        output io_ooo_to_mem_enqLsq_needAlloc_1;
        output io_ooo_to_mem_enqLsq_needAlloc_2;
        output io_ooo_to_mem_enqLsq_needAlloc_3;
        output io_ooo_to_mem_enqLsq_needAlloc_4;
        output io_ooo_to_mem_enqLsq_needAlloc_5;
        output io_ooo_to_mem_enqLsq_needAlloc_6;
        output io_ooo_to_mem_enqLsq_needAlloc_7;
        output io_ooo_to_mem_enqLsq_req_0_valid;
        output io_ooo_to_mem_enqLsq_req_0_bits_fuType;
        output io_ooo_to_mem_enqLsq_req_0_bits_uopIdx;
        output io_ooo_to_mem_enqLsq_req_0_bits_robIdx_flag;
        output io_ooo_to_mem_enqLsq_req_0_bits_robIdx_value;
        output io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_flag;
        output io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_value;
        output io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_flag;
        output io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_value;
        output io_ooo_to_mem_enqLsq_req_0_bits_numLsElem;
        output io_ooo_to_mem_enqLsq_req_1_valid;
        output io_ooo_to_mem_enqLsq_req_1_bits_fuType;
        output io_ooo_to_mem_enqLsq_req_1_bits_uopIdx;
        output io_ooo_to_mem_enqLsq_req_1_bits_robIdx_flag;
        output io_ooo_to_mem_enqLsq_req_1_bits_robIdx_value;
        output io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_flag;
        output io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_value;
        output io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_flag;
        output io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_value;
        output io_ooo_to_mem_enqLsq_req_1_bits_numLsElem;
        output io_ooo_to_mem_enqLsq_req_2_valid;
        output io_ooo_to_mem_enqLsq_req_2_bits_fuType;
        output io_ooo_to_mem_enqLsq_req_2_bits_uopIdx;
        output io_ooo_to_mem_enqLsq_req_2_bits_robIdx_flag;
        output io_ooo_to_mem_enqLsq_req_2_bits_robIdx_value;
        output io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_flag;
        output io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_value;
        output io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_flag;
        output io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_value;
        output io_ooo_to_mem_enqLsq_req_2_bits_numLsElem;
        output io_ooo_to_mem_enqLsq_req_3_valid;
        output io_ooo_to_mem_enqLsq_req_3_bits_fuType;
        output io_ooo_to_mem_enqLsq_req_3_bits_uopIdx;
        output io_ooo_to_mem_enqLsq_req_3_bits_robIdx_flag;
        output io_ooo_to_mem_enqLsq_req_3_bits_robIdx_value;
        output io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_flag;
        output io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_value;
        output io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_flag;
        output io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_value;
        output io_ooo_to_mem_enqLsq_req_3_bits_numLsElem;
        output io_ooo_to_mem_enqLsq_req_4_valid;
        output io_ooo_to_mem_enqLsq_req_4_bits_fuType;
        output io_ooo_to_mem_enqLsq_req_4_bits_uopIdx;
        output io_ooo_to_mem_enqLsq_req_4_bits_robIdx_flag;
        output io_ooo_to_mem_enqLsq_req_4_bits_robIdx_value;
        output io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_flag;
        output io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_value;
        output io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_flag;
        output io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_value;
        output io_ooo_to_mem_enqLsq_req_4_bits_numLsElem;
        output io_ooo_to_mem_enqLsq_req_5_valid;
        output io_ooo_to_mem_enqLsq_req_5_bits_fuType;
        output io_ooo_to_mem_enqLsq_req_5_bits_uopIdx;
        output io_ooo_to_mem_enqLsq_req_5_bits_robIdx_flag;
        output io_ooo_to_mem_enqLsq_req_5_bits_robIdx_value;
        output io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_flag;
        output io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_value;
        output io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_flag;
        output io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_value;
        output io_ooo_to_mem_enqLsq_req_5_bits_numLsElem;
        output io_ooo_to_mem_enqLsq_req_6_valid;
        output io_ooo_to_mem_enqLsq_req_6_bits_fuType;
        output io_ooo_to_mem_enqLsq_req_6_bits_uopIdx;
        output io_ooo_to_mem_enqLsq_req_6_bits_robIdx_flag;
        output io_ooo_to_mem_enqLsq_req_6_bits_robIdx_value;
        output io_ooo_to_mem_enqLsq_req_6_bits_lqIdx_flag;
        output io_ooo_to_mem_enqLsq_req_6_bits_lqIdx_value;
        output io_ooo_to_mem_enqLsq_req_6_bits_sqIdx_flag;
        output io_ooo_to_mem_enqLsq_req_6_bits_sqIdx_value;
        output io_ooo_to_mem_enqLsq_req_6_bits_numLsElem;
        output io_ooo_to_mem_enqLsq_req_7_valid;
        output io_ooo_to_mem_enqLsq_req_7_bits_fuType;
        output io_ooo_to_mem_enqLsq_req_7_bits_uopIdx;
        output io_ooo_to_mem_enqLsq_req_7_bits_robIdx_flag;
        output io_ooo_to_mem_enqLsq_req_7_bits_robIdx_value;
        output io_ooo_to_mem_enqLsq_req_7_bits_lqIdx_flag;
        output io_ooo_to_mem_enqLsq_req_7_bits_lqIdx_value;
        output io_ooo_to_mem_enqLsq_req_7_bits_sqIdx_flag;
        output io_ooo_to_mem_enqLsq_req_7_bits_sqIdx_value;
        output io_ooo_to_mem_enqLsq_req_7_bits_numLsElem;
        input  io_ooo_to_mem_enqLsq_resp_0_lqIdx_flag;
        input  io_ooo_to_mem_enqLsq_resp_0_lqIdx_value;
        input  io_ooo_to_mem_enqLsq_resp_0_sqIdx_flag;
        input  io_ooo_to_mem_enqLsq_resp_0_sqIdx_value;
        input  io_ooo_to_mem_enqLsq_resp_1_lqIdx_flag;
        input  io_ooo_to_mem_enqLsq_resp_1_lqIdx_value;
        input  io_ooo_to_mem_enqLsq_resp_1_sqIdx_flag;
        input  io_ooo_to_mem_enqLsq_resp_1_sqIdx_value;
        input  io_ooo_to_mem_enqLsq_resp_2_lqIdx_flag;
        input  io_ooo_to_mem_enqLsq_resp_2_lqIdx_value;
        input  io_ooo_to_mem_enqLsq_resp_2_sqIdx_flag;
        input  io_ooo_to_mem_enqLsq_resp_2_sqIdx_value;
        input  io_ooo_to_mem_enqLsq_resp_3_lqIdx_flag;
        input  io_ooo_to_mem_enqLsq_resp_3_lqIdx_value;
        input  io_ooo_to_mem_enqLsq_resp_3_sqIdx_flag;
        input  io_ooo_to_mem_enqLsq_resp_3_sqIdx_value;
        input  io_ooo_to_mem_enqLsq_resp_4_lqIdx_flag;
        input  io_ooo_to_mem_enqLsq_resp_4_lqIdx_value;
        input  io_ooo_to_mem_enqLsq_resp_4_sqIdx_flag;
        input  io_ooo_to_mem_enqLsq_resp_4_sqIdx_value;
        input  io_ooo_to_mem_enqLsq_resp_5_lqIdx_flag;
        input  io_ooo_to_mem_enqLsq_resp_5_lqIdx_value;
        input  io_ooo_to_mem_enqLsq_resp_5_sqIdx_flag;
        input  io_ooo_to_mem_enqLsq_resp_5_sqIdx_value;
        input  io_ooo_to_mem_enqLsq_resp_6_lqIdx_flag;
        input  io_ooo_to_mem_enqLsq_resp_6_lqIdx_value;
        input  io_ooo_to_mem_enqLsq_resp_6_sqIdx_flag;
        input  io_ooo_to_mem_enqLsq_resp_6_sqIdx_value;
        input  io_ooo_to_mem_enqLsq_resp_7_lqIdx_flag;
        input  io_ooo_to_mem_enqLsq_resp_7_lqIdx_value;
        input  io_ooo_to_mem_enqLsq_resp_7_sqIdx_flag;
        input  io_ooo_to_mem_enqLsq_resp_7_sqIdx_value;

    endclocking:drv_cb

    clocking mon_cb @(posedge clk);
        `ifdef INTERFACE_ADD_DELAY
            default input #`DEF_SETUP_TIME output #`DEF_HOLD_TIME;
        `endif
        input  io_ooo_to_mem_enqLsq_canAccept;
        input  io_ooo_to_mem_enqLsq_needAlloc_0;
        input  io_ooo_to_mem_enqLsq_needAlloc_1;
        input  io_ooo_to_mem_enqLsq_needAlloc_2;
        input  io_ooo_to_mem_enqLsq_needAlloc_3;
        input  io_ooo_to_mem_enqLsq_needAlloc_4;
        input  io_ooo_to_mem_enqLsq_needAlloc_5;
        input  io_ooo_to_mem_enqLsq_needAlloc_6;
        input  io_ooo_to_mem_enqLsq_needAlloc_7;
        input  io_ooo_to_mem_enqLsq_req_0_valid;
        input  io_ooo_to_mem_enqLsq_req_0_bits_fuType;
        input  io_ooo_to_mem_enqLsq_req_0_bits_uopIdx;
        input  io_ooo_to_mem_enqLsq_req_0_bits_robIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_0_bits_robIdx_value;
        input  io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_value;
        input  io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_value;
        input  io_ooo_to_mem_enqLsq_req_0_bits_numLsElem;
        input  io_ooo_to_mem_enqLsq_req_1_valid;
        input  io_ooo_to_mem_enqLsq_req_1_bits_fuType;
        input  io_ooo_to_mem_enqLsq_req_1_bits_uopIdx;
        input  io_ooo_to_mem_enqLsq_req_1_bits_robIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_1_bits_robIdx_value;
        input  io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_value;
        input  io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_value;
        input  io_ooo_to_mem_enqLsq_req_1_bits_numLsElem;
        input  io_ooo_to_mem_enqLsq_req_2_valid;
        input  io_ooo_to_mem_enqLsq_req_2_bits_fuType;
        input  io_ooo_to_mem_enqLsq_req_2_bits_uopIdx;
        input  io_ooo_to_mem_enqLsq_req_2_bits_robIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_2_bits_robIdx_value;
        input  io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_value;
        input  io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_value;
        input  io_ooo_to_mem_enqLsq_req_2_bits_numLsElem;
        input  io_ooo_to_mem_enqLsq_req_3_valid;
        input  io_ooo_to_mem_enqLsq_req_3_bits_fuType;
        input  io_ooo_to_mem_enqLsq_req_3_bits_uopIdx;
        input  io_ooo_to_mem_enqLsq_req_3_bits_robIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_3_bits_robIdx_value;
        input  io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_value;
        input  io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_value;
        input  io_ooo_to_mem_enqLsq_req_3_bits_numLsElem;
        input  io_ooo_to_mem_enqLsq_req_4_valid;
        input  io_ooo_to_mem_enqLsq_req_4_bits_fuType;
        input  io_ooo_to_mem_enqLsq_req_4_bits_uopIdx;
        input  io_ooo_to_mem_enqLsq_req_4_bits_robIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_4_bits_robIdx_value;
        input  io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_value;
        input  io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_value;
        input  io_ooo_to_mem_enqLsq_req_4_bits_numLsElem;
        input  io_ooo_to_mem_enqLsq_req_5_valid;
        input  io_ooo_to_mem_enqLsq_req_5_bits_fuType;
        input  io_ooo_to_mem_enqLsq_req_5_bits_uopIdx;
        input  io_ooo_to_mem_enqLsq_req_5_bits_robIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_5_bits_robIdx_value;
        input  io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_value;
        input  io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_value;
        input  io_ooo_to_mem_enqLsq_req_5_bits_numLsElem;
        input  io_ooo_to_mem_enqLsq_req_6_valid;
        input  io_ooo_to_mem_enqLsq_req_6_bits_fuType;
        input  io_ooo_to_mem_enqLsq_req_6_bits_uopIdx;
        input  io_ooo_to_mem_enqLsq_req_6_bits_robIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_6_bits_robIdx_value;
        input  io_ooo_to_mem_enqLsq_req_6_bits_lqIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_6_bits_lqIdx_value;
        input  io_ooo_to_mem_enqLsq_req_6_bits_sqIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_6_bits_sqIdx_value;
        input  io_ooo_to_mem_enqLsq_req_6_bits_numLsElem;
        input  io_ooo_to_mem_enqLsq_req_7_valid;
        input  io_ooo_to_mem_enqLsq_req_7_bits_fuType;
        input  io_ooo_to_mem_enqLsq_req_7_bits_uopIdx;
        input  io_ooo_to_mem_enqLsq_req_7_bits_robIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_7_bits_robIdx_value;
        input  io_ooo_to_mem_enqLsq_req_7_bits_lqIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_7_bits_lqIdx_value;
        input  io_ooo_to_mem_enqLsq_req_7_bits_sqIdx_flag;
        input  io_ooo_to_mem_enqLsq_req_7_bits_sqIdx_value;
        input  io_ooo_to_mem_enqLsq_req_7_bits_numLsElem;
        input  io_ooo_to_mem_enqLsq_resp_0_lqIdx_flag;
        input  io_ooo_to_mem_enqLsq_resp_0_lqIdx_value;
        input  io_ooo_to_mem_enqLsq_resp_0_sqIdx_flag;
        input  io_ooo_to_mem_enqLsq_resp_0_sqIdx_value;
        input  io_ooo_to_mem_enqLsq_resp_1_lqIdx_flag;
        input  io_ooo_to_mem_enqLsq_resp_1_lqIdx_value;
        input  io_ooo_to_mem_enqLsq_resp_1_sqIdx_flag;
        input  io_ooo_to_mem_enqLsq_resp_1_sqIdx_value;
        input  io_ooo_to_mem_enqLsq_resp_2_lqIdx_flag;
        input  io_ooo_to_mem_enqLsq_resp_2_lqIdx_value;
        input  io_ooo_to_mem_enqLsq_resp_2_sqIdx_flag;
        input  io_ooo_to_mem_enqLsq_resp_2_sqIdx_value;
        input  io_ooo_to_mem_enqLsq_resp_3_lqIdx_flag;
        input  io_ooo_to_mem_enqLsq_resp_3_lqIdx_value;
        input  io_ooo_to_mem_enqLsq_resp_3_sqIdx_flag;
        input  io_ooo_to_mem_enqLsq_resp_3_sqIdx_value;
        input  io_ooo_to_mem_enqLsq_resp_4_lqIdx_flag;
        input  io_ooo_to_mem_enqLsq_resp_4_lqIdx_value;
        input  io_ooo_to_mem_enqLsq_resp_4_sqIdx_flag;
        input  io_ooo_to_mem_enqLsq_resp_4_sqIdx_value;
        input  io_ooo_to_mem_enqLsq_resp_5_lqIdx_flag;
        input  io_ooo_to_mem_enqLsq_resp_5_lqIdx_value;
        input  io_ooo_to_mem_enqLsq_resp_5_sqIdx_flag;
        input  io_ooo_to_mem_enqLsq_resp_5_sqIdx_value;
        input  io_ooo_to_mem_enqLsq_resp_6_lqIdx_flag;
        input  io_ooo_to_mem_enqLsq_resp_6_lqIdx_value;
        input  io_ooo_to_mem_enqLsq_resp_6_sqIdx_flag;
        input  io_ooo_to_mem_enqLsq_resp_6_sqIdx_value;
        input  io_ooo_to_mem_enqLsq_resp_7_lqIdx_flag;
        input  io_ooo_to_mem_enqLsq_resp_7_lqIdx_value;
        input  io_ooo_to_mem_enqLsq_resp_7_sqIdx_flag;
        input  io_ooo_to_mem_enqLsq_resp_7_sqIdx_value;

    endclocking:mon_cb

    modport drv_mp (clocking drv_cb);
    modport mon_mp (clocking mon_cb);

endinterface:lsqenq_agent_agent_interface

`endif
