core:
  - "!.github/ISSUE_TEMPLATE/**"
  - "!.github/CODEOWNERS"
  - "!.github/filters.yaml"
  - "!.github/labeler.yml"
  - "!.github/workflows/nightly.yml"
  - "!.github/workflows/perf-template.yml"
  - "!.github/workflows/perf-v2.yml"
  - "!.github/workflows/perf-v3.yml"
  - "!.github/workflows/perf-trigger.yml"
  - "!.github/workflows/pr-labeler.yml"
  - "!.gitignore"
  - "!**/*.md"
  - "!LICENSE"
  - "!images/**"
