#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FRONTEND_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
REPO_DIR="$(cd "${FRONTEND_DIR}/../../../.." && pwd)"

usage() {
  cat <<'EOF'
Usage:
  src/test/python/Frontend/scripts/run_baremode_asm_bin_trace.sh [case.S]

Purpose:
  Compile a normal-path baremode assembly testcase into a bin, generate/reuse
  the NEMU golden trace, run the existing bin-trace DUT regression, and leave
  waveform/log/.dat/funcov artifacts in the normal Frontend data directories.

Defaults:
  case.S       src/test/python/Frontend/tests/asm_cases/jiabowen/fe_ifu_mixed_rvc_rvi_boundary.S
  LINK_ADDR    0x80000000
  NEMU_MEM_BASE 0x80000000
  TB_BASE_ADDR 0x80000000
  TB_RESET_VECTOR 0x80000000

Environment:
  NEMU_EXEC or TB_NEMU_EXEC
               NEMU executable path. If unset, this script tries
               ready-to-run/riscv64-nemu-interpreter.
  TB_RUN_DUT   Passed to run_bin_trace_pipeline.sh; default 1.
  TB_RUN_ID, TB_ARTIFACT_DIR, TB_COVERAGE_DIR, TB_WAVEFORM_DIR,
  TB_FUNCOV_DIR, TB_CASE_LOG_DIR
               Optional run layout overrides. By default all outputs use
               data/runs/<run_id>/{coverage,waveforms,funcov,logs}.
  TB_FUNCOV_TARGET_BINS, TB_FUNCOV_TARGET_TP_IDS,
  TB_FUNCOV_TARGET_TESTCASES
               Optional explicit coverage targets. This coverage-focused
               wrapper defaults the testcase target to the assembly case stem.
  TB_DUT_BUILD_MANIFEST
               Build manifest path; normally generated by `make frontend`.
  TB_LOG_LEVEL, TB_TRACE_TARGET_CURSOR, TB_TRACE_MAX_CYCLES,
  TB_PYTEST_TIMEOUT_SECS, TB_COVERAGE_DIR, TB_WAVEFORM_DIR
               Passed through to the existing bin-trace pipeline/fixtures.

After a successful run, this script prints the exact run artifact directory
and matching raw/HTML code-coverage commands.
EOF
}

if [[ $# -gt 1 ]]; then
  usage
  exit 1
fi

DEFAULT_ASM="${FRONTEND_DIR}/tests/asm_cases/jiabowen/fe_ifu_mixed_rvc_rvi_boundary.S"
ASM_PATH="${1:-${DEFAULT_ASM}}"
if [[ ! -f "${ASM_PATH}" ]]; then
  echo "[frontend][error] asm not found: ${ASM_PATH}" >&2
  exit 2
fi

CASE_NAME="$(basename "${ASM_PATH}")"
CASE_STEM="${CASE_NAME%.*}"
BIN_PATH="${FRONTEND_DIR}/tests/asm_cases/generated/${CASE_STEM}.bin"

LINK_ADDR="${LINK_ADDR:-0x80000000}"
NEMU_MEM_BASE="${NEMU_MEM_BASE:-0x80000000}"
TB_BASE_ADDR="${TB_BASE_ADDR:-${NEMU_MEM_BASE}}"
TB_RESET_VECTOR="${TB_RESET_VECTOR:-${LINK_ADDR}}"
TB_RUN_DUT="${TB_RUN_DUT:-1}"
RUN_ID_DEFAULT="frontend_${CASE_STEM}_$(date +%Y%m%d_%H%M%S)_$$"
TB_RUN_ID="${TB_RUN_ID:-${RUN_ID_DEFAULT}}"
TB_ARTIFACT_DIR="${TB_ARTIFACT_DIR:-${FRONTEND_DIR}/data/runs/${TB_RUN_ID}}"
TB_COVERAGE_DIR="${TB_COVERAGE_DIR:-${TB_ARTIFACT_DIR}/coverage}"
TB_FUNCOV_TARGET_TESTCASES="${TB_FUNCOV_TARGET_TESTCASES:-${CASE_STEM}}"
TRACE_PATH="${TB_TRACE_PATH:-${TB_ARTIFACT_DIR}/inputs/${CASE_STEM}.trace.jsonl}"
NEMU_LOG_PATH="${NEMU_LOG_PATH:-${TB_ARTIFACT_DIR}/inputs/${CASE_STEM}.nemu.log}"
if ! [[ "${TB_RUN_ID}" =~ ^[A-Za-z0-9_.=-]+$ ]]; then
  echo "[frontend][error] TB_RUN_ID must contain only A-Z, a-z, 0-9, _, ., =, or -: ${TB_RUN_ID}" >&2
  exit 2
fi
if [[ -d "${TB_ARTIFACT_DIR}" ]]; then
  shopt -s nullglob dotglob
  existing_run_entries=("${TB_ARTIFACT_DIR}"/*)
  shopt -u nullglob dotglob
  if [[ "${#existing_run_entries[@]}" -gt 0 ]]; then
    echo "[frontend][error] refusing to overwrite non-empty run root: ${TB_ARTIFACT_DIR}" >&2
    exit 2
  fi
fi
if [[ -z "${TB_RUN_COMMAND:-}" ]]; then
  printf -v TB_RUN_COMMAND '%q ' "$0" "$@"
  TB_RUN_COMMAND="${TB_RUN_COMMAND% }"
fi

resolve_nemu_exec() {
  local explicit="${NEMU_EXEC:-${TB_NEMU_EXEC:-}}"
  if [[ -n "${explicit}" ]]; then
    echo "${explicit}"
    return 0
  fi

  local candidate
  for candidate in \
    "${REPO_DIR}/ready-to-run/riscv64-nemu-interpreter"; do
    if [[ -f "${candidate}" ]]; then
      echo "${candidate}"
      return 0
    fi
  done

  return 1
}

NEMU_EXEC="$(resolve_nemu_exec)" || {
  echo "[frontend][error] NEMU executable not found. Set NEMU_EXEC or TB_NEMU_EXEC." >&2
  exit 2
}

if [[ ! -x "${NEMU_EXEC}" ]]; then
  echo "[frontend][error] NEMU path exists but is not executable: ${NEMU_EXEC}" >&2
  echo "[frontend][error] Fix the executable bit or point NEMU_EXEC/TB_NEMU_EXEC at an executable NEMU." >&2
  exit 2
fi

echo "[frontend] repo: ${REPO_DIR}"
echo "[frontend] asm: ${ASM_PATH}"
echo "[frontend] bin: ${BIN_PATH}"
echo "[frontend] trace: ${TRACE_PATH}"
echo "[frontend] nemu_log: ${NEMU_LOG_PATH}"
echo "[frontend] nemu_exec: ${NEMU_EXEC}"
echo "[frontend] link_addr: ${LINK_ADDR}"
echo "[frontend] nemu_mem_base: ${NEMU_MEM_BASE}"
echo "[frontend] tb_base_addr: ${TB_BASE_ADDR}"
echo "[frontend] tb_reset_vector: ${TB_RESET_VECTOR}"
echo "[frontend] tb_run_dut: ${TB_RUN_DUT}"
echo "[frontend] run_id: ${TB_RUN_ID}"
echo "[frontend] artifact_root: ${TB_ARTIFACT_DIR}"

cd "${REPO_DIR}"

LINK_ADDR="${LINK_ADDR}" \
NEMU_MEM_BASE="${NEMU_MEM_BASE}" \
NEMU_EXEC="${NEMU_EXEC}" \
NEMU_LOG_PATH="${NEMU_LOG_PATH}" \
TB_RUN_ID="${TB_RUN_ID}" \
TB_ARTIFACT_DIR="${TB_ARTIFACT_DIR}" \
"${FRONTEND_DIR}/scripts/asm_to_jsonl.sh" "${ASM_PATH}" "${BIN_PATH}" "${TRACE_PATH}"

TB_SKIP_NEMU=1 \
TB_RUN_DUT="${TB_RUN_DUT}" \
TB_ASM_PATH="${ASM_PATH}" \
TB_RUN_COMMAND="${TB_RUN_COMMAND}" \
TB_RUN_ID="${TB_RUN_ID}" \
TB_ARTIFACT_DIR="${TB_ARTIFACT_DIR}" \
TB_COVERAGE_DIR="${TB_COVERAGE_DIR}" \
TB_FUNCOV_TARGET_TESTCASES="${TB_FUNCOV_TARGET_TESTCASES}" \
TB_NEMU_EXEC="${NEMU_EXEC}" \
TB_BASE_ADDR="${TB_BASE_ADDR}" \
TB_RESET_VECTOR="${TB_RESET_VECTOR}" \
"${FRONTEND_DIR}/scripts/run_bin_trace_pipeline.sh" "${BIN_PATH}" "${TRACE_PATH}" "${NEMU_LOG_PATH}"

echo "[frontend] artifacts_dir=${TB_ARTIFACT_DIR}"
echo "[frontend] raw_coverage_command=python ${FRONTEND_DIR}/scripts/report_raw_code_coverage.py --data-dir ${TB_COVERAGE_DIR}"
echo "[frontend] html_coverage_command=${FRONTEND_DIR}/scripts/gen_coverage_html.sh ${TB_COVERAGE_DIR}"
