# only generate a small module: example
verilog-decode:
	$(MILL) -i XiangShan.test.runMain xiangshan.DecodeMain -td build --output-file DecodeUnit.v

# chiseltest
# autorun all the chiselTest case
test:
	$(MILL) -i XiangShan.test.test

# only run DecodeUnitTest
test-DecodeUnit:
	$(MILL) -i XiangShan.test.testOnly xiangshan.DecodeUnitTest
