//=========================================================
//File name    : vecissue_agent_agent_driver.sv
//Author       : OpenAI_Codex
//Module name  : vecissue_agent_agent_driver
//Discribution : vecissue_agent_agent_driver : driver
//Date         : 2026-04-12
//=========================================================
`ifndef VECISSUE_AGENT_AGENT_DRIVER__SV
`define VECISSUE_AGENT_AGENT_DRIVER__SV

class vecissue_agent_agent_driver  extends tcnt_driver_base#(virtual vecissue_agent_agent_interface,vecissue_agent_agent_cfg,vecissue_agent_agent_xaction);

    `uvm_component_utils(vecissue_agent_agent_driver)

    extern function new(string name, uvm_component parent);
    extern virtual function void build_phase(uvm_phase phase);
    extern virtual task reset_phase(uvm_phase phase);
    extern task main_phase(uvm_phase phase);
    extern task send_pkt(vecissue_agent_agent_xaction tr);
    extern task drive_idle(tcnt_dec_base::drv_mode_e drv_mode);
endclass:vecissue_agent_agent_driver

function vecissue_agent_agent_driver::new(string name, uvm_component parent);
    super.new(name,parent);
endfunction:new

function void vecissue_agent_agent_driver::build_phase(uvm_phase phase);
    super.build_phase(phase);
endfunction:build_phase

task vecissue_agent_agent_driver::reset_phase(uvm_phase phase);

    super.reset_phase(phase);
    phase.raise_objection(this);

    repeat(2) begin
        @this.vif.drv_mp.drv_cb;
        this.drive_idle(this.cfg.drv_mode);
    end
    wait(vif.rst_n == 1'b1);
    wait(memblock_sync_pkg::reset_backend_done == 1'b1);
    repeat(20) begin
        @this.vif.drv_mp.drv_cb;
        this.drive_idle(this.cfg.drv_mode);
    end

    phase.drop_objection(this);
endtask:reset_phase

task vecissue_agent_agent_driver::main_phase(uvm_phase phase);
    super.main_phase(phase);
    //while(1) begin
    if(this.cfg.sqr_sw==tcnt_dec_base::ON && this.cfg.drv_sw==tcnt_dec_base::ON) begin
        while(1) begin
            seq_item_port.try_next_item(req);
            if(req!=null) begin
                repeat(req.pre_pkt_gap) begin
                    @this.vif.drv_mp.drv_cb;
                    this.drive_idle(this.cfg.drv_mode);
                end
                @this.vif.drv_mp.drv_cb;
                this.send_pkt(req);
                repeat(req.post_pkt_gap) begin
                    @this.vif.drv_mp.drv_cb;
                    this.drive_idle(this.cfg.drv_mode);
                end
                seq_item_port.item_done();
            end
            else begin
                @this.vif.drv_mp.drv_cb;
                this.drive_idle(this.cfg.drv_mode);
            end
        end
    end
    else if (this.cfg.drv_sw==tcnt_dec_base::ON) begin
        while(1) begin
            @this.vif.drv_mp.drv_cb;
            `uvm_fatal(get_type_name(), $sformatf("sqr_sw==OFF & drv_sw==ON, please give a driver send task!"))
            //send task
        end
    end
endtask:main_phase

task vecissue_agent_agent_driver::send_pkt(vecissue_agent_agent_xaction tr);
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_valid <= tr.io_ooo_to_mem_vecIssue_1_0_valid;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_fuOpType <= tr.io_ooo_to_mem_vecIssue_1_0_bits_fuOpType;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_src_0 <= tr.io_ooo_to_mem_vecIssue_1_0_bits_src_0;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_src_1 <= tr.io_ooo_to_mem_vecIssue_1_0_bits_src_1;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_src_2 <= tr.io_ooo_to_mem_vecIssue_1_0_bits_src_2;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_src_3 <= tr.io_ooo_to_mem_vecIssue_1_0_bits_src_3;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vl <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vl;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_robIdx_flag <= tr.io_ooo_to_mem_vecIssue_1_0_bits_robIdx_flag;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_robIdx_value <= tr.io_ooo_to_mem_vecIssue_1_0_bits_robIdx_value;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_pdest <= tr.io_ooo_to_mem_vecIssue_1_0_bits_pdest;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_pdestVl <= tr.io_ooo_to_mem_vecIssue_1_0_bits_pdestVl;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vecWen <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vecWen;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_v0Wen <= tr.io_ooo_to_mem_vecIssue_1_0_bits_v0Wen;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vlWen <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vlWen;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vill <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vill;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vma <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vma;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vta <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vta;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vsew <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vsew;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vlmul <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vlmul;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVill <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVill;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVma <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVma;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVta <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVta;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVsew <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVsew;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVlmul <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVlmul;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vm <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vm;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vstart <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vstart;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_frm <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_frm;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFpToVecInst <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFpToVecInst;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFP32Instr <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFP32Instr;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFP64Instr <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFP64Instr;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isReduction <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isReduction;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFoldTo1_2 <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFoldTo1_2;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFoldTo1_4 <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFoldTo1_4;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFoldTo1_8 <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFoldTo1_8;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vxrm <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vxrm;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vuopIdx <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vuopIdx;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_lastUop <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_lastUop;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vmask <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vmask;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_nf <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_nf;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_veew <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_veew;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isReverse <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isReverse;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isExt <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isExt;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isNarrow <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isNarrow;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isDstMask <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isDstMask;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isOpMask <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isOpMask;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isMove <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isMove;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isDependOldVd <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isDependOldVd;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isWritePartVd <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isWritePartVd;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isVleff <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isVleff;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_maskVecGen <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_maskVecGen;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew8 <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew8;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew16 <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew16;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew32 <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew32;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew64 <= tr.io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew64;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_ftqIdx_flag <= tr.io_ooo_to_mem_vecIssue_1_0_bits_ftqIdx_flag;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_ftqIdx_value <= tr.io_ooo_to_mem_vecIssue_1_0_bits_ftqIdx_value;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_ftqOffset <= tr.io_ooo_to_mem_vecIssue_1_0_bits_ftqOffset;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_numLsElem <= tr.io_ooo_to_mem_vecIssue_1_0_bits_numLsElem;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_lqIdx_flag <= tr.io_ooo_to_mem_vecIssue_1_0_bits_lqIdx_flag;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_lqIdx_value <= tr.io_ooo_to_mem_vecIssue_1_0_bits_lqIdx_value;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_sqIdx_flag <= tr.io_ooo_to_mem_vecIssue_1_0_bits_sqIdx_flag;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_sqIdx_value <= tr.io_ooo_to_mem_vecIssue_1_0_bits_sqIdx_value;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_valid <= tr.io_ooo_to_mem_vecIssue_0_0_valid;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_fuType <= tr.io_ooo_to_mem_vecIssue_0_0_bits_fuType;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_fuOpType <= tr.io_ooo_to_mem_vecIssue_0_0_bits_fuOpType;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_src_0 <= tr.io_ooo_to_mem_vecIssue_0_0_bits_src_0;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_src_1 <= tr.io_ooo_to_mem_vecIssue_0_0_bits_src_1;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_src_2 <= tr.io_ooo_to_mem_vecIssue_0_0_bits_src_2;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_src_3 <= tr.io_ooo_to_mem_vecIssue_0_0_bits_src_3;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vl <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vl;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_robIdx_flag <= tr.io_ooo_to_mem_vecIssue_0_0_bits_robIdx_flag;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_robIdx_value <= tr.io_ooo_to_mem_vecIssue_0_0_bits_robIdx_value;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_pdest <= tr.io_ooo_to_mem_vecIssue_0_0_bits_pdest;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_pdestVl <= tr.io_ooo_to_mem_vecIssue_0_0_bits_pdestVl;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vecWen <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vecWen;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_v0Wen <= tr.io_ooo_to_mem_vecIssue_0_0_bits_v0Wen;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vlWen <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vlWen;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vill <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vill;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vma <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vma;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vta <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vta;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vsew <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vsew;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vlmul <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vlmul;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVill <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVill;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVma <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVma;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVta <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVta;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVsew <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVsew;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVlmul <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVlmul;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vm <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vm;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vstart <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vstart;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_frm <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_frm;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFpToVecInst <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFpToVecInst;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFP32Instr <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFP32Instr;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFP64Instr <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFP64Instr;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isReduction <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isReduction;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFoldTo1_2 <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFoldTo1_2;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFoldTo1_4 <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFoldTo1_4;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFoldTo1_8 <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFoldTo1_8;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vxrm <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vxrm;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vuopIdx <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vuopIdx;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_lastUop <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_lastUop;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vmask <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vmask;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_nf <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_nf;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_veew <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_veew;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isReverse <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isReverse;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isExt <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isExt;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isNarrow <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isNarrow;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isDstMask <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isDstMask;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isOpMask <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isOpMask;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isMove <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isMove;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isDependOldVd <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isDependOldVd;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isWritePartVd <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isWritePartVd;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isVleff <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isVleff;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_maskVecGen <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_maskVecGen;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew8 <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew8;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew16 <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew16;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew32 <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew32;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew64 <= tr.io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew64;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_ftqIdx_flag <= tr.io_ooo_to_mem_vecIssue_0_0_bits_ftqIdx_flag;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_ftqIdx_value <= tr.io_ooo_to_mem_vecIssue_0_0_bits_ftqIdx_value;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_ftqOffset <= tr.io_ooo_to_mem_vecIssue_0_0_bits_ftqOffset;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_numLsElem <= tr.io_ooo_to_mem_vecIssue_0_0_bits_numLsElem;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_lqIdx_flag <= tr.io_ooo_to_mem_vecIssue_0_0_bits_lqIdx_flag;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_lqIdx_value <= tr.io_ooo_to_mem_vecIssue_0_0_bits_lqIdx_value;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_sqIdx_flag <= tr.io_ooo_to_mem_vecIssue_0_0_bits_sqIdx_flag;
    vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_sqIdx_value <= tr.io_ooo_to_mem_vecIssue_0_0_bits_sqIdx_value;

endtask:send_pkt

task vecissue_agent_agent_driver::drive_idle(tcnt_dec_base::drv_mode_e drv_mode);

    if(drv_mode==tcnt_dec_base::DRV_0) begin
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_valid <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_fuOpType <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_src_0 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_src_1 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_src_2 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_src_3 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vl <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_robIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_robIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_pdest <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_pdestVl <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vecWen <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_v0Wen <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vlWen <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vill <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vma <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vta <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vsew <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vlmul <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVill <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVma <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVta <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVsew <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVlmul <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vm <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vstart <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_frm <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFpToVecInst <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFP32Instr <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFP64Instr <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isReduction <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFoldTo1_2 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFoldTo1_4 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFoldTo1_8 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vxrm <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vuopIdx <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_lastUop <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vmask <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_nf <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_veew <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isReverse <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isExt <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isNarrow <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isDstMask <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isOpMask <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isMove <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isDependOldVd <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isWritePartVd <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isVleff <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_maskVecGen <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew8 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew16 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew32 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew64 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_ftqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_ftqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_ftqOffset <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_numLsElem <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_lqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_lqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_sqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_sqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_valid <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_fuType <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_fuOpType <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_src_0 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_src_1 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_src_2 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_src_3 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vl <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_robIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_robIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_pdest <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_pdestVl <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vecWen <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_v0Wen <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vlWen <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vill <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vma <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vta <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vsew <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vlmul <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVill <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVma <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVta <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVsew <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVlmul <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vm <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vstart <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_frm <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFpToVecInst <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFP32Instr <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFP64Instr <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isReduction <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFoldTo1_2 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFoldTo1_4 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFoldTo1_8 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vxrm <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vuopIdx <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_lastUop <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vmask <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_nf <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_veew <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isReverse <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isExt <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isNarrow <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isDstMask <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isOpMask <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isMove <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isDependOldVd <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isWritePartVd <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isVleff <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_maskVecGen <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew8 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew16 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew32 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew64 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_ftqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_ftqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_ftqOffset <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_numLsElem <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_lqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_lqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_sqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_sqIdx_value <= '0;

    end
    else if(drv_mode==tcnt_dec_base::DRV_1) begin
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_valid <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_fuOpType <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_src_0 <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_src_1 <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_src_2 <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_src_3 <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vl <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_robIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_robIdx_value <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_pdest <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_pdestVl <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vecWen <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_v0Wen <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vlWen <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vill <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vma <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vta <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vsew <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vlmul <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVill <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVma <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVta <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVsew <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVlmul <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vm <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vstart <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_frm <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFpToVecInst <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFP32Instr <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFP64Instr <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isReduction <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFoldTo1_2 <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFoldTo1_4 <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFoldTo1_8 <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vxrm <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vuopIdx <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_lastUop <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vmask <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_nf <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_veew <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isReverse <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isExt <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isNarrow <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isDstMask <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isOpMask <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isMove <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isDependOldVd <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isWritePartVd <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isVleff <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_maskVecGen <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew8 <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew16 <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew32 <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew64 <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_ftqIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_ftqIdx_value <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_ftqOffset <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_numLsElem <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_lqIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_lqIdx_value <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_sqIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_sqIdx_value <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_valid <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_fuType <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_fuOpType <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_src_0 <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_src_1 <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_src_2 <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_src_3 <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vl <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_robIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_robIdx_value <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_pdest <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_pdestVl <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vecWen <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_v0Wen <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vlWen <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vill <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vma <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vta <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vsew <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vlmul <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVill <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVma <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVta <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVsew <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVlmul <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vm <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vstart <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_frm <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFpToVecInst <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFP32Instr <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFP64Instr <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isReduction <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFoldTo1_2 <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFoldTo1_4 <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFoldTo1_8 <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vxrm <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vuopIdx <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_lastUop <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vmask <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_nf <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_veew <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isReverse <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isExt <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isNarrow <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isDstMask <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isOpMask <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isMove <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isDependOldVd <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isWritePartVd <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isVleff <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_maskVecGen <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew8 <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew16 <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew32 <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew64 <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_ftqIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_ftqIdx_value <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_ftqOffset <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_numLsElem <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_lqIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_lqIdx_value <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_sqIdx_flag <= '1;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_sqIdx_value <= '1;

    end
    else if(drv_mode==tcnt_dec_base::DRV_X) begin
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_valid <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_fuOpType <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_src_0 <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_src_1 <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_src_2 <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_src_3 <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vl <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_robIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_robIdx_value <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_pdest <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_pdestVl <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vecWen <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_v0Wen <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vlWen <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vill <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vma <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vta <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vsew <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vlmul <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVill <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVma <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVta <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVsew <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVlmul <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vm <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vstart <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_frm <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFpToVecInst <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFP32Instr <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFP64Instr <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isReduction <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFoldTo1_2 <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFoldTo1_4 <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFoldTo1_8 <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vxrm <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vuopIdx <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_lastUop <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vmask <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_nf <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_veew <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isReverse <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isExt <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isNarrow <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isDstMask <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isOpMask <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isMove <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isDependOldVd <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isWritePartVd <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isVleff <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_maskVecGen <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew8 <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew16 <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew32 <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew64 <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_ftqIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_ftqIdx_value <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_ftqOffset <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_numLsElem <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_lqIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_lqIdx_value <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_sqIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_sqIdx_value <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_valid <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_fuType <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_fuOpType <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_src_0 <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_src_1 <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_src_2 <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_src_3 <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vl <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_robIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_robIdx_value <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_pdest <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_pdestVl <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vecWen <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_v0Wen <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vlWen <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vill <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vma <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vta <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vsew <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vlmul <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVill <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVma <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVta <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVsew <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVlmul <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vm <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vstart <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_frm <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFpToVecInst <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFP32Instr <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFP64Instr <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isReduction <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFoldTo1_2 <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFoldTo1_4 <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFoldTo1_8 <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vxrm <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vuopIdx <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_lastUop <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vmask <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_nf <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_veew <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isReverse <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isExt <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isNarrow <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isDstMask <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isOpMask <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isMove <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isDependOldVd <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isWritePartVd <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isVleff <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_maskVecGen <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew8 <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew16 <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew32 <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew64 <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_ftqIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_ftqIdx_value <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_ftqOffset <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_numLsElem <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_lqIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_lqIdx_value <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_sqIdx_flag <= 'x;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_sqIdx_value <= 'x;

    end
    else if(drv_mode==tcnt_dec_base::DRV_RAND) begin
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_valid <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_fuOpType <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_src_0 <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_src_1 <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_src_2 <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_src_3 <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vl <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_robIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_robIdx_value <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_pdest <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_pdestVl <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vecWen <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_v0Wen <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vlWen <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vill <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vma <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vta <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vsew <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vlmul <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVill <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVma <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVta <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVsew <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVlmul <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vm <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vstart <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_frm <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFpToVecInst <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFP32Instr <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFP64Instr <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isReduction <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFoldTo1_2 <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFoldTo1_4 <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFoldTo1_8 <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vxrm <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vuopIdx <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_lastUop <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vmask <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_nf <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_veew <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isReverse <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isExt <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isNarrow <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isDstMask <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isOpMask <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isMove <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isDependOldVd <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isWritePartVd <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isVleff <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_maskVecGen <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew8 <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew16 <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew32 <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew64 <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_ftqIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_ftqIdx_value <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_ftqOffset <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_numLsElem <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_lqIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_lqIdx_value <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_sqIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_sqIdx_value <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_valid <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_fuType <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_fuOpType <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_src_0 <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_src_1 <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_src_2 <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_src_3 <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vl <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_robIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_robIdx_value <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_pdest <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_pdestVl <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vecWen <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_v0Wen <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vlWen <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vill <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vma <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vta <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vsew <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vlmul <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVill <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVma <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVta <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVsew <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVlmul <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vm <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vstart <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_frm <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFpToVecInst <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFP32Instr <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFP64Instr <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isReduction <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFoldTo1_2 <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFoldTo1_4 <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFoldTo1_8 <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vxrm <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vuopIdx <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_lastUop <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vmask <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_nf <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_veew <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isReverse <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isExt <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isNarrow <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isDstMask <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isOpMask <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isMove <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isDependOldVd <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isWritePartVd <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isVleff <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_maskVecGen <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew8 <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew16 <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew32 <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew64 <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_ftqIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_ftqIdx_value <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_ftqOffset <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_numLsElem <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_lqIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_lqIdx_value <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_sqIdx_flag <= $urandom;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_sqIdx_value <= $urandom;

    end
    else if(drv_mode==tcnt_dec_base::DRV_LST) begin
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_valid <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_fuOpType <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_src_0 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_src_1 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_src_2 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_src_3 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vl <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_robIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_robIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_pdest <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_pdestVl <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vecWen <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_v0Wen <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vlWen <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vill <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vma <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vta <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vsew <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vlmul <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVill <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVma <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVta <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVsew <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVlmul <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vm <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vstart <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_frm <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFpToVecInst <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFP32Instr <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFP64Instr <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isReduction <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFoldTo1_2 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFoldTo1_4 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFoldTo1_8 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vxrm <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vuopIdx <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_lastUop <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_vmask <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_nf <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_veew <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isReverse <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isExt <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isNarrow <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isDstMask <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isOpMask <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isMove <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isDependOldVd <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isWritePartVd <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_isVleff <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_maskVecGen <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew8 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew16 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew32 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew64 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_ftqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_ftqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_ftqOffset <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_numLsElem <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_lqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_lqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_sqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_1_0_bits_sqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_valid <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_fuType <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_fuOpType <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_src_0 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_src_1 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_src_2 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_src_3 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vl <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_robIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_robIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_pdest <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_pdestVl <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vecWen <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_v0Wen <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vlWen <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vill <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vma <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vta <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vsew <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vlmul <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVill <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVma <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVta <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVsew <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVlmul <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vm <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vstart <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_frm <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFpToVecInst <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFP32Instr <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFP64Instr <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isReduction <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFoldTo1_2 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFoldTo1_4 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFoldTo1_8 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vxrm <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vuopIdx <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_lastUop <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_vmask <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_nf <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_veew <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isReverse <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isExt <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isNarrow <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isDstMask <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isOpMask <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isMove <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isDependOldVd <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isWritePartVd <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_isVleff <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_maskVecGen <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew8 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew16 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew32 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew64 <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_ftqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_ftqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_ftqOffset <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_numLsElem <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_lqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_lqIdx_value <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_sqIdx_flag <= '0;
        vif.drv_mp.drv_cb.io_ooo_to_mem_vecIssue_0_0_bits_sqIdx_value <= '0;

    end

endtask:drive_idle

`endif
