//=========================================================
//File name    : vecissue_agent_agent_interface.sv
//Author       : OpenAI_Codex
//Module name  : vecissue_agent_agent_interface
//Discribution : vecissue_agent_agent_interface : signal interface
//Date         : 2026-04-12
//=========================================================
`ifndef VECISSUE_AGENT_AGENT_INTERFACE__SV
`define VECISSUE_AGENT_AGENT_INTERFACE__SV

`ifndef DEF_SETUP_TIME
    `define DEF_SETUP_TIME 1
`endif
`ifndef DEF_HOLD_TIME
    `define DEF_HOLD_TIME 1
`endif

interface vecissue_agent_agent_interface  (input bit clk,input bit rst_n);

    logic io_ooo_to_mem_vecIssue_1_0_ready;
    logic io_ooo_to_mem_vecIssue_1_0_valid;
    logic [8:0] io_ooo_to_mem_vecIssue_1_0_bits_fuOpType;
    logic [127:0] io_ooo_to_mem_vecIssue_1_0_bits_src_0;
    logic [127:0] io_ooo_to_mem_vecIssue_1_0_bits_src_1;
    logic [127:0] io_ooo_to_mem_vecIssue_1_0_bits_src_2;
    logic [127:0] io_ooo_to_mem_vecIssue_1_0_bits_src_3;
    logic [7:0] io_ooo_to_mem_vecIssue_1_0_bits_vl;
    logic io_ooo_to_mem_vecIssue_1_0_bits_robIdx_flag;
    logic [8:0] io_ooo_to_mem_vecIssue_1_0_bits_robIdx_value;
    logic [6:0] io_ooo_to_mem_vecIssue_1_0_bits_pdest;
    logic [4:0] io_ooo_to_mem_vecIssue_1_0_bits_pdestVl;
    logic io_ooo_to_mem_vecIssue_1_0_bits_vecWen;
    logic io_ooo_to_mem_vecIssue_1_0_bits_v0Wen;
    logic io_ooo_to_mem_vecIssue_1_0_bits_vlWen;
    logic io_ooo_to_mem_vecIssue_1_0_bits_vpu_vill;
    logic io_ooo_to_mem_vecIssue_1_0_bits_vpu_vma;
    logic io_ooo_to_mem_vecIssue_1_0_bits_vpu_vta;
    logic [1:0] io_ooo_to_mem_vecIssue_1_0_bits_vpu_vsew;
    logic [2:0] io_ooo_to_mem_vecIssue_1_0_bits_vpu_vlmul;
    logic io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVill;
    logic io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVma;
    logic io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVta;
    logic [1:0] io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVsew;
    logic [2:0] io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVlmul;
    logic io_ooo_to_mem_vecIssue_1_0_bits_vpu_vm;
    logic [7:0] io_ooo_to_mem_vecIssue_1_0_bits_vpu_vstart;
    logic [2:0] io_ooo_to_mem_vecIssue_1_0_bits_vpu_frm;
    logic io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFpToVecInst;
    logic io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFP32Instr;
    logic io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFP64Instr;
    logic io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isReduction;
    logic io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFoldTo1_2;
    logic io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFoldTo1_4;
    logic io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFoldTo1_8;
    logic [1:0] io_ooo_to_mem_vecIssue_1_0_bits_vpu_vxrm;
    logic [6:0] io_ooo_to_mem_vecIssue_1_0_bits_vpu_vuopIdx;
    logic io_ooo_to_mem_vecIssue_1_0_bits_vpu_lastUop;
    logic [127:0] io_ooo_to_mem_vecIssue_1_0_bits_vpu_vmask;
    logic [2:0] io_ooo_to_mem_vecIssue_1_0_bits_vpu_nf;
    logic [1:0] io_ooo_to_mem_vecIssue_1_0_bits_vpu_veew;
    logic io_ooo_to_mem_vecIssue_1_0_bits_vpu_isReverse;
    logic io_ooo_to_mem_vecIssue_1_0_bits_vpu_isExt;
    logic io_ooo_to_mem_vecIssue_1_0_bits_vpu_isNarrow;
    logic io_ooo_to_mem_vecIssue_1_0_bits_vpu_isDstMask;
    logic io_ooo_to_mem_vecIssue_1_0_bits_vpu_isOpMask;
    logic io_ooo_to_mem_vecIssue_1_0_bits_vpu_isMove;
    logic io_ooo_to_mem_vecIssue_1_0_bits_vpu_isDependOldVd;
    logic io_ooo_to_mem_vecIssue_1_0_bits_vpu_isWritePartVd;
    logic io_ooo_to_mem_vecIssue_1_0_bits_vpu_isVleff;
    logic [15:0] io_ooo_to_mem_vecIssue_1_0_bits_vpu_maskVecGen;
    logic io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew8;
    logic io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew16;
    logic io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew32;
    logic io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew64;
    logic io_ooo_to_mem_vecIssue_1_0_bits_ftqIdx_flag;
    logic [5:0] io_ooo_to_mem_vecIssue_1_0_bits_ftqIdx_value;
    logic [4:0] io_ooo_to_mem_vecIssue_1_0_bits_ftqOffset;
    logic [4:0] io_ooo_to_mem_vecIssue_1_0_bits_numLsElem;
    logic io_ooo_to_mem_vecIssue_1_0_bits_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_vecIssue_1_0_bits_lqIdx_value;
    logic io_ooo_to_mem_vecIssue_1_0_bits_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_vecIssue_1_0_bits_sqIdx_value;
    logic io_ooo_to_mem_vecIssue_0_0_ready;
    logic io_ooo_to_mem_vecIssue_0_0_valid;
    logic [35:0] io_ooo_to_mem_vecIssue_0_0_bits_fuType;
    logic [8:0] io_ooo_to_mem_vecIssue_0_0_bits_fuOpType;
    logic [127:0] io_ooo_to_mem_vecIssue_0_0_bits_src_0;
    logic [127:0] io_ooo_to_mem_vecIssue_0_0_bits_src_1;
    logic [127:0] io_ooo_to_mem_vecIssue_0_0_bits_src_2;
    logic [127:0] io_ooo_to_mem_vecIssue_0_0_bits_src_3;
    logic [7:0] io_ooo_to_mem_vecIssue_0_0_bits_vl;
    logic io_ooo_to_mem_vecIssue_0_0_bits_robIdx_flag;
    logic [8:0] io_ooo_to_mem_vecIssue_0_0_bits_robIdx_value;
    logic [6:0] io_ooo_to_mem_vecIssue_0_0_bits_pdest;
    logic [4:0] io_ooo_to_mem_vecIssue_0_0_bits_pdestVl;
    logic io_ooo_to_mem_vecIssue_0_0_bits_vecWen;
    logic io_ooo_to_mem_vecIssue_0_0_bits_v0Wen;
    logic io_ooo_to_mem_vecIssue_0_0_bits_vlWen;
    logic io_ooo_to_mem_vecIssue_0_0_bits_vpu_vill;
    logic io_ooo_to_mem_vecIssue_0_0_bits_vpu_vma;
    logic io_ooo_to_mem_vecIssue_0_0_bits_vpu_vta;
    logic [1:0] io_ooo_to_mem_vecIssue_0_0_bits_vpu_vsew;
    logic [2:0] io_ooo_to_mem_vecIssue_0_0_bits_vpu_vlmul;
    logic io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVill;
    logic io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVma;
    logic io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVta;
    logic [1:0] io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVsew;
    logic [2:0] io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVlmul;
    logic io_ooo_to_mem_vecIssue_0_0_bits_vpu_vm;
    logic [7:0] io_ooo_to_mem_vecIssue_0_0_bits_vpu_vstart;
    logic [2:0] io_ooo_to_mem_vecIssue_0_0_bits_vpu_frm;
    logic io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFpToVecInst;
    logic io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFP32Instr;
    logic io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFP64Instr;
    logic io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isReduction;
    logic io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFoldTo1_2;
    logic io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFoldTo1_4;
    logic io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFoldTo1_8;
    logic [1:0] io_ooo_to_mem_vecIssue_0_0_bits_vpu_vxrm;
    logic [6:0] io_ooo_to_mem_vecIssue_0_0_bits_vpu_vuopIdx;
    logic io_ooo_to_mem_vecIssue_0_0_bits_vpu_lastUop;
    logic [127:0] io_ooo_to_mem_vecIssue_0_0_bits_vpu_vmask;
    logic [2:0] io_ooo_to_mem_vecIssue_0_0_bits_vpu_nf;
    logic [1:0] io_ooo_to_mem_vecIssue_0_0_bits_vpu_veew;
    logic io_ooo_to_mem_vecIssue_0_0_bits_vpu_isReverse;
    logic io_ooo_to_mem_vecIssue_0_0_bits_vpu_isExt;
    logic io_ooo_to_mem_vecIssue_0_0_bits_vpu_isNarrow;
    logic io_ooo_to_mem_vecIssue_0_0_bits_vpu_isDstMask;
    logic io_ooo_to_mem_vecIssue_0_0_bits_vpu_isOpMask;
    logic io_ooo_to_mem_vecIssue_0_0_bits_vpu_isMove;
    logic io_ooo_to_mem_vecIssue_0_0_bits_vpu_isDependOldVd;
    logic io_ooo_to_mem_vecIssue_0_0_bits_vpu_isWritePartVd;
    logic io_ooo_to_mem_vecIssue_0_0_bits_vpu_isVleff;
    logic [15:0] io_ooo_to_mem_vecIssue_0_0_bits_vpu_maskVecGen;
    logic io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew8;
    logic io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew16;
    logic io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew32;
    logic io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew64;
    logic io_ooo_to_mem_vecIssue_0_0_bits_ftqIdx_flag;
    logic [5:0] io_ooo_to_mem_vecIssue_0_0_bits_ftqIdx_value;
    logic [4:0] io_ooo_to_mem_vecIssue_0_0_bits_ftqOffset;
    logic [4:0] io_ooo_to_mem_vecIssue_0_0_bits_numLsElem;
    logic io_ooo_to_mem_vecIssue_0_0_bits_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_vecIssue_0_0_bits_lqIdx_value;
    logic io_ooo_to_mem_vecIssue_0_0_bits_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_vecIssue_0_0_bits_sqIdx_value;

    clocking drv_cb @(posedge clk);
        `ifdef INTERFACE_ADD_DELAY
            default input #`DEF_SETUP_TIME output #`DEF_HOLD_TIME;
        `endif
        input  io_ooo_to_mem_vecIssue_1_0_ready;
        output io_ooo_to_mem_vecIssue_1_0_valid;
        output io_ooo_to_mem_vecIssue_1_0_bits_fuOpType;
        output io_ooo_to_mem_vecIssue_1_0_bits_src_0;
        output io_ooo_to_mem_vecIssue_1_0_bits_src_1;
        output io_ooo_to_mem_vecIssue_1_0_bits_src_2;
        output io_ooo_to_mem_vecIssue_1_0_bits_src_3;
        output io_ooo_to_mem_vecIssue_1_0_bits_vl;
        output io_ooo_to_mem_vecIssue_1_0_bits_robIdx_flag;
        output io_ooo_to_mem_vecIssue_1_0_bits_robIdx_value;
        output io_ooo_to_mem_vecIssue_1_0_bits_pdest;
        output io_ooo_to_mem_vecIssue_1_0_bits_pdestVl;
        output io_ooo_to_mem_vecIssue_1_0_bits_vecWen;
        output io_ooo_to_mem_vecIssue_1_0_bits_v0Wen;
        output io_ooo_to_mem_vecIssue_1_0_bits_vlWen;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_vill;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_vma;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_vta;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_vsew;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_vlmul;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVill;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVma;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVta;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVsew;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVlmul;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_vm;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_vstart;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_frm;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFpToVecInst;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFP32Instr;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFP64Instr;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isReduction;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFoldTo1_2;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFoldTo1_4;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFoldTo1_8;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_vxrm;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_vuopIdx;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_lastUop;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_vmask;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_nf;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_veew;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_isReverse;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_isExt;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_isNarrow;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_isDstMask;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_isOpMask;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_isMove;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_isDependOldVd;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_isWritePartVd;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_isVleff;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_maskVecGen;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew8;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew16;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew32;
        output io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew64;
        output io_ooo_to_mem_vecIssue_1_0_bits_ftqIdx_flag;
        output io_ooo_to_mem_vecIssue_1_0_bits_ftqIdx_value;
        output io_ooo_to_mem_vecIssue_1_0_bits_ftqOffset;
        output io_ooo_to_mem_vecIssue_1_0_bits_numLsElem;
        output io_ooo_to_mem_vecIssue_1_0_bits_lqIdx_flag;
        output io_ooo_to_mem_vecIssue_1_0_bits_lqIdx_value;
        output io_ooo_to_mem_vecIssue_1_0_bits_sqIdx_flag;
        output io_ooo_to_mem_vecIssue_1_0_bits_sqIdx_value;
        input  io_ooo_to_mem_vecIssue_0_0_ready;
        output io_ooo_to_mem_vecIssue_0_0_valid;
        output io_ooo_to_mem_vecIssue_0_0_bits_fuType;
        output io_ooo_to_mem_vecIssue_0_0_bits_fuOpType;
        output io_ooo_to_mem_vecIssue_0_0_bits_src_0;
        output io_ooo_to_mem_vecIssue_0_0_bits_src_1;
        output io_ooo_to_mem_vecIssue_0_0_bits_src_2;
        output io_ooo_to_mem_vecIssue_0_0_bits_src_3;
        output io_ooo_to_mem_vecIssue_0_0_bits_vl;
        output io_ooo_to_mem_vecIssue_0_0_bits_robIdx_flag;
        output io_ooo_to_mem_vecIssue_0_0_bits_robIdx_value;
        output io_ooo_to_mem_vecIssue_0_0_bits_pdest;
        output io_ooo_to_mem_vecIssue_0_0_bits_pdestVl;
        output io_ooo_to_mem_vecIssue_0_0_bits_vecWen;
        output io_ooo_to_mem_vecIssue_0_0_bits_v0Wen;
        output io_ooo_to_mem_vecIssue_0_0_bits_vlWen;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_vill;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_vma;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_vta;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_vsew;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_vlmul;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVill;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVma;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVta;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVsew;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVlmul;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_vm;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_vstart;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_frm;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFpToVecInst;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFP32Instr;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFP64Instr;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isReduction;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFoldTo1_2;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFoldTo1_4;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFoldTo1_8;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_vxrm;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_vuopIdx;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_lastUop;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_vmask;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_nf;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_veew;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_isReverse;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_isExt;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_isNarrow;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_isDstMask;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_isOpMask;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_isMove;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_isDependOldVd;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_isWritePartVd;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_isVleff;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_maskVecGen;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew8;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew16;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew32;
        output io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew64;
        output io_ooo_to_mem_vecIssue_0_0_bits_ftqIdx_flag;
        output io_ooo_to_mem_vecIssue_0_0_bits_ftqIdx_value;
        output io_ooo_to_mem_vecIssue_0_0_bits_ftqOffset;
        output io_ooo_to_mem_vecIssue_0_0_bits_numLsElem;
        output io_ooo_to_mem_vecIssue_0_0_bits_lqIdx_flag;
        output io_ooo_to_mem_vecIssue_0_0_bits_lqIdx_value;
        output io_ooo_to_mem_vecIssue_0_0_bits_sqIdx_flag;
        output io_ooo_to_mem_vecIssue_0_0_bits_sqIdx_value;

    endclocking:drv_cb

    clocking mon_cb @(posedge clk);
        `ifdef INTERFACE_ADD_DELAY
            default input #`DEF_SETUP_TIME output #`DEF_HOLD_TIME;
        `endif
        input  io_ooo_to_mem_vecIssue_1_0_ready;
        input  io_ooo_to_mem_vecIssue_1_0_valid;
        input  io_ooo_to_mem_vecIssue_1_0_bits_fuOpType;
        input  io_ooo_to_mem_vecIssue_1_0_bits_src_0;
        input  io_ooo_to_mem_vecIssue_1_0_bits_src_1;
        input  io_ooo_to_mem_vecIssue_1_0_bits_src_2;
        input  io_ooo_to_mem_vecIssue_1_0_bits_src_3;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vl;
        input  io_ooo_to_mem_vecIssue_1_0_bits_robIdx_flag;
        input  io_ooo_to_mem_vecIssue_1_0_bits_robIdx_value;
        input  io_ooo_to_mem_vecIssue_1_0_bits_pdest;
        input  io_ooo_to_mem_vecIssue_1_0_bits_pdestVl;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vecWen;
        input  io_ooo_to_mem_vecIssue_1_0_bits_v0Wen;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vlWen;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_vill;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_vma;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_vta;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_vsew;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_vlmul;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVill;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVma;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVta;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVsew;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_specVlmul;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_vm;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_vstart;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_frm;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFpToVecInst;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFP32Instr;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFP64Instr;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isReduction;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFoldTo1_2;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFoldTo1_4;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_fpu_isFoldTo1_8;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_vxrm;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_vuopIdx;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_lastUop;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_vmask;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_nf;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_veew;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_isReverse;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_isExt;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_isNarrow;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_isDstMask;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_isOpMask;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_isMove;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_isDependOldVd;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_isWritePartVd;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_isVleff;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_maskVecGen;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew8;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew16;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew32;
        input  io_ooo_to_mem_vecIssue_1_0_bits_vpu_sew64;
        input  io_ooo_to_mem_vecIssue_1_0_bits_ftqIdx_flag;
        input  io_ooo_to_mem_vecIssue_1_0_bits_ftqIdx_value;
        input  io_ooo_to_mem_vecIssue_1_0_bits_ftqOffset;
        input  io_ooo_to_mem_vecIssue_1_0_bits_numLsElem;
        input  io_ooo_to_mem_vecIssue_1_0_bits_lqIdx_flag;
        input  io_ooo_to_mem_vecIssue_1_0_bits_lqIdx_value;
        input  io_ooo_to_mem_vecIssue_1_0_bits_sqIdx_flag;
        input  io_ooo_to_mem_vecIssue_1_0_bits_sqIdx_value;
        input  io_ooo_to_mem_vecIssue_0_0_ready;
        input  io_ooo_to_mem_vecIssue_0_0_valid;
        input  io_ooo_to_mem_vecIssue_0_0_bits_fuType;
        input  io_ooo_to_mem_vecIssue_0_0_bits_fuOpType;
        input  io_ooo_to_mem_vecIssue_0_0_bits_src_0;
        input  io_ooo_to_mem_vecIssue_0_0_bits_src_1;
        input  io_ooo_to_mem_vecIssue_0_0_bits_src_2;
        input  io_ooo_to_mem_vecIssue_0_0_bits_src_3;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vl;
        input  io_ooo_to_mem_vecIssue_0_0_bits_robIdx_flag;
        input  io_ooo_to_mem_vecIssue_0_0_bits_robIdx_value;
        input  io_ooo_to_mem_vecIssue_0_0_bits_pdest;
        input  io_ooo_to_mem_vecIssue_0_0_bits_pdestVl;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vecWen;
        input  io_ooo_to_mem_vecIssue_0_0_bits_v0Wen;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vlWen;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_vill;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_vma;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_vta;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_vsew;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_vlmul;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVill;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVma;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVta;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVsew;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_specVlmul;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_vm;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_vstart;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_frm;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFpToVecInst;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFP32Instr;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFP64Instr;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isReduction;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFoldTo1_2;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFoldTo1_4;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_fpu_isFoldTo1_8;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_vxrm;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_vuopIdx;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_lastUop;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_vmask;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_nf;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_veew;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_isReverse;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_isExt;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_isNarrow;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_isDstMask;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_isOpMask;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_isMove;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_isDependOldVd;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_isWritePartVd;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_isVleff;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_maskVecGen;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew8;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew16;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew32;
        input  io_ooo_to_mem_vecIssue_0_0_bits_vpu_sew64;
        input  io_ooo_to_mem_vecIssue_0_0_bits_ftqIdx_flag;
        input  io_ooo_to_mem_vecIssue_0_0_bits_ftqIdx_value;
        input  io_ooo_to_mem_vecIssue_0_0_bits_ftqOffset;
        input  io_ooo_to_mem_vecIssue_0_0_bits_numLsElem;
        input  io_ooo_to_mem_vecIssue_0_0_bits_lqIdx_flag;
        input  io_ooo_to_mem_vecIssue_0_0_bits_lqIdx_value;
        input  io_ooo_to_mem_vecIssue_0_0_bits_sqIdx_flag;
        input  io_ooo_to_mem_vecIssue_0_0_bits_sqIdx_value;

    endclocking:mon_cb

    modport drv_mp (clocking drv_cb);
    modport mon_mp (clocking mon_cb);

endinterface:vecissue_agent_agent_interface

`endif
