//=========================================================
//File name    : lsqenq_agent_connect.sv
//Author       : OpenAI_Codex
//Module name  : lsqenq_agent_connect
//Discribution : lsqenq_agent_connect : lsqenq_agent Interface connection macro
//Date         : 2026-04-12
//=========================================================
`ifndef LSQENQ_AGENT_CONNECT__SV
`define LSQENQ_AGENT_CONNECT__SV

`define MEMBLOCK__LSQENQ_AGENT_CONNECT(U_IF_NAME,AGENT_PATH,RTL_PATH) \
    lsqenq_agent_agent_interface  U_IF_NAME (clk,tc_if.rst_n); \
    initial begin \
        uvm_config_db#(virtual lsqenq_agent_agent_interface)::set(null,`"*AGENT_PATH*`", "vif", U_IF_NAME); \
    end \
    `ifdef MEMBLOCK_UT \
    initial begin \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_canAccept = '0; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_needAlloc_0 = U_IF_NAME.io_ooo_to_mem_enqLsq_needAlloc_0; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_needAlloc_1 = U_IF_NAME.io_ooo_to_mem_enqLsq_needAlloc_1; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_needAlloc_2 = U_IF_NAME.io_ooo_to_mem_enqLsq_needAlloc_2; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_needAlloc_3 = U_IF_NAME.io_ooo_to_mem_enqLsq_needAlloc_3; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_needAlloc_4 = U_IF_NAME.io_ooo_to_mem_enqLsq_needAlloc_4; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_needAlloc_5 = U_IF_NAME.io_ooo_to_mem_enqLsq_needAlloc_5; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_0_valid = U_IF_NAME.io_ooo_to_mem_enqLsq_req_0_valid; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_0_bits_fuType = U_IF_NAME.io_ooo_to_mem_enqLsq_req_0_bits_fuType; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_0_bits_uopIdx = U_IF_NAME.io_ooo_to_mem_enqLsq_req_0_bits_uopIdx; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_0_bits_robIdx_flag = U_IF_NAME.io_ooo_to_mem_enqLsq_req_0_bits_robIdx_flag; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_0_bits_robIdx_value = U_IF_NAME.io_ooo_to_mem_enqLsq_req_0_bits_robIdx_value; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_flag = U_IF_NAME.io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_flag; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_value = U_IF_NAME.io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_value; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_flag = U_IF_NAME.io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_flag; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_value = U_IF_NAME.io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_value; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_0_bits_numLsElem = U_IF_NAME.io_ooo_to_mem_enqLsq_req_0_bits_numLsElem; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_1_valid = U_IF_NAME.io_ooo_to_mem_enqLsq_req_1_valid; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_1_bits_fuType = U_IF_NAME.io_ooo_to_mem_enqLsq_req_1_bits_fuType; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_1_bits_uopIdx = U_IF_NAME.io_ooo_to_mem_enqLsq_req_1_bits_uopIdx; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_1_bits_robIdx_flag = U_IF_NAME.io_ooo_to_mem_enqLsq_req_1_bits_robIdx_flag; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_1_bits_robIdx_value = U_IF_NAME.io_ooo_to_mem_enqLsq_req_1_bits_robIdx_value; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_flag = U_IF_NAME.io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_flag; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_value = U_IF_NAME.io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_value; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_flag = U_IF_NAME.io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_flag; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_value = U_IF_NAME.io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_value; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_1_bits_numLsElem = U_IF_NAME.io_ooo_to_mem_enqLsq_req_1_bits_numLsElem; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_2_valid = U_IF_NAME.io_ooo_to_mem_enqLsq_req_2_valid; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_2_bits_fuType = U_IF_NAME.io_ooo_to_mem_enqLsq_req_2_bits_fuType; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_2_bits_uopIdx = U_IF_NAME.io_ooo_to_mem_enqLsq_req_2_bits_uopIdx; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_2_bits_robIdx_flag = U_IF_NAME.io_ooo_to_mem_enqLsq_req_2_bits_robIdx_flag; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_2_bits_robIdx_value = U_IF_NAME.io_ooo_to_mem_enqLsq_req_2_bits_robIdx_value; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_flag = U_IF_NAME.io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_flag; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_value = U_IF_NAME.io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_value; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_flag = U_IF_NAME.io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_flag; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_value = U_IF_NAME.io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_value; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_2_bits_numLsElem = U_IF_NAME.io_ooo_to_mem_enqLsq_req_2_bits_numLsElem; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_3_valid = U_IF_NAME.io_ooo_to_mem_enqLsq_req_3_valid; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_3_bits_fuType = U_IF_NAME.io_ooo_to_mem_enqLsq_req_3_bits_fuType; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_3_bits_uopIdx = U_IF_NAME.io_ooo_to_mem_enqLsq_req_3_bits_uopIdx; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_3_bits_robIdx_flag = U_IF_NAME.io_ooo_to_mem_enqLsq_req_3_bits_robIdx_flag; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_3_bits_robIdx_value = U_IF_NAME.io_ooo_to_mem_enqLsq_req_3_bits_robIdx_value; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_flag = U_IF_NAME.io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_flag; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_value = U_IF_NAME.io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_value; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_flag = U_IF_NAME.io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_flag; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_value = U_IF_NAME.io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_value; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_3_bits_numLsElem = U_IF_NAME.io_ooo_to_mem_enqLsq_req_3_bits_numLsElem; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_4_valid = U_IF_NAME.io_ooo_to_mem_enqLsq_req_4_valid; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_4_bits_fuType = U_IF_NAME.io_ooo_to_mem_enqLsq_req_4_bits_fuType; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_4_bits_uopIdx = U_IF_NAME.io_ooo_to_mem_enqLsq_req_4_bits_uopIdx; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_4_bits_robIdx_flag = U_IF_NAME.io_ooo_to_mem_enqLsq_req_4_bits_robIdx_flag; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_4_bits_robIdx_value = U_IF_NAME.io_ooo_to_mem_enqLsq_req_4_bits_robIdx_value; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_flag = U_IF_NAME.io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_flag; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_value = U_IF_NAME.io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_value; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_flag = U_IF_NAME.io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_flag; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_value = U_IF_NAME.io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_value; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_4_bits_numLsElem = U_IF_NAME.io_ooo_to_mem_enqLsq_req_4_bits_numLsElem; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_5_valid = U_IF_NAME.io_ooo_to_mem_enqLsq_req_5_valid; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_5_bits_fuType = U_IF_NAME.io_ooo_to_mem_enqLsq_req_5_bits_fuType; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_5_bits_uopIdx = U_IF_NAME.io_ooo_to_mem_enqLsq_req_5_bits_uopIdx; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_5_bits_robIdx_flag = U_IF_NAME.io_ooo_to_mem_enqLsq_req_5_bits_robIdx_flag; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_5_bits_robIdx_value = U_IF_NAME.io_ooo_to_mem_enqLsq_req_5_bits_robIdx_value; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_flag = U_IF_NAME.io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_flag; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_value = U_IF_NAME.io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_value; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_flag = U_IF_NAME.io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_flag; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_value = U_IF_NAME.io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_value; \
        force RTL_PATH.io_ooo_to_mem_enqLsq_req_5_bits_numLsElem = U_IF_NAME.io_ooo_to_mem_enqLsq_req_5_bits_numLsElem; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_0_lqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_0_lqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_0_sqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_0_sqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_1_lqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_1_lqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_1_sqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_1_sqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_2_lqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_2_lqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_2_sqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_2_sqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_3_lqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_3_lqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_3_sqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_3_sqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_4_lqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_4_lqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_4_sqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_4_sqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_5_lqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_5_lqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_5_sqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_5_sqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_6_lqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_6_lqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_6_sqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_6_sqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_7_lqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_7_lqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_7_sqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_7_sqIdx_value = '0; \
    end \
    `else \
    initial begin \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_canAccept = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_needAlloc_0 = RTL_PATH.io_ooo_to_mem_enqLsq_needAlloc_0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_needAlloc_1 = RTL_PATH.io_ooo_to_mem_enqLsq_needAlloc_1; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_needAlloc_2 = RTL_PATH.io_ooo_to_mem_enqLsq_needAlloc_2; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_needAlloc_3 = RTL_PATH.io_ooo_to_mem_enqLsq_needAlloc_3; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_needAlloc_4 = RTL_PATH.io_ooo_to_mem_enqLsq_needAlloc_4; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_needAlloc_5 = RTL_PATH.io_ooo_to_mem_enqLsq_needAlloc_5; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_needAlloc_6 = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_needAlloc_7 = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_0_valid = RTL_PATH.io_ooo_to_mem_enqLsq_req_0_valid; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_0_bits_fuType = RTL_PATH.io_ooo_to_mem_enqLsq_req_0_bits_fuType; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_0_bits_uopIdx = RTL_PATH.io_ooo_to_mem_enqLsq_req_0_bits_uopIdx; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_0_bits_robIdx_flag = RTL_PATH.io_ooo_to_mem_enqLsq_req_0_bits_robIdx_flag; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_0_bits_robIdx_value = RTL_PATH.io_ooo_to_mem_enqLsq_req_0_bits_robIdx_value; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_flag = RTL_PATH.io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_flag; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_value = RTL_PATH.io_ooo_to_mem_enqLsq_req_0_bits_lqIdx_value; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_flag = RTL_PATH.io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_flag; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_value = RTL_PATH.io_ooo_to_mem_enqLsq_req_0_bits_sqIdx_value; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_0_bits_numLsElem = RTL_PATH.io_ooo_to_mem_enqLsq_req_0_bits_numLsElem; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_1_valid = RTL_PATH.io_ooo_to_mem_enqLsq_req_1_valid; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_1_bits_fuType = RTL_PATH.io_ooo_to_mem_enqLsq_req_1_bits_fuType; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_1_bits_uopIdx = RTL_PATH.io_ooo_to_mem_enqLsq_req_1_bits_uopIdx; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_1_bits_robIdx_flag = RTL_PATH.io_ooo_to_mem_enqLsq_req_1_bits_robIdx_flag; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_1_bits_robIdx_value = RTL_PATH.io_ooo_to_mem_enqLsq_req_1_bits_robIdx_value; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_flag = RTL_PATH.io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_flag; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_value = RTL_PATH.io_ooo_to_mem_enqLsq_req_1_bits_lqIdx_value; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_flag = RTL_PATH.io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_flag; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_value = RTL_PATH.io_ooo_to_mem_enqLsq_req_1_bits_sqIdx_value; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_1_bits_numLsElem = RTL_PATH.io_ooo_to_mem_enqLsq_req_1_bits_numLsElem; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_2_valid = RTL_PATH.io_ooo_to_mem_enqLsq_req_2_valid; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_2_bits_fuType = RTL_PATH.io_ooo_to_mem_enqLsq_req_2_bits_fuType; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_2_bits_uopIdx = RTL_PATH.io_ooo_to_mem_enqLsq_req_2_bits_uopIdx; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_2_bits_robIdx_flag = RTL_PATH.io_ooo_to_mem_enqLsq_req_2_bits_robIdx_flag; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_2_bits_robIdx_value = RTL_PATH.io_ooo_to_mem_enqLsq_req_2_bits_robIdx_value; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_flag = RTL_PATH.io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_flag; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_value = RTL_PATH.io_ooo_to_mem_enqLsq_req_2_bits_lqIdx_value; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_flag = RTL_PATH.io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_flag; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_value = RTL_PATH.io_ooo_to_mem_enqLsq_req_2_bits_sqIdx_value; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_2_bits_numLsElem = RTL_PATH.io_ooo_to_mem_enqLsq_req_2_bits_numLsElem; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_3_valid = RTL_PATH.io_ooo_to_mem_enqLsq_req_3_valid; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_3_bits_fuType = RTL_PATH.io_ooo_to_mem_enqLsq_req_3_bits_fuType; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_3_bits_uopIdx = RTL_PATH.io_ooo_to_mem_enqLsq_req_3_bits_uopIdx; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_3_bits_robIdx_flag = RTL_PATH.io_ooo_to_mem_enqLsq_req_3_bits_robIdx_flag; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_3_bits_robIdx_value = RTL_PATH.io_ooo_to_mem_enqLsq_req_3_bits_robIdx_value; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_flag = RTL_PATH.io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_flag; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_value = RTL_PATH.io_ooo_to_mem_enqLsq_req_3_bits_lqIdx_value; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_flag = RTL_PATH.io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_flag; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_value = RTL_PATH.io_ooo_to_mem_enqLsq_req_3_bits_sqIdx_value; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_3_bits_numLsElem = RTL_PATH.io_ooo_to_mem_enqLsq_req_3_bits_numLsElem; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_4_valid = RTL_PATH.io_ooo_to_mem_enqLsq_req_4_valid; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_4_bits_fuType = RTL_PATH.io_ooo_to_mem_enqLsq_req_4_bits_fuType; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_4_bits_uopIdx = RTL_PATH.io_ooo_to_mem_enqLsq_req_4_bits_uopIdx; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_4_bits_robIdx_flag = RTL_PATH.io_ooo_to_mem_enqLsq_req_4_bits_robIdx_flag; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_4_bits_robIdx_value = RTL_PATH.io_ooo_to_mem_enqLsq_req_4_bits_robIdx_value; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_flag = RTL_PATH.io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_flag; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_value = RTL_PATH.io_ooo_to_mem_enqLsq_req_4_bits_lqIdx_value; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_flag = RTL_PATH.io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_flag; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_value = RTL_PATH.io_ooo_to_mem_enqLsq_req_4_bits_sqIdx_value; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_4_bits_numLsElem = RTL_PATH.io_ooo_to_mem_enqLsq_req_4_bits_numLsElem; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_5_valid = RTL_PATH.io_ooo_to_mem_enqLsq_req_5_valid; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_5_bits_fuType = RTL_PATH.io_ooo_to_mem_enqLsq_req_5_bits_fuType; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_5_bits_uopIdx = RTL_PATH.io_ooo_to_mem_enqLsq_req_5_bits_uopIdx; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_5_bits_robIdx_flag = RTL_PATH.io_ooo_to_mem_enqLsq_req_5_bits_robIdx_flag; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_5_bits_robIdx_value = RTL_PATH.io_ooo_to_mem_enqLsq_req_5_bits_robIdx_value; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_flag = RTL_PATH.io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_flag; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_value = RTL_PATH.io_ooo_to_mem_enqLsq_req_5_bits_lqIdx_value; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_flag = RTL_PATH.io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_flag; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_value = RTL_PATH.io_ooo_to_mem_enqLsq_req_5_bits_sqIdx_value; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_5_bits_numLsElem = RTL_PATH.io_ooo_to_mem_enqLsq_req_5_bits_numLsElem; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_6_valid = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_6_bits_fuType = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_6_bits_uopIdx = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_6_bits_robIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_6_bits_robIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_6_bits_lqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_6_bits_lqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_6_bits_sqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_6_bits_sqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_6_bits_numLsElem = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_7_valid = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_7_bits_fuType = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_7_bits_uopIdx = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_7_bits_robIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_7_bits_robIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_7_bits_lqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_7_bits_lqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_7_bits_sqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_7_bits_sqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_req_7_bits_numLsElem = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_0_lqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_0_lqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_0_sqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_0_sqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_1_lqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_1_lqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_1_sqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_1_sqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_2_lqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_2_lqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_2_sqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_2_sqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_3_lqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_3_lqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_3_sqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_3_sqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_4_lqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_4_lqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_4_sqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_4_sqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_5_lqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_5_lqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_5_sqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_5_sqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_6_lqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_6_lqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_6_sqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_6_sqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_7_lqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_7_lqIdx_value = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_7_sqIdx_flag = '0; \
        force U_IF_NAME.io_ooo_to_mem_enqLsq_resp_7_sqIdx_value = '0; \
    end \
    `endif

`endif
