// Generated by scripts/generate_sva.py; do not edit manually.
// MemBlock RTL SHA-256: 0b6c6aa34dc8aa148d0f6da91091df58e6622415136e60baf985d7560824e7e3

`ifndef SYNTHESIS
module memblock_stability_assertion #(
  parameter integer WIDTH = 1,
  parameter integer ASSERTION_ID = 0
) (
  input logic                 clock,
  input logic                 reset,
  input logic                 valid,
  input logic                 ready,
  input logic [WIDTH-1:0]     payload
);
  logic                 previous_stalled;
  logic [WIDTH-1:0]     previous_payload;

  always_ff @(posedge clock) begin
    if (reset) begin
      previous_stalled <= 1'b0;
      previous_payload <= '0;
    end
    else begin
      if (previous_stalled) begin
        assert (valid)
          else $error("MemBlock producer %0d dropped valid while stalled", ASSERTION_ID);
        assert (payload == previous_payload)
          else $error("MemBlock producer %0d changed payload while stalled", ASSERTION_ID);
      end
      previous_stalled <= valid && !ready;
      previous_payload <= payload;
    end
  end
endmodule

// 0: decoupled io_fetch_to_mem_itlb_resp
bind MemBlock memblock_stability_assertion #(
  .WIDTH(270),
  .ASSERTION_ID(0)
) memblock_stable_io_fetch_to_mem_itlb_resp (
  .clock(clock),
  .reset(reset),
  .valid(io_fetch_to_mem_itlb_resp_valid),
  .ready(io_fetch_to_mem_itlb_resp_ready),
  .payload({
    io_fetch_to_mem_itlb_resp_bits_s2xlate,
    io_fetch_to_mem_itlb_resp_bits_s1_entry_tag,
    io_fetch_to_mem_itlb_resp_bits_s1_entry_asid,
    io_fetch_to_mem_itlb_resp_bits_s1_entry_vmid,
    io_fetch_to_mem_itlb_resp_bits_s1_entry_n,
    io_fetch_to_mem_itlb_resp_bits_s1_entry_pbmt,
    io_fetch_to_mem_itlb_resp_bits_s1_entry_perm_d,
    io_fetch_to_mem_itlb_resp_bits_s1_entry_perm_a,
    io_fetch_to_mem_itlb_resp_bits_s1_entry_perm_g,
    io_fetch_to_mem_itlb_resp_bits_s1_entry_perm_u,
    io_fetch_to_mem_itlb_resp_bits_s1_entry_perm_x,
    io_fetch_to_mem_itlb_resp_bits_s1_entry_perm_w,
    io_fetch_to_mem_itlb_resp_bits_s1_entry_perm_r,
    io_fetch_to_mem_itlb_resp_bits_s1_entry_level,
    io_fetch_to_mem_itlb_resp_bits_s1_entry_v,
    io_fetch_to_mem_itlb_resp_bits_s1_entry_ppn,
    io_fetch_to_mem_itlb_resp_bits_s1_addr_low,
    io_fetch_to_mem_itlb_resp_bits_s1_ppn_low_0,
    io_fetch_to_mem_itlb_resp_bits_s1_ppn_low_1,
    io_fetch_to_mem_itlb_resp_bits_s1_ppn_low_2,
    io_fetch_to_mem_itlb_resp_bits_s1_ppn_low_3,
    io_fetch_to_mem_itlb_resp_bits_s1_ppn_low_4,
    io_fetch_to_mem_itlb_resp_bits_s1_ppn_low_5,
    io_fetch_to_mem_itlb_resp_bits_s1_ppn_low_6,
    io_fetch_to_mem_itlb_resp_bits_s1_ppn_low_7,
    io_fetch_to_mem_itlb_resp_bits_s1_valididx_0,
    io_fetch_to_mem_itlb_resp_bits_s1_valididx_1,
    io_fetch_to_mem_itlb_resp_bits_s1_valididx_2,
    io_fetch_to_mem_itlb_resp_bits_s1_valididx_3,
    io_fetch_to_mem_itlb_resp_bits_s1_valididx_4,
    io_fetch_to_mem_itlb_resp_bits_s1_valididx_5,
    io_fetch_to_mem_itlb_resp_bits_s1_valididx_6,
    io_fetch_to_mem_itlb_resp_bits_s1_valididx_7,
    io_fetch_to_mem_itlb_resp_bits_s1_pteidx_0,
    io_fetch_to_mem_itlb_resp_bits_s1_pteidx_1,
    io_fetch_to_mem_itlb_resp_bits_s1_pteidx_2,
    io_fetch_to_mem_itlb_resp_bits_s1_pteidx_3,
    io_fetch_to_mem_itlb_resp_bits_s1_pteidx_4,
    io_fetch_to_mem_itlb_resp_bits_s1_pteidx_5,
    io_fetch_to_mem_itlb_resp_bits_s1_pteidx_6,
    io_fetch_to_mem_itlb_resp_bits_s1_pteidx_7,
    io_fetch_to_mem_itlb_resp_bits_s1_pf,
    io_fetch_to_mem_itlb_resp_bits_s1_af,
    io_fetch_to_mem_itlb_resp_bits_s2_entry_tag,
    io_fetch_to_mem_itlb_resp_bits_s2_entry_vmid,
    io_fetch_to_mem_itlb_resp_bits_s2_entry_n,
    io_fetch_to_mem_itlb_resp_bits_s2_entry_pbmt,
    io_fetch_to_mem_itlb_resp_bits_s2_entry_ppn,
    io_fetch_to_mem_itlb_resp_bits_s2_entry_perm_d,
    io_fetch_to_mem_itlb_resp_bits_s2_entry_perm_a,
    io_fetch_to_mem_itlb_resp_bits_s2_entry_perm_g,
    io_fetch_to_mem_itlb_resp_bits_s2_entry_perm_u,
    io_fetch_to_mem_itlb_resp_bits_s2_entry_perm_x,
    io_fetch_to_mem_itlb_resp_bits_s2_entry_perm_w,
    io_fetch_to_mem_itlb_resp_bits_s2_entry_perm_r,
    io_fetch_to_mem_itlb_resp_bits_s2_entry_level,
    io_fetch_to_mem_itlb_resp_bits_s2_gpf,
    io_fetch_to_mem_itlb_resp_bits_s2_gaf
  })
);

// 1: tilelink auto_inner_buffers_out_a
bind MemBlock memblock_stability_assertion #(
  .WIDTH(135),
  .ASSERTION_ID(1)
) memblock_stable_auto_inner_buffers_out_a (
  .clock(clock),
  .reset(reset),
  .valid(auto_inner_buffers_out_a_valid),
  .ready(auto_inner_buffers_out_a_ready),
  .payload({
    auto_inner_buffers_out_a_bits_opcode,
    auto_inner_buffers_out_a_bits_param,
    auto_inner_buffers_out_a_bits_size,
    auto_inner_buffers_out_a_bits_source,
    auto_inner_buffers_out_a_bits_address,
    auto_inner_buffers_out_a_bits_mask,
    auto_inner_buffers_out_a_bits_data,
    auto_inner_buffers_out_a_bits_corrupt
  })
);

// 2: tilelink auto_inner_dcache_client_out_a
bind MemBlock memblock_stability_assertion #(
  .WIDTH(406),
  .ASSERTION_ID(2)
) memblock_stable_auto_inner_dcache_client_out_a (
  .clock(clock),
  .reset(reset),
  .valid(auto_inner_dcache_client_out_a_valid),
  .ready(auto_inner_dcache_client_out_a_ready),
  .payload({
    auto_inner_dcache_client_out_a_bits_opcode,
    auto_inner_dcache_client_out_a_bits_param,
    auto_inner_dcache_client_out_a_bits_size,
    auto_inner_dcache_client_out_a_bits_source,
    auto_inner_dcache_client_out_a_bits_address,
    auto_inner_dcache_client_out_a_bits_user_alias,
    auto_inner_dcache_client_out_a_bits_user_vaddr,
    auto_inner_dcache_client_out_a_bits_user_reqSource,
    auto_inner_dcache_client_out_a_bits_user_needHint,
    auto_inner_dcache_client_out_a_bits_echo_isKeyword,
    auto_inner_dcache_client_out_a_bits_mask,
    auto_inner_dcache_client_out_a_bits_data,
    auto_inner_dcache_client_out_a_bits_corrupt
  })
);

// 3: tilelink auto_inner_dcache_client_out_c
bind MemBlock memblock_stability_assertion #(
  .WIDTH(373),
  .ASSERTION_ID(3)
) memblock_stable_auto_inner_dcache_client_out_c (
  .clock(clock),
  .reset(reset),
  .valid(auto_inner_dcache_client_out_c_valid),
  .ready(auto_inner_dcache_client_out_c_ready),
  .payload({
    auto_inner_dcache_client_out_c_bits_opcode,
    auto_inner_dcache_client_out_c_bits_param,
    auto_inner_dcache_client_out_c_bits_size,
    auto_inner_dcache_client_out_c_bits_source,
    auto_inner_dcache_client_out_c_bits_address,
    auto_inner_dcache_client_out_c_bits_user_alias,
    auto_inner_dcache_client_out_c_bits_user_vaddr,
    auto_inner_dcache_client_out_c_bits_user_reqSource,
    auto_inner_dcache_client_out_c_bits_user_needHint,
    auto_inner_dcache_client_out_c_bits_echo_isKeyword,
    auto_inner_dcache_client_out_c_bits_data,
    auto_inner_dcache_client_out_c_bits_corrupt
  })
);

// 4: tilelink auto_inner_dcache_client_out_e
bind MemBlock memblock_stability_assertion #(
  .WIDTH(10),
  .ASSERTION_ID(4)
) memblock_stable_auto_inner_dcache_client_out_e (
  .clock(clock),
  .reset(reset),
  .valid(auto_inner_dcache_client_out_e_valid),
  .ready(auto_inner_dcache_client_out_e_ready),
  .payload({
    auto_inner_dcache_client_out_e_bits_sink
  })
);

// 5: tilelink auto_inner_frontendBridge_icache_out_a
bind MemBlock memblock_stability_assertion #(
  .WIDTH(359),
  .ASSERTION_ID(5)
) memblock_stable_auto_inner_frontendBridge_icache_out_a (
  .clock(clock),
  .reset(reset),
  .valid(auto_inner_frontendBridge_icache_out_a_valid),
  .ready(auto_inner_frontendBridge_icache_out_a_ready),
  .payload({
    auto_inner_frontendBridge_icache_out_a_bits_opcode,
    auto_inner_frontendBridge_icache_out_a_bits_param,
    auto_inner_frontendBridge_icache_out_a_bits_size,
    auto_inner_frontendBridge_icache_out_a_bits_source,
    auto_inner_frontendBridge_icache_out_a_bits_address,
    auto_inner_frontendBridge_icache_out_a_bits_user_alias,
    auto_inner_frontendBridge_icache_out_a_bits_user_reqSource,
    auto_inner_frontendBridge_icache_out_a_bits_user_needHint,
    auto_inner_frontendBridge_icache_out_a_bits_mask,
    auto_inner_frontendBridge_icache_out_a_bits_data,
    auto_inner_frontendBridge_icache_out_a_bits_corrupt
  })
);

// 6: tilelink auto_inner_frontendBridge_icachectrl_in_d
bind MemBlock memblock_stability_assertion #(
  .WIDTH(80),
  .ASSERTION_ID(6)
) memblock_stable_auto_inner_frontendBridge_icachectrl_in_d (
  .clock(clock),
  .reset(reset),
  .valid(auto_inner_frontendBridge_icachectrl_in_d_valid),
  .ready(auto_inner_frontendBridge_icachectrl_in_d_ready),
  .payload({
    auto_inner_frontendBridge_icachectrl_in_d_bits_opcode,
    auto_inner_frontendBridge_icachectrl_in_d_bits_param,
    auto_inner_frontendBridge_icachectrl_in_d_bits_size,
    auto_inner_frontendBridge_icachectrl_in_d_bits_source,
    auto_inner_frontendBridge_icachectrl_in_d_bits_sink,
    auto_inner_frontendBridge_icachectrl_in_d_bits_denied,
    auto_inner_frontendBridge_icachectrl_in_d_bits_data,
    auto_inner_frontendBridge_icachectrl_in_d_bits_corrupt
  })
);

// 7: tilelink auto_inner_frontendBridge_icachectrl_out_a
bind MemBlock memblock_stability_assertion #(
  .WIDTH(113),
  .ASSERTION_ID(7)
) memblock_stable_auto_inner_frontendBridge_icachectrl_out_a (
  .clock(clock),
  .reset(reset),
  .valid(auto_inner_frontendBridge_icachectrl_out_a_valid),
  .ready(auto_inner_frontendBridge_icachectrl_out_a_ready),
  .payload({
    auto_inner_frontendBridge_icachectrl_out_a_bits_opcode,
    auto_inner_frontendBridge_icachectrl_out_a_bits_size,
    auto_inner_frontendBridge_icachectrl_out_a_bits_source,
    auto_inner_frontendBridge_icachectrl_out_a_bits_address,
    auto_inner_frontendBridge_icachectrl_out_a_bits_mask,
    auto_inner_frontendBridge_icachectrl_out_a_bits_data
  })
);

// 8: tilelink auto_inner_frontendBridge_instr_uncache_out_a
bind MemBlock memblock_stability_assertion #(
  .WIDTH(52),
  .ASSERTION_ID(8)
) memblock_stable_auto_inner_frontendBridge_instr_uncache_out_a (
  .clock(clock),
  .reset(reset),
  .valid(auto_inner_frontendBridge_instr_uncache_out_a_valid),
  .ready(auto_inner_frontendBridge_instr_uncache_out_a_ready),
  .payload({
    auto_inner_frontendBridge_instr_uncache_out_a_bits_param,
    auto_inner_frontendBridge_instr_uncache_out_a_bits_address,
    auto_inner_frontendBridge_instr_uncache_out_a_bits_corrupt
  })
);

// 9: tilelink auto_inner_ptw_to_l2_buffer_out_a
bind MemBlock memblock_stability_assertion #(
  .WIDTH(356),
  .ASSERTION_ID(9)
) memblock_stable_auto_inner_ptw_to_l2_buffer_out_a (
  .clock(clock),
  .reset(reset),
  .valid(auto_inner_ptw_to_l2_buffer_out_a_valid),
  .ready(auto_inner_ptw_to_l2_buffer_out_a_ready),
  .payload({
    auto_inner_ptw_to_l2_buffer_out_a_bits_opcode,
    auto_inner_ptw_to_l2_buffer_out_a_bits_param,
    auto_inner_ptw_to_l2_buffer_out_a_bits_size,
    auto_inner_ptw_to_l2_buffer_out_a_bits_source,
    auto_inner_ptw_to_l2_buffer_out_a_bits_address,
    auto_inner_ptw_to_l2_buffer_out_a_bits_user_reqSource,
    auto_inner_ptw_to_l2_buffer_out_a_bits_mask,
    auto_inner_ptw_to_l2_buffer_out_a_bits_data,
    auto_inner_ptw_to_l2_buffer_out_a_bits_corrupt
  })
);

module memblock_store_tlb_miss_preserve_assertion #(
  parameter logic [5:0] SQ_INDEX = 6'd0
) (
  input logic       clock,
  input logic       reset,
  input logic       lane0_valid,
  input logic       lane0_update,
  input logic       lane0_miss,
  input logic [5:0] lane0_sq_idx,
  input logic       lane1_valid,
  input logic       lane1_update,
  input logic       lane1_miss,
  input logic [5:0] lane1_sq_idx,
  input logic       allocated,
  input logic       addr_valid,
  input logic       stored_rob_flag,
  input logic [7:0] stored_rob_value,
  input logic [6:0] stored_uop_idx
);
  logic check_next;
  logic previous_rob_flag;
  logic [7:0] previous_rob_value;
  logic [6:0] previous_uop_idx;
  always_ff @(posedge clock) begin
    if (reset) begin
      check_next <= 1'b0;
      previous_rob_flag <= 1'b0;
      previous_rob_value <= '0;
      previous_uop_idx <= '0;
    end
    else begin
      if (check_next) begin
        assert (!allocated ||
                stored_rob_flag != previous_rob_flag ||
                stored_rob_value != previous_rob_value ||
                stored_uop_idx != previous_uop_idx ||
                addr_valid)
          else $error("StoreQueue entry %0d lost addrvalid on TLB miss", SQ_INDEX);
      end
      check_next <= allocated && addr_valid && (
        lane0_valid && lane0_update && lane0_miss && lane0_sq_idx == SQ_INDEX
        || lane1_valid && lane1_update && lane1_miss && lane1_sq_idx == SQ_INDEX
      );
      previous_rob_flag <= stored_rob_flag;
      previous_rob_value <= stored_rob_value;
      previous_uop_idx <= stored_uop_idx;
    end
  end
endmodule

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd0)
) memblock_store_tlb_miss_preserve_0 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_0),
  .addr_valid(addrvalid_0),
  .stored_rob_flag(uop_0_robIdx_flag),
  .stored_rob_value(uop_0_robIdx_value),
  .stored_uop_idx(uop_0_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd1)
) memblock_store_tlb_miss_preserve_1 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_1),
  .addr_valid(addrvalid_1),
  .stored_rob_flag(uop_1_robIdx_flag),
  .stored_rob_value(uop_1_robIdx_value),
  .stored_uop_idx(uop_1_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd2)
) memblock_store_tlb_miss_preserve_2 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_2),
  .addr_valid(addrvalid_2),
  .stored_rob_flag(uop_2_robIdx_flag),
  .stored_rob_value(uop_2_robIdx_value),
  .stored_uop_idx(uop_2_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd3)
) memblock_store_tlb_miss_preserve_3 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_3),
  .addr_valid(addrvalid_3),
  .stored_rob_flag(uop_3_robIdx_flag),
  .stored_rob_value(uop_3_robIdx_value),
  .stored_uop_idx(uop_3_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd4)
) memblock_store_tlb_miss_preserve_4 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_4),
  .addr_valid(addrvalid_4),
  .stored_rob_flag(uop_4_robIdx_flag),
  .stored_rob_value(uop_4_robIdx_value),
  .stored_uop_idx(uop_4_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd5)
) memblock_store_tlb_miss_preserve_5 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_5),
  .addr_valid(addrvalid_5),
  .stored_rob_flag(uop_5_robIdx_flag),
  .stored_rob_value(uop_5_robIdx_value),
  .stored_uop_idx(uop_5_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd6)
) memblock_store_tlb_miss_preserve_6 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_6),
  .addr_valid(addrvalid_6),
  .stored_rob_flag(uop_6_robIdx_flag),
  .stored_rob_value(uop_6_robIdx_value),
  .stored_uop_idx(uop_6_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd7)
) memblock_store_tlb_miss_preserve_7 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_7),
  .addr_valid(addrvalid_7),
  .stored_rob_flag(uop_7_robIdx_flag),
  .stored_rob_value(uop_7_robIdx_value),
  .stored_uop_idx(uop_7_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd8)
) memblock_store_tlb_miss_preserve_8 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_8),
  .addr_valid(addrvalid_8),
  .stored_rob_flag(uop_8_robIdx_flag),
  .stored_rob_value(uop_8_robIdx_value),
  .stored_uop_idx(uop_8_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd9)
) memblock_store_tlb_miss_preserve_9 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_9),
  .addr_valid(addrvalid_9),
  .stored_rob_flag(uop_9_robIdx_flag),
  .stored_rob_value(uop_9_robIdx_value),
  .stored_uop_idx(uop_9_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd10)
) memblock_store_tlb_miss_preserve_10 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_10),
  .addr_valid(addrvalid_10),
  .stored_rob_flag(uop_10_robIdx_flag),
  .stored_rob_value(uop_10_robIdx_value),
  .stored_uop_idx(uop_10_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd11)
) memblock_store_tlb_miss_preserve_11 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_11),
  .addr_valid(addrvalid_11),
  .stored_rob_flag(uop_11_robIdx_flag),
  .stored_rob_value(uop_11_robIdx_value),
  .stored_uop_idx(uop_11_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd12)
) memblock_store_tlb_miss_preserve_12 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_12),
  .addr_valid(addrvalid_12),
  .stored_rob_flag(uop_12_robIdx_flag),
  .stored_rob_value(uop_12_robIdx_value),
  .stored_uop_idx(uop_12_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd13)
) memblock_store_tlb_miss_preserve_13 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_13),
  .addr_valid(addrvalid_13),
  .stored_rob_flag(uop_13_robIdx_flag),
  .stored_rob_value(uop_13_robIdx_value),
  .stored_uop_idx(uop_13_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd14)
) memblock_store_tlb_miss_preserve_14 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_14),
  .addr_valid(addrvalid_14),
  .stored_rob_flag(uop_14_robIdx_flag),
  .stored_rob_value(uop_14_robIdx_value),
  .stored_uop_idx(uop_14_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd15)
) memblock_store_tlb_miss_preserve_15 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_15),
  .addr_valid(addrvalid_15),
  .stored_rob_flag(uop_15_robIdx_flag),
  .stored_rob_value(uop_15_robIdx_value),
  .stored_uop_idx(uop_15_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd16)
) memblock_store_tlb_miss_preserve_16 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_16),
  .addr_valid(addrvalid_16),
  .stored_rob_flag(uop_16_robIdx_flag),
  .stored_rob_value(uop_16_robIdx_value),
  .stored_uop_idx(uop_16_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd17)
) memblock_store_tlb_miss_preserve_17 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_17),
  .addr_valid(addrvalid_17),
  .stored_rob_flag(uop_17_robIdx_flag),
  .stored_rob_value(uop_17_robIdx_value),
  .stored_uop_idx(uop_17_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd18)
) memblock_store_tlb_miss_preserve_18 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_18),
  .addr_valid(addrvalid_18),
  .stored_rob_flag(uop_18_robIdx_flag),
  .stored_rob_value(uop_18_robIdx_value),
  .stored_uop_idx(uop_18_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd19)
) memblock_store_tlb_miss_preserve_19 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_19),
  .addr_valid(addrvalid_19),
  .stored_rob_flag(uop_19_robIdx_flag),
  .stored_rob_value(uop_19_robIdx_value),
  .stored_uop_idx(uop_19_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd20)
) memblock_store_tlb_miss_preserve_20 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_20),
  .addr_valid(addrvalid_20),
  .stored_rob_flag(uop_20_robIdx_flag),
  .stored_rob_value(uop_20_robIdx_value),
  .stored_uop_idx(uop_20_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd21)
) memblock_store_tlb_miss_preserve_21 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_21),
  .addr_valid(addrvalid_21),
  .stored_rob_flag(uop_21_robIdx_flag),
  .stored_rob_value(uop_21_robIdx_value),
  .stored_uop_idx(uop_21_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd22)
) memblock_store_tlb_miss_preserve_22 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_22),
  .addr_valid(addrvalid_22),
  .stored_rob_flag(uop_22_robIdx_flag),
  .stored_rob_value(uop_22_robIdx_value),
  .stored_uop_idx(uop_22_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd23)
) memblock_store_tlb_miss_preserve_23 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_23),
  .addr_valid(addrvalid_23),
  .stored_rob_flag(uop_23_robIdx_flag),
  .stored_rob_value(uop_23_robIdx_value),
  .stored_uop_idx(uop_23_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd24)
) memblock_store_tlb_miss_preserve_24 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_24),
  .addr_valid(addrvalid_24),
  .stored_rob_flag(uop_24_robIdx_flag),
  .stored_rob_value(uop_24_robIdx_value),
  .stored_uop_idx(uop_24_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd25)
) memblock_store_tlb_miss_preserve_25 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_25),
  .addr_valid(addrvalid_25),
  .stored_rob_flag(uop_25_robIdx_flag),
  .stored_rob_value(uop_25_robIdx_value),
  .stored_uop_idx(uop_25_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd26)
) memblock_store_tlb_miss_preserve_26 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_26),
  .addr_valid(addrvalid_26),
  .stored_rob_flag(uop_26_robIdx_flag),
  .stored_rob_value(uop_26_robIdx_value),
  .stored_uop_idx(uop_26_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd27)
) memblock_store_tlb_miss_preserve_27 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_27),
  .addr_valid(addrvalid_27),
  .stored_rob_flag(uop_27_robIdx_flag),
  .stored_rob_value(uop_27_robIdx_value),
  .stored_uop_idx(uop_27_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd28)
) memblock_store_tlb_miss_preserve_28 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_28),
  .addr_valid(addrvalid_28),
  .stored_rob_flag(uop_28_robIdx_flag),
  .stored_rob_value(uop_28_robIdx_value),
  .stored_uop_idx(uop_28_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd29)
) memblock_store_tlb_miss_preserve_29 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_29),
  .addr_valid(addrvalid_29),
  .stored_rob_flag(uop_29_robIdx_flag),
  .stored_rob_value(uop_29_robIdx_value),
  .stored_uop_idx(uop_29_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd30)
) memblock_store_tlb_miss_preserve_30 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_30),
  .addr_valid(addrvalid_30),
  .stored_rob_flag(uop_30_robIdx_flag),
  .stored_rob_value(uop_30_robIdx_value),
  .stored_uop_idx(uop_30_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd31)
) memblock_store_tlb_miss_preserve_31 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_31),
  .addr_valid(addrvalid_31),
  .stored_rob_flag(uop_31_robIdx_flag),
  .stored_rob_value(uop_31_robIdx_value),
  .stored_uop_idx(uop_31_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd32)
) memblock_store_tlb_miss_preserve_32 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_32),
  .addr_valid(addrvalid_32),
  .stored_rob_flag(uop_32_robIdx_flag),
  .stored_rob_value(uop_32_robIdx_value),
  .stored_uop_idx(uop_32_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd33)
) memblock_store_tlb_miss_preserve_33 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_33),
  .addr_valid(addrvalid_33),
  .stored_rob_flag(uop_33_robIdx_flag),
  .stored_rob_value(uop_33_robIdx_value),
  .stored_uop_idx(uop_33_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd34)
) memblock_store_tlb_miss_preserve_34 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_34),
  .addr_valid(addrvalid_34),
  .stored_rob_flag(uop_34_robIdx_flag),
  .stored_rob_value(uop_34_robIdx_value),
  .stored_uop_idx(uop_34_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd35)
) memblock_store_tlb_miss_preserve_35 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_35),
  .addr_valid(addrvalid_35),
  .stored_rob_flag(uop_35_robIdx_flag),
  .stored_rob_value(uop_35_robIdx_value),
  .stored_uop_idx(uop_35_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd36)
) memblock_store_tlb_miss_preserve_36 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_36),
  .addr_valid(addrvalid_36),
  .stored_rob_flag(uop_36_robIdx_flag),
  .stored_rob_value(uop_36_robIdx_value),
  .stored_uop_idx(uop_36_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd37)
) memblock_store_tlb_miss_preserve_37 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_37),
  .addr_valid(addrvalid_37),
  .stored_rob_flag(uop_37_robIdx_flag),
  .stored_rob_value(uop_37_robIdx_value),
  .stored_uop_idx(uop_37_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd38)
) memblock_store_tlb_miss_preserve_38 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_38),
  .addr_valid(addrvalid_38),
  .stored_rob_flag(uop_38_robIdx_flag),
  .stored_rob_value(uop_38_robIdx_value),
  .stored_uop_idx(uop_38_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd39)
) memblock_store_tlb_miss_preserve_39 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_39),
  .addr_valid(addrvalid_39),
  .stored_rob_flag(uop_39_robIdx_flag),
  .stored_rob_value(uop_39_robIdx_value),
  .stored_uop_idx(uop_39_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd40)
) memblock_store_tlb_miss_preserve_40 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_40),
  .addr_valid(addrvalid_40),
  .stored_rob_flag(uop_40_robIdx_flag),
  .stored_rob_value(uop_40_robIdx_value),
  .stored_uop_idx(uop_40_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd41)
) memblock_store_tlb_miss_preserve_41 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_41),
  .addr_valid(addrvalid_41),
  .stored_rob_flag(uop_41_robIdx_flag),
  .stored_rob_value(uop_41_robIdx_value),
  .stored_uop_idx(uop_41_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd42)
) memblock_store_tlb_miss_preserve_42 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_42),
  .addr_valid(addrvalid_42),
  .stored_rob_flag(uop_42_robIdx_flag),
  .stored_rob_value(uop_42_robIdx_value),
  .stored_uop_idx(uop_42_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd43)
) memblock_store_tlb_miss_preserve_43 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_43),
  .addr_valid(addrvalid_43),
  .stored_rob_flag(uop_43_robIdx_flag),
  .stored_rob_value(uop_43_robIdx_value),
  .stored_uop_idx(uop_43_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd44)
) memblock_store_tlb_miss_preserve_44 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_44),
  .addr_valid(addrvalid_44),
  .stored_rob_flag(uop_44_robIdx_flag),
  .stored_rob_value(uop_44_robIdx_value),
  .stored_uop_idx(uop_44_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd45)
) memblock_store_tlb_miss_preserve_45 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_45),
  .addr_valid(addrvalid_45),
  .stored_rob_flag(uop_45_robIdx_flag),
  .stored_rob_value(uop_45_robIdx_value),
  .stored_uop_idx(uop_45_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd46)
) memblock_store_tlb_miss_preserve_46 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_46),
  .addr_valid(addrvalid_46),
  .stored_rob_flag(uop_46_robIdx_flag),
  .stored_rob_value(uop_46_robIdx_value),
  .stored_uop_idx(uop_46_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd47)
) memblock_store_tlb_miss_preserve_47 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_47),
  .addr_valid(addrvalid_47),
  .stored_rob_flag(uop_47_robIdx_flag),
  .stored_rob_value(uop_47_robIdx_value),
  .stored_uop_idx(uop_47_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd48)
) memblock_store_tlb_miss_preserve_48 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_48),
  .addr_valid(addrvalid_48),
  .stored_rob_flag(uop_48_robIdx_flag),
  .stored_rob_value(uop_48_robIdx_value),
  .stored_uop_idx(uop_48_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd49)
) memblock_store_tlb_miss_preserve_49 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_49),
  .addr_valid(addrvalid_49),
  .stored_rob_flag(uop_49_robIdx_flag),
  .stored_rob_value(uop_49_robIdx_value),
  .stored_uop_idx(uop_49_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd50)
) memblock_store_tlb_miss_preserve_50 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_50),
  .addr_valid(addrvalid_50),
  .stored_rob_flag(uop_50_robIdx_flag),
  .stored_rob_value(uop_50_robIdx_value),
  .stored_uop_idx(uop_50_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd51)
) memblock_store_tlb_miss_preserve_51 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_51),
  .addr_valid(addrvalid_51),
  .stored_rob_flag(uop_51_robIdx_flag),
  .stored_rob_value(uop_51_robIdx_value),
  .stored_uop_idx(uop_51_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd52)
) memblock_store_tlb_miss_preserve_52 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_52),
  .addr_valid(addrvalid_52),
  .stored_rob_flag(uop_52_robIdx_flag),
  .stored_rob_value(uop_52_robIdx_value),
  .stored_uop_idx(uop_52_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd53)
) memblock_store_tlb_miss_preserve_53 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_53),
  .addr_valid(addrvalid_53),
  .stored_rob_flag(uop_53_robIdx_flag),
  .stored_rob_value(uop_53_robIdx_value),
  .stored_uop_idx(uop_53_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd54)
) memblock_store_tlb_miss_preserve_54 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_54),
  .addr_valid(addrvalid_54),
  .stored_rob_flag(uop_54_robIdx_flag),
  .stored_rob_value(uop_54_robIdx_value),
  .stored_uop_idx(uop_54_uopIdx)
);

bind StoreQueue memblock_store_tlb_miss_preserve_assertion #(
  .SQ_INDEX(6'd55)
) memblock_store_tlb_miss_preserve_55 (
  .clock(clock),
  .reset(reset),
  .lane0_valid(io_storeAddrIn_0_valid),
  .lane0_update(io_storeAddrIn_0_bits_updateAddrValid),
  .lane0_miss(io_storeAddrIn_0_bits_miss),
  .lane0_sq_idx(io_storeAddrIn_0_bits_uop_sqIdx_value),
  .lane1_valid(io_storeAddrIn_1_valid),
  .lane1_update(io_storeAddrIn_1_bits_updateAddrValid),
  .lane1_miss(io_storeAddrIn_1_bits_miss),
  .lane1_sq_idx(io_storeAddrIn_1_bits_uop_sqIdx_value),
  .allocated(allocated_55),
  .addr_valid(addrvalid_55),
  .stored_rob_flag(uop_55_robIdx_flag),
  .stored_rob_value(uop_55_robIdx_value),
  .stored_uop_idx(uop_55_uopIdx)
);

`endif
