`ifndef MEMBLOCK_RTL_FCOV_BIND__SV
`define MEMBLOCK_RTL_FCOV_BIND__SV

`ifdef MEMBLOCK_UT_FCOV
bind MemBlock memblock_rtl_fcov u_memblock_rtl_fcov (
    .clock              (clock),
    .reset              (reset),
    .reset_backend_done (memblock_sync_pkg::reset_backend_done),

    .io_ooo_to_mem_issueVldu_0_valid                       (io_ooo_to_mem_issueVldu_0_valid),
    .io_ooo_to_mem_issueVldu_0_ready                       (io_ooo_to_mem_issueVldu_0_ready),
    .io_ooo_to_mem_issueVldu_0_bits_uop_fuType             (io_ooo_to_mem_issueVldu_0_bits_uop_fuType),
    .io_ooo_to_mem_issueVldu_0_bits_uop_fuOpType           (io_ooo_to_mem_issueVldu_0_bits_uop_fuOpType),
    .io_ooo_to_mem_issueVldu_0_bits_uop_vpu_vma            (io_ooo_to_mem_issueVldu_0_bits_uop_vpu_vma),
    .io_ooo_to_mem_issueVldu_0_bits_uop_vpu_vta            (io_ooo_to_mem_issueVldu_0_bits_uop_vpu_vta),
    .io_ooo_to_mem_issueVldu_0_bits_uop_vpu_vsew           (io_ooo_to_mem_issueVldu_0_bits_uop_vpu_vsew),
    .io_ooo_to_mem_issueVldu_0_bits_uop_vpu_vlmul          (io_ooo_to_mem_issueVldu_0_bits_uop_vpu_vlmul),
    .io_ooo_to_mem_issueVldu_0_bits_uop_vpu_vm             (io_ooo_to_mem_issueVldu_0_bits_uop_vpu_vm),
    .io_ooo_to_mem_issueVldu_0_bits_uop_vpu_vstart         (io_ooo_to_mem_issueVldu_0_bits_uop_vpu_vstart),
    .io_ooo_to_mem_issueVldu_0_bits_uop_vpu_vuopIdx        (io_ooo_to_mem_issueVldu_0_bits_uop_vpu_vuopIdx),
    .io_ooo_to_mem_issueVldu_0_bits_uop_vpu_lastUop        (io_ooo_to_mem_issueVldu_0_bits_uop_vpu_lastUop),
    .io_ooo_to_mem_issueVldu_0_bits_uop_vpu_vmask          (io_ooo_to_mem_issueVldu_0_bits_uop_vpu_vmask),
    .io_ooo_to_mem_issueVldu_0_bits_uop_vpu_nf             (io_ooo_to_mem_issueVldu_0_bits_uop_vpu_nf),
    .io_ooo_to_mem_issueVldu_0_bits_uop_vpu_veew           (io_ooo_to_mem_issueVldu_0_bits_uop_vpu_veew),
    .io_ooo_to_mem_issueVldu_0_bits_uop_vpu_isVleff        (io_ooo_to_mem_issueVldu_0_bits_uop_vpu_isVleff),
    .io_ooo_to_mem_issueVldu_0_bits_uop_robIdx_value       (io_ooo_to_mem_issueVldu_0_bits_uop_robIdx_value),
    .io_ooo_to_mem_issueVldu_0_bits_src_0                  (io_ooo_to_mem_issueVldu_0_bits_src_0),
    .io_ooo_to_mem_issueVldu_0_bits_src_2                  (io_ooo_to_mem_issueVldu_0_bits_src_2),
    .io_ooo_to_mem_issueVldu_0_bits_src_3                  (io_ooo_to_mem_issueVldu_0_bits_src_3),
    .io_ooo_to_mem_issueVldu_0_bits_src_4                  (io_ooo_to_mem_issueVldu_0_bits_src_4),
    .io_ooo_to_mem_issueVldu_0_bits_flowNum                (io_ooo_to_mem_issueVldu_0_bits_flowNum),
    .io_ooo_to_mem_issueVldu_0_bits_isVecPartReplay        (io_ooo_to_mem_issueVldu_0_bits_isVecPartReplay),

    .io_ooo_to_mem_issueVldu_1_valid                       (io_ooo_to_mem_issueVldu_1_valid),
    .io_ooo_to_mem_issueVldu_1_ready                       (io_ooo_to_mem_issueVldu_1_ready),
    .io_ooo_to_mem_issueVldu_1_bits_uop_fuOpType           (io_ooo_to_mem_issueVldu_1_bits_uop_fuOpType),
    .io_ooo_to_mem_issueVldu_1_bits_uop_vpu_vma            (io_ooo_to_mem_issueVldu_1_bits_uop_vpu_vma),
    .io_ooo_to_mem_issueVldu_1_bits_uop_vpu_vta            (io_ooo_to_mem_issueVldu_1_bits_uop_vpu_vta),
    .io_ooo_to_mem_issueVldu_1_bits_uop_vpu_vsew           (io_ooo_to_mem_issueVldu_1_bits_uop_vpu_vsew),
    .io_ooo_to_mem_issueVldu_1_bits_uop_vpu_vlmul          (io_ooo_to_mem_issueVldu_1_bits_uop_vpu_vlmul),
    .io_ooo_to_mem_issueVldu_1_bits_uop_vpu_vm             (io_ooo_to_mem_issueVldu_1_bits_uop_vpu_vm),
    .io_ooo_to_mem_issueVldu_1_bits_uop_vpu_vstart         (io_ooo_to_mem_issueVldu_1_bits_uop_vpu_vstart),
    .io_ooo_to_mem_issueVldu_1_bits_uop_vpu_vuopIdx        (io_ooo_to_mem_issueVldu_1_bits_uop_vpu_vuopIdx),
    .io_ooo_to_mem_issueVldu_1_bits_uop_vpu_lastUop        (io_ooo_to_mem_issueVldu_1_bits_uop_vpu_lastUop),
    .io_ooo_to_mem_issueVldu_1_bits_uop_vpu_vmask          (io_ooo_to_mem_issueVldu_1_bits_uop_vpu_vmask),
    .io_ooo_to_mem_issueVldu_1_bits_uop_vpu_nf             (io_ooo_to_mem_issueVldu_1_bits_uop_vpu_nf),
    .io_ooo_to_mem_issueVldu_1_bits_uop_vpu_veew           (io_ooo_to_mem_issueVldu_1_bits_uop_vpu_veew),
    .io_ooo_to_mem_issueVldu_1_bits_uop_vpu_isVleff        (io_ooo_to_mem_issueVldu_1_bits_uop_vpu_isVleff),
    .io_ooo_to_mem_issueVldu_1_bits_uop_robIdx_value       (io_ooo_to_mem_issueVldu_1_bits_uop_robIdx_value),
    .io_ooo_to_mem_issueVldu_1_bits_src_0                  (io_ooo_to_mem_issueVldu_1_bits_src_0),
    .io_ooo_to_mem_issueVldu_1_bits_src_2                  (io_ooo_to_mem_issueVldu_1_bits_src_2),
    .io_ooo_to_mem_issueVldu_1_bits_src_3                  (io_ooo_to_mem_issueVldu_1_bits_src_3),
    .io_ooo_to_mem_issueVldu_1_bits_src_4                  (io_ooo_to_mem_issueVldu_1_bits_src_4),
    .io_ooo_to_mem_issueVldu_1_bits_flowNum                (io_ooo_to_mem_issueVldu_1_bits_flowNum),
    .io_ooo_to_mem_issueVldu_1_bits_isVecPartReplay        (io_ooo_to_mem_issueVldu_1_bits_isVecPartReplay),

    .io_mem_to_ooo_writebackVldu_0_valid                   (io_mem_to_ooo_writebackVldu_0_valid),
    .io_mem_to_ooo_writebackVldu_0_exceptionVec            ({io_mem_to_ooo_writebackVldu_0_bits_uop_exceptionVec_23,
                                                                io_mem_to_ooo_writebackVldu_0_bits_uop_exceptionVec_21,
                                                                io_mem_to_ooo_writebackVldu_0_bits_uop_exceptionVec_19,
                                                                io_mem_to_ooo_writebackVldu_0_bits_uop_exceptionVec_15,
                                                                io_mem_to_ooo_writebackVldu_0_bits_uop_exceptionVec_13,
                                                                io_mem_to_ooo_writebackVldu_0_bits_uop_exceptionVec_7,
                                                                io_mem_to_ooo_writebackVldu_0_bits_uop_exceptionVec_6,
                                                                io_mem_to_ooo_writebackVldu_0_bits_uop_exceptionVec_5,
                                                                io_mem_to_ooo_writebackVldu_0_bits_uop_exceptionVec_4,
                                                                io_mem_to_ooo_writebackVldu_0_bits_uop_exceptionVec_3}),
    .io_mem_to_ooo_writebackVldu_0_bits_uop_fuOpType        (io_mem_to_ooo_writebackVldu_0_bits_uop_fuOpType),
    .io_mem_to_ooo_writebackVldu_0_bits_uop_vpu_vma         (io_mem_to_ooo_writebackVldu_0_bits_uop_vpu_vma),
    .io_mem_to_ooo_writebackVldu_0_bits_uop_vpu_vta         (io_mem_to_ooo_writebackVldu_0_bits_uop_vpu_vta),
    .io_mem_to_ooo_writebackVldu_0_bits_uop_vpu_vsew        (io_mem_to_ooo_writebackVldu_0_bits_uop_vpu_vsew),
    .io_mem_to_ooo_writebackVldu_0_bits_uop_vpu_vlmul       (io_mem_to_ooo_writebackVldu_0_bits_uop_vpu_vlmul),
    .io_mem_to_ooo_writebackVldu_0_bits_uop_vpu_vm          (io_mem_to_ooo_writebackVldu_0_bits_uop_vpu_vm),
    .io_mem_to_ooo_writebackVldu_0_bits_uop_vpu_vstart      (io_mem_to_ooo_writebackVldu_0_bits_uop_vpu_vstart),
    .io_mem_to_ooo_writebackVldu_0_bits_uop_vpu_vuopIdx     (io_mem_to_ooo_writebackVldu_0_bits_uop_vpu_vuopIdx),
    .io_mem_to_ooo_writebackVldu_0_bits_uop_vpu_vmask       (io_mem_to_ooo_writebackVldu_0_bits_uop_vpu_vmask),
    .io_mem_to_ooo_writebackVldu_0_bits_uop_vpu_vl          (io_mem_to_ooo_writebackVldu_0_bits_uop_vpu_vl),
    .io_mem_to_ooo_writebackVldu_0_bits_uop_vpu_nf          (io_mem_to_ooo_writebackVldu_0_bits_uop_vpu_nf),
    .io_mem_to_ooo_writebackVldu_0_bits_uop_vpu_veew        (io_mem_to_ooo_writebackVldu_0_bits_uop_vpu_veew),
    .io_mem_to_ooo_writebackVldu_0_bits_uop_pdest           (io_mem_to_ooo_writebackVldu_0_bits_uop_pdest),
    .io_mem_to_ooo_writebackVldu_0_bits_uop_robIdx_flag     (io_mem_to_ooo_writebackVldu_0_bits_uop_robIdx_flag),
    .io_mem_to_ooo_writebackVldu_0_bits_uop_robIdx_value    (io_mem_to_ooo_writebackVldu_0_bits_uop_robIdx_value),
    .io_mem_to_ooo_writebackVldu_0_bits_uop_replayInst      (io_mem_to_ooo_writebackVldu_0_bits_uop_replayInst),
    .io_mem_to_ooo_writebackVldu_0_bits_data                (io_mem_to_ooo_writebackVldu_0_bits_data),
    .io_mem_to_ooo_writebackVldu_0_bits_vdIdxInField        (io_mem_to_ooo_writebackVldu_0_bits_vdIdxInField),

    .io_mem_to_ooo_writebackVldu_1_valid                   (io_mem_to_ooo_writebackVldu_1_valid),
    .io_mem_to_ooo_writebackVldu_1_exceptionVec            ({io_mem_to_ooo_writebackVldu_1_bits_uop_exceptionVec_23,
                                                                io_mem_to_ooo_writebackVldu_1_bits_uop_exceptionVec_21,
                                                                io_mem_to_ooo_writebackVldu_1_bits_uop_exceptionVec_19,
                                                                io_mem_to_ooo_writebackVldu_1_bits_uop_exceptionVec_15,
                                                                io_mem_to_ooo_writebackVldu_1_bits_uop_exceptionVec_13,
                                                                io_mem_to_ooo_writebackVldu_1_bits_uop_exceptionVec_7,
                                                                io_mem_to_ooo_writebackVldu_1_bits_uop_exceptionVec_6,
                                                                io_mem_to_ooo_writebackVldu_1_bits_uop_exceptionVec_5,
                                                                io_mem_to_ooo_writebackVldu_1_bits_uop_exceptionVec_4,
                                                                io_mem_to_ooo_writebackVldu_1_bits_uop_exceptionVec_3}),
    .io_mem_to_ooo_writebackVldu_1_bits_uop_fuOpType        (io_mem_to_ooo_writebackVldu_1_bits_uop_fuOpType),
    .io_mem_to_ooo_writebackVldu_1_bits_uop_vpu_vma         (io_mem_to_ooo_writebackVldu_1_bits_uop_vpu_vma),
    .io_mem_to_ooo_writebackVldu_1_bits_uop_vpu_vta         (io_mem_to_ooo_writebackVldu_1_bits_uop_vpu_vta),
    .io_mem_to_ooo_writebackVldu_1_bits_uop_vpu_vsew        (io_mem_to_ooo_writebackVldu_1_bits_uop_vpu_vsew),
    .io_mem_to_ooo_writebackVldu_1_bits_uop_vpu_vlmul       (io_mem_to_ooo_writebackVldu_1_bits_uop_vpu_vlmul),
    .io_mem_to_ooo_writebackVldu_1_bits_uop_vpu_vm          (io_mem_to_ooo_writebackVldu_1_bits_uop_vpu_vm),
    .io_mem_to_ooo_writebackVldu_1_bits_uop_vpu_vstart      (io_mem_to_ooo_writebackVldu_1_bits_uop_vpu_vstart),
    .io_mem_to_ooo_writebackVldu_1_bits_uop_vpu_vuopIdx     (io_mem_to_ooo_writebackVldu_1_bits_uop_vpu_vuopIdx),
    .io_mem_to_ooo_writebackVldu_1_bits_uop_vpu_vmask       (io_mem_to_ooo_writebackVldu_1_bits_uop_vpu_vmask),
    .io_mem_to_ooo_writebackVldu_1_bits_uop_vpu_vl          (io_mem_to_ooo_writebackVldu_1_bits_uop_vpu_vl),
    .io_mem_to_ooo_writebackVldu_1_bits_uop_vpu_nf          (io_mem_to_ooo_writebackVldu_1_bits_uop_vpu_nf),
    .io_mem_to_ooo_writebackVldu_1_bits_uop_vpu_veew        (io_mem_to_ooo_writebackVldu_1_bits_uop_vpu_veew),
    .io_mem_to_ooo_writebackVldu_1_bits_uop_pdest           (io_mem_to_ooo_writebackVldu_1_bits_uop_pdest),
    .io_mem_to_ooo_writebackVldu_1_bits_uop_robIdx_flag     (io_mem_to_ooo_writebackVldu_1_bits_uop_robIdx_flag),
    .io_mem_to_ooo_writebackVldu_1_bits_uop_robIdx_value    (io_mem_to_ooo_writebackVldu_1_bits_uop_robIdx_value),
    .io_mem_to_ooo_writebackVldu_1_bits_uop_replayInst      (io_mem_to_ooo_writebackVldu_1_bits_uop_replayInst),
    .io_mem_to_ooo_writebackVldu_1_bits_data                (io_mem_to_ooo_writebackVldu_1_bits_data),
    .io_mem_to_ooo_writebackVldu_1_bits_vdIdxInField        (io_mem_to_ooo_writebackVldu_1_bits_vdIdxInField),

    .io_mem_to_ooo_vstuIqFeedback_0_feedbackSlow_valid                 (io_mem_to_ooo_vstuIqFeedback_0_feedbackSlow_valid),
    .io_mem_to_ooo_vstuIqFeedback_0_feedbackSlow_bits_hit              (io_mem_to_ooo_vstuIqFeedback_0_feedbackSlow_bits_hit),
    .io_mem_to_ooo_vstuIqFeedback_0_feedbackSlow_bits_isVecPartReplay  (io_mem_to_ooo_vstuIqFeedback_0_feedbackSlow_bits_isVecPartReplay),
    .io_mem_to_ooo_vstuIqFeedback_0_feedbackSlow_bits_vecReplayMask    (io_mem_to_ooo_vstuIqFeedback_0_feedbackSlow_bits_vecReplayMask),
    .io_mem_to_ooo_vstuIqFeedback_0_feedbackSlow_bits_vecReplayMbIdx   (io_mem_to_ooo_vstuIqFeedback_0_feedbackSlow_bits_vecReplayMbIdx),
    .io_mem_to_ooo_vstuIqFeedback_1_feedbackSlow_valid                 (io_mem_to_ooo_vstuIqFeedback_1_feedbackSlow_valid),
    .io_mem_to_ooo_vstuIqFeedback_1_feedbackSlow_bits_hit              (io_mem_to_ooo_vstuIqFeedback_1_feedbackSlow_bits_hit),
    .io_mem_to_ooo_vstuIqFeedback_1_feedbackSlow_bits_isVecPartReplay  (io_mem_to_ooo_vstuIqFeedback_1_feedbackSlow_bits_isVecPartReplay),
    .io_mem_to_ooo_vstuIqFeedback_1_feedbackSlow_bits_vecReplayMask    (io_mem_to_ooo_vstuIqFeedback_1_feedbackSlow_bits_vecReplayMask),
    .io_mem_to_ooo_vstuIqFeedback_1_feedbackSlow_bits_vecReplayMbIdx   (io_mem_to_ooo_vstuIqFeedback_1_feedbackSlow_bits_vecReplayMbIdx),

    .io_redirect_valid                  (io_redirect_valid),
    .io_redirect_bits_level             (io_redirect_bits_level),
    .io_redirect_bits_isVlsException    (io_redirect_bits_isVlsException),
    .io_redirect_bits_robIdx_value      (io_redirect_bits_robIdx_value)
);
`endif
`endif
