//=========================================================
// File name    : memblock_ldu_scalar_fcov_bind.sv
// Description  : bind scalar coverage shells to every V2 LoadUnit instance
//=========================================================
`ifndef MEMBLOCK_LDU_SCALAR_FCOV_BIND__SV
`define MEMBLOCK_LDU_SCALAR_FCOV_BIND__SV

`ifdef MEMBLOCK_UT_FCOV
bind LoadUnit memblock_ldu_scalar_fcov u_memblock_ldu_scalar_fcov (
    .clock(clock), .reset(reset), .reset_backend_done(memblock_sync_pkg::reset_backend_done),
    .io_ldin_valid(io_ldin_valid), .io_ldin_ready(io_ldin_ready),
    .io_ldin_fuOpType(io_ldin_bits_uop_fuOpType), .io_ldin_rfWen(io_ldin_bits_uop_rfWen),
    .io_ldin_fpWen(io_ldin_bits_uop_fpWen), .io_ldin_imm(io_ldin_bits_uop_imm),
    .io_ldin_pdest(io_ldin_bits_uop_pdest), .io_ldin_robIdx_flag(io_ldin_bits_uop_robIdx_flag),
    .io_ldin_robIdx_value(io_ldin_bits_uop_robIdx_value), .io_ldin_lqIdx_flag(io_ldin_bits_uop_lqIdx_flag),
    .io_ldin_lqIdx_value(io_ldin_bits_uop_lqIdx_value), .io_ldin_src0(io_ldin_bits_src_0),
    .io_misalign_ldin_valid(io_misalign_ldin_valid),
    .io_fast_rep_in_valid(io_fast_rep_in_valid), .io_vecldin_valid(io_vecldin_valid),
    .io_lsq_uncache_valid(io_lsq_uncache_valid), .io_lsq_nc_ldin_valid(io_lsq_nc_ldin_valid),
    .s0_src_selector_1(s0_src_selector_1), .s0_src_selector_3(s0_src_selector_3),
    .s0_src_selector_4(s0_src_selector_4), .s0_src_select_vec_2(s0_src_select_vec_2),
    .s0_src_select_vec_5(s0_src_select_vec_5), .s0_src_select_vec_6(s0_src_select_vec_6),
    .s0_src_select_vec_7(s0_src_select_vec_7), .s0_src_select_vec_8(s0_src_select_vec_8),
    .s0_src_valid_vec_10(s0_src_valid_vec_10), .s0_rep_stall(s0_rep_stall),
    .s0_fire(s0_fire), .s0_sel_src_fuOpType(s0_sel_src_uop_fuOpType),
    .s0_out_tlbNoQuery(s0_out_tlbNoQuery),
    .s0_addr_aligned(s0_addr_aligned), .s0_rs_cross16Bytes(s0_rs_cross16Bytes),
    .s0_misalignWith16Byte(s0_misalignWith16Byte), .s0_is128bit(s0_is128bit),
    .s0_out_isHWPrefetch(s0_out_isHWPrefetch), .s0_sel_src_isnc(s0_sel_src_isnc),
    .s0_sel_src_frm_mabuf(s0_sel_src_frm_mabuf), .s0_mmio_fire(s0_mmio_fire), .s0_nc_fire(s0_nc_fire),
    .s1_valid(s1_valid), .s1_in_r_isvec(s1_in_r_isvec),
    .s1_kill(s1_kill), .s1_misalign_kill(s1_misalign_kill), .s1_tlb_miss(s1_tlb_miss),
    .s1_trigger_debug_mode(s1_trigger_debug_mode), .s1_trigger_breakpoint(s1_trigger_breakpoint),
    .io_redirect_valid(io_redirect_valid),
    .io_tlb_req_valid(io_tlb_req_valid), .io_tlb_req_cmd(io_tlb_req_bits_cmd),
    .io_tlb_req_vaddr(io_tlb_req_bits_vaddr),
    .io_tlb_req_bits_checkfullva(io_tlb_req_bits_checkfullva), .io_tlb_req_bits_hyperinst(io_tlb_req_bits_hyperinst),
    .io_tlb_req_bits_hlvx(io_tlb_req_bits_hlvx), .io_tlb_req_bits_kill(io_tlb_req_bits_kill),
    .io_tlb_req_bits_isPrefetch(io_tlb_req_bits_isPrefetch), .io_tlb_req_bits_no_translate(io_tlb_req_bits_no_translate),
    .io_tlb_resp_valid(io_tlb_resp_valid), .io_tlb_resp_bits_miss(io_tlb_resp_bits_miss),
    .io_tlb_resp_bits_pbmt(io_tlb_resp_bits_pbmt_0), .io_tlb_resp_bits_excp_gpf(io_tlb_resp_bits_excp_0_gpf_ld),
    .io_tlb_resp_bits_excp_pf(io_tlb_resp_bits_excp_0_pf_ld), .io_tlb_resp_bits_excp_af(io_tlb_resp_bits_excp_0_af_ld),
    .io_pmp_ld(io_pmp_ld), .io_pmp_st(io_pmp_st), .io_pmp_instr(io_pmp_instr), .io_pmp_mmio(io_pmp_mmio),
    .io_dcache_req_valid(io_dcache_req_valid), .io_dcache_req_ready(io_dcache_req_ready),
    .io_dcache_req_cmd(io_dcache_req_bits_cmd), .io_dcache_req_instrtype(io_dcache_req_bits_instrtype),
    .io_dcache_req_vaddr(io_dcache_req_bits_vaddr),
    .io_dcache_req_lqIdx_flag(io_dcache_req_bits_lqIdx_flag), .io_dcache_req_lqIdx_value(io_dcache_req_bits_lqIdx_value),
    .io_dcache_is128Req(io_dcache_is128Req), .io_dcache_resp_bits_miss(io_dcache_resp_bits_miss),
    .io_dcache_resp_bits_mshr_id(io_dcache_resp_bits_mshr_id), .io_dcache_resp_bits_meta_prefetch(io_dcache_resp_bits_meta_prefetch),
    .io_dcache_resp_bits_handled(io_dcache_resp_bits_handled),
    .io_dcache_resp_bits_denied(io_dcache_resp_bits_tl_error_delayed_tl_denied),
    .io_dcache_resp_bits_corrupt(io_dcache_resp_bits_tl_error_delayed_tl_corrupt),
    .io_dcache_s2_bank_conflict(io_dcache_s2_bank_conflict), .io_dcache_s2_mq_nack(io_dcache_s2_mq_nack),
    .io_dcache_s1_kill(io_dcache_s1_kill), .io_dcache_s1_kill_data_read(io_dcache_s1_kill_data_read),
    .io_sbuffer_valid(io_sbuffer_valid),
    .io_sbuffer_forwardMask({io_sbuffer_forwardMask_15, io_sbuffer_forwardMask_14, io_sbuffer_forwardMask_13, io_sbuffer_forwardMask_12, io_sbuffer_forwardMask_11, io_sbuffer_forwardMask_10, io_sbuffer_forwardMask_9, io_sbuffer_forwardMask_8, io_sbuffer_forwardMask_7, io_sbuffer_forwardMask_6, io_sbuffer_forwardMask_5, io_sbuffer_forwardMask_4, io_sbuffer_forwardMask_3, io_sbuffer_forwardMask_2, io_sbuffer_forwardMask_1, io_sbuffer_forwardMask_0}),
    .io_sbuffer_matchInvalid(io_sbuffer_matchInvalid), .io_ubuffer_valid(io_ubuffer_valid),
    .io_ubuffer_forwardMask({io_ubuffer_forwardMask_15, io_ubuffer_forwardMask_14, io_ubuffer_forwardMask_13, io_ubuffer_forwardMask_12, io_ubuffer_forwardMask_11, io_ubuffer_forwardMask_10, io_ubuffer_forwardMask_9, io_ubuffer_forwardMask_8, io_ubuffer_forwardMask_7, io_ubuffer_forwardMask_6, io_ubuffer_forwardMask_5, io_ubuffer_forwardMask_4, io_ubuffer_forwardMask_3, io_ubuffer_forwardMask_2, io_ubuffer_forwardMask_1, io_ubuffer_forwardMask_0}),
    .io_ubuffer_matchInvalid(io_ubuffer_matchInvalid), .io_lsq_forward_valid(io_lsq_forward_valid),
    .io_lsq_forward_forwardMask({io_lsq_forward_forwardMask_15, io_lsq_forward_forwardMask_14, io_lsq_forward_forwardMask_13, io_lsq_forward_forwardMask_12, io_lsq_forward_forwardMask_11, io_lsq_forward_forwardMask_10, io_lsq_forward_forwardMask_9, io_lsq_forward_forwardMask_8, io_lsq_forward_forwardMask_7, io_lsq_forward_forwardMask_6, io_lsq_forward_forwardMask_5, io_lsq_forward_forwardMask_4, io_lsq_forward_forwardMask_3, io_lsq_forward_forwardMask_2, io_lsq_forward_forwardMask_1, io_lsq_forward_forwardMask_0}),
    .io_lsq_forward_dataInvalid(io_lsq_forward_dataInvalid), .io_lsq_forward_matchInvalid(io_lsq_forward_matchInvalid),
    .io_lsq_forward_addrInvalid(io_lsq_forward_addrInvalid),
    .s2_fwd_mask({s2_fwd_mask_15, s2_fwd_mask_14, s2_fwd_mask_13, s2_fwd_mask_12, s2_fwd_mask_11, s2_fwd_mask_10, s2_fwd_mask_9, s2_fwd_mask_8, s2_fwd_mask_7, s2_fwd_mask_6, s2_fwd_mask_5, s2_fwd_mask_4, s2_fwd_mask_3, s2_fwd_mask_2, s2_fwd_mask_1, s2_fwd_mask_0}),
    .s2_full_fwd(s2_full_fwd), .s2_mem_amb(s2_mem_amb), .s2_fwd_fail(s2_fwd_fail),
    .s2_safe_wakeup(s2_safe_wakeup), .s2_real_exception(s2_real_exception), .s2_valid(s2_valid), .s2_isvec(s2_isvec),
    .s2_in_r_fuOpType(s2_in_r_uop_fuOpType), .s2_in_r_is128bit(s2_in_r_is128bit),
    .s2_in_r_nc(s2_in_r_nc), .s2_in_r_mmio(s2_in_r_mmio), .s2_in_r_isPrefetch(s2_in_r_isPrefetch),
    .s2_in_r_isLoadReplay(s2_in_r_isLoadReplay), .s2_in_r_isFastReplay(s2_in_r_isFastReplay),
    .s2_in_r_isFrmMisAlignBuf(s2_in_r_isFrmMisAlignBuf),
    .s2_in_r_rep_info_cause_9(s2_in_r_rep_info_cause_9), .s2_nuke(s2_nuke),
    .io_stld_nuke_query_0_valid(io_stld_nuke_query_0_valid),
    .io_stld_nuke_query_0_matchType(io_stld_nuke_query_0_bits_matchType),
    .io_stld_nuke_query_1_valid(io_stld_nuke_query_1_valid),
    .io_stld_nuke_query_1_matchType(io_stld_nuke_query_1_bits_matchType),
    .io_lsq_stld_nuke_query_req_valid(io_lsq_stld_nuke_query_req_valid), .io_lsq_stld_nuke_query_req_ready(io_lsq_stld_nuke_query_req_ready),
    .io_lsq_stld_nuke_query_req_bits_data_valid(io_lsq_stld_nuke_query_req_bits_data_valid), .io_lsq_stld_nuke_query_revoke(io_lsq_stld_nuke_query_revoke),
    .io_lsq_ldld_nuke_query_req_valid(io_lsq_ldld_nuke_query_req_valid), .io_lsq_ldld_nuke_query_req_ready(io_lsq_ldld_nuke_query_req_ready),
    .io_lsq_ldld_nuke_query_req_bits_data_valid(io_lsq_ldld_nuke_query_req_bits_data_valid), .io_lsq_ldld_nuke_query_req_bits_is_nc(io_lsq_ldld_nuke_query_req_bits_is_nc),
    .io_lsq_ldld_nuke_query_revoke(io_lsq_ldld_nuke_query_revoke),
    .io_lsq_ldin_rep_cause({io_lsq_ldin_bits_rep_info_cause_10, io_lsq_ldin_bits_rep_info_cause_9, io_lsq_ldin_bits_rep_info_cause_8, io_lsq_ldin_bits_rep_info_cause_7, io_lsq_ldin_bits_rep_info_cause_6, io_lsq_ldin_bits_rep_info_cause_5, io_lsq_ldin_bits_rep_info_cause_4, io_lsq_ldin_bits_rep_info_cause_3, io_lsq_ldin_bits_rep_info_cause_2, io_lsq_ldin_bits_rep_info_cause_1, io_lsq_ldin_bits_rep_info_cause_0}),
    .io_lsq_ldin_valid(io_lsq_ldin_valid), .io_fast_rep_out_valid(io_fast_rep_out_valid),
    .io_misalign_enq_req_valid(io_misalign_enq_req_valid), .io_misalign_enq_req_ready(io_misalign_enq_req_ready),
    .io_misalign_ldout_valid(io_misalign_ldout_valid), .s3_in_isFrmMisAlignBuf(s3_in_isFrmMisAlignBuf),
    .s3_misalign_can_go(s3_misalign_can_go), .s3_misalign_wakeup_req_valid(s3_misalign_wakeup_req_valid_REG_2),
    .io_rollback_valid(io_rollback_valid), .io_rollback_level(io_rollback_bits_level),
    .io_wakeup_valid(io_wakeup_valid), .io_wakeup_rfWen(io_wakeup_bits_rfWen),
    .io_wakeup_fpWen(io_wakeup_bits_fpWen), .io_ldCancel_ld2Cancel(io_ldCancel_ld2Cancel),
    .s3_valid_last_REG(s3_valid_last_REG), .s3_isvec(s3_isvec), .s3_exception(s3_exception),
    .s3_safe_writeback(s3_safe_writeback),
    .io_csrCtrl_ldld_vio_check_enable(io_csrCtrl_ldld_vio_check_enable),
    .io_csrCtrl_hd_misalign_ld_enable(io_csrCtrl_hd_misalign_ld_enable),
    .io_ldout_valid(io_ldout_valid), .io_ldout_ready(io_ldout_ready),
    .io_ldout_exceptionVec({io_ldout_bits_uop_exceptionVec_21, io_ldout_bits_uop_exceptionVec_19, io_ldout_bits_uop_exceptionVec_13, io_ldout_bits_uop_exceptionVec_5, io_ldout_bits_uop_exceptionVec_4, io_ldout_bits_uop_exceptionVec_3}),
    .io_ldout_rfWen(io_ldout_bits_uop_rfWen), .io_ldout_fpWen(io_ldout_bits_uop_fpWen), .io_ldout_pdest(io_ldout_bits_uop_pdest),
    .io_ldout_robIdx_flag(io_ldout_bits_uop_robIdx_flag), .io_ldout_robIdx_value(io_ldout_bits_uop_robIdx_value),
    .io_ldout_replayInst(io_ldout_bits_uop_replayInst), .io_ldout_debug_isMMIO(io_ldout_bits_debug_isMMIO), .io_ldout_debug_isNCIO(io_ldout_bits_debug_isNCIO)
);

bind LoadUnit memblock_ldu_scalar_sva u_memblock_ldu_scalar_sva (
    .clock              (clock),
    .reset              (reset),
    .reset_backend_done (memblock_sync_pkg::reset_backend_done)
);
`endif

`endif
