//=========================================================
//File name    : io_mem_to_ooo_vec_wb_agent_agent_interface.sv
//Author       : OpenAI_Codex
//Module name  : io_mem_to_ooo_vec_wb_agent_agent_interface
//Discribution : io_mem_to_ooo_vec_wb_agent_agent_interface : signal interface
//Date         : 2026-04-12
//=========================================================
`ifndef IO_MEM_TO_OOO_VEC_WB_AGENT_AGENT_INTERFACE__SV
`define IO_MEM_TO_OOO_VEC_WB_AGENT_AGENT_INTERFACE__SV

`ifndef DEF_SETUP_TIME
    `define DEF_SETUP_TIME 1
`endif
`ifndef DEF_HOLD_TIME
    `define DEF_HOLD_TIME 1
`endif

interface io_mem_to_ooo_vec_wb_agent_agent_interface  (input bit clk,input bit rst_n);

    logic io_mem_to_ooo_vecWriteback_1_0_ready;
    logic io_mem_to_ooo_vecWriteback_1_0_valid;
    logic [127:0] io_mem_to_ooo_vecWriteback_1_0_bits_data_0;
    logic [6:0] io_mem_to_ooo_vecWriteback_1_0_bits_pdest;
    logic [4:0] io_mem_to_ooo_vecWriteback_1_0_bits_pdestVl;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_robIdx_flag;
    logic [8:0] io_mem_to_ooo_vecWriteback_1_0_bits_robIdx_value;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vecWen;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_v0Wen;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vlWen;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_exceptionVec_3;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_exceptionVec_4;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_exceptionVec_5;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_exceptionVec_6;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_exceptionVec_7;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_exceptionVec_13;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_exceptionVec_15;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_exceptionVec_19;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_exceptionVec_21;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_exceptionVec_23;
    logic [3:0] io_mem_to_ooo_vecWriteback_1_0_bits_trigger;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vill;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vma;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vta;
    logic [1:0] io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vsew;
    logic [2:0] io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vlmul;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_specVill;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_specVma;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_specVta;
    logic [1:0] io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_specVsew;
    logic [2:0] io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_specVlmul;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vm;
    logic [7:0] io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vstart;
    logic [2:0] io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_frm;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_fpu_isFpToVecInst;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_fpu_isFP32Instr;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_fpu_isFP64Instr;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_fpu_isReduction;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_fpu_isFoldTo1_2;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_fpu_isFoldTo1_4;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_fpu_isFoldTo1_8;
    logic [1:0] io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vxrm;
    logic [6:0] io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vuopIdx;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_lastUop;
    logic [127:0] io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vmask;
    logic [7:0] io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vl;
    logic [2:0] io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_nf;
    logic [1:0] io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_veew;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_isReverse;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_isExt;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_isNarrow;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_isDstMask;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_isOpMask;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_isMove;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_isDependOldVd;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_isWritePartVd;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_isVleff;
    logic [15:0] io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_maskVecGen;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_sew8;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_sew16;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_sew32;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_sew64;
    logic [7:0] io_mem_to_ooo_vecWriteback_1_0_bits_vls_oldVdPsrc;
    logic [2:0] io_mem_to_ooo_vecWriteback_1_0_bits_vls_vdIdx;
    logic [2:0] io_mem_to_ooo_vecWriteback_1_0_bits_vls_vdIdxInField;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_isIndexed;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_isMasked;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_isStrided;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_isWhole;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_isVecLoad;
    logic io_mem_to_ooo_vecWriteback_1_0_bits_vls_isVlm;
    logic io_mem_to_ooo_vecWriteback_0_0_ready;
    logic io_mem_to_ooo_vecWriteback_0_0_valid;
    logic [127:0] io_mem_to_ooo_vecWriteback_0_0_bits_data_0;
    logic [6:0] io_mem_to_ooo_vecWriteback_0_0_bits_pdest;
    logic [4:0] io_mem_to_ooo_vecWriteback_0_0_bits_pdestVl;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_robIdx_flag;
    logic [8:0] io_mem_to_ooo_vecWriteback_0_0_bits_robIdx_value;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vecWen;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_v0Wen;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vlWen;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_exceptionVec_3;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_exceptionVec_4;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_exceptionVec_5;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_exceptionVec_6;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_exceptionVec_7;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_exceptionVec_13;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_exceptionVec_15;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_exceptionVec_19;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_exceptionVec_21;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_exceptionVec_23;
    logic [3:0] io_mem_to_ooo_vecWriteback_0_0_bits_trigger;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vill;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vma;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vta;
    logic [1:0] io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vsew;
    logic [2:0] io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vlmul;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_specVill;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_specVma;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_specVta;
    logic [1:0] io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_specVsew;
    logic [2:0] io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_specVlmul;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vm;
    logic [7:0] io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vstart;
    logic [2:0] io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_frm;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_fpu_isFpToVecInst;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_fpu_isFP32Instr;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_fpu_isFP64Instr;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_fpu_isReduction;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_fpu_isFoldTo1_2;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_fpu_isFoldTo1_4;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_fpu_isFoldTo1_8;
    logic [1:0] io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vxrm;
    logic [6:0] io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vuopIdx;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_lastUop;
    logic [127:0] io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vmask;
    logic [7:0] io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vl;
    logic [2:0] io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_nf;
    logic [1:0] io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_veew;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_isReverse;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_isExt;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_isNarrow;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_isDstMask;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_isOpMask;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_isMove;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_isDependOldVd;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_isWritePartVd;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_isVleff;
    logic [15:0] io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_maskVecGen;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_sew8;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_sew16;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_sew32;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_sew64;
    logic [7:0] io_mem_to_ooo_vecWriteback_0_0_bits_vls_oldVdPsrc;
    logic [2:0] io_mem_to_ooo_vecWriteback_0_0_bits_vls_vdIdx;
    logic [2:0] io_mem_to_ooo_vecWriteback_0_0_bits_vls_vdIdxInField;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_isIndexed;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_isMasked;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_isStrided;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_isWhole;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_isVecLoad;
    logic io_mem_to_ooo_vecWriteback_0_0_bits_vls_isVlm;

    clocking drv_cb @(posedge clk);
        `ifdef INTERFACE_ADD_DELAY
            default input #`DEF_SETUP_TIME output #`DEF_HOLD_TIME;
        `endif
        output io_mem_to_ooo_vecWriteback_1_0_ready;
        input  io_mem_to_ooo_vecWriteback_1_0_valid;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_data_0;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_pdest;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_pdestVl;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_robIdx_flag;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_robIdx_value;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vecWen;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_v0Wen;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vlWen;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_exceptionVec_3;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_exceptionVec_4;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_exceptionVec_5;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_exceptionVec_6;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_exceptionVec_7;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_exceptionVec_13;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_exceptionVec_15;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_exceptionVec_19;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_exceptionVec_21;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_exceptionVec_23;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_trigger;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vill;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vma;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vta;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vsew;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vlmul;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_specVill;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_specVma;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_specVta;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_specVsew;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_specVlmul;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vm;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vstart;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_frm;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_fpu_isFpToVecInst;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_fpu_isFP32Instr;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_fpu_isFP64Instr;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_fpu_isReduction;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_fpu_isFoldTo1_2;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_fpu_isFoldTo1_4;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_fpu_isFoldTo1_8;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vxrm;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vuopIdx;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_lastUop;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vmask;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vl;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_nf;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_veew;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_isReverse;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_isExt;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_isNarrow;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_isDstMask;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_isOpMask;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_isMove;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_isDependOldVd;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_isWritePartVd;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_isVleff;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_maskVecGen;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_sew8;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_sew16;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_sew32;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_sew64;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_oldVdPsrc;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vdIdx;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vdIdxInField;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_isIndexed;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_isMasked;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_isStrided;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_isWhole;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_isVecLoad;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_isVlm;
        output io_mem_to_ooo_vecWriteback_0_0_ready;
        input  io_mem_to_ooo_vecWriteback_0_0_valid;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_data_0;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_pdest;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_pdestVl;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_robIdx_flag;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_robIdx_value;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vecWen;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_v0Wen;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vlWen;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_exceptionVec_3;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_exceptionVec_4;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_exceptionVec_5;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_exceptionVec_6;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_exceptionVec_7;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_exceptionVec_13;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_exceptionVec_15;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_exceptionVec_19;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_exceptionVec_21;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_exceptionVec_23;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_trigger;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vill;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vma;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vta;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vsew;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vlmul;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_specVill;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_specVma;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_specVta;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_specVsew;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_specVlmul;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vm;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vstart;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_frm;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_fpu_isFpToVecInst;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_fpu_isFP32Instr;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_fpu_isFP64Instr;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_fpu_isReduction;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_fpu_isFoldTo1_2;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_fpu_isFoldTo1_4;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_fpu_isFoldTo1_8;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vxrm;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vuopIdx;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_lastUop;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vmask;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vl;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_nf;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_veew;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_isReverse;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_isExt;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_isNarrow;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_isDstMask;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_isOpMask;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_isMove;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_isDependOldVd;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_isWritePartVd;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_isVleff;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_maskVecGen;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_sew8;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_sew16;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_sew32;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_sew64;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_oldVdPsrc;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vdIdx;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vdIdxInField;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_isIndexed;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_isMasked;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_isStrided;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_isWhole;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_isVecLoad;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_isVlm;

    endclocking:drv_cb

    clocking mon_cb @(posedge clk);
        `ifdef INTERFACE_ADD_DELAY
            default input #`DEF_SETUP_TIME output #`DEF_HOLD_TIME;
        `endif
        input  io_mem_to_ooo_vecWriteback_1_0_ready;
        input  io_mem_to_ooo_vecWriteback_1_0_valid;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_data_0;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_pdest;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_pdestVl;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_robIdx_flag;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_robIdx_value;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vecWen;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_v0Wen;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vlWen;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_exceptionVec_3;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_exceptionVec_4;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_exceptionVec_5;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_exceptionVec_6;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_exceptionVec_7;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_exceptionVec_13;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_exceptionVec_15;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_exceptionVec_19;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_exceptionVec_21;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_exceptionVec_23;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_trigger;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vill;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vma;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vta;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vsew;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vlmul;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_specVill;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_specVma;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_specVta;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_specVsew;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_specVlmul;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vm;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vstart;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_frm;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_fpu_isFpToVecInst;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_fpu_isFP32Instr;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_fpu_isFP64Instr;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_fpu_isReduction;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_fpu_isFoldTo1_2;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_fpu_isFoldTo1_4;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_fpu_isFoldTo1_8;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vxrm;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vuopIdx;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_lastUop;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vmask;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_vl;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_nf;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_veew;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_isReverse;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_isExt;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_isNarrow;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_isDstMask;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_isOpMask;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_isMove;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_isDependOldVd;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_isWritePartVd;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_isVleff;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_maskVecGen;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_sew8;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_sew16;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_sew32;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vpu_sew64;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_oldVdPsrc;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vdIdx;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_vdIdxInField;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_isIndexed;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_isMasked;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_isStrided;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_isWhole;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_isVecLoad;
        input  io_mem_to_ooo_vecWriteback_1_0_bits_vls_isVlm;
        input  io_mem_to_ooo_vecWriteback_0_0_ready;
        input  io_mem_to_ooo_vecWriteback_0_0_valid;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_data_0;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_pdest;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_pdestVl;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_robIdx_flag;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_robIdx_value;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vecWen;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_v0Wen;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vlWen;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_exceptionVec_3;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_exceptionVec_4;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_exceptionVec_5;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_exceptionVec_6;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_exceptionVec_7;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_exceptionVec_13;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_exceptionVec_15;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_exceptionVec_19;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_exceptionVec_21;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_exceptionVec_23;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_trigger;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vill;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vma;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vta;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vsew;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vlmul;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_specVill;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_specVma;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_specVta;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_specVsew;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_specVlmul;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vm;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vstart;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_frm;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_fpu_isFpToVecInst;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_fpu_isFP32Instr;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_fpu_isFP64Instr;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_fpu_isReduction;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_fpu_isFoldTo1_2;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_fpu_isFoldTo1_4;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_fpu_isFoldTo1_8;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vxrm;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vuopIdx;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_lastUop;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vmask;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_vl;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_nf;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_veew;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_isReverse;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_isExt;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_isNarrow;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_isDstMask;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_isOpMask;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_isMove;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_isDependOldVd;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_isWritePartVd;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_isVleff;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_maskVecGen;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_sew8;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_sew16;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_sew32;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vpu_sew64;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_oldVdPsrc;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vdIdx;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_vdIdxInField;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_isIndexed;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_isMasked;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_isStrided;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_isWhole;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_isVecLoad;
        input  io_mem_to_ooo_vecWriteback_0_0_bits_vls_isVlm;

    endclocking:mon_cb

    modport drv_mp (clocking drv_cb);
    modport mon_mp (clocking mon_cb);

endinterface:io_mem_to_ooo_vec_wb_agent_agent_interface

`endif
