package xiangshan.backend.vector.Decoder.Split

import chisel3.util.BitPat
import freechips.rocketchip.rocket.Instructions._
import xiangshan.backend.vector.Decoder.Uop.UopType.UopBase
import xiangshan.backend.vector.Decoder.Uop.VecUopDefines._

object SplitTable {
  val opiDupTable = Map(
    VADD_VV  -> vadd.vv,
    VADD_VX  -> vadd.vx,
    VADD_VI  -> vadd.vi,
    VSUB_VV  -> vsub.vv,
    VSUB_VX  -> vsub.vx,
    VRSUB_VX -> vsub.vx.setSrc12Rev,
    VRSUB_VI -> vsub.vi.setSrc12Rev,
    VMINU_VV -> vminu.vv,
    VMINU_VX -> vminu.vx,
    VMIN_VV  -> vmin.vv,
    VMIN_VX  -> vmin.vx,
    VMAXU_VV -> vmaxu.vv,
    VMAXU_VX -> vmaxu.vx,
    VMAX_VV  -> vmax.vv,
    VMAX_VX  -> vmax.vx,
    VAND_VV  -> vand.vv,
    VAND_VX  -> vand.vx,
    VAND_VI  -> vand.vi,
    VOR_VV   -> vor.vv,
    VOR_VX   -> vor.vx,
    VOR_VI   -> vor.vi,
    VXOR_VV  -> vxor.vv,
    VXOR_VX  -> vxor.vx,
    VXOR_VI  -> vxor.vi,

    VADC_VVM   -> vadc.vv,
    VADC_VXM   -> vadc.vx,
    VADC_VIM   -> vadc.vi,
    VMADC_VV   -> vmadc_vv.vv,
    VMADC_VX   -> vmadc_vv.vx,
    VMADC_VI   -> vmadc_vv.vi,
    VMADC_VVM  -> vmadc_vvm.vv,
    VMADC_VXM  -> vmadc_vvm.vx,
    VMADC_VIM  -> vmadc_vvm.vi,
    VSBC_VVM   -> vsbc.vv,
    VSBC_VXM   -> vsbc.vx,
    VMSBC_VV   -> vmsbc_vv.vv,
    VMSBC_VX   -> vmsbc_vv.vx,
    VMSBC_VVM  -> vmsbc_vvm.vv,
    VMSBC_VXM  -> vmsbc_vvm.vx,
    VMERGE_VVM -> vmerge.vv,
    VMERGE_VXM -> vmerge.vx,
    VMERGE_VIM -> vmerge.vi,
    VMV_V_V    -> vmvO2V.v,
    VMV_V_X    -> vmvO2V.x,
    VMV_V_I    -> vmvO2V.i,
    VMSEQ_VV   -> vmseq.vv,
    VMSEQ_VX   -> vmseq.vx,
    VMSEQ_VI   -> vmseq.vi,
    VMSNE_VV   -> vmsne.vv,
    VMSNE_VX   -> vmsne.vx,
    VMSNE_VI   -> vmsne.vi,
    VMSLTU_VV  -> vmsltu.vv,
    VMSLTU_VX  -> vmsltu.vx,
    VMSLT_VV   -> vmslt.vv,
    VMSLT_VX   -> vmslt.vx,
    VMSLEU_VV  -> vmsleu.vv,
    VMSLEU_VX  -> vmsleu.vx,
    VMSLEU_VI  -> vmsleu.vi,
    VMSLE_VV   -> vmsle.vv,
    VMSLE_VX   -> vmsle.vx,
    VMSLE_VI   -> vmsle.vi,
    VMSGTU_VX  -> vmsgtu.vx,
    VMSGTU_VI  -> vmsgtu.vi,
    VMSGT_VX   -> vmsgt.vx,
    VMSGT_VI   -> vmsgt.vi,
    VSADDU_VV  -> vsaddu.vv,
    VSADDU_VX  -> vsaddu.vx,
    VSADDU_VI  -> vsaddu.vi,
    VSADD_VV   -> vsadd.vv,
    VSADD_VX   -> vsadd.vx,
    VSADD_VI   -> vsadd.vi,
    VSSUBU_VV  -> vssubu.vv,
    VSSUBU_VX  -> vssubu.vx,
    VSSUB_VV   -> vssub.vv,
    VSSUB_VX   -> vssub.vx,
    VSLL_VV    -> vsll.vv,
    VSLL_VX    -> vsll.vx,
    VSLL_VI    -> vsll.vi,
    VSMUL_VV   -> vsmul.vv,
    VSMUL_VX   -> vsmul.vx,
    VSRL_VV    -> vsrl.vv,
    VSRL_VX    -> vsrl.vx,
    VSRL_VI    -> vsrl.vi,
    VSRA_VV    -> vsra.vv,
    VSRA_VX    -> vsra.vx,
    VSRA_VI    -> vsra.vi,
    VSSRL_VV   -> vssrl.vv,
    VSSRL_VX   -> vssrl.vx,
    VSSRL_VI   -> vssrl.vi,
    VSSRA_VV   -> vssra.vv,
    VSSRA_VX   -> vssra.vx,
    VSSRA_VI   -> vssra.vi,
  )

  val opiLmulUnrelatedTable: Map[BitPat, Seq[UopBase]] = Map(
    VMV1R_V    -> Seq.fill(1)(vmvnr.v),
    VMV2R_V    -> Seq.fill(2)(vmvnr.v),
    VMV4R_V    -> Seq.fill(4)(vmvnr.v),
    VMV8R_V    -> Seq.fill(8)(vmvnr.v),
  )

  val opiTableF2: Map[BitPat, Seq[UopBase]] = Map(
    VNSRL_WV   -> Seq.fill(1)(vnsrl.vv),
    VNSRL_WX   -> Seq.fill(1)(vnsrl.vx),
    VNSRL_WI   -> Seq.fill(1)(vnsrl.vi),
    VNSRA_WV   -> Seq.fill(1)(vnsra.vv),
    VNSRA_WX   -> Seq.fill(1)(vnsra.vx),
    VNSRA_WI   -> Seq.fill(1)(vnsra.vi),
    VNCLIPU_WV -> Seq.fill(1)(vnclipu.vv),
    VNCLIPU_WX -> Seq.fill(1)(vnclipu.vx),
    VNCLIPU_WI -> Seq.fill(1)(vnclipu.vi),
    VNCLIP_WV  -> Seq.fill(1)(vnclip.vv),
    VNCLIP_WX  -> Seq.fill(1)(vnclip.vx),
    VNCLIP_WI  -> Seq.fill(1)(vnclip.vi),
  )

  val opiTable1: Map[BitPat, Seq[UopBase]] = Map(
    VNSRL_WV   -> Seq.fill(2)(vnsrl.vv),
    VNSRL_WX   -> Seq.fill(2)(vnsrl.vx),
    VNSRL_WI   -> Seq.fill(2)(vnsrl.vi),
    VNSRA_WV   -> Seq.fill(2)(vnsra.vv),
    VNSRA_WX   -> Seq.fill(2)(vnsra.vx),
    VNSRA_WI   -> Seq.fill(2)(vnsra.vi),
    VNCLIPU_WV -> Seq.fill(2)(vnclipu.vv),
    VNCLIPU_WX -> Seq.fill(2)(vnclipu.vx),
    VNCLIPU_WI -> Seq.fill(2)(vnclipu.vi),
    VNCLIP_WV  -> Seq.fill(2)(vnclip.vv),
    VNCLIP_WX  -> Seq.fill(2)(vnclip.vx),
    VNCLIP_WI  -> Seq.fill(2)(vnclip.vi),

    VRGATHER_VV -> Seq.fill(1)(vrgather_vv.vv),
    VRGATHER_VX -> Seq.fill(1)(vrgather_xi.vx),
    VRGATHER_VI -> Seq.fill(1)(vrgather_xi.vi),
    VSLIDEUP_VX -> Seq.fill(1)(vslideup.vx),
    VSLIDEUP_VI -> Seq.fill(1)(vslideup.vi),
    VRGATHEREI16_VV -> Seq.fill(1)(vrgather_vv.vv),
    VSLIDEDOWN_VX   -> Seq.fill(1)(vslidedown.vx),
    VSLIDEDOWN_VI   -> Seq.fill(1)(vslidedown.vi),

    VWREDSUMU_VS -> Seq(
      vwaddu.vv.src12Mask,
      vwredsumu.vv.noMask,
    ),
    VWREDSUM_VS -> Seq(
      vwadd.vv.src12Mask,
      vwredsum.vv.noMask,
    )
  )

  val opiTable2: Map[BitPat, Seq[UopBase]] = Map(
    VNSRL_WV   -> Seq.fill(4)(vnsrl.vv),
    VNSRL_WX   -> Seq.fill(4)(vnsrl.vx),
    VNSRL_WI   -> Seq.fill(4)(vnsrl.vi),
    VNSRA_WV   -> Seq.fill(4)(vnsra.vv),
    VNSRA_WX   -> Seq.fill(4)(vnsra.vx),
    VNSRA_WI   -> Seq.fill(4)(vnsra.vi),
    VNCLIPU_WV -> Seq.fill(4)(vnclipu.vv),
    VNCLIPU_WX -> Seq.fill(4)(vnclipu.vx),
    VNCLIPU_WI -> Seq.fill(4)(vnclipu.vi),
    VNCLIP_WV  -> Seq.fill(4)(vnclip.vv),
    VNCLIP_WX  -> Seq.fill(4)(vnclip.vx),
    VNCLIP_WI  -> Seq.fill(4)(vnclip.vi),

    VRGATHER_VV -> Seq.fill(2)(vrgather_vv.vv),
    VRGATHER_VX -> Seq.fill(2)(vrgather_xi.vx),
    VRGATHER_VI -> Seq.fill(2)(vrgather_xi.vi),
    VSLIDEUP_VX -> Seq.fill(2)(vslideup.vx),
    VSLIDEUP_VI -> Seq.fill(2)(vslideup.vi),
    VRGATHEREI16_VV -> Seq.fill(2)(vrgather_vv.vv),
    VSLIDEDOWN_VX -> Seq.fill(2)(vslidedown.vx),
    VSLIDEDOWN_VI -> Seq.fill(2)(vslidedown.vi),
    VWREDSUMU_VS -> Seq(
      vwaddu.vv.src12Mask,
      vwaddu_w.vv.src2Mask,
      vwaddu_w.vv.src2Mask,
      vwredsumu.vv.noMask,
    ),
    VWREDSUM_VS -> Seq(
      vwadd.vv.src12Mask,
      vwadd_w.vv.src2Mask,
      vwadd_w.vv.src2Mask,
      vwredsum.vv.noMask,
    ),
  )

  val opiTable4: Map[BitPat, Seq[UopBase]] = Map(
    VNSRL_WV   -> Seq.fill(8)(vnsrl.vv),
    VNSRL_WX   -> Seq.fill(8)(vnsrl.vx),
    VNSRL_WI   -> Seq.fill(8)(vnsrl.vi),
    VNSRA_WV   -> Seq.fill(8)(vnsra.vv),
    VNSRA_WX   -> Seq.fill(8)(vnsra.vx),
    VNSRA_WI   -> Seq.fill(8)(vnsra.vi),
    VNCLIPU_WV -> Seq.fill(8)(vnclipu.vv),
    VNCLIPU_WX -> Seq.fill(8)(vnclipu.vx),
    VNCLIPU_WI -> Seq.fill(8)(vnclipu.vi),
    VNCLIP_WV  -> Seq.fill(8)(vnclip.vv),
    VNCLIP_WX  -> Seq.fill(8)(vnclip.vx),
    VNCLIP_WI  -> Seq.fill(8)(vnclip.vi),

    VRGATHER_VV     -> Seq.fill(4)(vrgather_vv.vv),
    VRGATHER_VX     -> Seq.fill(4)(vrgather_xi.vx),
    VRGATHER_VI     -> Seq.fill(4)(vrgather_xi.vi),
    VSLIDEUP_VX     -> Seq.fill(4)(vslideup.vx),
    VSLIDEUP_VI     -> Seq.fill(4)(vslideup.vi),
    VRGATHEREI16_VV -> Seq.fill(4)(vrgather_vv.vv),
    VSLIDEDOWN_VX   -> Seq.fill(4)(vslidedown.vx),
    VSLIDEDOWN_VI   -> Seq.fill(4)(vslidedown.vi),
    VWREDSUMU_VS    -> Seq(
      vwaddu.vv.src12Mask,
      vwaddu_w.vv.src2Mask,
      vwaddu_w.vv.src2Mask,
      vwaddu_w.vv.src2Mask,
      vwaddu_w.vv.src2Mask,
      vwaddu_w.vv.src2Mask,
      vwaddu_w.vv.src2Mask,
      vwredsumu.vv.noMask,
    ),
    VWREDSUM_VS -> Seq(
      vwadd.vv.src12Mask,
      vwadd_w.vv.src2Mask,
      vwadd_w.vv.src2Mask,
      vwadd_w.vv.src2Mask,
      vwadd_w.vv.src2Mask,
      vwadd_w.vv.src2Mask,
      vwadd_w.vv.src2Mask,
      vwredsum.vv.noMask,
    ),
  )

  val opiTable8: Map[BitPat, Seq[UopBase]] = Map(
    VNSRL_WV   -> Seq(),
    VNSRL_WX   -> Seq(),
    VNSRL_WI   -> Seq(),
    VNSRA_WV   -> Seq(),
    VNSRA_WX   -> Seq(),
    VNSRA_WI   -> Seq(),
    VNCLIPU_WV -> Seq(),
    VNCLIPU_WX -> Seq(),
    VNCLIPU_WI -> Seq(),
    VNCLIP_WV  -> Seq(),
    VNCLIP_WX  -> Seq(),
    VNCLIP_WI  -> Seq(),

    VRGATHER_VV     -> Seq.fill(8)(vrgather_vv.vv),
    VRGATHER_VX     -> Seq.fill(8)(vrgather_xi.vx),
    VRGATHER_VI     -> Seq.fill(8)(vrgather_xi.vi),
    VSLIDEUP_VX     -> Seq.fill(8)(vslideup.vx),
    VSLIDEUP_VI     -> Seq.fill(8)(vslideup.vi),
    VRGATHEREI16_VV -> Seq.fill(8)(vrgather_vv.vv),
    VSLIDEDOWN_VX   -> Seq.fill(8)(vslidedown.vx),
    VSLIDEDOWN_VI   -> Seq.fill(8)(vslidedown.vi),
    VWREDSUMU_VS    -> Seq(),
    VWREDSUM_VS     -> Seq(),
  )

  val opmDupTable: Map[BitPat, UopBase] = Map(
    VAADDU_VV   -> vaaddu.vv,
    VAADDU_VX   -> vaaddu.vx,
    VAADD_VV    -> vaadd.vv,
    VAADD_VX    -> vaadd.vx,
    VASUBU_VV   -> vasubu.vv,
    VASUBU_VX   -> vasubu.vx,
    VASUB_VV    -> vasub.vv,
    VASUB_VX    -> vasub.vx,
    // VXUNARY0
    VZEXT_VF8   -> vzext8.v,
    VZEXT_VF4   -> vzext4.v,
    VZEXT_VF2   -> vzext2.v,
    VSEXT_VF8   -> vsext8.v,
    VSEXT_VF4   -> vsext4.v,
    VSEXT_VF2   -> vsext2.v,

    VDIVU_VV    -> vdivu.vv,
    VDIVU_VX    -> vdivu.vx,
    VDIV_VV     -> vdiv.vv,
    VDIV_VX     -> vdiv.vx,
    VREMU_VV    -> vremu.vv,
    VREMU_VX    -> vremu.vx,
    VREM_VV     -> vrem.vv,
    VREM_VX     -> vrem.vx,

    VMULHU_VV   -> vmulhu.vv,
    VMULHU_VX   -> vmulhu.vx,
    VMUL_VV     -> vmul.vv,
    VMUL_VX     -> vmul.vx,
    VMULHSU_VV  -> vmulhsu.vv,
    VMULHSU_VX  -> vmulhsu.vx,
    VMULH_VV    -> vmulh.vv,
    VMULH_VX    -> vmulh.vx,

    VMADD_VV    -> vmadd.vv,
    VMADD_VX    -> vmadd.vx,
    VNMSUB_VV   -> vnmsub.vv,
    VNMSUB_VX   -> vnmsub.vx,
    VMACC_VV    -> vmacc.vv,
    VMACC_VX    -> vmacc.vx,
    VNMSAC_VV   -> vnmsac.vv,
    VNMSAC_VX   -> vnmsac.vx,
  ).asInstanceOf[Map[BitPat, UopBase]]

  val opmLmulUnrelatedTable: Map[BitPat, Seq[UopBase]] = Map(
    // VWXUNARY0
    VMV_X_S     -> Seq(vmvS2X.v),
    VCPOP_M     -> Seq(vcpop_m.m),
    VFIRST_M    -> Seq(vfirst.m),
    // VMUNARY0
    VMSBF_M     -> Seq(vmsbf.m),
    VMSOF_M     -> Seq(vmsof.m),
    VMSIF_M     -> Seq(vmsif.m),
    VIOTA_M     -> Seq(viota.m),
    VID_V       -> Seq(vid),

    VMANDN_MM   -> Seq(vmandn.mm),
    VMAND_MM    -> Seq(vmand.mm),
    VMOR_MM     -> Seq(vmor.mm),
    VMXOR_MM    -> Seq(vmxor.mm),
    VMORN_MM    -> Seq(vmorn.mm),
    VMNAND_MM   -> Seq(vmnand.mm),
    VMNOR_MM    -> Seq(vmnor.mm),
    VMXNOR_MM   -> Seq(vmxnor.mm),
  ).asInstanceOf[Map[BitPat, Seq[UopBase]]]

  val opmTableF2: Map[BitPat, Seq[UopBase]] = Map(
    VWADDU_VV   -> Seq.fill(1)(vwaddu.vv),
    VWADDU_VX   -> Seq.fill(1)(vwaddu.vx),
    VWADD_VV    -> Seq.fill(1)(vwadd.vv),
    VWADD_VX    -> Seq.fill(1)(vwadd.vx),
    VWSUBU_VV   -> Seq.fill(1)(vwsubu.vv),
    VWSUBU_VX   -> Seq.fill(1)(vwsubu.vx),
    VWSUB_VV    -> Seq.fill(1)(vwsub.vv),
    VWSUB_VX    -> Seq.fill(1)(vwsub.vx),
    VWADDU_WV   -> Seq.fill(1)(vwaddu_w.vv),
    VWADDU_WX   -> Seq.fill(1)(vwaddu_w.vx),
    VWADD_WV    -> Seq.fill(1)(vwadd_w.vv),
    VWADD_WX    -> Seq.fill(1)(vwadd_w.vx),
    VWSUBU_WV   -> Seq.fill(1)(vwsubu_w.vv),
    VWSUBU_WX   -> Seq.fill(1)(vwsubu_w.vx),
    VWSUB_WV    -> Seq.fill(1)(vwsub_w.vv),
    VWSUB_WX    -> Seq.fill(1)(vwsub_w.vx),
    VWMULU_VV   -> Seq.fill(1)(vwmulu.vv),
    VWMULU_VX   -> Seq.fill(1)(vwmulu.vx),
    VWMULSU_VV  -> Seq.fill(1)(vwmulsu.vv),
    VWMULSU_VX  -> Seq.fill(1)(vwmulsu.vx),
    VWMUL_VV    -> Seq.fill(1)(vwmul.vv),
    VWMUL_VX    -> Seq.fill(1)(vwmul.vx),
    VWMACCU_VV  -> Seq.fill(1)(vwmaccu.vv),
    VWMACCU_VX  -> Seq.fill(1)(vwmaccu.vx),
    VWMACC_VV   -> Seq.fill(1)(vwmacc.vv),
    VWMACC_VX   -> Seq.fill(1)(vwmacc.vx),
    VWMACCUS_VX -> Seq.fill(1)(vwmaccus.vx),
    VWMACCSU_VV -> Seq.fill(1)(vwmaccsu.vv),
    VWMACCSU_VX -> Seq.fill(1)(vwmaccsu.vx),
  )

  val opmTable1: Map[BitPat, Seq[UopBase]] = Map(
    // VRXUNARY0
    VMV_S_X         -> Seq(vmvX2S.x),

    VWADDU_VV   -> Seq.fill(2)(vwaddu.vv),
    VWADDU_VX   -> Seq.fill(2)(vwaddu.vx),
    VWADD_VV    -> Seq.fill(2)(vwadd.vv),
    VWADD_VX    -> Seq.fill(2)(vwadd.vx),
    VWSUBU_VV   -> Seq.fill(2)(vwsubu.vv),
    VWSUBU_VX   -> Seq.fill(2)(vwsubu.vx),
    VWSUB_VV    -> Seq.fill(2)(vwsub.vv),
    VWSUB_VX    -> Seq.fill(2)(vwsub.vx),
    VWADDU_WV   -> Seq.fill(2)(vwaddu_w.vv),
    VWADDU_WX   -> Seq.fill(2)(vwaddu_w.vx),
    VWADD_WV    -> Seq.fill(2)(vwadd_w.vv),
    VWADD_WX    -> Seq.fill(2)(vwadd_w.vx),
    VWSUBU_WV   -> Seq.fill(2)(vwsubu_w.vv),
    VWSUBU_WX   -> Seq.fill(2)(vwsubu_w.vx),
    VWSUB_WV    -> Seq.fill(2)(vwsub_w.vv),
    VWSUB_WX    -> Seq.fill(2)(vwsub_w.vx),
    VWMULU_VV   -> Seq.fill(2)(vwmulu.vv),
    VWMULU_VX   -> Seq.fill(2)(vwmulu.vx),
    VWMULSU_VV  -> Seq.fill(2)(vwmulsu.vv),
    VWMULSU_VX  -> Seq.fill(2)(vwmulsu.vx),
    VWMUL_VV    -> Seq.fill(2)(vwmul.vv),
    VWMUL_VX    -> Seq.fill(2)(vwmul.vx),
    VWMACCU_VV  -> Seq.fill(2)(vwmaccu.vv),
    VWMACCU_VX  -> Seq.fill(2)(vwmaccu.vx),
    VWMACC_VV   -> Seq.fill(2)(vwmacc.vv),
    VWMACC_VX   -> Seq.fill(2)(vwmacc.vx),
    VWMACCUS_VX -> Seq.fill(2)(vwmaccus.vx),
    VWMACCSU_VV -> Seq.fill(2)(vwmaccsu.vv),
    VWMACCSU_VX -> Seq.fill(2)(vwmaccsu.vx),

    VREDSUM_VS      -> Seq(vredsum.vv.src2Mask),
    VREDAND_VS      -> Seq(vredand.vv.src2Mask),
    VREDOR_VS       -> Seq(vredor.vv.src2Mask),
    VREDXOR_VS      -> Seq(vredxor.vv.src2Mask),
    VREDMINU_VS     -> Seq(vredminu.vv.src2Mask),
    VREDMIN_VS      -> Seq(vredmin.vv.src2Mask),
    VREDMAXU_VS     -> Seq(vredmaxu.vv.src2Mask),
    VREDMAX_VS      -> Seq(vredmax.vv.src2Mask),
    VSLIDE1UP_VX    -> Seq(vslide1up.vx),
    VSLIDE1DOWN_VX  -> Seq(vslide1down.vx),
    VCOMPRESS_VM    -> Seq(vcompress.vv),
  )

  val opmTable2: Map[BitPat, Seq[UopBase]] = Map(
    // VRXUNARY0
    VMV_S_X         -> Seq(
      vmvX2S.x,
      vtail,
    ),

    VWADDU_VV   -> Seq.fill(4)(vwaddu.vv),
    VWADDU_VX   -> Seq.fill(4)(vwaddu.vx),
    VWADD_VV    -> Seq.fill(4)(vwadd.vv),
    VWADD_VX    -> Seq.fill(4)(vwadd.vx),
    VWSUBU_VV   -> Seq.fill(4)(vwsubu.vv),
    VWSUBU_VX   -> Seq.fill(4)(vwsubu.vx),
    VWSUB_VV    -> Seq.fill(4)(vwsub.vv),
    VWSUB_VX    -> Seq.fill(4)(vwsub.vx),
    VWADDU_WV   -> Seq.fill(4)(vwaddu_w.vv),
    VWADDU_WX   -> Seq.fill(4)(vwaddu_w.vx),
    VWADD_WV    -> Seq.fill(4)(vwadd_w.vv),
    VWADD_WX    -> Seq.fill(4)(vwadd_w.vx),
    VWSUBU_WV   -> Seq.fill(4)(vwsubu_w.vv),
    VWSUBU_WX   -> Seq.fill(4)(vwsubu_w.vx),
    VWSUB_WV    -> Seq.fill(4)(vwsub_w.vv),
    VWSUB_WX    -> Seq.fill(4)(vwsub_w.vx),
    VWMULU_VV   -> Seq.fill(4)(vwmulu.vv),
    VWMULU_VX   -> Seq.fill(4)(vwmulu.vx),
    VWMULSU_VV  -> Seq.fill(4)(vwmulsu.vv),
    VWMULSU_VX  -> Seq.fill(4)(vwmulsu.vx),
    VWMUL_VV    -> Seq.fill(4)(vwmul.vv),
    VWMUL_VX    -> Seq.fill(4)(vwmul.vx),
    VWMACCU_VV  -> Seq.fill(4)(vwmaccu.vv),
    VWMACCU_VX  -> Seq.fill(4)(vwmaccu.vx),
    VWMACC_VV   -> Seq.fill(4)(vwmacc.vv),
    VWMACC_VX   -> Seq.fill(4)(vwmacc.vx),
    VWMACCUS_VX -> Seq.fill(4)(vwmaccus.vx),
    VWMACCSU_VV -> Seq.fill(4)(vwmaccsu.vv),
    VWMACCSU_VX -> Seq.fill(4)(vwmaccsu.vx),

    VREDSUM_VS      -> Seq(
      vadd.vv.src12Mask,
      vredsum.vv.noMask,
    ),
    VREDAND_VS      -> Seq(
      vand.vv.src12Mask,
      vredand.vv.noMask,
    ),
    VREDOR_VS       -> Seq(
      vor.vv.src12Mask,
      vredor.vv.noMask,
    ),
    VREDXOR_VS      -> Seq(
      vxor.vv.src12Mask,
      vredxor.vv.noMask,
    ),
    VREDMINU_VS     -> Seq(
      vminu.vv.src12Mask,
      vredminu.vv.noMask,
    ),
    VREDMIN_VS      -> Seq(
      vmin.vv.src12Mask,
      vredmin.vv.noMask,
    ),
    VREDMAXU_VS     -> Seq(
      vmaxu.vv.src12Mask,
      vredmaxu.vv.noMask,
    ),
    VREDMAX_VS      -> Seq(
      vmax.vv.src12Mask,
      vredmax.vv.noMask,
    ),
    VSLIDE1UP_VX    -> Seq(
      vslide1up.vx,
      vslide1up.vx,
    ),
    VSLIDE1DOWN_VX  -> Seq(
      vslide1down.vx,
      vslide1down.vx,
    ),
    VCOMPRESS_VM    -> Seq(
      vcompress.vv,
      vcompress.vv,
    ),
  )

  val opmTable4: Map[BitPat, Seq[UopBase]] = Map(
    VMV_S_X         -> (Seq(
      vmvX2S.x,
    ) ++ Seq.fill(3)(vtail)),

    VWADDU_VV   -> Seq.fill(8)(vwaddu.vv),
    VWADDU_VX   -> Seq.fill(8)(vwaddu.vx),
    VWADD_VV    -> Seq.fill(8)(vwadd.vv),
    VWADD_VX    -> Seq.fill(8)(vwadd.vx),
    VWSUBU_VV   -> Seq.fill(8)(vwsubu.vv),
    VWSUBU_VX   -> Seq.fill(8)(vwsubu.vx),
    VWSUB_VV    -> Seq.fill(8)(vwsub.vv),
    VWSUB_VX    -> Seq.fill(8)(vwsub.vx),
    VWADDU_WV   -> Seq.fill(8)(vwaddu_w.vv),
    VWADDU_WX   -> Seq.fill(8)(vwaddu_w.vx),
    VWADD_WV    -> Seq.fill(8)(vwadd_w.vv),
    VWADD_WX    -> Seq.fill(8)(vwadd_w.vx),
    VWSUBU_WV   -> Seq.fill(8)(vwsubu_w.vv),
    VWSUBU_WX   -> Seq.fill(8)(vwsubu_w.vx),
    VWSUB_WV    -> Seq.fill(8)(vwsub_w.vv),
    VWSUB_WX    -> Seq.fill(8)(vwsub_w.vx),
    VWMULU_VV   -> Seq.fill(8)(vwmulu.vv),
    VWMULU_VX   -> Seq.fill(8)(vwmulu.vx),
    VWMULSU_VV  -> Seq.fill(8)(vwmulsu.vv),
    VWMULSU_VX  -> Seq.fill(8)(vwmulsu.vx),
    VWMUL_VV    -> Seq.fill(8)(vwmul.vv),
    VWMUL_VX    -> Seq.fill(8)(vwmul.vx),
    VWMACCU_VV  -> Seq.fill(8)(vwmaccu.vv),
    VWMACCU_VX  -> Seq.fill(8)(vwmaccu.vx),
    VWMACC_VV   -> Seq.fill(8)(vwmacc.vv),
    VWMACC_VX   -> Seq.fill(8)(vwmacc.vx),
    VWMACCUS_VX -> Seq.fill(8)(vwmaccus.vx),
    VWMACCSU_VV -> Seq.fill(8)(vwmaccsu.vv),
    VWMACCSU_VX -> Seq.fill(8)(vwmaccsu.vx),

    VREDSUM_VS      -> Seq(
      vadd.vv.src12Mask,
      vadd.vv.src2Mask,
      vadd.vv.src2Mask,
      vredsum.vv.noMask,
    ),
    VREDAND_VS      -> Seq(
      vand.vv.src12Mask,
      vand.vv.src2Mask,
      vand.vv.src2Mask,
      vredand.vv.noMask,
    ),
    VREDOR_VS       -> Seq(
      vor.vv.src12Mask,
      vor.vv.src2Mask,
      vor.vv.src2Mask,
      vredor.vv.noMask,
    ),
    VREDXOR_VS      -> Seq(
      vxor.vv.src12Mask,
      vxor.vv.src2Mask,
      vxor.vv.src2Mask,
      vredxor.vv.noMask,
    ),
    VREDMINU_VS     -> Seq(
      vminu.vv.src12Mask,
      vminu.vv.src2Mask,
      vminu.vv.src2Mask,
      vredminu.vv.noMask,
    ),
    VREDMIN_VS      -> Seq(
      vmin.vv.src12Mask,
      vmin.vv.src2Mask,
      vmin.vv.src2Mask,
      vredmin.vv.noMask,
    ),
    VREDMAXU_VS     -> Seq(
      vmaxu.vv.src12Mask,
      vmaxu.vv.src2Mask,
      vmaxu.vv.src2Mask,
      vredmaxu.vv.noMask,
    ),
    VREDMAX_VS      -> Seq(
      vmax.vv.src12Mask,
      vmax.vv.src2Mask,
      vmax.vv.src2Mask,
      vredmax.vv.noMask,
    ),
    VSLIDE1UP_VX    -> Seq(
      vslide1up.vx,
      vslide1up.vx,
      vslide1up.vx,
      vslide1up.vx,
    ),
    VSLIDE1DOWN_VX  -> Seq(
      vslide1down.vx,
      vslide1down.vx,
      vslide1down.vx,
      vslide1down.vx,
    ),
    VCOMPRESS_VM    -> Seq(
      vcompress.vv,
      vcompress.vv,
      vcompress.vv,
      vcompress.vv,
    ),
  )

  val opmTable8: Map[BitPat, Seq[UopBase]] = Map(
    VMV_S_X         -> (Seq(
      vmvX2S.x,
    ) ++ Seq.fill(7)(vtail)),
    VWADDU_VV   -> Seq(),
    VWADDU_VX   -> Seq(),
    VWADD_VV    -> Seq(),
    VWADD_VX    -> Seq(),
    VWSUBU_VV   -> Seq(),
    VWSUBU_VX   -> Seq(),
    VWSUB_VV    -> Seq(),
    VWSUB_VX    -> Seq(),
    VWADDU_WV   -> Seq(),
    VWADDU_WX   -> Seq(),
    VWADD_WV    -> Seq(),
    VWADD_WX    -> Seq(),
    VWSUBU_WV   -> Seq(),
    VWSUBU_WX   -> Seq(),
    VWSUB_WV    -> Seq(),
    VWSUB_WX    -> Seq(),
    VWMULU_VV   -> Seq(),
    VWMULU_VX   -> Seq(),
    VWMULSU_VV  -> Seq(),
    VWMULSU_VX  -> Seq(),
    VWMUL_VV    -> Seq(),
    VWMUL_VX    -> Seq(),
    VWMACCU_VV  -> Seq(),
    VWMACCU_VX  -> Seq(),
    VWMACC_VV   -> Seq(),
    VWMACC_VX   -> Seq(),
    VWMACCUS_VX -> Seq(),
    VWMACCSU_VV -> Seq(),
    VWMACCSU_VX -> Seq(),

    VREDSUM_VS      -> Seq(
      vadd.vv.src12Mask,
      vadd.vv.src2Mask,
      vadd.vv.src2Mask,
      vadd.vv.src2Mask,
      vadd.vv.src2Mask,
      vadd.vv.src2Mask,
      vadd.vv.src2Mask,
      vredsum.vv.noMask,
    ),
    VREDAND_VS      -> Seq(
      vand.vv.src12Mask,
      vand.vv.src2Mask,
      vand.vv.src2Mask,
      vand.vv.src2Mask,
      vand.vv.src2Mask,
      vand.vv.src2Mask,
      vand.vv.src2Mask,
      vredand.vv.noMask,
    ),
    VREDOR_VS       -> Seq(
      vor.vv.src12Mask,
      vor.vv.src2Mask,
      vor.vv.src2Mask,
      vor.vv.src2Mask,
      vor.vv.src2Mask,
      vor.vv.src2Mask,
      vor.vv.src2Mask,
      vredor.vv.noMask,
    ),
    VREDXOR_VS      -> Seq(
      vxor.vv.src12Mask,
      vxor.vv.src2Mask,
      vxor.vv.src2Mask,
      vxor.vv.src2Mask,
      vxor.vv.src2Mask,
      vxor.vv.src2Mask,
      vxor.vv.src2Mask,
      vredxor.vv.noMask,
    ),
    VREDMINU_VS     -> Seq(
      vminu.vv.src12Mask,
      vminu.vv.src2Mask,
      vminu.vv.src2Mask,
      vminu.vv.src2Mask,
      vminu.vv.src2Mask,
      vminu.vv.src2Mask,
      vminu.vv.src2Mask,
      vredminu.vv.noMask,
    ),
    VREDMIN_VS      -> Seq(
      vmin.vv.src12Mask,
      vmin.vv.src2Mask,
      vmin.vv.src2Mask,
      vmin.vv.src2Mask,
      vmin.vv.src2Mask,
      vmin.vv.src2Mask,
      vmin.vv.src2Mask,
      vredmin.vv.noMask,
    ),
    VREDMAXU_VS     -> Seq(
      vmaxu.vv.src12Mask,
      vmaxu.vv.src2Mask,
      vmaxu.vv.src2Mask,
      vmaxu.vv.src2Mask,
      vmaxu.vv.src2Mask,
      vmaxu.vv.src2Mask,
      vmaxu.vv.src2Mask,
      vredmaxu.vv.noMask,
    ),
    VREDMAX_VS      -> Seq(
      vmax.vv.src12Mask,
      vmax.vv.src2Mask,
      vmax.vv.src2Mask,
      vmax.vv.src2Mask,
      vmax.vv.src2Mask,
      vmax.vv.src2Mask,
      vmax.vv.src2Mask,
      vredmax.vv.noMask,
    ),
    VSLIDE1UP_VX    -> Seq(
      vslide1up.vx,
      vslide1up.vx,
      vslide1up.vx,
      vslide1up.vx,
      vslide1up.vx,
      vslide1up.vx,
      vslide1up.vx,
      vslide1up.vx,
    ),
    VSLIDE1DOWN_VX  -> Seq(
      vslide1down.vx,
      vslide1down.vx,
      vslide1down.vx,
      vslide1down.vx,
      vslide1down.vx,
      vslide1down.vx,
      vslide1down.vx,
      vslide1down.vx,
    ),
    VCOMPRESS_VM    -> Seq(
      vcompress.vv,
      vcompress.vv,
      vcompress.vv,
      vcompress.vv,
      vcompress.vv,
      vcompress.vv,
      vcompress.vv,
      vcompress.vv,
    ),
  )

  val opfDupTable: Map[BitPat, UopBase] = Map(
    VFADD_VV -> vfadd.vv,
    VFADD_VF -> vfadd.vf,
    VFSUB_VV -> vfsub.vv,
    VFSUB_VF -> vfsub.vf,
    VFMIN_VV -> vfmin.vv,
    VFMIN_VF -> vfmin.vf,
    VFMAX_VV -> vfmax.vv,
    VFMAX_VF -> vfmax.vf,
    VFSGNJ_VV -> vfsgnj.vv,
    VFSGNJ_VF -> vfsgnj.vf,
    VFSGNJN_VV -> vfsgnjn.vv,
    VFSGNJN_VF -> vfsgnjn.vf,
    VFSGNJX_VV -> vfsgnjx.vv,
    VFSGNJX_VF -> vfsgnjx.vf,
    // VFUNARY0
    VFCVT_XU_F_V      -> vfcvt_xu_f.v,
    VFCVT_X_F_V       -> vfcvt_x_f.v,
    VFCVT_F_XU_V      -> vfcvt_f_xu.v,
    VFCVT_F_X_V       -> vfcvt_f_x.v,
    VFCVT_RTZ_XU_F_V  -> vfcvt_xu_f_rtz.v,
    VFCVT_RTZ_X_F_V   -> vfcvt_x_f_rtz.v,

    // VFUNARY1
    VFSQRT_V          -> vfsqrt.v,
    VFRSQRT7_V        -> vfrsqrt7.v,
    VFREC7_V          -> vfrec7.v,
    VFCLASS_V         -> vfclass.v,

    VFMERGE_VFM       -> vfmerge.vf,
    VFMV_V_F          -> vmvF2V.f,

    VMFEQ_VV          -> vmfeq.vv,
    VMFEQ_VF          -> vmfeq.vf,
    VMFLE_VV          -> vmfle.vv,
    VMFLE_VF          -> vmfle.vf,
    VMFLT_VV          -> vmflt.vv,
    VMFLT_VF          -> vmflt.vf,
    VMFNE_VV          -> vmfne.vv,
    VMFNE_VF          -> vmfne.vf,
    VMFGT_VF          -> vmfgt.vf,
    VMFGE_VF          -> vmfge.vf,

    VFDIV_VV          -> vfdiv.vv,
    VFDIV_VF          -> vfdiv.vf,
    VFRDIV_VF         -> vfdiv.vf.setSrc12Rev,
    VFMUL_VV          -> vfmul.vv,
    VFMUL_VF          -> vfmul.vf,

    VFRSUB_VF         -> vfsub.vf.setSrc12Rev,

    VFMADD_VV         -> vfmadd.vv,
    VFMADD_VF         -> vfmadd.vf,
    VFNMADD_VV        -> vfnmadd.vv,
    VFNMADD_VF        -> vfnmadd.vf,
    VFMSUB_VV         -> vfmsub.vv,
    VFMSUB_VF         -> vfmsub.vf,
    VFNMSUB_VV        -> vfnmsub.vv,
    VFNMSUB_VF        -> vfnmsub.vf,
    VFMACC_VV         -> vfmacc.vv,
    VFMACC_VF         -> vfmacc.vf,
    VFNMACC_VV        -> vfnmacc.vv,
    VFNMACC_VF        -> vfnmacc.vf,
    VFMSAC_VV         -> vfmsac.vv,
    VFMSAC_VF         -> vfmsac.vf,
    VFNMSAC_VV        -> vfnmsac.vv,
    VFNMSAC_VF        -> vfnmsac.vf,
  )

  val opfLmulUnrelatedTable: Map[BitPat, Seq[UopBase]] = Map(
    // VWFUNARY0
    VFMV_F_S -> Seq(vmvS2F.v),
  )

  val opfTableF2: Map[BitPat, Seq[UopBase]] = Map(
    VFNCVT_XU_F_W     -> Seq.fill(1)(vfncvt_xu_f.v),
    VFNCVT_X_F_W      -> Seq.fill(1)(vfncvt_x_f.v),
    VFNCVT_F_XU_W     -> Seq.fill(1)(vfncvt_f_xu.v),
    VFNCVT_F_X_W      -> Seq.fill(1)(vfncvt_f_x.v),
    VFNCVT_F_F_W      -> Seq.fill(1)(vfncvt_f_f.v),
    VFNCVT_ROD_F_F_W  -> Seq.fill(1)(vfncvt_f_f_rod.v),
    VFNCVT_RTZ_XU_F_W -> Seq.fill(1)(vfncvt_xu_f_rtz.v),
    VFNCVT_RTZ_X_F_W  -> Seq.fill(1)(vfncvt_x_f_rtz.v),

    VFWCVT_XU_F_V     -> Seq.fill(1)(vfwcvt_xu_f.v),
    VFWCVT_X_F_V      -> Seq.fill(1)(vfwcvt_x_f.v),
    VFWCVT_F_XU_V     -> Seq.fill(1)(vfwcvt_f_xu.v),
    VFWCVT_F_X_V      -> Seq.fill(1)(vfwcvt_f_x.v),
    VFWCVT_F_F_V      -> Seq.fill(1)(vfwcvt_f_f.v),
    VFWCVT_RTZ_XU_F_V -> Seq.fill(1)(vfwcvt_xu_f_rtz.v),
    VFWCVT_RTZ_X_F_V  -> Seq.fill(1)(vfwcvt_x_f_rtz.v),

    VFWADD_VV         -> Seq.fill(1)(vfwadd.vv),
    VFWADD_VF         -> Seq.fill(1)(vfwadd.vf),
    VFWSUB_VV         -> Seq.fill(1)(vfwsub.vv),
    VFWSUB_VF         -> Seq.fill(1)(vfwsub.vf),
    VFWADD_WV         -> Seq.fill(1)(vfwadd_w.vv),
    VFWADD_WF         -> Seq.fill(1)(vfwadd_w.vf),
    VFWSUB_WV         -> Seq.fill(1)(vfwsub_w.vv),
    VFWSUB_WF         -> Seq.fill(1)(vfwsub_w.vf),
    VFWMUL_VV         -> Seq.fill(1)(vfwmul.vv),
    VFWMUL_VF         -> Seq.fill(1)(vfwmul.vf),
    VFWMACC_VV        -> Seq.fill(1)(vfwmacc.vv),
    VFWMACC_VF        -> Seq.fill(1)(vfwmacc.vf),
    VFWNMACC_VV       -> Seq.fill(1)(vfwnmacc.vv),
    VFWNMACC_VF       -> Seq.fill(1)(vfwnmacc.vf),
    VFWMSAC_VV        -> Seq.fill(1)(vfwmsac.vv),
    VFWMSAC_VF        -> Seq.fill(1)(vfwmsac.vf),
    VFWNMSAC_VV       -> Seq.fill(1)(vfwnmsac.vv),
    VFWNMSAC_VF       -> Seq.fill(1)(vfwnmsac.vf),
  )

  val opfTable1: Map[BitPat, Seq[UopBase]] = Map(
    // VRFUNARY0
    VFMV_S_F -> Seq(vmvF2S.f),

    VFNCVT_XU_F_W     -> Seq.fill(2)(vfncvt_xu_f.v),
    VFNCVT_X_F_W      -> Seq.fill(2)(vfncvt_x_f.v),
    VFNCVT_F_XU_W     -> Seq.fill(2)(vfncvt_f_xu.v),
    VFNCVT_F_X_W      -> Seq.fill(2)(vfncvt_f_x.v),
    VFNCVT_F_F_W      -> Seq.fill(2)(vfncvt_f_f.v),
    VFNCVT_ROD_F_F_W  -> Seq.fill(2)(vfncvt_f_f_rod.v),
    VFNCVT_RTZ_XU_F_W -> Seq.fill(2)(vfncvt_xu_f_rtz.v),
    VFNCVT_RTZ_X_F_W  -> Seq.fill(2)(vfncvt_x_f_rtz.v),

    VFWCVT_XU_F_V     -> Seq.fill(2)(vfwcvt_xu_f.v),
    VFWCVT_X_F_V      -> Seq.fill(2)(vfwcvt_x_f.v),
    VFWCVT_F_XU_V     -> Seq.fill(2)(vfwcvt_f_xu.v),
    VFWCVT_F_X_V      -> Seq.fill(2)(vfwcvt_f_x.v),
    VFWCVT_F_F_V      -> Seq.fill(2)(vfwcvt_f_f.v),
    VFWCVT_RTZ_XU_F_V -> Seq.fill(2)(vfwcvt_xu_f_rtz.v),
    VFWCVT_RTZ_X_F_V  -> Seq.fill(2)(vfwcvt_x_f_rtz.v),

    VFWADD_VV         -> Seq.fill(2)(vfwadd.vv),
    VFWADD_VF         -> Seq.fill(2)(vfwadd.vf),
    VFWSUB_VV         -> Seq.fill(2)(vfwsub.vv),
    VFWSUB_VF         -> Seq.fill(2)(vfwsub.vf),
    VFWADD_WV         -> Seq.fill(2)(vfwadd_w.vv),
    VFWADD_WF         -> Seq.fill(2)(vfwadd_w.vf),
    VFWSUB_WV         -> Seq.fill(2)(vfwsub_w.vv),
    VFWSUB_WF         -> Seq.fill(2)(vfwsub_w.vf),
    VFWMUL_VV         -> Seq.fill(2)(vfwmul.vv),
    VFWMUL_VF         -> Seq.fill(2)(vfwmul.vf),
    VFWMACC_VV        -> Seq.fill(2)(vfwmacc.vv),
    VFWMACC_VF        -> Seq.fill(2)(vfwmacc.vf),
    VFWNMACC_VV       -> Seq.fill(2)(vfwnmacc.vv),
    VFWNMACC_VF       -> Seq.fill(2)(vfwnmacc.vf),
    VFWMSAC_VV        -> Seq.fill(2)(vfwmsac.vv),
    VFWMSAC_VF        -> Seq.fill(2)(vfwmsac.vf),
    VFWNMSAC_VV       -> Seq.fill(2)(vfwnmsac.vv),
    VFWNMSAC_VF       -> Seq.fill(2)(vfwnmsac.vf),

    VFSLIDE1UP_VF   -> Seq.fill(1)(vslide1up.vf),
    VFSLIDE1DOWN_VF -> Seq.fill(1)(vslide1down.vf),

    VFREDUSUM_VS -> Seq.fill(1)(vfredosum.vv.src2Mask),
    VFREDOSUM_VS -> Seq.fill(1)(vfredosum.vv.src2Mask),
    VFREDMIN_VS  -> Seq.fill(1)(vfredmin.vv.src2Mask),
    VFREDMAX_VS  -> Seq.fill(1)(vfredmax.vv.src2Mask),

    VFWREDUSUM_VS -> Seq(
      vfwadd.vv.src12Mask,
      vfwredosum.vv.noMask,
    ),
    VFWREDOSUM_VS -> Seq(
      vfwredosum.vv.src2Mask,
      vfwredosum.vv.src2Mask,
    ),
  )

  val opfTable2: Map[BitPat, Seq[UopBase]] = Map(
    // VRFUNARY0
    VFMV_S_F -> (Seq(
      vmvF2S.f,
    ) ++ Seq.fill(1)(vtail)),

    VFNCVT_XU_F_W     -> Seq.fill(4)(vfncvt_xu_f.v),
    VFNCVT_X_F_W      -> Seq.fill(4)(vfncvt_x_f.v),
    VFNCVT_F_XU_W     -> Seq.fill(4)(vfncvt_f_xu.v),
    VFNCVT_F_X_W      -> Seq.fill(4)(vfncvt_f_x.v),
    VFNCVT_F_F_W      -> Seq.fill(4)(vfncvt_f_f.v),
    VFNCVT_ROD_F_F_W  -> Seq.fill(4)(vfncvt_f_f_rod.v),
    VFNCVT_RTZ_XU_F_W -> Seq.fill(4)(vfncvt_xu_f_rtz.v),
    VFNCVT_RTZ_X_F_W  -> Seq.fill(4)(vfncvt_x_f_rtz.v),

    VFWCVT_XU_F_V     -> Seq.fill(4)(vfwcvt_xu_f.v),
    VFWCVT_X_F_V      -> Seq.fill(4)(vfwcvt_x_f.v),
    VFWCVT_F_XU_V     -> Seq.fill(4)(vfwcvt_f_xu.v),
    VFWCVT_F_X_V      -> Seq.fill(4)(vfwcvt_f_x.v),
    VFWCVT_F_F_V      -> Seq.fill(4)(vfwcvt_f_f.v),
    VFWCVT_RTZ_XU_F_V -> Seq.fill(4)(vfwcvt_xu_f_rtz.v),
    VFWCVT_RTZ_X_F_V  -> Seq.fill(4)(vfwcvt_x_f_rtz.v),
    VFWADD_VV         -> Seq.fill(4)(vfwadd.vv),
    VFWADD_VF         -> Seq.fill(4)(vfwadd.vf),
    VFWSUB_VV         -> Seq.fill(4)(vfwsub.vv),
    VFWSUB_VF         -> Seq.fill(4)(vfwsub.vf),
    VFWADD_WV         -> Seq.fill(4)(vfwadd_w.vv),
    VFWADD_WF         -> Seq.fill(4)(vfwadd_w.vf),
    VFWSUB_WV         -> Seq.fill(4)(vfwsub_w.vv),
    VFWSUB_WF         -> Seq.fill(4)(vfwsub_w.vf),
    VFWMUL_VV         -> Seq.fill(4)(vfwmul.vv),
    VFWMUL_VF         -> Seq.fill(4)(vfwmul.vf),
    VFWMACC_VV        -> Seq.fill(4)(vfwmacc.vv),
    VFWMACC_VF        -> Seq.fill(4)(vfwmacc.vf),
    VFWNMACC_VV       -> Seq.fill(4)(vfwnmacc.vv),
    VFWNMACC_VF       -> Seq.fill(4)(vfwnmacc.vf),
    VFWMSAC_VV        -> Seq.fill(4)(vfwmsac.vv),
    VFWMSAC_VF        -> Seq.fill(4)(vfwmsac.vf),
    VFWNMSAC_VV       -> Seq.fill(4)(vfwnmsac.vv),
    VFWNMSAC_VF       -> Seq.fill(4)(vfwnmsac.vf),

    VFSLIDE1UP_VF   -> Seq.fill(2)(vslide1up.vf),
    VFSLIDE1DOWN_VF -> Seq.fill(2)(vslide1down.vf),
    VFREDUSUM_VS -> Seq(
      vfadd.vv.src12Mask,
      vfredosum.vv.noMask,
    ),
    VFREDOSUM_VS -> Seq(
      vfredosum.vv.src2Mask,
      vfredosum.vv.src2Mask,
    ),
    VFREDMIN_VS  -> Seq(
      vfmin.vv.src12Mask,
      vfredmin.vv.noMask,
    ),
    VFREDMAX_VS  -> Seq(
      vfmax.vv.src12Mask,
      vfredmax.vv.noMask,
    ),
    VFWREDUSUM_VS -> Seq(
      vfwadd.vv.src12Mask,
      vfwadd_w.vv.src2Mask,
      vfwadd_w.vv.src2Mask,
      vfwredosum.vv.noMask,
    ),
    VFWREDOSUM_VS -> Seq(
      vfwredosum.vv.src2Mask,
      vfwredosum.vv.src2Mask,
      vfwredosum.vv.src2Mask,
      vfwredosum.vv.src2Mask,
    ),
  )

  val opfTable4: Map[BitPat, Seq[UopBase]] = Map(
    // VRFUNARY0
    VFMV_S_F -> (Seq(
      vmvF2S.f,
    ) ++ Seq.fill(3)(vtail)),

    VFNCVT_XU_F_W     -> Seq.fill(8)(vfncvt_xu_f.v),
    VFNCVT_X_F_W      -> Seq.fill(8)(vfncvt_x_f.v),
    VFNCVT_F_XU_W     -> Seq.fill(8)(vfncvt_f_xu.v),
    VFNCVT_F_X_W      -> Seq.fill(8)(vfncvt_f_x.v),
    VFNCVT_F_F_W      -> Seq.fill(8)(vfncvt_f_f.v),
    VFNCVT_ROD_F_F_W  -> Seq.fill(8)(vfncvt_f_f_rod.v),
    VFNCVT_RTZ_XU_F_W -> Seq.fill(8)(vfncvt_xu_f_rtz.v),
    VFNCVT_RTZ_X_F_W  -> Seq.fill(8)(vfncvt_x_f_rtz.v),

    VFWCVT_XU_F_V     -> Seq.fill(8)(vfwcvt_xu_f.v),
    VFWCVT_X_F_V      -> Seq.fill(8)(vfwcvt_x_f.v),
    VFWCVT_F_XU_V     -> Seq.fill(8)(vfwcvt_f_xu.v),
    VFWCVT_F_X_V      -> Seq.fill(8)(vfwcvt_f_x.v),
    VFWCVT_F_F_V      -> Seq.fill(8)(vfwcvt_f_f.v),
    VFWCVT_RTZ_XU_F_V -> Seq.fill(8)(vfwcvt_xu_f_rtz.v),
    VFWCVT_RTZ_X_F_V  -> Seq.fill(8)(vfwcvt_x_f_rtz.v),

    VFWADD_VV         -> Seq.fill(8)(vfwadd.vv),
    VFWADD_VF         -> Seq.fill(8)(vfwadd.vf),
    VFWSUB_VV         -> Seq.fill(8)(vfwsub.vv),
    VFWSUB_VF         -> Seq.fill(8)(vfwsub.vf),
    VFWADD_WV         -> Seq.fill(8)(vfwadd_w.vv),
    VFWADD_WF         -> Seq.fill(8)(vfwadd_w.vf),
    VFWSUB_WV         -> Seq.fill(8)(vfwsub_w.vv),
    VFWSUB_WF         -> Seq.fill(8)(vfwsub_w.vf),
    VFWMUL_VV         -> Seq.fill(8)(vfwmul.vv),
    VFWMUL_VF         -> Seq.fill(8)(vfwmul.vf),
    VFWMACC_VV        -> Seq.fill(8)(vfwmacc.vv),
    VFWMACC_VF        -> Seq.fill(8)(vfwmacc.vf),
    VFWNMACC_VV       -> Seq.fill(8)(vfwnmacc.vv),
    VFWNMACC_VF       -> Seq.fill(8)(vfwnmacc.vf),
    VFWMSAC_VV        -> Seq.fill(8)(vfwmsac.vv),
    VFWMSAC_VF        -> Seq.fill(8)(vfwmsac.vf),
    VFWNMSAC_VV       -> Seq.fill(8)(vfwnmsac.vv),
    VFWNMSAC_VF       -> Seq.fill(8)(vfwnmsac.vf),

    VFSLIDE1UP_VF   -> Seq.fill(4)(vslide1up.vf),
    VFSLIDE1DOWN_VF -> Seq.fill(4)(vslide1down.vf),
    VFREDUSUM_VS -> Seq(
      vfadd.vv.src12Mask,
      vfadd.vv.src2Mask,
      vfadd.vv.src2Mask,
      vfredosum.vv.noMask,
    ),
    VFREDOSUM_VS -> Seq(
      vfredosum.vv.src2Mask,
      vfredosum.vv.src2Mask,
      vfredosum.vv.src2Mask,
      vfredosum.vv.src2Mask,
    ),
    VFREDMIN_VS  -> Seq(
      vfmin.vv.src12Mask,
      vfmin.vv.src2Mask,
      vfmin.vv.src2Mask,
      vfredmin.vv.noMask,
    ),
    VFREDMAX_VS  -> Seq(
      vfmax.vv.src12Mask,
      vfmax.vv.src2Mask,
      vfmax.vv.src2Mask,
      vfredmax.vv.noMask,
    ),
    VFWREDUSUM_VS -> Seq(
      vfwadd.vv.src12Mask,
      vfwadd_w.vv.src2Mask,
      vfwadd_w.vv.src2Mask,
      vfwadd_w.vv.src2Mask,
      vfwadd_w.vv.src2Mask,
      vfwadd_w.vv.src2Mask,
      vfwadd_w.vv.src2Mask,
      vfwredosum.vv.noMask,
    ),
    VFWREDOSUM_VS -> Seq(
      vfwredosum.vv.src2Mask,
      vfwredosum.vv.src2Mask,
      vfwredosum.vv.src2Mask,
      vfwredosum.vv.src2Mask,
      vfwredosum.vv.src2Mask,
      vfwredosum.vv.src2Mask,
      vfwredosum.vv.src2Mask,
      vfwredosum.vv.src2Mask,
    ),
  )

  val opfTable8: Map[BitPat, Seq[UopBase]] = Map(
    // VRFUNARY0
    VFMV_S_F -> (Seq(
      vmvF2S.f,
    ) ++ Seq.fill(7)(vtail)),

    VFNCVT_XU_F_W     -> Seq(),
    VFNCVT_X_F_W      -> Seq(),
    VFNCVT_F_XU_W     -> Seq(),
    VFNCVT_F_X_W      -> Seq(),
    VFNCVT_F_F_W      -> Seq(),
    VFNCVT_ROD_F_F_W  -> Seq(),
    VFNCVT_RTZ_XU_F_W -> Seq(),
    VFNCVT_RTZ_X_F_W  -> Seq(),

    VFWCVT_XU_F_V     -> Seq(),
    VFWCVT_X_F_V      -> Seq(),
    VFWCVT_F_XU_V     -> Seq(),
    VFWCVT_F_X_V      -> Seq(),
    VFWCVT_F_F_V      -> Seq(),
    VFWCVT_RTZ_XU_F_V -> Seq(),
    VFWCVT_RTZ_X_F_V  -> Seq(),

    VFWADD_VV         -> Seq(),
    VFWADD_VF         -> Seq(),
    VFWSUB_VV         -> Seq(),
    VFWSUB_VF         -> Seq(),
    VFWADD_WV         -> Seq(),
    VFWADD_WF         -> Seq(),
    VFWSUB_WV         -> Seq(),
    VFWSUB_WF         -> Seq(),
    VFWMUL_VV         -> Seq(),
    VFWMUL_VF         -> Seq(),
    VFWMACC_VV        -> Seq(),
    VFWMACC_VF        -> Seq(),
    VFWNMACC_VV       -> Seq(),
    VFWNMACC_VF       -> Seq(),
    VFWMSAC_VV        -> Seq(),
    VFWMSAC_VF        -> Seq(),
    VFWNMSAC_VV       -> Seq(),
    VFWNMSAC_VF       -> Seq(),

    VFSLIDE1UP_VF   -> Seq.fill(8)(vslide1up.vf),
    VFSLIDE1DOWN_VF -> Seq.fill(8)(vslide1down.vf),
    VFREDUSUM_VS -> Seq(
      vfadd.vv.src12Mask,
      vfadd.vv.src2Mask,
      vfadd.vv.src2Mask,
      vfadd.vv.src2Mask,
      vfadd.vv.src2Mask,
      vfadd.vv.src2Mask,
      vfadd.vv.src2Mask,
      vfredosum.vv.noMask,
    ),
    VFREDOSUM_VS -> Seq(
      vfredosum.vv.src2Mask,
      vfredosum.vv.src2Mask,
      vfredosum.vv.src2Mask,
      vfredosum.vv.src2Mask,
      vfredosum.vv.src2Mask,
      vfredosum.vv.src2Mask,
      vfredosum.vv.src2Mask,
      vfredosum.vv.src2Mask,
    ),
    VFREDMIN_VS  -> Seq(
      vfmin.vv.src12Mask,
      vfmin.vv.src2Mask,
      vfmin.vv.src2Mask,
      vfmin.vv.src2Mask,
      vfmin.vv.src2Mask,
      vfmin.vv.src2Mask,
      vfmin.vv.src2Mask,
      vfredmin.vv.noMask,
    ),
    VFREDMAX_VS  -> Seq(
      vfmax.vv.src12Mask,
      vfmax.vv.src2Mask,
      vfmax.vv.src2Mask,
      vfmax.vv.src2Mask,
      vfmax.vv.src2Mask,
      vfmax.vv.src2Mask,
      vfmax.vv.src2Mask,
      vfredmax.vv.noMask,
    ),
    VFWREDUSUM_VS -> Seq(),
    VFWREDOSUM_VS -> Seq(),
  )

  val dupTable = opiDupTable ++ opmDupTable ++ opfDupTable

  val lmulUnrelatedTable = opiLmulUnrelatedTable ++ opmLmulUnrelatedTable ++ opfLmulUnrelatedTable

  val lmul8Table: Map[BitPat, Seq[UopBase]] = opiTable8 ++ opmTable8 ++ opfTable8

  val lmul4Table: Map[BitPat, Seq[UopBase]] = opiTable4 ++ opmTable4 ++ opfTable4

  val lmul2Table: Map[BitPat, Seq[UopBase]] = opiTable2 ++ opmTable2 ++ opfTable2

  val lmul1Table: Map[BitPat, Seq[UopBase]] = opiTable1 ++ opmTable1 ++ opfTable1

  val lmulF2Table: Map[BitPat, Seq[UopBase]] = opiTableF2 ++ opmTableF2 ++ opfTableF2
}
