//=========================================================
//File name    : lintsissue_agent_agent_interface.sv
//Author       : OpenAI_Codex
//Module name  : lintsissue_agent_agent_interface
//Discribution : lintsissue_agent_agent_interface : signal interface
//Date         : 2026-04-12
//=========================================================
`ifndef LINTSISSUE_AGENT_AGENT_INTERFACE__SV
`define LINTSISSUE_AGENT_AGENT_INTERFACE__SV

`ifndef DEF_SETUP_TIME
    `define DEF_SETUP_TIME 1
`endif
`ifndef DEF_HOLD_TIME
    `define DEF_HOLD_TIME 1
`endif

interface lintsissue_agent_agent_interface  (input bit clk,input bit rst_n);

    logic io_ooo_to_mem_intIssue_6_0_ready;
    logic io_ooo_to_mem_intIssue_6_0_valid;
    logic [35:0] io_ooo_to_mem_intIssue_6_0_bits_fuType;
    logic [8:0] io_ooo_to_mem_intIssue_6_0_bits_fuOpType;
    logic [63:0] io_ooo_to_mem_intIssue_6_0_bits_src_0;
    logic io_ooo_to_mem_intIssue_6_0_bits_robIdx_flag;
    logic [8:0] io_ooo_to_mem_intIssue_6_0_bits_robIdx_value;
    logic io_ooo_to_mem_intIssue_6_0_bits_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_intIssue_6_0_bits_sqIdx_value;
    logic io_ooo_to_mem_intIssue_5_0_ready;
    logic io_ooo_to_mem_intIssue_5_0_valid;
    logic [35:0] io_ooo_to_mem_intIssue_5_0_bits_fuType;
    logic [8:0] io_ooo_to_mem_intIssue_5_0_bits_fuOpType;
    logic [63:0] io_ooo_to_mem_intIssue_5_0_bits_src_0;
    logic io_ooo_to_mem_intIssue_5_0_bits_robIdx_flag;
    logic [8:0] io_ooo_to_mem_intIssue_5_0_bits_robIdx_value;
    logic io_ooo_to_mem_intIssue_5_0_bits_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_intIssue_5_0_bits_sqIdx_value;
    logic io_ooo_to_mem_intIssue_4_0_ready;
    logic io_ooo_to_mem_intIssue_4_0_valid;
    logic [35:0] io_ooo_to_mem_intIssue_4_0_bits_fuType;
    logic [8:0] io_ooo_to_mem_intIssue_4_0_bits_fuOpType;
    logic [63:0] io_ooo_to_mem_intIssue_4_0_bits_src_0;
    logic [63:0] io_ooo_to_mem_intIssue_4_0_bits_imm;
    logic io_ooo_to_mem_intIssue_4_0_bits_robIdx_flag;
    logic [8:0] io_ooo_to_mem_intIssue_4_0_bits_robIdx_value;
    logic io_ooo_to_mem_intIssue_4_0_bits_isFirstIssue;
    logic [7:0] io_ooo_to_mem_intIssue_4_0_bits_pdest;
    logic io_ooo_to_mem_intIssue_4_0_bits_isRVC;
    logic io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_flag;
    logic [5:0] io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_value;
    logic [4:0] io_ooo_to_mem_intIssue_4_0_bits_ftqOffset;
    logic io_ooo_to_mem_intIssue_4_0_bits_storeSetHit;
    logic [4:0] io_ooo_to_mem_intIssue_4_0_bits_ssid;
    logic io_ooo_to_mem_intIssue_4_0_bits_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_intIssue_4_0_bits_sqIdx_value;
    logic io_ooo_to_mem_intIssue_3_0_ready;
    logic io_ooo_to_mem_intIssue_3_0_valid;
    logic [35:0] io_ooo_to_mem_intIssue_3_0_bits_fuType;
    logic [8:0] io_ooo_to_mem_intIssue_3_0_bits_fuOpType;
    logic [63:0] io_ooo_to_mem_intIssue_3_0_bits_src_0;
    logic [63:0] io_ooo_to_mem_intIssue_3_0_bits_imm;
    logic io_ooo_to_mem_intIssue_3_0_bits_robIdx_flag;
    logic [8:0] io_ooo_to_mem_intIssue_3_0_bits_robIdx_value;
    logic io_ooo_to_mem_intIssue_3_0_bits_isFirstIssue;
    logic [7:0] io_ooo_to_mem_intIssue_3_0_bits_pdest;
    logic io_ooo_to_mem_intIssue_3_0_bits_isRVC;
    logic io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_flag;
    logic [5:0] io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_value;
    logic [4:0] io_ooo_to_mem_intIssue_3_0_bits_ftqOffset;
    logic io_ooo_to_mem_intIssue_3_0_bits_storeSetHit;
    logic [4:0] io_ooo_to_mem_intIssue_3_0_bits_ssid;
    logic io_ooo_to_mem_intIssue_3_0_bits_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_intIssue_3_0_bits_sqIdx_value;
    logic io_ooo_to_mem_intIssue_2_0_ready;
    logic io_ooo_to_mem_intIssue_2_0_valid;
    logic [8:0] io_ooo_to_mem_intIssue_2_0_bits_fuOpType;
    logic [63:0] io_ooo_to_mem_intIssue_2_0_bits_src_0;
    logic [63:0] io_ooo_to_mem_intIssue_2_0_bits_imm;
    logic io_ooo_to_mem_intIssue_2_0_bits_robIdx_flag;
    logic [8:0] io_ooo_to_mem_intIssue_2_0_bits_robIdx_value;
    logic [7:0] io_ooo_to_mem_intIssue_2_0_bits_pdest;
    logic io_ooo_to_mem_intIssue_2_0_bits_rfWen;
    logic io_ooo_to_mem_intIssue_2_0_bits_fpWen;
    logic [49:0] io_ooo_to_mem_intIssue_2_0_bits_pc;
    logic io_ooo_to_mem_intIssue_2_0_bits_isRVC;
    logic io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_flag;
    logic [5:0] io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_value;
    logic [4:0] io_ooo_to_mem_intIssue_2_0_bits_ftqOffset;
    logic io_ooo_to_mem_intIssue_2_0_bits_loadWaitBit;
    logic io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_flag;
    logic [8:0] io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_value;
    logic io_ooo_to_mem_intIssue_2_0_bits_storeSetHit;
    logic io_ooo_to_mem_intIssue_2_0_bits_loadWaitStrict;
    logic io_ooo_to_mem_intIssue_2_0_bits_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_intIssue_2_0_bits_lqIdx_value;
    logic io_ooo_to_mem_intIssue_2_0_bits_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_intIssue_2_0_bits_sqIdx_value;
    logic io_ooo_to_mem_intIssue_1_0_ready;
    logic io_ooo_to_mem_intIssue_1_0_valid;
    logic [8:0] io_ooo_to_mem_intIssue_1_0_bits_fuOpType;
    logic [63:0] io_ooo_to_mem_intIssue_1_0_bits_src_0;
    logic [63:0] io_ooo_to_mem_intIssue_1_0_bits_imm;
    logic io_ooo_to_mem_intIssue_1_0_bits_robIdx_flag;
    logic [8:0] io_ooo_to_mem_intIssue_1_0_bits_robIdx_value;
    logic [7:0] io_ooo_to_mem_intIssue_1_0_bits_pdest;
    logic io_ooo_to_mem_intIssue_1_0_bits_rfWen;
    logic io_ooo_to_mem_intIssue_1_0_bits_fpWen;
    logic [49:0] io_ooo_to_mem_intIssue_1_0_bits_pc;
    logic io_ooo_to_mem_intIssue_1_0_bits_isRVC;
    logic io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_flag;
    logic [5:0] io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_value;
    logic [4:0] io_ooo_to_mem_intIssue_1_0_bits_ftqOffset;
    logic io_ooo_to_mem_intIssue_1_0_bits_loadWaitBit;
    logic io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_flag;
    logic [8:0] io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_value;
    logic io_ooo_to_mem_intIssue_1_0_bits_storeSetHit;
    logic io_ooo_to_mem_intIssue_1_0_bits_loadWaitStrict;
    logic io_ooo_to_mem_intIssue_1_0_bits_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_intIssue_1_0_bits_lqIdx_value;
    logic io_ooo_to_mem_intIssue_1_0_bits_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_intIssue_1_0_bits_sqIdx_value;
    logic io_ooo_to_mem_intIssue_0_0_ready;
    logic io_ooo_to_mem_intIssue_0_0_valid;
    logic [8:0] io_ooo_to_mem_intIssue_0_0_bits_fuOpType;
    logic [63:0] io_ooo_to_mem_intIssue_0_0_bits_src_0;
    logic [63:0] io_ooo_to_mem_intIssue_0_0_bits_imm;
    logic io_ooo_to_mem_intIssue_0_0_bits_robIdx_flag;
    logic [8:0] io_ooo_to_mem_intIssue_0_0_bits_robIdx_value;
    logic [7:0] io_ooo_to_mem_intIssue_0_0_bits_pdest;
    logic io_ooo_to_mem_intIssue_0_0_bits_rfWen;
    logic io_ooo_to_mem_intIssue_0_0_bits_fpWen;
    logic [49:0] io_ooo_to_mem_intIssue_0_0_bits_pc;
    logic io_ooo_to_mem_intIssue_0_0_bits_isRVC;
    logic io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_flag;
    logic [5:0] io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_value;
    logic [4:0] io_ooo_to_mem_intIssue_0_0_bits_ftqOffset;
    logic io_ooo_to_mem_intIssue_0_0_bits_loadWaitBit;
    logic io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_flag;
    logic [8:0] io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_value;
    logic io_ooo_to_mem_intIssue_0_0_bits_storeSetHit;
    logic io_ooo_to_mem_intIssue_0_0_bits_loadWaitStrict;
    logic io_ooo_to_mem_intIssue_0_0_bits_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_intIssue_0_0_bits_lqIdx_value;
    logic io_ooo_to_mem_intIssue_0_0_bits_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_intIssue_0_0_bits_sqIdx_value;

    clocking drv_cb @(posedge clk);
        `ifdef INTERFACE_ADD_DELAY
            default input #`DEF_SETUP_TIME output #`DEF_HOLD_TIME;
        `endif
        input  io_ooo_to_mem_intIssue_6_0_ready;
        output io_ooo_to_mem_intIssue_6_0_valid;
        output io_ooo_to_mem_intIssue_6_0_bits_fuType;
        output io_ooo_to_mem_intIssue_6_0_bits_fuOpType;
        output io_ooo_to_mem_intIssue_6_0_bits_src_0;
        output io_ooo_to_mem_intIssue_6_0_bits_robIdx_flag;
        output io_ooo_to_mem_intIssue_6_0_bits_robIdx_value;
        output io_ooo_to_mem_intIssue_6_0_bits_sqIdx_flag;
        output io_ooo_to_mem_intIssue_6_0_bits_sqIdx_value;
        input  io_ooo_to_mem_intIssue_5_0_ready;
        output io_ooo_to_mem_intIssue_5_0_valid;
        output io_ooo_to_mem_intIssue_5_0_bits_fuType;
        output io_ooo_to_mem_intIssue_5_0_bits_fuOpType;
        output io_ooo_to_mem_intIssue_5_0_bits_src_0;
        output io_ooo_to_mem_intIssue_5_0_bits_robIdx_flag;
        output io_ooo_to_mem_intIssue_5_0_bits_robIdx_value;
        output io_ooo_to_mem_intIssue_5_0_bits_sqIdx_flag;
        output io_ooo_to_mem_intIssue_5_0_bits_sqIdx_value;
        input  io_ooo_to_mem_intIssue_4_0_ready;
        output io_ooo_to_mem_intIssue_4_0_valid;
        output io_ooo_to_mem_intIssue_4_0_bits_fuType;
        output io_ooo_to_mem_intIssue_4_0_bits_fuOpType;
        output io_ooo_to_mem_intIssue_4_0_bits_src_0;
        output io_ooo_to_mem_intIssue_4_0_bits_imm;
        output io_ooo_to_mem_intIssue_4_0_bits_robIdx_flag;
        output io_ooo_to_mem_intIssue_4_0_bits_robIdx_value;
        output io_ooo_to_mem_intIssue_4_0_bits_isFirstIssue;
        output io_ooo_to_mem_intIssue_4_0_bits_pdest;
        output io_ooo_to_mem_intIssue_4_0_bits_isRVC;
        output io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_flag;
        output io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_value;
        output io_ooo_to_mem_intIssue_4_0_bits_ftqOffset;
        output io_ooo_to_mem_intIssue_4_0_bits_storeSetHit;
        output io_ooo_to_mem_intIssue_4_0_bits_ssid;
        output io_ooo_to_mem_intIssue_4_0_bits_sqIdx_flag;
        output io_ooo_to_mem_intIssue_4_0_bits_sqIdx_value;
        input  io_ooo_to_mem_intIssue_3_0_ready;
        output io_ooo_to_mem_intIssue_3_0_valid;
        output io_ooo_to_mem_intIssue_3_0_bits_fuType;
        output io_ooo_to_mem_intIssue_3_0_bits_fuOpType;
        output io_ooo_to_mem_intIssue_3_0_bits_src_0;
        output io_ooo_to_mem_intIssue_3_0_bits_imm;
        output io_ooo_to_mem_intIssue_3_0_bits_robIdx_flag;
        output io_ooo_to_mem_intIssue_3_0_bits_robIdx_value;
        output io_ooo_to_mem_intIssue_3_0_bits_isFirstIssue;
        output io_ooo_to_mem_intIssue_3_0_bits_pdest;
        output io_ooo_to_mem_intIssue_3_0_bits_isRVC;
        output io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_flag;
        output io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_value;
        output io_ooo_to_mem_intIssue_3_0_bits_ftqOffset;
        output io_ooo_to_mem_intIssue_3_0_bits_storeSetHit;
        output io_ooo_to_mem_intIssue_3_0_bits_ssid;
        output io_ooo_to_mem_intIssue_3_0_bits_sqIdx_flag;
        output io_ooo_to_mem_intIssue_3_0_bits_sqIdx_value;
        input  io_ooo_to_mem_intIssue_2_0_ready;
        output io_ooo_to_mem_intIssue_2_0_valid;
        output io_ooo_to_mem_intIssue_2_0_bits_fuOpType;
        output io_ooo_to_mem_intIssue_2_0_bits_src_0;
        output io_ooo_to_mem_intIssue_2_0_bits_imm;
        output io_ooo_to_mem_intIssue_2_0_bits_robIdx_flag;
        output io_ooo_to_mem_intIssue_2_0_bits_robIdx_value;
        output io_ooo_to_mem_intIssue_2_0_bits_pdest;
        output io_ooo_to_mem_intIssue_2_0_bits_rfWen;
        output io_ooo_to_mem_intIssue_2_0_bits_fpWen;
        output io_ooo_to_mem_intIssue_2_0_bits_pc;
        output io_ooo_to_mem_intIssue_2_0_bits_isRVC;
        output io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_flag;
        output io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_value;
        output io_ooo_to_mem_intIssue_2_0_bits_ftqOffset;
        output io_ooo_to_mem_intIssue_2_0_bits_loadWaitBit;
        output io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_flag;
        output io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_value;
        output io_ooo_to_mem_intIssue_2_0_bits_storeSetHit;
        output io_ooo_to_mem_intIssue_2_0_bits_loadWaitStrict;
        output io_ooo_to_mem_intIssue_2_0_bits_lqIdx_flag;
        output io_ooo_to_mem_intIssue_2_0_bits_lqIdx_value;
        output io_ooo_to_mem_intIssue_2_0_bits_sqIdx_flag;
        output io_ooo_to_mem_intIssue_2_0_bits_sqIdx_value;
        input  io_ooo_to_mem_intIssue_1_0_ready;
        output io_ooo_to_mem_intIssue_1_0_valid;
        output io_ooo_to_mem_intIssue_1_0_bits_fuOpType;
        output io_ooo_to_mem_intIssue_1_0_bits_src_0;
        output io_ooo_to_mem_intIssue_1_0_bits_imm;
        output io_ooo_to_mem_intIssue_1_0_bits_robIdx_flag;
        output io_ooo_to_mem_intIssue_1_0_bits_robIdx_value;
        output io_ooo_to_mem_intIssue_1_0_bits_pdest;
        output io_ooo_to_mem_intIssue_1_0_bits_rfWen;
        output io_ooo_to_mem_intIssue_1_0_bits_fpWen;
        output io_ooo_to_mem_intIssue_1_0_bits_pc;
        output io_ooo_to_mem_intIssue_1_0_bits_isRVC;
        output io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_flag;
        output io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_value;
        output io_ooo_to_mem_intIssue_1_0_bits_ftqOffset;
        output io_ooo_to_mem_intIssue_1_0_bits_loadWaitBit;
        output io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_flag;
        output io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_value;
        output io_ooo_to_mem_intIssue_1_0_bits_storeSetHit;
        output io_ooo_to_mem_intIssue_1_0_bits_loadWaitStrict;
        output io_ooo_to_mem_intIssue_1_0_bits_lqIdx_flag;
        output io_ooo_to_mem_intIssue_1_0_bits_lqIdx_value;
        output io_ooo_to_mem_intIssue_1_0_bits_sqIdx_flag;
        output io_ooo_to_mem_intIssue_1_0_bits_sqIdx_value;
        input  io_ooo_to_mem_intIssue_0_0_ready;
        output io_ooo_to_mem_intIssue_0_0_valid;
        output io_ooo_to_mem_intIssue_0_0_bits_fuOpType;
        output io_ooo_to_mem_intIssue_0_0_bits_src_0;
        output io_ooo_to_mem_intIssue_0_0_bits_imm;
        output io_ooo_to_mem_intIssue_0_0_bits_robIdx_flag;
        output io_ooo_to_mem_intIssue_0_0_bits_robIdx_value;
        output io_ooo_to_mem_intIssue_0_0_bits_pdest;
        output io_ooo_to_mem_intIssue_0_0_bits_rfWen;
        output io_ooo_to_mem_intIssue_0_0_bits_fpWen;
        output io_ooo_to_mem_intIssue_0_0_bits_pc;
        output io_ooo_to_mem_intIssue_0_0_bits_isRVC;
        output io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_flag;
        output io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_value;
        output io_ooo_to_mem_intIssue_0_0_bits_ftqOffset;
        output io_ooo_to_mem_intIssue_0_0_bits_loadWaitBit;
        output io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_flag;
        output io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_value;
        output io_ooo_to_mem_intIssue_0_0_bits_storeSetHit;
        output io_ooo_to_mem_intIssue_0_0_bits_loadWaitStrict;
        output io_ooo_to_mem_intIssue_0_0_bits_lqIdx_flag;
        output io_ooo_to_mem_intIssue_0_0_bits_lqIdx_value;
        output io_ooo_to_mem_intIssue_0_0_bits_sqIdx_flag;
        output io_ooo_to_mem_intIssue_0_0_bits_sqIdx_value;

    endclocking:drv_cb

    clocking mon_cb @(posedge clk);
        `ifdef INTERFACE_ADD_DELAY
            default input #`DEF_SETUP_TIME output #`DEF_HOLD_TIME;
        `endif
        input  io_ooo_to_mem_intIssue_6_0_ready;
        input  io_ooo_to_mem_intIssue_6_0_valid;
        input  io_ooo_to_mem_intIssue_6_0_bits_fuType;
        input  io_ooo_to_mem_intIssue_6_0_bits_fuOpType;
        input  io_ooo_to_mem_intIssue_6_0_bits_src_0;
        input  io_ooo_to_mem_intIssue_6_0_bits_robIdx_flag;
        input  io_ooo_to_mem_intIssue_6_0_bits_robIdx_value;
        input  io_ooo_to_mem_intIssue_6_0_bits_sqIdx_flag;
        input  io_ooo_to_mem_intIssue_6_0_bits_sqIdx_value;
        input  io_ooo_to_mem_intIssue_5_0_ready;
        input  io_ooo_to_mem_intIssue_5_0_valid;
        input  io_ooo_to_mem_intIssue_5_0_bits_fuType;
        input  io_ooo_to_mem_intIssue_5_0_bits_fuOpType;
        input  io_ooo_to_mem_intIssue_5_0_bits_src_0;
        input  io_ooo_to_mem_intIssue_5_0_bits_robIdx_flag;
        input  io_ooo_to_mem_intIssue_5_0_bits_robIdx_value;
        input  io_ooo_to_mem_intIssue_5_0_bits_sqIdx_flag;
        input  io_ooo_to_mem_intIssue_5_0_bits_sqIdx_value;
        input  io_ooo_to_mem_intIssue_4_0_ready;
        input  io_ooo_to_mem_intIssue_4_0_valid;
        input  io_ooo_to_mem_intIssue_4_0_bits_fuType;
        input  io_ooo_to_mem_intIssue_4_0_bits_fuOpType;
        input  io_ooo_to_mem_intIssue_4_0_bits_src_0;
        input  io_ooo_to_mem_intIssue_4_0_bits_imm;
        input  io_ooo_to_mem_intIssue_4_0_bits_robIdx_flag;
        input  io_ooo_to_mem_intIssue_4_0_bits_robIdx_value;
        input  io_ooo_to_mem_intIssue_4_0_bits_isFirstIssue;
        input  io_ooo_to_mem_intIssue_4_0_bits_pdest;
        input  io_ooo_to_mem_intIssue_4_0_bits_isRVC;
        input  io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_flag;
        input  io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_value;
        input  io_ooo_to_mem_intIssue_4_0_bits_ftqOffset;
        input  io_ooo_to_mem_intIssue_4_0_bits_storeSetHit;
        input  io_ooo_to_mem_intIssue_4_0_bits_ssid;
        input  io_ooo_to_mem_intIssue_4_0_bits_sqIdx_flag;
        input  io_ooo_to_mem_intIssue_4_0_bits_sqIdx_value;
        input  io_ooo_to_mem_intIssue_3_0_ready;
        input  io_ooo_to_mem_intIssue_3_0_valid;
        input  io_ooo_to_mem_intIssue_3_0_bits_fuType;
        input  io_ooo_to_mem_intIssue_3_0_bits_fuOpType;
        input  io_ooo_to_mem_intIssue_3_0_bits_src_0;
        input  io_ooo_to_mem_intIssue_3_0_bits_imm;
        input  io_ooo_to_mem_intIssue_3_0_bits_robIdx_flag;
        input  io_ooo_to_mem_intIssue_3_0_bits_robIdx_value;
        input  io_ooo_to_mem_intIssue_3_0_bits_isFirstIssue;
        input  io_ooo_to_mem_intIssue_3_0_bits_pdest;
        input  io_ooo_to_mem_intIssue_3_0_bits_isRVC;
        input  io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_flag;
        input  io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_value;
        input  io_ooo_to_mem_intIssue_3_0_bits_ftqOffset;
        input  io_ooo_to_mem_intIssue_3_0_bits_storeSetHit;
        input  io_ooo_to_mem_intIssue_3_0_bits_ssid;
        input  io_ooo_to_mem_intIssue_3_0_bits_sqIdx_flag;
        input  io_ooo_to_mem_intIssue_3_0_bits_sqIdx_value;
        input  io_ooo_to_mem_intIssue_2_0_ready;
        input  io_ooo_to_mem_intIssue_2_0_valid;
        input  io_ooo_to_mem_intIssue_2_0_bits_fuOpType;
        input  io_ooo_to_mem_intIssue_2_0_bits_src_0;
        input  io_ooo_to_mem_intIssue_2_0_bits_imm;
        input  io_ooo_to_mem_intIssue_2_0_bits_robIdx_flag;
        input  io_ooo_to_mem_intIssue_2_0_bits_robIdx_value;
        input  io_ooo_to_mem_intIssue_2_0_bits_pdest;
        input  io_ooo_to_mem_intIssue_2_0_bits_rfWen;
        input  io_ooo_to_mem_intIssue_2_0_bits_fpWen;
        input  io_ooo_to_mem_intIssue_2_0_bits_pc;
        input  io_ooo_to_mem_intIssue_2_0_bits_isRVC;
        input  io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_flag;
        input  io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_value;
        input  io_ooo_to_mem_intIssue_2_0_bits_ftqOffset;
        input  io_ooo_to_mem_intIssue_2_0_bits_loadWaitBit;
        input  io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_flag;
        input  io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_value;
        input  io_ooo_to_mem_intIssue_2_0_bits_storeSetHit;
        input  io_ooo_to_mem_intIssue_2_0_bits_loadWaitStrict;
        input  io_ooo_to_mem_intIssue_2_0_bits_lqIdx_flag;
        input  io_ooo_to_mem_intIssue_2_0_bits_lqIdx_value;
        input  io_ooo_to_mem_intIssue_2_0_bits_sqIdx_flag;
        input  io_ooo_to_mem_intIssue_2_0_bits_sqIdx_value;
        input  io_ooo_to_mem_intIssue_1_0_ready;
        input  io_ooo_to_mem_intIssue_1_0_valid;
        input  io_ooo_to_mem_intIssue_1_0_bits_fuOpType;
        input  io_ooo_to_mem_intIssue_1_0_bits_src_0;
        input  io_ooo_to_mem_intIssue_1_0_bits_imm;
        input  io_ooo_to_mem_intIssue_1_0_bits_robIdx_flag;
        input  io_ooo_to_mem_intIssue_1_0_bits_robIdx_value;
        input  io_ooo_to_mem_intIssue_1_0_bits_pdest;
        input  io_ooo_to_mem_intIssue_1_0_bits_rfWen;
        input  io_ooo_to_mem_intIssue_1_0_bits_fpWen;
        input  io_ooo_to_mem_intIssue_1_0_bits_pc;
        input  io_ooo_to_mem_intIssue_1_0_bits_isRVC;
        input  io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_flag;
        input  io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_value;
        input  io_ooo_to_mem_intIssue_1_0_bits_ftqOffset;
        input  io_ooo_to_mem_intIssue_1_0_bits_loadWaitBit;
        input  io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_flag;
        input  io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_value;
        input  io_ooo_to_mem_intIssue_1_0_bits_storeSetHit;
        input  io_ooo_to_mem_intIssue_1_0_bits_loadWaitStrict;
        input  io_ooo_to_mem_intIssue_1_0_bits_lqIdx_flag;
        input  io_ooo_to_mem_intIssue_1_0_bits_lqIdx_value;
        input  io_ooo_to_mem_intIssue_1_0_bits_sqIdx_flag;
        input  io_ooo_to_mem_intIssue_1_0_bits_sqIdx_value;
        input  io_ooo_to_mem_intIssue_0_0_ready;
        input  io_ooo_to_mem_intIssue_0_0_valid;
        input  io_ooo_to_mem_intIssue_0_0_bits_fuOpType;
        input  io_ooo_to_mem_intIssue_0_0_bits_src_0;
        input  io_ooo_to_mem_intIssue_0_0_bits_imm;
        input  io_ooo_to_mem_intIssue_0_0_bits_robIdx_flag;
        input  io_ooo_to_mem_intIssue_0_0_bits_robIdx_value;
        input  io_ooo_to_mem_intIssue_0_0_bits_pdest;
        input  io_ooo_to_mem_intIssue_0_0_bits_rfWen;
        input  io_ooo_to_mem_intIssue_0_0_bits_fpWen;
        input  io_ooo_to_mem_intIssue_0_0_bits_pc;
        input  io_ooo_to_mem_intIssue_0_0_bits_isRVC;
        input  io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_flag;
        input  io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_value;
        input  io_ooo_to_mem_intIssue_0_0_bits_ftqOffset;
        input  io_ooo_to_mem_intIssue_0_0_bits_loadWaitBit;
        input  io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_flag;
        input  io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_value;
        input  io_ooo_to_mem_intIssue_0_0_bits_storeSetHit;
        input  io_ooo_to_mem_intIssue_0_0_bits_loadWaitStrict;
        input  io_ooo_to_mem_intIssue_0_0_bits_lqIdx_flag;
        input  io_ooo_to_mem_intIssue_0_0_bits_lqIdx_value;
        input  io_ooo_to_mem_intIssue_0_0_bits_sqIdx_flag;
        input  io_ooo_to_mem_intIssue_0_0_bits_sqIdx_value;

    endclocking:mon_cb

    modport drv_mp (clocking drv_cb);
    modport mon_mp (clocking mon_cb);

endinterface:lintsissue_agent_agent_interface

`endif
