//=========================================================
//File name    : lintsissue_agent_agent_interface.sv
//Author       : OpenAI_Codex
//Module name  : lintsissue_agent_agent_interface
//Discribution : lintsissue_agent_agent_interface : signal interface
//Date         : 2026-04-12
//=========================================================
`ifndef LINTSISSUE_AGENT_AGENT_INTERFACE__SV
`define LINTSISSUE_AGENT_AGENT_INTERFACE__SV

`ifndef DEF_SETUP_TIME
    `define DEF_SETUP_TIME 1
`endif
`ifndef DEF_HOLD_TIME
    `define DEF_HOLD_TIME 1
`endif

interface lintsissue_agent_agent_interface  (input bit clk,input bit rst_n);


    logic [63:0] io_ooo_to_mem_issueLda_0_bits_src_0;
    logic io_ooo_to_mem_issueLda_0_bits_uop_fpWen;
    logic [3:0] io_ooo_to_mem_issueLda_0_bits_uop_ftqOffset;
    logic io_ooo_to_mem_issueLda_0_bits_uop_ftqPtr_flag;
    logic [5:0] io_ooo_to_mem_issueLda_0_bits_uop_ftqPtr_value;
    logic [8:0] io_ooo_to_mem_issueLda_0_bits_uop_fuOpType;
    logic [31:0] io_ooo_to_mem_issueLda_0_bits_uop_imm;
    logic io_ooo_to_mem_issueLda_0_bits_uop_loadWaitBit;
    logic io_ooo_to_mem_issueLda_0_bits_uop_loadWaitStrict;
    logic io_ooo_to_mem_issueLda_0_bits_uop_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_issueLda_0_bits_uop_lqIdx_value;
    logic [49:0] io_ooo_to_mem_issueLda_0_bits_uop_pc;
    logic [7:0] io_ooo_to_mem_issueLda_0_bits_uop_pdest;
    logic io_ooo_to_mem_issueLda_0_bits_uop_preDecodeInfo_isRVC;
    logic io_ooo_to_mem_issueLda_0_bits_uop_rfWen;
    logic io_ooo_to_mem_issueLda_0_bits_uop_robIdx_flag;
    logic [7:0] io_ooo_to_mem_issueLda_0_bits_uop_robIdx_value;
    logic io_ooo_to_mem_issueLda_0_bits_uop_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_issueLda_0_bits_uop_sqIdx_value;
    logic io_ooo_to_mem_issueLda_0_bits_uop_storeSetHit;
    logic io_ooo_to_mem_issueLda_0_bits_uop_waitForRobIdx_flag;
    logic [7:0] io_ooo_to_mem_issueLda_0_bits_uop_waitForRobIdx_value;
    logic io_ooo_to_mem_issueLda_0_ready;
    logic io_ooo_to_mem_issueLda_0_valid;
    logic [63:0] io_ooo_to_mem_issueLda_1_bits_src_0;
    logic io_ooo_to_mem_issueLda_1_bits_uop_fpWen;
    logic [3:0] io_ooo_to_mem_issueLda_1_bits_uop_ftqOffset;
    logic io_ooo_to_mem_issueLda_1_bits_uop_ftqPtr_flag;
    logic [5:0] io_ooo_to_mem_issueLda_1_bits_uop_ftqPtr_value;
    logic [8:0] io_ooo_to_mem_issueLda_1_bits_uop_fuOpType;
    logic [31:0] io_ooo_to_mem_issueLda_1_bits_uop_imm;
    logic io_ooo_to_mem_issueLda_1_bits_uop_loadWaitBit;
    logic io_ooo_to_mem_issueLda_1_bits_uop_loadWaitStrict;
    logic io_ooo_to_mem_issueLda_1_bits_uop_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_issueLda_1_bits_uop_lqIdx_value;
    logic [49:0] io_ooo_to_mem_issueLda_1_bits_uop_pc;
    logic [7:0] io_ooo_to_mem_issueLda_1_bits_uop_pdest;
    logic io_ooo_to_mem_issueLda_1_bits_uop_preDecodeInfo_isRVC;
    logic io_ooo_to_mem_issueLda_1_bits_uop_rfWen;
    logic io_ooo_to_mem_issueLda_1_bits_uop_robIdx_flag;
    logic [7:0] io_ooo_to_mem_issueLda_1_bits_uop_robIdx_value;
    logic io_ooo_to_mem_issueLda_1_bits_uop_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_issueLda_1_bits_uop_sqIdx_value;
    logic io_ooo_to_mem_issueLda_1_bits_uop_storeSetHit;
    logic io_ooo_to_mem_issueLda_1_bits_uop_waitForRobIdx_flag;
    logic [7:0] io_ooo_to_mem_issueLda_1_bits_uop_waitForRobIdx_value;
    logic io_ooo_to_mem_issueLda_1_ready;
    logic io_ooo_to_mem_issueLda_1_valid;
    logic [63:0] io_ooo_to_mem_issueLda_2_bits_src_0;
    logic io_ooo_to_mem_issueLda_2_bits_uop_fpWen;
    logic [3:0] io_ooo_to_mem_issueLda_2_bits_uop_ftqOffset;
    logic io_ooo_to_mem_issueLda_2_bits_uop_ftqPtr_flag;
    logic [5:0] io_ooo_to_mem_issueLda_2_bits_uop_ftqPtr_value;
    logic [8:0] io_ooo_to_mem_issueLda_2_bits_uop_fuOpType;
    logic [31:0] io_ooo_to_mem_issueLda_2_bits_uop_imm;
    logic io_ooo_to_mem_issueLda_2_bits_uop_loadWaitBit;
    logic io_ooo_to_mem_issueLda_2_bits_uop_loadWaitStrict;
    logic io_ooo_to_mem_issueLda_2_bits_uop_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_issueLda_2_bits_uop_lqIdx_value;
    logic [49:0] io_ooo_to_mem_issueLda_2_bits_uop_pc;
    logic [7:0] io_ooo_to_mem_issueLda_2_bits_uop_pdest;
    logic io_ooo_to_mem_issueLda_2_bits_uop_preDecodeInfo_isRVC;
    logic io_ooo_to_mem_issueLda_2_bits_uop_rfWen;
    logic io_ooo_to_mem_issueLda_2_bits_uop_robIdx_flag;
    logic [7:0] io_ooo_to_mem_issueLda_2_bits_uop_robIdx_value;
    logic io_ooo_to_mem_issueLda_2_bits_uop_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_issueLda_2_bits_uop_sqIdx_value;
    logic io_ooo_to_mem_issueLda_2_bits_uop_storeSetHit;
    logic io_ooo_to_mem_issueLda_2_bits_uop_waitForRobIdx_flag;
    logic [7:0] io_ooo_to_mem_issueLda_2_bits_uop_waitForRobIdx_value;
    logic io_ooo_to_mem_issueLda_2_ready;
    logic io_ooo_to_mem_issueLda_2_valid;
    logic [63:0] io_ooo_to_mem_issueSta_0_bits_src_0;
    logic [8:0] io_ooo_to_mem_issueSta_0_bits_uop_fuOpType;
    logic [34:0] io_ooo_to_mem_issueSta_0_bits_uop_fuType;
    logic [31:0] io_ooo_to_mem_issueSta_0_bits_uop_imm;
    logic [7:0] io_ooo_to_mem_issueSta_0_bits_uop_pdest;
    logic io_ooo_to_mem_issueSta_0_bits_uop_rfWen;
    logic io_ooo_to_mem_issueSta_0_bits_uop_robIdx_flag;
    logic [7:0] io_ooo_to_mem_issueSta_0_bits_uop_robIdx_value;
    logic io_ooo_to_mem_issueSta_0_bits_uop_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_issueSta_0_bits_uop_sqIdx_value;
    logic io_ooo_to_mem_issueSta_0_ready;
    logic io_ooo_to_mem_issueSta_0_valid;
    logic [63:0] io_ooo_to_mem_issueSta_1_bits_src_0;
    logic [8:0] io_ooo_to_mem_issueSta_1_bits_uop_fuOpType;
    logic [34:0] io_ooo_to_mem_issueSta_1_bits_uop_fuType;
    logic [31:0] io_ooo_to_mem_issueSta_1_bits_uop_imm;
    logic [7:0] io_ooo_to_mem_issueSta_1_bits_uop_pdest;
    logic io_ooo_to_mem_issueSta_1_bits_uop_rfWen;
    logic io_ooo_to_mem_issueSta_1_bits_uop_robIdx_flag;
    logic [7:0] io_ooo_to_mem_issueSta_1_bits_uop_robIdx_value;
    logic io_ooo_to_mem_issueSta_1_bits_uop_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_issueSta_1_bits_uop_sqIdx_value;
    logic io_ooo_to_mem_issueSta_1_ready;
    logic io_ooo_to_mem_issueSta_1_valid;
    logic [63:0] io_ooo_to_mem_issueStd_0_bits_src_0;
    logic [8:0] io_ooo_to_mem_issueStd_0_bits_uop_fuOpType;
    logic [34:0] io_ooo_to_mem_issueStd_0_bits_uop_fuType;
    logic [7:0] io_ooo_to_mem_issueStd_0_bits_uop_robIdx_value;
    logic io_ooo_to_mem_issueStd_0_bits_uop_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_issueStd_0_bits_uop_sqIdx_value;
    logic io_ooo_to_mem_issueStd_0_ready;
    logic io_ooo_to_mem_issueStd_0_valid;
    logic [63:0] io_ooo_to_mem_issueStd_1_bits_src_0;
    logic [8:0] io_ooo_to_mem_issueStd_1_bits_uop_fuOpType;
    logic [34:0] io_ooo_to_mem_issueStd_1_bits_uop_fuType;
    logic [7:0] io_ooo_to_mem_issueStd_1_bits_uop_robIdx_value;
    logic io_ooo_to_mem_issueStd_1_bits_uop_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_issueStd_1_bits_uop_sqIdx_value;
    logic io_ooo_to_mem_issueStd_1_ready;
    logic io_ooo_to_mem_issueStd_1_valid;

    clocking drv_cb @(posedge clk);
        `ifdef INTERFACE_ADD_DELAY
            default input #`DEF_SETUP_TIME output #`DEF_HOLD_TIME;
        `endif

        output io_ooo_to_mem_issueLda_0_bits_src_0;
        output io_ooo_to_mem_issueLda_0_bits_uop_fpWen;
        output io_ooo_to_mem_issueLda_0_bits_uop_ftqOffset;
        output io_ooo_to_mem_issueLda_0_bits_uop_ftqPtr_flag;
        output io_ooo_to_mem_issueLda_0_bits_uop_ftqPtr_value;
        output io_ooo_to_mem_issueLda_0_bits_uop_fuOpType;
        output io_ooo_to_mem_issueLda_0_bits_uop_imm;
        output io_ooo_to_mem_issueLda_0_bits_uop_loadWaitBit;
        output io_ooo_to_mem_issueLda_0_bits_uop_loadWaitStrict;
        output io_ooo_to_mem_issueLda_0_bits_uop_lqIdx_flag;
        output io_ooo_to_mem_issueLda_0_bits_uop_lqIdx_value;
        output io_ooo_to_mem_issueLda_0_bits_uop_pc;
        output io_ooo_to_mem_issueLda_0_bits_uop_pdest;
        output io_ooo_to_mem_issueLda_0_bits_uop_preDecodeInfo_isRVC;
        output io_ooo_to_mem_issueLda_0_bits_uop_rfWen;
        output io_ooo_to_mem_issueLda_0_bits_uop_robIdx_flag;
        output io_ooo_to_mem_issueLda_0_bits_uop_robIdx_value;
        output io_ooo_to_mem_issueLda_0_bits_uop_sqIdx_flag;
        output io_ooo_to_mem_issueLda_0_bits_uop_sqIdx_value;
        output io_ooo_to_mem_issueLda_0_bits_uop_storeSetHit;
        output io_ooo_to_mem_issueLda_0_bits_uop_waitForRobIdx_flag;
        output io_ooo_to_mem_issueLda_0_bits_uop_waitForRobIdx_value;
        input  io_ooo_to_mem_issueLda_0_ready;
        output io_ooo_to_mem_issueLda_0_valid;
        output io_ooo_to_mem_issueLda_1_bits_src_0;
        output io_ooo_to_mem_issueLda_1_bits_uop_fpWen;
        output io_ooo_to_mem_issueLda_1_bits_uop_ftqOffset;
        output io_ooo_to_mem_issueLda_1_bits_uop_ftqPtr_flag;
        output io_ooo_to_mem_issueLda_1_bits_uop_ftqPtr_value;
        output io_ooo_to_mem_issueLda_1_bits_uop_fuOpType;
        output io_ooo_to_mem_issueLda_1_bits_uop_imm;
        output io_ooo_to_mem_issueLda_1_bits_uop_loadWaitBit;
        output io_ooo_to_mem_issueLda_1_bits_uop_loadWaitStrict;
        output io_ooo_to_mem_issueLda_1_bits_uop_lqIdx_flag;
        output io_ooo_to_mem_issueLda_1_bits_uop_lqIdx_value;
        output io_ooo_to_mem_issueLda_1_bits_uop_pc;
        output io_ooo_to_mem_issueLda_1_bits_uop_pdest;
        output io_ooo_to_mem_issueLda_1_bits_uop_preDecodeInfo_isRVC;
        output io_ooo_to_mem_issueLda_1_bits_uop_rfWen;
        output io_ooo_to_mem_issueLda_1_bits_uop_robIdx_flag;
        output io_ooo_to_mem_issueLda_1_bits_uop_robIdx_value;
        output io_ooo_to_mem_issueLda_1_bits_uop_sqIdx_flag;
        output io_ooo_to_mem_issueLda_1_bits_uop_sqIdx_value;
        output io_ooo_to_mem_issueLda_1_bits_uop_storeSetHit;
        output io_ooo_to_mem_issueLda_1_bits_uop_waitForRobIdx_flag;
        output io_ooo_to_mem_issueLda_1_bits_uop_waitForRobIdx_value;
        input  io_ooo_to_mem_issueLda_1_ready;
        output io_ooo_to_mem_issueLda_1_valid;
        output io_ooo_to_mem_issueLda_2_bits_src_0;
        output io_ooo_to_mem_issueLda_2_bits_uop_fpWen;
        output io_ooo_to_mem_issueLda_2_bits_uop_ftqOffset;
        output io_ooo_to_mem_issueLda_2_bits_uop_ftqPtr_flag;
        output io_ooo_to_mem_issueLda_2_bits_uop_ftqPtr_value;
        output io_ooo_to_mem_issueLda_2_bits_uop_fuOpType;
        output io_ooo_to_mem_issueLda_2_bits_uop_imm;
        output io_ooo_to_mem_issueLda_2_bits_uop_loadWaitBit;
        output io_ooo_to_mem_issueLda_2_bits_uop_loadWaitStrict;
        output io_ooo_to_mem_issueLda_2_bits_uop_lqIdx_flag;
        output io_ooo_to_mem_issueLda_2_bits_uop_lqIdx_value;
        output io_ooo_to_mem_issueLda_2_bits_uop_pc;
        output io_ooo_to_mem_issueLda_2_bits_uop_pdest;
        output io_ooo_to_mem_issueLda_2_bits_uop_preDecodeInfo_isRVC;
        output io_ooo_to_mem_issueLda_2_bits_uop_rfWen;
        output io_ooo_to_mem_issueLda_2_bits_uop_robIdx_flag;
        output io_ooo_to_mem_issueLda_2_bits_uop_robIdx_value;
        output io_ooo_to_mem_issueLda_2_bits_uop_sqIdx_flag;
        output io_ooo_to_mem_issueLda_2_bits_uop_sqIdx_value;
        output io_ooo_to_mem_issueLda_2_bits_uop_storeSetHit;
        output io_ooo_to_mem_issueLda_2_bits_uop_waitForRobIdx_flag;
        output io_ooo_to_mem_issueLda_2_bits_uop_waitForRobIdx_value;
        input  io_ooo_to_mem_issueLda_2_ready;
        output io_ooo_to_mem_issueLda_2_valid;
        output io_ooo_to_mem_issueSta_0_bits_src_0;
        output io_ooo_to_mem_issueSta_0_bits_uop_fuOpType;
        output io_ooo_to_mem_issueSta_0_bits_uop_fuType;
        output io_ooo_to_mem_issueSta_0_bits_uop_imm;
        output io_ooo_to_mem_issueSta_0_bits_uop_pdest;
        output io_ooo_to_mem_issueSta_0_bits_uop_rfWen;
        output io_ooo_to_mem_issueSta_0_bits_uop_robIdx_flag;
        output io_ooo_to_mem_issueSta_0_bits_uop_robIdx_value;
        output io_ooo_to_mem_issueSta_0_bits_uop_sqIdx_flag;
        output io_ooo_to_mem_issueSta_0_bits_uop_sqIdx_value;
        input  io_ooo_to_mem_issueSta_0_ready;
        output io_ooo_to_mem_issueSta_0_valid;
        output io_ooo_to_mem_issueSta_1_bits_src_0;
        output io_ooo_to_mem_issueSta_1_bits_uop_fuOpType;
        output io_ooo_to_mem_issueSta_1_bits_uop_fuType;
        output io_ooo_to_mem_issueSta_1_bits_uop_imm;
        output io_ooo_to_mem_issueSta_1_bits_uop_pdest;
        output io_ooo_to_mem_issueSta_1_bits_uop_rfWen;
        output io_ooo_to_mem_issueSta_1_bits_uop_robIdx_flag;
        output io_ooo_to_mem_issueSta_1_bits_uop_robIdx_value;
        output io_ooo_to_mem_issueSta_1_bits_uop_sqIdx_flag;
        output io_ooo_to_mem_issueSta_1_bits_uop_sqIdx_value;
        input  io_ooo_to_mem_issueSta_1_ready;
        output io_ooo_to_mem_issueSta_1_valid;
        output io_ooo_to_mem_issueStd_0_bits_src_0;
        output io_ooo_to_mem_issueStd_0_bits_uop_fuOpType;
        output io_ooo_to_mem_issueStd_0_bits_uop_fuType;
        output io_ooo_to_mem_issueStd_0_bits_uop_robIdx_value;
        output io_ooo_to_mem_issueStd_0_bits_uop_sqIdx_flag;
        output io_ooo_to_mem_issueStd_0_bits_uop_sqIdx_value;
        input  io_ooo_to_mem_issueStd_0_ready;
        output io_ooo_to_mem_issueStd_0_valid;
        output io_ooo_to_mem_issueStd_1_bits_src_0;
        output io_ooo_to_mem_issueStd_1_bits_uop_fuOpType;
        output io_ooo_to_mem_issueStd_1_bits_uop_fuType;
        output io_ooo_to_mem_issueStd_1_bits_uop_robIdx_value;
        output io_ooo_to_mem_issueStd_1_bits_uop_sqIdx_flag;
        output io_ooo_to_mem_issueStd_1_bits_uop_sqIdx_value;
        input  io_ooo_to_mem_issueStd_1_ready;
        output io_ooo_to_mem_issueStd_1_valid;
    endclocking:drv_cb

    clocking mon_cb @(posedge clk);
        `ifdef INTERFACE_ADD_DELAY
            default input #`DEF_SETUP_TIME output #`DEF_HOLD_TIME;
        `endif

        input  io_ooo_to_mem_issueLda_0_bits_src_0;
        input  io_ooo_to_mem_issueLda_0_bits_uop_fpWen;
        input  io_ooo_to_mem_issueLda_0_bits_uop_ftqOffset;
        input  io_ooo_to_mem_issueLda_0_bits_uop_ftqPtr_flag;
        input  io_ooo_to_mem_issueLda_0_bits_uop_ftqPtr_value;
        input  io_ooo_to_mem_issueLda_0_bits_uop_fuOpType;
        input  io_ooo_to_mem_issueLda_0_bits_uop_imm;
        input  io_ooo_to_mem_issueLda_0_bits_uop_loadWaitBit;
        input  io_ooo_to_mem_issueLda_0_bits_uop_loadWaitStrict;
        input  io_ooo_to_mem_issueLda_0_bits_uop_lqIdx_flag;
        input  io_ooo_to_mem_issueLda_0_bits_uop_lqIdx_value;
        input  io_ooo_to_mem_issueLda_0_bits_uop_pc;
        input  io_ooo_to_mem_issueLda_0_bits_uop_pdest;
        input  io_ooo_to_mem_issueLda_0_bits_uop_preDecodeInfo_isRVC;
        input  io_ooo_to_mem_issueLda_0_bits_uop_rfWen;
        input  io_ooo_to_mem_issueLda_0_bits_uop_robIdx_flag;
        input  io_ooo_to_mem_issueLda_0_bits_uop_robIdx_value;
        input  io_ooo_to_mem_issueLda_0_bits_uop_sqIdx_flag;
        input  io_ooo_to_mem_issueLda_0_bits_uop_sqIdx_value;
        input  io_ooo_to_mem_issueLda_0_bits_uop_storeSetHit;
        input  io_ooo_to_mem_issueLda_0_bits_uop_waitForRobIdx_flag;
        input  io_ooo_to_mem_issueLda_0_bits_uop_waitForRobIdx_value;
        input  io_ooo_to_mem_issueLda_0_ready;
        input  io_ooo_to_mem_issueLda_0_valid;
        input  io_ooo_to_mem_issueLda_1_bits_src_0;
        input  io_ooo_to_mem_issueLda_1_bits_uop_fpWen;
        input  io_ooo_to_mem_issueLda_1_bits_uop_ftqOffset;
        input  io_ooo_to_mem_issueLda_1_bits_uop_ftqPtr_flag;
        input  io_ooo_to_mem_issueLda_1_bits_uop_ftqPtr_value;
        input  io_ooo_to_mem_issueLda_1_bits_uop_fuOpType;
        input  io_ooo_to_mem_issueLda_1_bits_uop_imm;
        input  io_ooo_to_mem_issueLda_1_bits_uop_loadWaitBit;
        input  io_ooo_to_mem_issueLda_1_bits_uop_loadWaitStrict;
        input  io_ooo_to_mem_issueLda_1_bits_uop_lqIdx_flag;
        input  io_ooo_to_mem_issueLda_1_bits_uop_lqIdx_value;
        input  io_ooo_to_mem_issueLda_1_bits_uop_pc;
        input  io_ooo_to_mem_issueLda_1_bits_uop_pdest;
        input  io_ooo_to_mem_issueLda_1_bits_uop_preDecodeInfo_isRVC;
        input  io_ooo_to_mem_issueLda_1_bits_uop_rfWen;
        input  io_ooo_to_mem_issueLda_1_bits_uop_robIdx_flag;
        input  io_ooo_to_mem_issueLda_1_bits_uop_robIdx_value;
        input  io_ooo_to_mem_issueLda_1_bits_uop_sqIdx_flag;
        input  io_ooo_to_mem_issueLda_1_bits_uop_sqIdx_value;
        input  io_ooo_to_mem_issueLda_1_bits_uop_storeSetHit;
        input  io_ooo_to_mem_issueLda_1_bits_uop_waitForRobIdx_flag;
        input  io_ooo_to_mem_issueLda_1_bits_uop_waitForRobIdx_value;
        input  io_ooo_to_mem_issueLda_1_ready;
        input  io_ooo_to_mem_issueLda_1_valid;
        input  io_ooo_to_mem_issueLda_2_bits_src_0;
        input  io_ooo_to_mem_issueLda_2_bits_uop_fpWen;
        input  io_ooo_to_mem_issueLda_2_bits_uop_ftqOffset;
        input  io_ooo_to_mem_issueLda_2_bits_uop_ftqPtr_flag;
        input  io_ooo_to_mem_issueLda_2_bits_uop_ftqPtr_value;
        input  io_ooo_to_mem_issueLda_2_bits_uop_fuOpType;
        input  io_ooo_to_mem_issueLda_2_bits_uop_imm;
        input  io_ooo_to_mem_issueLda_2_bits_uop_loadWaitBit;
        input  io_ooo_to_mem_issueLda_2_bits_uop_loadWaitStrict;
        input  io_ooo_to_mem_issueLda_2_bits_uop_lqIdx_flag;
        input  io_ooo_to_mem_issueLda_2_bits_uop_lqIdx_value;
        input  io_ooo_to_mem_issueLda_2_bits_uop_pc;
        input  io_ooo_to_mem_issueLda_2_bits_uop_pdest;
        input  io_ooo_to_mem_issueLda_2_bits_uop_preDecodeInfo_isRVC;
        input  io_ooo_to_mem_issueLda_2_bits_uop_rfWen;
        input  io_ooo_to_mem_issueLda_2_bits_uop_robIdx_flag;
        input  io_ooo_to_mem_issueLda_2_bits_uop_robIdx_value;
        input  io_ooo_to_mem_issueLda_2_bits_uop_sqIdx_flag;
        input  io_ooo_to_mem_issueLda_2_bits_uop_sqIdx_value;
        input  io_ooo_to_mem_issueLda_2_bits_uop_storeSetHit;
        input  io_ooo_to_mem_issueLda_2_bits_uop_waitForRobIdx_flag;
        input  io_ooo_to_mem_issueLda_2_bits_uop_waitForRobIdx_value;
        input  io_ooo_to_mem_issueLda_2_ready;
        input  io_ooo_to_mem_issueLda_2_valid;
        input  io_ooo_to_mem_issueSta_0_bits_src_0;
        input  io_ooo_to_mem_issueSta_0_bits_uop_fuOpType;
        input  io_ooo_to_mem_issueSta_0_bits_uop_fuType;
        input  io_ooo_to_mem_issueSta_0_bits_uop_imm;
        input  io_ooo_to_mem_issueSta_0_bits_uop_pdest;
        input  io_ooo_to_mem_issueSta_0_bits_uop_rfWen;
        input  io_ooo_to_mem_issueSta_0_bits_uop_robIdx_flag;
        input  io_ooo_to_mem_issueSta_0_bits_uop_robIdx_value;
        input  io_ooo_to_mem_issueSta_0_bits_uop_sqIdx_flag;
        input  io_ooo_to_mem_issueSta_0_bits_uop_sqIdx_value;
        input  io_ooo_to_mem_issueSta_0_ready;
        input  io_ooo_to_mem_issueSta_0_valid;
        input  io_ooo_to_mem_issueSta_1_bits_src_0;
        input  io_ooo_to_mem_issueSta_1_bits_uop_fuOpType;
        input  io_ooo_to_mem_issueSta_1_bits_uop_fuType;
        input  io_ooo_to_mem_issueSta_1_bits_uop_imm;
        input  io_ooo_to_mem_issueSta_1_bits_uop_pdest;
        input  io_ooo_to_mem_issueSta_1_bits_uop_rfWen;
        input  io_ooo_to_mem_issueSta_1_bits_uop_robIdx_flag;
        input  io_ooo_to_mem_issueSta_1_bits_uop_robIdx_value;
        input  io_ooo_to_mem_issueSta_1_bits_uop_sqIdx_flag;
        input  io_ooo_to_mem_issueSta_1_bits_uop_sqIdx_value;
        input  io_ooo_to_mem_issueSta_1_ready;
        input  io_ooo_to_mem_issueSta_1_valid;
        input  io_ooo_to_mem_issueStd_0_bits_src_0;
        input  io_ooo_to_mem_issueStd_0_bits_uop_fuOpType;
        input  io_ooo_to_mem_issueStd_0_bits_uop_fuType;
        input  io_ooo_to_mem_issueStd_0_bits_uop_robIdx_value;
        input  io_ooo_to_mem_issueStd_0_bits_uop_sqIdx_flag;
        input  io_ooo_to_mem_issueStd_0_bits_uop_sqIdx_value;
        input  io_ooo_to_mem_issueStd_0_ready;
        input  io_ooo_to_mem_issueStd_0_valid;
        input  io_ooo_to_mem_issueStd_1_bits_src_0;
        input  io_ooo_to_mem_issueStd_1_bits_uop_fuOpType;
        input  io_ooo_to_mem_issueStd_1_bits_uop_fuType;
        input  io_ooo_to_mem_issueStd_1_bits_uop_robIdx_value;
        input  io_ooo_to_mem_issueStd_1_bits_uop_sqIdx_flag;
        input  io_ooo_to_mem_issueStd_1_bits_uop_sqIdx_value;
        input  io_ooo_to_mem_issueStd_1_ready;
        input  io_ooo_to_mem_issueStd_1_valid;
    endclocking:mon_cb

    modport drv_mp (clocking drv_cb);
    modport mon_mp (clocking mon_cb);

endinterface:lintsissue_agent_agent_interface

`endif
