//=========================================================
//File name    : lintsissue_agent_agent_monitor.sv
//Author       : OpenAI_Codex
//Module name  : lintsissue_agent_agent_monitor
//Discribution : lintsissue_agent_agent_monitor : monitor
//Date         : 2026-04-12
//=========================================================
`ifndef LINTSISSUE_AGENT_AGENT_MONITOR__SV
`define LINTSISSUE_AGENT_AGENT_MONITOR__SV

class lintsissue_agent_agent_monitor  extends tcnt_monitor_base#(virtual lintsissue_agent_agent_interface,lintsissue_agent_agent_cfg,lintsissue_agent_agent_xaction);

    `uvm_component_utils(lintsissue_agent_agent_monitor)

    extern function new(string name, uvm_component parent);
    extern virtual function void build_phase(uvm_phase phase);
    extern task run_phase(uvm_phase phase);
    extern task mon_data();
endclass:lintsissue_agent_agent_monitor

function lintsissue_agent_agent_monitor::new(string name, uvm_component parent);
    super.new(name,parent);
endfunction:new

function void lintsissue_agent_agent_monitor::build_phase(uvm_phase phase);
    super.build_phase(phase);
endfunction:build_phase

task lintsissue_agent_agent_monitor::run_phase(uvm_phase phase);
    super.run_phase(phase);
    this.mon_data();
endtask:run_phase

task lintsissue_agent_agent_monitor::mon_data();

    logic io_ooo_to_mem_intIssue_6_0_ready;
    logic io_ooo_to_mem_intIssue_6_0_valid;
    logic [35:0] io_ooo_to_mem_intIssue_6_0_bits_fuType;
    logic [8:0] io_ooo_to_mem_intIssue_6_0_bits_fuOpType;
    logic [63:0] io_ooo_to_mem_intIssue_6_0_bits_src_0;
    logic io_ooo_to_mem_intIssue_6_0_bits_robIdx_flag;
    logic [8:0] io_ooo_to_mem_intIssue_6_0_bits_robIdx_value;
    logic io_ooo_to_mem_intIssue_6_0_bits_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_intIssue_6_0_bits_sqIdx_value;
    logic io_ooo_to_mem_intIssue_5_0_ready;
    logic io_ooo_to_mem_intIssue_5_0_valid;
    logic [35:0] io_ooo_to_mem_intIssue_5_0_bits_fuType;
    logic [8:0] io_ooo_to_mem_intIssue_5_0_bits_fuOpType;
    logic [63:0] io_ooo_to_mem_intIssue_5_0_bits_src_0;
    logic io_ooo_to_mem_intIssue_5_0_bits_robIdx_flag;
    logic [8:0] io_ooo_to_mem_intIssue_5_0_bits_robIdx_value;
    logic io_ooo_to_mem_intIssue_5_0_bits_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_intIssue_5_0_bits_sqIdx_value;
    logic io_ooo_to_mem_intIssue_4_0_ready;
    logic io_ooo_to_mem_intIssue_4_0_valid;
    logic [35:0] io_ooo_to_mem_intIssue_4_0_bits_fuType;
    logic [8:0] io_ooo_to_mem_intIssue_4_0_bits_fuOpType;
    logic [63:0] io_ooo_to_mem_intIssue_4_0_bits_src_0;
    logic [63:0] io_ooo_to_mem_intIssue_4_0_bits_imm;
    logic io_ooo_to_mem_intIssue_4_0_bits_robIdx_flag;
    logic [8:0] io_ooo_to_mem_intIssue_4_0_bits_robIdx_value;
    logic io_ooo_to_mem_intIssue_4_0_bits_isFirstIssue;
    logic [7:0] io_ooo_to_mem_intIssue_4_0_bits_pdest;
    logic io_ooo_to_mem_intIssue_4_0_bits_isRVC;
    logic io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_flag;
    logic [5:0] io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_value;
    logic [4:0] io_ooo_to_mem_intIssue_4_0_bits_ftqOffset;
    logic io_ooo_to_mem_intIssue_4_0_bits_storeSetHit;
    logic [4:0] io_ooo_to_mem_intIssue_4_0_bits_ssid;
    logic io_ooo_to_mem_intIssue_4_0_bits_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_intIssue_4_0_bits_sqIdx_value;
    logic io_ooo_to_mem_intIssue_3_0_ready;
    logic io_ooo_to_mem_intIssue_3_0_valid;
    logic [35:0] io_ooo_to_mem_intIssue_3_0_bits_fuType;
    logic [8:0] io_ooo_to_mem_intIssue_3_0_bits_fuOpType;
    logic [63:0] io_ooo_to_mem_intIssue_3_0_bits_src_0;
    logic [63:0] io_ooo_to_mem_intIssue_3_0_bits_imm;
    logic io_ooo_to_mem_intIssue_3_0_bits_robIdx_flag;
    logic [8:0] io_ooo_to_mem_intIssue_3_0_bits_robIdx_value;
    logic io_ooo_to_mem_intIssue_3_0_bits_isFirstIssue;
    logic [7:0] io_ooo_to_mem_intIssue_3_0_bits_pdest;
    logic io_ooo_to_mem_intIssue_3_0_bits_isRVC;
    logic io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_flag;
    logic [5:0] io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_value;
    logic [4:0] io_ooo_to_mem_intIssue_3_0_bits_ftqOffset;
    logic io_ooo_to_mem_intIssue_3_0_bits_storeSetHit;
    logic [4:0] io_ooo_to_mem_intIssue_3_0_bits_ssid;
    logic io_ooo_to_mem_intIssue_3_0_bits_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_intIssue_3_0_bits_sqIdx_value;
    logic io_ooo_to_mem_intIssue_2_0_ready;
    logic io_ooo_to_mem_intIssue_2_0_valid;
    logic [8:0] io_ooo_to_mem_intIssue_2_0_bits_fuOpType;
    logic [63:0] io_ooo_to_mem_intIssue_2_0_bits_src_0;
    logic [63:0] io_ooo_to_mem_intIssue_2_0_bits_imm;
    logic io_ooo_to_mem_intIssue_2_0_bits_robIdx_flag;
    logic [8:0] io_ooo_to_mem_intIssue_2_0_bits_robIdx_value;
    logic [7:0] io_ooo_to_mem_intIssue_2_0_bits_pdest;
    logic io_ooo_to_mem_intIssue_2_0_bits_rfWen;
    logic io_ooo_to_mem_intIssue_2_0_bits_fpWen;
    logic [49:0] io_ooo_to_mem_intIssue_2_0_bits_pc;
    logic io_ooo_to_mem_intIssue_2_0_bits_isRVC;
    logic io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_flag;
    logic [5:0] io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_value;
    logic [4:0] io_ooo_to_mem_intIssue_2_0_bits_ftqOffset;
    logic io_ooo_to_mem_intIssue_2_0_bits_loadWaitBit;
    logic io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_flag;
    logic [8:0] io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_value;
    logic io_ooo_to_mem_intIssue_2_0_bits_storeSetHit;
    logic io_ooo_to_mem_intIssue_2_0_bits_loadWaitStrict;
    logic io_ooo_to_mem_intIssue_2_0_bits_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_intIssue_2_0_bits_lqIdx_value;
    logic io_ooo_to_mem_intIssue_2_0_bits_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_intIssue_2_0_bits_sqIdx_value;
    logic io_ooo_to_mem_intIssue_1_0_ready;
    logic io_ooo_to_mem_intIssue_1_0_valid;
    logic [8:0] io_ooo_to_mem_intIssue_1_0_bits_fuOpType;
    logic [63:0] io_ooo_to_mem_intIssue_1_0_bits_src_0;
    logic [63:0] io_ooo_to_mem_intIssue_1_0_bits_imm;
    logic io_ooo_to_mem_intIssue_1_0_bits_robIdx_flag;
    logic [8:0] io_ooo_to_mem_intIssue_1_0_bits_robIdx_value;
    logic [7:0] io_ooo_to_mem_intIssue_1_0_bits_pdest;
    logic io_ooo_to_mem_intIssue_1_0_bits_rfWen;
    logic io_ooo_to_mem_intIssue_1_0_bits_fpWen;
    logic [49:0] io_ooo_to_mem_intIssue_1_0_bits_pc;
    logic io_ooo_to_mem_intIssue_1_0_bits_isRVC;
    logic io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_flag;
    logic [5:0] io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_value;
    logic [4:0] io_ooo_to_mem_intIssue_1_0_bits_ftqOffset;
    logic io_ooo_to_mem_intIssue_1_0_bits_loadWaitBit;
    logic io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_flag;
    logic [8:0] io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_value;
    logic io_ooo_to_mem_intIssue_1_0_bits_storeSetHit;
    logic io_ooo_to_mem_intIssue_1_0_bits_loadWaitStrict;
    logic io_ooo_to_mem_intIssue_1_0_bits_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_intIssue_1_0_bits_lqIdx_value;
    logic io_ooo_to_mem_intIssue_1_0_bits_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_intIssue_1_0_bits_sqIdx_value;
    logic io_ooo_to_mem_intIssue_0_0_ready;
    logic io_ooo_to_mem_intIssue_0_0_valid;
    logic [8:0] io_ooo_to_mem_intIssue_0_0_bits_fuOpType;
    logic [63:0] io_ooo_to_mem_intIssue_0_0_bits_src_0;
    logic [63:0] io_ooo_to_mem_intIssue_0_0_bits_imm;
    logic io_ooo_to_mem_intIssue_0_0_bits_robIdx_flag;
    logic [8:0] io_ooo_to_mem_intIssue_0_0_bits_robIdx_value;
    logic [7:0] io_ooo_to_mem_intIssue_0_0_bits_pdest;
    logic io_ooo_to_mem_intIssue_0_0_bits_rfWen;
    logic io_ooo_to_mem_intIssue_0_0_bits_fpWen;
    logic [49:0] io_ooo_to_mem_intIssue_0_0_bits_pc;
    logic io_ooo_to_mem_intIssue_0_0_bits_isRVC;
    logic io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_flag;
    logic [5:0] io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_value;
    logic [4:0] io_ooo_to_mem_intIssue_0_0_bits_ftqOffset;
    logic io_ooo_to_mem_intIssue_0_0_bits_loadWaitBit;
    logic io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_flag;
    logic [8:0] io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_value;
    logic io_ooo_to_mem_intIssue_0_0_bits_storeSetHit;
    logic io_ooo_to_mem_intIssue_0_0_bits_loadWaitStrict;
    logic io_ooo_to_mem_intIssue_0_0_bits_lqIdx_flag;
    logic [6:0] io_ooo_to_mem_intIssue_0_0_bits_lqIdx_value;
    logic io_ooo_to_mem_intIssue_0_0_bits_sqIdx_flag;
    logic [5:0] io_ooo_to_mem_intIssue_0_0_bits_sqIdx_value;

    lintsissue_agent_agent_xaction  mon_tr;
    while(1) begin
        @this.vif.mon_mp.mon_cb;
        io_ooo_to_mem_intIssue_6_0_ready = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_6_0_ready;
        io_ooo_to_mem_intIssue_6_0_valid = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_6_0_valid;
        io_ooo_to_mem_intIssue_6_0_bits_fuType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_6_0_bits_fuType;
        io_ooo_to_mem_intIssue_6_0_bits_fuOpType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_6_0_bits_fuOpType;
        io_ooo_to_mem_intIssue_6_0_bits_src_0 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_6_0_bits_src_0;
        io_ooo_to_mem_intIssue_6_0_bits_robIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_6_0_bits_robIdx_flag;
        io_ooo_to_mem_intIssue_6_0_bits_robIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_6_0_bits_robIdx_value;
        io_ooo_to_mem_intIssue_6_0_bits_sqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_6_0_bits_sqIdx_flag;
        io_ooo_to_mem_intIssue_6_0_bits_sqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_6_0_bits_sqIdx_value;
        io_ooo_to_mem_intIssue_5_0_ready = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_5_0_ready;
        io_ooo_to_mem_intIssue_5_0_valid = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_5_0_valid;
        io_ooo_to_mem_intIssue_5_0_bits_fuType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_5_0_bits_fuType;
        io_ooo_to_mem_intIssue_5_0_bits_fuOpType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_5_0_bits_fuOpType;
        io_ooo_to_mem_intIssue_5_0_bits_src_0 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_5_0_bits_src_0;
        io_ooo_to_mem_intIssue_5_0_bits_robIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_5_0_bits_robIdx_flag;
        io_ooo_to_mem_intIssue_5_0_bits_robIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_5_0_bits_robIdx_value;
        io_ooo_to_mem_intIssue_5_0_bits_sqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_5_0_bits_sqIdx_flag;
        io_ooo_to_mem_intIssue_5_0_bits_sqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_5_0_bits_sqIdx_value;
        io_ooo_to_mem_intIssue_4_0_ready = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_4_0_ready;
        io_ooo_to_mem_intIssue_4_0_valid = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_4_0_valid;
        io_ooo_to_mem_intIssue_4_0_bits_fuType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_4_0_bits_fuType;
        io_ooo_to_mem_intIssue_4_0_bits_fuOpType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_4_0_bits_fuOpType;
        io_ooo_to_mem_intIssue_4_0_bits_src_0 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_4_0_bits_src_0;
        io_ooo_to_mem_intIssue_4_0_bits_imm = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_4_0_bits_imm;
        io_ooo_to_mem_intIssue_4_0_bits_robIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_4_0_bits_robIdx_flag;
        io_ooo_to_mem_intIssue_4_0_bits_robIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_4_0_bits_robIdx_value;
        io_ooo_to_mem_intIssue_4_0_bits_isFirstIssue = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_4_0_bits_isFirstIssue;
        io_ooo_to_mem_intIssue_4_0_bits_pdest = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_4_0_bits_pdest;
        io_ooo_to_mem_intIssue_4_0_bits_isRVC = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_4_0_bits_isRVC;
        io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_flag;
        io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_value;
        io_ooo_to_mem_intIssue_4_0_bits_ftqOffset = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_4_0_bits_ftqOffset;
        io_ooo_to_mem_intIssue_4_0_bits_storeSetHit = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_4_0_bits_storeSetHit;
        io_ooo_to_mem_intIssue_4_0_bits_ssid = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_4_0_bits_ssid;
        io_ooo_to_mem_intIssue_4_0_bits_sqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_4_0_bits_sqIdx_flag;
        io_ooo_to_mem_intIssue_4_0_bits_sqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_4_0_bits_sqIdx_value;
        io_ooo_to_mem_intIssue_3_0_ready = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_3_0_ready;
        io_ooo_to_mem_intIssue_3_0_valid = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_3_0_valid;
        io_ooo_to_mem_intIssue_3_0_bits_fuType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_3_0_bits_fuType;
        io_ooo_to_mem_intIssue_3_0_bits_fuOpType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_3_0_bits_fuOpType;
        io_ooo_to_mem_intIssue_3_0_bits_src_0 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_3_0_bits_src_0;
        io_ooo_to_mem_intIssue_3_0_bits_imm = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_3_0_bits_imm;
        io_ooo_to_mem_intIssue_3_0_bits_robIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_3_0_bits_robIdx_flag;
        io_ooo_to_mem_intIssue_3_0_bits_robIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_3_0_bits_robIdx_value;
        io_ooo_to_mem_intIssue_3_0_bits_isFirstIssue = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_3_0_bits_isFirstIssue;
        io_ooo_to_mem_intIssue_3_0_bits_pdest = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_3_0_bits_pdest;
        io_ooo_to_mem_intIssue_3_0_bits_isRVC = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_3_0_bits_isRVC;
        io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_flag;
        io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_value;
        io_ooo_to_mem_intIssue_3_0_bits_ftqOffset = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_3_0_bits_ftqOffset;
        io_ooo_to_mem_intIssue_3_0_bits_storeSetHit = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_3_0_bits_storeSetHit;
        io_ooo_to_mem_intIssue_3_0_bits_ssid = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_3_0_bits_ssid;
        io_ooo_to_mem_intIssue_3_0_bits_sqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_3_0_bits_sqIdx_flag;
        io_ooo_to_mem_intIssue_3_0_bits_sqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_3_0_bits_sqIdx_value;
        io_ooo_to_mem_intIssue_2_0_ready = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_2_0_ready;
        io_ooo_to_mem_intIssue_2_0_valid = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_2_0_valid;
        io_ooo_to_mem_intIssue_2_0_bits_fuOpType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_2_0_bits_fuOpType;
        io_ooo_to_mem_intIssue_2_0_bits_src_0 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_2_0_bits_src_0;
        io_ooo_to_mem_intIssue_2_0_bits_imm = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_2_0_bits_imm;
        io_ooo_to_mem_intIssue_2_0_bits_robIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_2_0_bits_robIdx_flag;
        io_ooo_to_mem_intIssue_2_0_bits_robIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_2_0_bits_robIdx_value;
        io_ooo_to_mem_intIssue_2_0_bits_pdest = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_2_0_bits_pdest;
        io_ooo_to_mem_intIssue_2_0_bits_rfWen = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_2_0_bits_rfWen;
        io_ooo_to_mem_intIssue_2_0_bits_fpWen = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_2_0_bits_fpWen;
        io_ooo_to_mem_intIssue_2_0_bits_pc = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_2_0_bits_pc;
        io_ooo_to_mem_intIssue_2_0_bits_isRVC = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_2_0_bits_isRVC;
        io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_flag;
        io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_value;
        io_ooo_to_mem_intIssue_2_0_bits_ftqOffset = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_2_0_bits_ftqOffset;
        io_ooo_to_mem_intIssue_2_0_bits_loadWaitBit = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_2_0_bits_loadWaitBit;
        io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_flag;
        io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_value;
        io_ooo_to_mem_intIssue_2_0_bits_storeSetHit = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_2_0_bits_storeSetHit;
        io_ooo_to_mem_intIssue_2_0_bits_loadWaitStrict = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_2_0_bits_loadWaitStrict;
        io_ooo_to_mem_intIssue_2_0_bits_lqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_2_0_bits_lqIdx_flag;
        io_ooo_to_mem_intIssue_2_0_bits_lqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_2_0_bits_lqIdx_value;
        io_ooo_to_mem_intIssue_2_0_bits_sqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_2_0_bits_sqIdx_flag;
        io_ooo_to_mem_intIssue_2_0_bits_sqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_2_0_bits_sqIdx_value;
        io_ooo_to_mem_intIssue_1_0_ready = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_1_0_ready;
        io_ooo_to_mem_intIssue_1_0_valid = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_1_0_valid;
        io_ooo_to_mem_intIssue_1_0_bits_fuOpType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_1_0_bits_fuOpType;
        io_ooo_to_mem_intIssue_1_0_bits_src_0 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_1_0_bits_src_0;
        io_ooo_to_mem_intIssue_1_0_bits_imm = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_1_0_bits_imm;
        io_ooo_to_mem_intIssue_1_0_bits_robIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_1_0_bits_robIdx_flag;
        io_ooo_to_mem_intIssue_1_0_bits_robIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_1_0_bits_robIdx_value;
        io_ooo_to_mem_intIssue_1_0_bits_pdest = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_1_0_bits_pdest;
        io_ooo_to_mem_intIssue_1_0_bits_rfWen = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_1_0_bits_rfWen;
        io_ooo_to_mem_intIssue_1_0_bits_fpWen = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_1_0_bits_fpWen;
        io_ooo_to_mem_intIssue_1_0_bits_pc = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_1_0_bits_pc;
        io_ooo_to_mem_intIssue_1_0_bits_isRVC = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_1_0_bits_isRVC;
        io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_flag;
        io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_value;
        io_ooo_to_mem_intIssue_1_0_bits_ftqOffset = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_1_0_bits_ftqOffset;
        io_ooo_to_mem_intIssue_1_0_bits_loadWaitBit = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_1_0_bits_loadWaitBit;
        io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_flag;
        io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_value;
        io_ooo_to_mem_intIssue_1_0_bits_storeSetHit = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_1_0_bits_storeSetHit;
        io_ooo_to_mem_intIssue_1_0_bits_loadWaitStrict = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_1_0_bits_loadWaitStrict;
        io_ooo_to_mem_intIssue_1_0_bits_lqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_1_0_bits_lqIdx_flag;
        io_ooo_to_mem_intIssue_1_0_bits_lqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_1_0_bits_lqIdx_value;
        io_ooo_to_mem_intIssue_1_0_bits_sqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_1_0_bits_sqIdx_flag;
        io_ooo_to_mem_intIssue_1_0_bits_sqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_1_0_bits_sqIdx_value;
        io_ooo_to_mem_intIssue_0_0_ready = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_0_0_ready;
        io_ooo_to_mem_intIssue_0_0_valid = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_0_0_valid;
        io_ooo_to_mem_intIssue_0_0_bits_fuOpType = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_0_0_bits_fuOpType;
        io_ooo_to_mem_intIssue_0_0_bits_src_0 = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_0_0_bits_src_0;
        io_ooo_to_mem_intIssue_0_0_bits_imm = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_0_0_bits_imm;
        io_ooo_to_mem_intIssue_0_0_bits_robIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_0_0_bits_robIdx_flag;
        io_ooo_to_mem_intIssue_0_0_bits_robIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_0_0_bits_robIdx_value;
        io_ooo_to_mem_intIssue_0_0_bits_pdest = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_0_0_bits_pdest;
        io_ooo_to_mem_intIssue_0_0_bits_rfWen = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_0_0_bits_rfWen;
        io_ooo_to_mem_intIssue_0_0_bits_fpWen = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_0_0_bits_fpWen;
        io_ooo_to_mem_intIssue_0_0_bits_pc = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_0_0_bits_pc;
        io_ooo_to_mem_intIssue_0_0_bits_isRVC = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_0_0_bits_isRVC;
        io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_flag;
        io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_value;
        io_ooo_to_mem_intIssue_0_0_bits_ftqOffset = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_0_0_bits_ftqOffset;
        io_ooo_to_mem_intIssue_0_0_bits_loadWaitBit = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_0_0_bits_loadWaitBit;
        io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_flag;
        io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_value;
        io_ooo_to_mem_intIssue_0_0_bits_storeSetHit = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_0_0_bits_storeSetHit;
        io_ooo_to_mem_intIssue_0_0_bits_loadWaitStrict = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_0_0_bits_loadWaitStrict;
        io_ooo_to_mem_intIssue_0_0_bits_lqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_0_0_bits_lqIdx_flag;
        io_ooo_to_mem_intIssue_0_0_bits_lqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_0_0_bits_lqIdx_value;
        io_ooo_to_mem_intIssue_0_0_bits_sqIdx_flag = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_0_0_bits_sqIdx_flag;
        io_ooo_to_mem_intIssue_0_0_bits_sqIdx_value = this.vif.mon_mp.mon_cb.io_ooo_to_mem_intIssue_0_0_bits_sqIdx_value;

        if(this.cfg.xz_sw==tcnt_dec_base::ON && this.vif.rst_n==1'b1 && memblock_sync_pkg::reset_backend_done==1'b1) begin
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_6_0_ready,io_ooo_to_mem_intIssue_6_0_ready,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_6_0_valid,io_ooo_to_mem_intIssue_6_0_valid,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_6_0_bits_fuType,io_ooo_to_mem_intIssue_6_0_bits_fuType,36);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_6_0_bits_fuOpType,io_ooo_to_mem_intIssue_6_0_bits_fuOpType,9);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_6_0_bits_src_0,io_ooo_to_mem_intIssue_6_0_bits_src_0,64);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_6_0_bits_robIdx_flag,io_ooo_to_mem_intIssue_6_0_bits_robIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_6_0_bits_robIdx_value,io_ooo_to_mem_intIssue_6_0_bits_robIdx_value,9);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_6_0_bits_sqIdx_flag,io_ooo_to_mem_intIssue_6_0_bits_sqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_6_0_bits_sqIdx_value,io_ooo_to_mem_intIssue_6_0_bits_sqIdx_value,6);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_5_0_ready,io_ooo_to_mem_intIssue_5_0_ready,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_5_0_valid,io_ooo_to_mem_intIssue_5_0_valid,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_5_0_bits_fuType,io_ooo_to_mem_intIssue_5_0_bits_fuType,36);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_5_0_bits_fuOpType,io_ooo_to_mem_intIssue_5_0_bits_fuOpType,9);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_5_0_bits_src_0,io_ooo_to_mem_intIssue_5_0_bits_src_0,64);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_5_0_bits_robIdx_flag,io_ooo_to_mem_intIssue_5_0_bits_robIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_5_0_bits_robIdx_value,io_ooo_to_mem_intIssue_5_0_bits_robIdx_value,9);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_5_0_bits_sqIdx_flag,io_ooo_to_mem_intIssue_5_0_bits_sqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_5_0_bits_sqIdx_value,io_ooo_to_mem_intIssue_5_0_bits_sqIdx_value,6);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_4_0_ready,io_ooo_to_mem_intIssue_4_0_ready,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_4_0_valid,io_ooo_to_mem_intIssue_4_0_valid,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_4_0_bits_fuType,io_ooo_to_mem_intIssue_4_0_bits_fuType,36);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_4_0_bits_fuOpType,io_ooo_to_mem_intIssue_4_0_bits_fuOpType,9);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_4_0_bits_src_0,io_ooo_to_mem_intIssue_4_0_bits_src_0,64);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_4_0_bits_imm,io_ooo_to_mem_intIssue_4_0_bits_imm,64);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_4_0_bits_robIdx_flag,io_ooo_to_mem_intIssue_4_0_bits_robIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_4_0_bits_robIdx_value,io_ooo_to_mem_intIssue_4_0_bits_robIdx_value,9);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_4_0_bits_isFirstIssue,io_ooo_to_mem_intIssue_4_0_bits_isFirstIssue,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_4_0_bits_pdest,io_ooo_to_mem_intIssue_4_0_bits_pdest,8);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_4_0_bits_isRVC,io_ooo_to_mem_intIssue_4_0_bits_isRVC,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_flag,io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_value,io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_value,6);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_4_0_bits_ftqOffset,io_ooo_to_mem_intIssue_4_0_bits_ftqOffset,5);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_4_0_bits_storeSetHit,io_ooo_to_mem_intIssue_4_0_bits_storeSetHit,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_4_0_bits_ssid,io_ooo_to_mem_intIssue_4_0_bits_ssid,5);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_4_0_bits_sqIdx_flag,io_ooo_to_mem_intIssue_4_0_bits_sqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_4_0_bits_sqIdx_value,io_ooo_to_mem_intIssue_4_0_bits_sqIdx_value,6);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_3_0_ready,io_ooo_to_mem_intIssue_3_0_ready,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_3_0_valid,io_ooo_to_mem_intIssue_3_0_valid,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_3_0_bits_fuType,io_ooo_to_mem_intIssue_3_0_bits_fuType,36);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_3_0_bits_fuOpType,io_ooo_to_mem_intIssue_3_0_bits_fuOpType,9);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_3_0_bits_src_0,io_ooo_to_mem_intIssue_3_0_bits_src_0,64);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_3_0_bits_imm,io_ooo_to_mem_intIssue_3_0_bits_imm,64);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_3_0_bits_robIdx_flag,io_ooo_to_mem_intIssue_3_0_bits_robIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_3_0_bits_robIdx_value,io_ooo_to_mem_intIssue_3_0_bits_robIdx_value,9);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_3_0_bits_isFirstIssue,io_ooo_to_mem_intIssue_3_0_bits_isFirstIssue,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_3_0_bits_pdest,io_ooo_to_mem_intIssue_3_0_bits_pdest,8);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_3_0_bits_isRVC,io_ooo_to_mem_intIssue_3_0_bits_isRVC,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_flag,io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_value,io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_value,6);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_3_0_bits_ftqOffset,io_ooo_to_mem_intIssue_3_0_bits_ftqOffset,5);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_3_0_bits_storeSetHit,io_ooo_to_mem_intIssue_3_0_bits_storeSetHit,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_3_0_bits_ssid,io_ooo_to_mem_intIssue_3_0_bits_ssid,5);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_3_0_bits_sqIdx_flag,io_ooo_to_mem_intIssue_3_0_bits_sqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_3_0_bits_sqIdx_value,io_ooo_to_mem_intIssue_3_0_bits_sqIdx_value,6);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_2_0_ready,io_ooo_to_mem_intIssue_2_0_ready,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_2_0_valid,io_ooo_to_mem_intIssue_2_0_valid,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_2_0_bits_fuOpType,io_ooo_to_mem_intIssue_2_0_bits_fuOpType,9);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_2_0_bits_src_0,io_ooo_to_mem_intIssue_2_0_bits_src_0,64);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_2_0_bits_imm,io_ooo_to_mem_intIssue_2_0_bits_imm,64);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_2_0_bits_robIdx_flag,io_ooo_to_mem_intIssue_2_0_bits_robIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_2_0_bits_robIdx_value,io_ooo_to_mem_intIssue_2_0_bits_robIdx_value,9);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_2_0_bits_pdest,io_ooo_to_mem_intIssue_2_0_bits_pdest,8);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_2_0_bits_rfWen,io_ooo_to_mem_intIssue_2_0_bits_rfWen,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_2_0_bits_fpWen,io_ooo_to_mem_intIssue_2_0_bits_fpWen,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_2_0_bits_pc,io_ooo_to_mem_intIssue_2_0_bits_pc,50);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_2_0_bits_isRVC,io_ooo_to_mem_intIssue_2_0_bits_isRVC,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_flag,io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_value,io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_value,6);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_2_0_bits_ftqOffset,io_ooo_to_mem_intIssue_2_0_bits_ftqOffset,5);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_2_0_bits_loadWaitBit,io_ooo_to_mem_intIssue_2_0_bits_loadWaitBit,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_flag,io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_value,io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_value,9);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_2_0_bits_storeSetHit,io_ooo_to_mem_intIssue_2_0_bits_storeSetHit,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_2_0_bits_loadWaitStrict,io_ooo_to_mem_intIssue_2_0_bits_loadWaitStrict,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_2_0_bits_lqIdx_flag,io_ooo_to_mem_intIssue_2_0_bits_lqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_2_0_bits_lqIdx_value,io_ooo_to_mem_intIssue_2_0_bits_lqIdx_value,7);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_2_0_bits_sqIdx_flag,io_ooo_to_mem_intIssue_2_0_bits_sqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_2_0_bits_sqIdx_value,io_ooo_to_mem_intIssue_2_0_bits_sqIdx_value,6);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_1_0_ready,io_ooo_to_mem_intIssue_1_0_ready,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_1_0_valid,io_ooo_to_mem_intIssue_1_0_valid,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_1_0_bits_fuOpType,io_ooo_to_mem_intIssue_1_0_bits_fuOpType,9);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_1_0_bits_src_0,io_ooo_to_mem_intIssue_1_0_bits_src_0,64);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_1_0_bits_imm,io_ooo_to_mem_intIssue_1_0_bits_imm,64);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_1_0_bits_robIdx_flag,io_ooo_to_mem_intIssue_1_0_bits_robIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_1_0_bits_robIdx_value,io_ooo_to_mem_intIssue_1_0_bits_robIdx_value,9);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_1_0_bits_pdest,io_ooo_to_mem_intIssue_1_0_bits_pdest,8);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_1_0_bits_rfWen,io_ooo_to_mem_intIssue_1_0_bits_rfWen,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_1_0_bits_fpWen,io_ooo_to_mem_intIssue_1_0_bits_fpWen,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_1_0_bits_pc,io_ooo_to_mem_intIssue_1_0_bits_pc,50);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_1_0_bits_isRVC,io_ooo_to_mem_intIssue_1_0_bits_isRVC,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_flag,io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_value,io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_value,6);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_1_0_bits_ftqOffset,io_ooo_to_mem_intIssue_1_0_bits_ftqOffset,5);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_1_0_bits_loadWaitBit,io_ooo_to_mem_intIssue_1_0_bits_loadWaitBit,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_flag,io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_value,io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_value,9);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_1_0_bits_storeSetHit,io_ooo_to_mem_intIssue_1_0_bits_storeSetHit,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_1_0_bits_loadWaitStrict,io_ooo_to_mem_intIssue_1_0_bits_loadWaitStrict,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_1_0_bits_lqIdx_flag,io_ooo_to_mem_intIssue_1_0_bits_lqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_1_0_bits_lqIdx_value,io_ooo_to_mem_intIssue_1_0_bits_lqIdx_value,7);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_1_0_bits_sqIdx_flag,io_ooo_to_mem_intIssue_1_0_bits_sqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_1_0_bits_sqIdx_value,io_ooo_to_mem_intIssue_1_0_bits_sqIdx_value,6);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_0_0_ready,io_ooo_to_mem_intIssue_0_0_ready,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_0_0_valid,io_ooo_to_mem_intIssue_0_0_valid,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_0_0_bits_fuOpType,io_ooo_to_mem_intIssue_0_0_bits_fuOpType,9);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_0_0_bits_src_0,io_ooo_to_mem_intIssue_0_0_bits_src_0,64);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_0_0_bits_imm,io_ooo_to_mem_intIssue_0_0_bits_imm,64);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_0_0_bits_robIdx_flag,io_ooo_to_mem_intIssue_0_0_bits_robIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_0_0_bits_robIdx_value,io_ooo_to_mem_intIssue_0_0_bits_robIdx_value,9);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_0_0_bits_pdest,io_ooo_to_mem_intIssue_0_0_bits_pdest,8);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_0_0_bits_rfWen,io_ooo_to_mem_intIssue_0_0_bits_rfWen,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_0_0_bits_fpWen,io_ooo_to_mem_intIssue_0_0_bits_fpWen,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_0_0_bits_pc,io_ooo_to_mem_intIssue_0_0_bits_pc,50);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_0_0_bits_isRVC,io_ooo_to_mem_intIssue_0_0_bits_isRVC,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_flag,io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_value,io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_value,6);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_0_0_bits_ftqOffset,io_ooo_to_mem_intIssue_0_0_bits_ftqOffset,5);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_0_0_bits_loadWaitBit,io_ooo_to_mem_intIssue_0_0_bits_loadWaitBit,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_flag,io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_value,io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_value,9);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_0_0_bits_storeSetHit,io_ooo_to_mem_intIssue_0_0_bits_storeSetHit,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_0_0_bits_loadWaitStrict,io_ooo_to_mem_intIssue_0_0_bits_loadWaitStrict,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_0_0_bits_lqIdx_flag,io_ooo_to_mem_intIssue_0_0_bits_lqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_0_0_bits_lqIdx_value,io_ooo_to_mem_intIssue_0_0_bits_lqIdx_value,7);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_0_0_bits_sqIdx_flag,io_ooo_to_mem_intIssue_0_0_bits_sqIdx_flag,1);
            `TCNT_CHECK_SIG_XZ(io_ooo_to_mem_intIssue_0_0_bits_sqIdx_value,io_ooo_to_mem_intIssue_0_0_bits_sqIdx_value,6);

        end
        //if(xxxTODOxxx==1'b1) begin
        //    mon_tr = lintsissue_agent_agent_xaction::type_id::create("mon_tr");
        //    mon_tr.io_ooo_to_mem_intIssue_6_0_ready = io_ooo_to_mem_intIssue_6_0_ready;
        //    mon_tr.io_ooo_to_mem_intIssue_6_0_valid = io_ooo_to_mem_intIssue_6_0_valid;
        //    mon_tr.io_ooo_to_mem_intIssue_6_0_bits_fuType = io_ooo_to_mem_intIssue_6_0_bits_fuType;
        //    mon_tr.io_ooo_to_mem_intIssue_6_0_bits_fuOpType = io_ooo_to_mem_intIssue_6_0_bits_fuOpType;
        //    mon_tr.io_ooo_to_mem_intIssue_6_0_bits_src_0 = io_ooo_to_mem_intIssue_6_0_bits_src_0;
        //    mon_tr.io_ooo_to_mem_intIssue_6_0_bits_robIdx_flag = io_ooo_to_mem_intIssue_6_0_bits_robIdx_flag;
        //    mon_tr.io_ooo_to_mem_intIssue_6_0_bits_robIdx_value = io_ooo_to_mem_intIssue_6_0_bits_robIdx_value;
        //    mon_tr.io_ooo_to_mem_intIssue_6_0_bits_sqIdx_flag = io_ooo_to_mem_intIssue_6_0_bits_sqIdx_flag;
        //    mon_tr.io_ooo_to_mem_intIssue_6_0_bits_sqIdx_value = io_ooo_to_mem_intIssue_6_0_bits_sqIdx_value;
        //    mon_tr.io_ooo_to_mem_intIssue_5_0_ready = io_ooo_to_mem_intIssue_5_0_ready;
        //    mon_tr.io_ooo_to_mem_intIssue_5_0_valid = io_ooo_to_mem_intIssue_5_0_valid;
        //    mon_tr.io_ooo_to_mem_intIssue_5_0_bits_fuType = io_ooo_to_mem_intIssue_5_0_bits_fuType;
        //    mon_tr.io_ooo_to_mem_intIssue_5_0_bits_fuOpType = io_ooo_to_mem_intIssue_5_0_bits_fuOpType;
        //    mon_tr.io_ooo_to_mem_intIssue_5_0_bits_src_0 = io_ooo_to_mem_intIssue_5_0_bits_src_0;
        //    mon_tr.io_ooo_to_mem_intIssue_5_0_bits_robIdx_flag = io_ooo_to_mem_intIssue_5_0_bits_robIdx_flag;
        //    mon_tr.io_ooo_to_mem_intIssue_5_0_bits_robIdx_value = io_ooo_to_mem_intIssue_5_0_bits_robIdx_value;
        //    mon_tr.io_ooo_to_mem_intIssue_5_0_bits_sqIdx_flag = io_ooo_to_mem_intIssue_5_0_bits_sqIdx_flag;
        //    mon_tr.io_ooo_to_mem_intIssue_5_0_bits_sqIdx_value = io_ooo_to_mem_intIssue_5_0_bits_sqIdx_value;
        //    mon_tr.io_ooo_to_mem_intIssue_4_0_ready = io_ooo_to_mem_intIssue_4_0_ready;
        //    mon_tr.io_ooo_to_mem_intIssue_4_0_valid = io_ooo_to_mem_intIssue_4_0_valid;
        //    mon_tr.io_ooo_to_mem_intIssue_4_0_bits_fuType = io_ooo_to_mem_intIssue_4_0_bits_fuType;
        //    mon_tr.io_ooo_to_mem_intIssue_4_0_bits_fuOpType = io_ooo_to_mem_intIssue_4_0_bits_fuOpType;
        //    mon_tr.io_ooo_to_mem_intIssue_4_0_bits_src_0 = io_ooo_to_mem_intIssue_4_0_bits_src_0;
        //    mon_tr.io_ooo_to_mem_intIssue_4_0_bits_imm = io_ooo_to_mem_intIssue_4_0_bits_imm;
        //    mon_tr.io_ooo_to_mem_intIssue_4_0_bits_robIdx_flag = io_ooo_to_mem_intIssue_4_0_bits_robIdx_flag;
        //    mon_tr.io_ooo_to_mem_intIssue_4_0_bits_robIdx_value = io_ooo_to_mem_intIssue_4_0_bits_robIdx_value;
        //    mon_tr.io_ooo_to_mem_intIssue_4_0_bits_isFirstIssue = io_ooo_to_mem_intIssue_4_0_bits_isFirstIssue;
        //    mon_tr.io_ooo_to_mem_intIssue_4_0_bits_pdest = io_ooo_to_mem_intIssue_4_0_bits_pdest;
        //    mon_tr.io_ooo_to_mem_intIssue_4_0_bits_isRVC = io_ooo_to_mem_intIssue_4_0_bits_isRVC;
        //    mon_tr.io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_flag = io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_flag;
        //    mon_tr.io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_value = io_ooo_to_mem_intIssue_4_0_bits_ftqIdx_value;
        //    mon_tr.io_ooo_to_mem_intIssue_4_0_bits_ftqOffset = io_ooo_to_mem_intIssue_4_0_bits_ftqOffset;
        //    mon_tr.io_ooo_to_mem_intIssue_4_0_bits_storeSetHit = io_ooo_to_mem_intIssue_4_0_bits_storeSetHit;
        //    mon_tr.io_ooo_to_mem_intIssue_4_0_bits_ssid = io_ooo_to_mem_intIssue_4_0_bits_ssid;
        //    mon_tr.io_ooo_to_mem_intIssue_4_0_bits_sqIdx_flag = io_ooo_to_mem_intIssue_4_0_bits_sqIdx_flag;
        //    mon_tr.io_ooo_to_mem_intIssue_4_0_bits_sqIdx_value = io_ooo_to_mem_intIssue_4_0_bits_sqIdx_value;
        //    mon_tr.io_ooo_to_mem_intIssue_3_0_ready = io_ooo_to_mem_intIssue_3_0_ready;
        //    mon_tr.io_ooo_to_mem_intIssue_3_0_valid = io_ooo_to_mem_intIssue_3_0_valid;
        //    mon_tr.io_ooo_to_mem_intIssue_3_0_bits_fuType = io_ooo_to_mem_intIssue_3_0_bits_fuType;
        //    mon_tr.io_ooo_to_mem_intIssue_3_0_bits_fuOpType = io_ooo_to_mem_intIssue_3_0_bits_fuOpType;
        //    mon_tr.io_ooo_to_mem_intIssue_3_0_bits_src_0 = io_ooo_to_mem_intIssue_3_0_bits_src_0;
        //    mon_tr.io_ooo_to_mem_intIssue_3_0_bits_imm = io_ooo_to_mem_intIssue_3_0_bits_imm;
        //    mon_tr.io_ooo_to_mem_intIssue_3_0_bits_robIdx_flag = io_ooo_to_mem_intIssue_3_0_bits_robIdx_flag;
        //    mon_tr.io_ooo_to_mem_intIssue_3_0_bits_robIdx_value = io_ooo_to_mem_intIssue_3_0_bits_robIdx_value;
        //    mon_tr.io_ooo_to_mem_intIssue_3_0_bits_isFirstIssue = io_ooo_to_mem_intIssue_3_0_bits_isFirstIssue;
        //    mon_tr.io_ooo_to_mem_intIssue_3_0_bits_pdest = io_ooo_to_mem_intIssue_3_0_bits_pdest;
        //    mon_tr.io_ooo_to_mem_intIssue_3_0_bits_isRVC = io_ooo_to_mem_intIssue_3_0_bits_isRVC;
        //    mon_tr.io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_flag = io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_flag;
        //    mon_tr.io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_value = io_ooo_to_mem_intIssue_3_0_bits_ftqIdx_value;
        //    mon_tr.io_ooo_to_mem_intIssue_3_0_bits_ftqOffset = io_ooo_to_mem_intIssue_3_0_bits_ftqOffset;
        //    mon_tr.io_ooo_to_mem_intIssue_3_0_bits_storeSetHit = io_ooo_to_mem_intIssue_3_0_bits_storeSetHit;
        //    mon_tr.io_ooo_to_mem_intIssue_3_0_bits_ssid = io_ooo_to_mem_intIssue_3_0_bits_ssid;
        //    mon_tr.io_ooo_to_mem_intIssue_3_0_bits_sqIdx_flag = io_ooo_to_mem_intIssue_3_0_bits_sqIdx_flag;
        //    mon_tr.io_ooo_to_mem_intIssue_3_0_bits_sqIdx_value = io_ooo_to_mem_intIssue_3_0_bits_sqIdx_value;
        //    mon_tr.io_ooo_to_mem_intIssue_2_0_ready = io_ooo_to_mem_intIssue_2_0_ready;
        //    mon_tr.io_ooo_to_mem_intIssue_2_0_valid = io_ooo_to_mem_intIssue_2_0_valid;
        //    mon_tr.io_ooo_to_mem_intIssue_2_0_bits_fuOpType = io_ooo_to_mem_intIssue_2_0_bits_fuOpType;
        //    mon_tr.io_ooo_to_mem_intIssue_2_0_bits_src_0 = io_ooo_to_mem_intIssue_2_0_bits_src_0;
        //    mon_tr.io_ooo_to_mem_intIssue_2_0_bits_imm = io_ooo_to_mem_intIssue_2_0_bits_imm;
        //    mon_tr.io_ooo_to_mem_intIssue_2_0_bits_robIdx_flag = io_ooo_to_mem_intIssue_2_0_bits_robIdx_flag;
        //    mon_tr.io_ooo_to_mem_intIssue_2_0_bits_robIdx_value = io_ooo_to_mem_intIssue_2_0_bits_robIdx_value;
        //    mon_tr.io_ooo_to_mem_intIssue_2_0_bits_pdest = io_ooo_to_mem_intIssue_2_0_bits_pdest;
        //    mon_tr.io_ooo_to_mem_intIssue_2_0_bits_rfWen = io_ooo_to_mem_intIssue_2_0_bits_rfWen;
        //    mon_tr.io_ooo_to_mem_intIssue_2_0_bits_fpWen = io_ooo_to_mem_intIssue_2_0_bits_fpWen;
        //    mon_tr.io_ooo_to_mem_intIssue_2_0_bits_pc = io_ooo_to_mem_intIssue_2_0_bits_pc;
        //    mon_tr.io_ooo_to_mem_intIssue_2_0_bits_isRVC = io_ooo_to_mem_intIssue_2_0_bits_isRVC;
        //    mon_tr.io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_flag = io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_flag;
        //    mon_tr.io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_value = io_ooo_to_mem_intIssue_2_0_bits_ftqIdx_value;
        //    mon_tr.io_ooo_to_mem_intIssue_2_0_bits_ftqOffset = io_ooo_to_mem_intIssue_2_0_bits_ftqOffset;
        //    mon_tr.io_ooo_to_mem_intIssue_2_0_bits_loadWaitBit = io_ooo_to_mem_intIssue_2_0_bits_loadWaitBit;
        //    mon_tr.io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_flag = io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_flag;
        //    mon_tr.io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_value = io_ooo_to_mem_intIssue_2_0_bits_waitForRobIdx_value;
        //    mon_tr.io_ooo_to_mem_intIssue_2_0_bits_storeSetHit = io_ooo_to_mem_intIssue_2_0_bits_storeSetHit;
        //    mon_tr.io_ooo_to_mem_intIssue_2_0_bits_loadWaitStrict = io_ooo_to_mem_intIssue_2_0_bits_loadWaitStrict;
        //    mon_tr.io_ooo_to_mem_intIssue_2_0_bits_lqIdx_flag = io_ooo_to_mem_intIssue_2_0_bits_lqIdx_flag;
        //    mon_tr.io_ooo_to_mem_intIssue_2_0_bits_lqIdx_value = io_ooo_to_mem_intIssue_2_0_bits_lqIdx_value;
        //    mon_tr.io_ooo_to_mem_intIssue_2_0_bits_sqIdx_flag = io_ooo_to_mem_intIssue_2_0_bits_sqIdx_flag;
        //    mon_tr.io_ooo_to_mem_intIssue_2_0_bits_sqIdx_value = io_ooo_to_mem_intIssue_2_0_bits_sqIdx_value;
        //    mon_tr.io_ooo_to_mem_intIssue_1_0_ready = io_ooo_to_mem_intIssue_1_0_ready;
        //    mon_tr.io_ooo_to_mem_intIssue_1_0_valid = io_ooo_to_mem_intIssue_1_0_valid;
        //    mon_tr.io_ooo_to_mem_intIssue_1_0_bits_fuOpType = io_ooo_to_mem_intIssue_1_0_bits_fuOpType;
        //    mon_tr.io_ooo_to_mem_intIssue_1_0_bits_src_0 = io_ooo_to_mem_intIssue_1_0_bits_src_0;
        //    mon_tr.io_ooo_to_mem_intIssue_1_0_bits_imm = io_ooo_to_mem_intIssue_1_0_bits_imm;
        //    mon_tr.io_ooo_to_mem_intIssue_1_0_bits_robIdx_flag = io_ooo_to_mem_intIssue_1_0_bits_robIdx_flag;
        //    mon_tr.io_ooo_to_mem_intIssue_1_0_bits_robIdx_value = io_ooo_to_mem_intIssue_1_0_bits_robIdx_value;
        //    mon_tr.io_ooo_to_mem_intIssue_1_0_bits_pdest = io_ooo_to_mem_intIssue_1_0_bits_pdest;
        //    mon_tr.io_ooo_to_mem_intIssue_1_0_bits_rfWen = io_ooo_to_mem_intIssue_1_0_bits_rfWen;
        //    mon_tr.io_ooo_to_mem_intIssue_1_0_bits_fpWen = io_ooo_to_mem_intIssue_1_0_bits_fpWen;
        //    mon_tr.io_ooo_to_mem_intIssue_1_0_bits_pc = io_ooo_to_mem_intIssue_1_0_bits_pc;
        //    mon_tr.io_ooo_to_mem_intIssue_1_0_bits_isRVC = io_ooo_to_mem_intIssue_1_0_bits_isRVC;
        //    mon_tr.io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_flag = io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_flag;
        //    mon_tr.io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_value = io_ooo_to_mem_intIssue_1_0_bits_ftqIdx_value;
        //    mon_tr.io_ooo_to_mem_intIssue_1_0_bits_ftqOffset = io_ooo_to_mem_intIssue_1_0_bits_ftqOffset;
        //    mon_tr.io_ooo_to_mem_intIssue_1_0_bits_loadWaitBit = io_ooo_to_mem_intIssue_1_0_bits_loadWaitBit;
        //    mon_tr.io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_flag = io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_flag;
        //    mon_tr.io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_value = io_ooo_to_mem_intIssue_1_0_bits_waitForRobIdx_value;
        //    mon_tr.io_ooo_to_mem_intIssue_1_0_bits_storeSetHit = io_ooo_to_mem_intIssue_1_0_bits_storeSetHit;
        //    mon_tr.io_ooo_to_mem_intIssue_1_0_bits_loadWaitStrict = io_ooo_to_mem_intIssue_1_0_bits_loadWaitStrict;
        //    mon_tr.io_ooo_to_mem_intIssue_1_0_bits_lqIdx_flag = io_ooo_to_mem_intIssue_1_0_bits_lqIdx_flag;
        //    mon_tr.io_ooo_to_mem_intIssue_1_0_bits_lqIdx_value = io_ooo_to_mem_intIssue_1_0_bits_lqIdx_value;
        //    mon_tr.io_ooo_to_mem_intIssue_1_0_bits_sqIdx_flag = io_ooo_to_mem_intIssue_1_0_bits_sqIdx_flag;
        //    mon_tr.io_ooo_to_mem_intIssue_1_0_bits_sqIdx_value = io_ooo_to_mem_intIssue_1_0_bits_sqIdx_value;
        //    mon_tr.io_ooo_to_mem_intIssue_0_0_ready = io_ooo_to_mem_intIssue_0_0_ready;
        //    mon_tr.io_ooo_to_mem_intIssue_0_0_valid = io_ooo_to_mem_intIssue_0_0_valid;
        //    mon_tr.io_ooo_to_mem_intIssue_0_0_bits_fuOpType = io_ooo_to_mem_intIssue_0_0_bits_fuOpType;
        //    mon_tr.io_ooo_to_mem_intIssue_0_0_bits_src_0 = io_ooo_to_mem_intIssue_0_0_bits_src_0;
        //    mon_tr.io_ooo_to_mem_intIssue_0_0_bits_imm = io_ooo_to_mem_intIssue_0_0_bits_imm;
        //    mon_tr.io_ooo_to_mem_intIssue_0_0_bits_robIdx_flag = io_ooo_to_mem_intIssue_0_0_bits_robIdx_flag;
        //    mon_tr.io_ooo_to_mem_intIssue_0_0_bits_robIdx_value = io_ooo_to_mem_intIssue_0_0_bits_robIdx_value;
        //    mon_tr.io_ooo_to_mem_intIssue_0_0_bits_pdest = io_ooo_to_mem_intIssue_0_0_bits_pdest;
        //    mon_tr.io_ooo_to_mem_intIssue_0_0_bits_rfWen = io_ooo_to_mem_intIssue_0_0_bits_rfWen;
        //    mon_tr.io_ooo_to_mem_intIssue_0_0_bits_fpWen = io_ooo_to_mem_intIssue_0_0_bits_fpWen;
        //    mon_tr.io_ooo_to_mem_intIssue_0_0_bits_pc = io_ooo_to_mem_intIssue_0_0_bits_pc;
        //    mon_tr.io_ooo_to_mem_intIssue_0_0_bits_isRVC = io_ooo_to_mem_intIssue_0_0_bits_isRVC;
        //    mon_tr.io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_flag = io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_flag;
        //    mon_tr.io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_value = io_ooo_to_mem_intIssue_0_0_bits_ftqIdx_value;
        //    mon_tr.io_ooo_to_mem_intIssue_0_0_bits_ftqOffset = io_ooo_to_mem_intIssue_0_0_bits_ftqOffset;
        //    mon_tr.io_ooo_to_mem_intIssue_0_0_bits_loadWaitBit = io_ooo_to_mem_intIssue_0_0_bits_loadWaitBit;
        //    mon_tr.io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_flag = io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_flag;
        //    mon_tr.io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_value = io_ooo_to_mem_intIssue_0_0_bits_waitForRobIdx_value;
        //    mon_tr.io_ooo_to_mem_intIssue_0_0_bits_storeSetHit = io_ooo_to_mem_intIssue_0_0_bits_storeSetHit;
        //    mon_tr.io_ooo_to_mem_intIssue_0_0_bits_loadWaitStrict = io_ooo_to_mem_intIssue_0_0_bits_loadWaitStrict;
        //    mon_tr.io_ooo_to_mem_intIssue_0_0_bits_lqIdx_flag = io_ooo_to_mem_intIssue_0_0_bits_lqIdx_flag;
        //    mon_tr.io_ooo_to_mem_intIssue_0_0_bits_lqIdx_value = io_ooo_to_mem_intIssue_0_0_bits_lqIdx_value;
        //    mon_tr.io_ooo_to_mem_intIssue_0_0_bits_sqIdx_flag = io_ooo_to_mem_intIssue_0_0_bits_sqIdx_flag;
        //    mon_tr.io_ooo_to_mem_intIssue_0_0_bits_sqIdx_value = io_ooo_to_mem_intIssue_0_0_bits_sqIdx_value;

        //    mon_tr.channel_id = this.cfg.channel_id;
        //    mon_tr.unpack();
        //    this.mon_item_port.write(mon_tr);
        //end
    end
endtask:mon_data

`endif
