set_property PACKAGE_PIN F12 [get_ports {led[7]}]
set_property PACKAGE_PIN G12 [get_ports {led[6]}]
set_property PACKAGE_PIN G11 [get_ports {led[5]}]
set_property PACKAGE_PIN H11 [get_ports {led[4]}]
set_property PACKAGE_PIN F10 [get_ports {led[3]}]
set_property PACKAGE_PIN G10 [get_ports {led[2]}]
set_property PACKAGE_PIN H9  [get_ports {led[1]}]
set_property PACKAGE_PIN H10 [get_ports {led[0]}]

set_property IOSTANDARD LVCMOS18 [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {led[0]}]
