// Copyright (c) 2024-2025 Beijing Institute of Open Source Chip (BOSC)
// Copyright (c) 2020-2025 Institute of Computing Technology, Chinese Academy of Sciences
// Copyright (c) 2020-2021 Peng Cheng Laboratory
//
// XiangShan is licensed under Mulan PSL v2.
// You can use this software according to the terms and conditions of the Mulan PSL v2.
// You may obtain a copy of Mulan PSL v2 at:
//          https://license.coscl.org.cn/MulanPSL2
//
// THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
// EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
// MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
//
// See the Mulan PSL v2 for more details.

package xiangshan.frontend.bpu.ras

import chisel3._
import chisel3.util._
import org.chipsalliance.cde.config.Parameters
import utility.XSPerfAccumulate
import xiangshan.frontend.GuardedPc
import xiangshan.frontend.bpu.BasePredictor
import xiangshan.frontend.bpu.BasePredictorIO
import xiangshan.frontend.bpu.BranchAttribute
import xiangshan.frontend.bpu.HalfAlignHelper

/**
 * A speculative micro Return Address Stack (micro-RAS) used in the branch predictor.
 *
 * This module tracks pending call/return operations in the S1–S3 pipeline stages
 * and predicts the return target for upcoming RET instructions by modeling
 * the effect of in-flight push/pop operations on the main RAS.
 *
 * It outputs a predicted return address and a validity flag indicating whether
 * the prediction can be trusted in the current cycle.
 */
//
class MicroRas(implicit p: Parameters) extends BasePredictor with HasRasParameters with HalfAlignHelper {
  class MicroRasIO(implicit p: Parameters) extends BasePredictorIO {

    /** Input bundle containing speculative CFI (Control Flow Instruction) info from S1 */
    class MicroRasSpecIn extends Bundle {
      val startPc:     GuardedPc       = GuardedPc()
      val cfiPosition: UInt            = UInt(CfiPositionWidth.W)
      val attribute:   BranchAttribute = new BranchAttribute
    }

    /** Output bundle providing predicted return target and validity */
    class MicroRasSpecOut extends Bundle {
      val retTarget: GuardedPc = GuardedPc() // Predicted return address
      val isCanUse:  Bool      = Bool()      // Whether the prediction is valid
    }
    val specIn:      MicroRasSpecIn  = Input(new MicroRasSpecIn)
    val specOut:     MicroRasSpecOut = Output(new MicroRasSpecOut)
    val hasRedirect: Bool            = Input(Bool()) // Global redirect signal (e.g., misprediction)
    val overrideData: Valid[MicroRasSpecIn] = Input(Valid(new MicroRasSpecIn)) // S3-level override (flushes S1–S2)
    val fullRetAddr:  GuardedPc             = Input(GuardedPc())               // Current top of the main RAS
  }
  val io = IO(new MicroRasIO)
  io.sramResetDone := true.B
  io.trainReady    := true.B

  // Track whether S2/S3 stages contain pending push/pop operations
  private val s2_hasPush = RegInit(false.B)
  private val s2_hasPop  = RegInit(false.B)
  private val s3_hasPush = RegInit(false.B)
  private val s3_hasPop  = RegInit(false.B)

  // Store return addresses generated by speculative pushes
  private val stackAddr        = RegInit(VecInit(Seq.fill(MicroRasDepth)(0.U.asTypeOf(GuardedPc()))))
  private val stackHead        = RegInit(MicroRasPtr(false.B, 0.U))
  private val pushCountInStack = RegInit(0.U(log2Ceil(MicroRasDepth + 1).W))

  // Final output: whether a valid return target is available, and what its target is.
  private val isCanUse   = RegInit(false.B)
  private val topRetAddr = RegInit(0.U.asTypeOf(GuardedPc()))

  // Decode speculative operation from S1 input
  private val specPush = io.specIn.attribute.isCall
  private val specPop  = io.specIn.attribute.isReturn
  // Compute return address for a CALL
  private val specPushAddr = getCfiPcFromPosition(io.specIn.startPc, io.specIn.cfiPosition) + 2.U

  // One-cycle delayed version of redirect; used to detect RAS recovery state
  private val redirectDelay1 = RegNext(io.hasRedirect, init = false.B)
  private val hasOverride    = io.overrideData.valid
  private val s3_realPush    = io.overrideData.bits.attribute.isCall
  private val s3_realPop     = io.overrideData.bits.attribute.isReturn
  private val s3_realPushAddr =
    getCfiPcFromPosition(io.overrideData.bits.startPc, io.overrideData.bits.cfiPosition) + 2.U

  private val ptrZero       = 0.U.asTypeOf(new MicroRasPtr)
  private val pcZero        = 0.U.asTypeOf(GuardedPc())
  private val zeroPushCount = 0.U(log2Ceil(MicroRasDepth + 1).W)
  private val onePushCount  = 1.U(log2Ceil(MicroRasDepth + 1).W)
  private val flushPipeline = hasOverride || io.hasRedirect
  private val s1Fire        = io.stageCtrl.s1_fire
  private val s2Fire        = io.stageCtrl.s2_fire
  private val s3Fire        = io.stageCtrl.s3_fire
  private val s1SpecPush    = s1Fire && specPush
  private val s1SpecPop     = s1Fire && specPop
  private val s1Normal      = s1Fire && !specPush && !specPop
  private val s2MoveToS3    = s2Fire
  private val s3Clear       = s3Fire

  private val s2_stackHead        = RegInit(MicroRasPtr(false.B, 0.U))
  private val s2_pushCountInStack = RegInit(0.U(log2Ceil(MicroRasDepth + 1).W))
  private val s3_stackHead        = RegInit(MicroRasPtr(false.B, 0.U))
  private val s3_pushCountInStack = RegInit(0.U(log2Ceil(MicroRasDepth + 1).W))
  // -------------------------------
  // Pipeline control for S2 stage
  // -------------------------------
  when(flushPipeline) {
    s2_hasPush          := false.B
    s2_hasPop           := false.B
    s2_stackHead        := ptrZero
    s2_pushCountInStack := zeroPushCount
  }.elsewhen(s1Fire) {
    s2_hasPush          := specPush
    s2_hasPop           := specPop
    s2_stackHead        := stackHead
    s2_pushCountInStack := pushCountInStack
  }.elsewhen(s2Fire) {
    s2_hasPush          := false.B
    s2_hasPop           := false.B
    s2_stackHead        := ptrZero
    s2_pushCountInStack := zeroPushCount
  }

  // -------------------------------
  // Pipeline control for S3 stage
  // -------------------------------
  when(flushPipeline) {
    // Redirect flushes entire pipeline, including S3
    s3_hasPush          := false.B
    s3_hasPop           := false.B
    s3_stackHead        := ptrZero
    s3_pushCountInStack := 0.U
  }.elsewhen(s2MoveToS3) {
    // Move S2 ops into S3
    s3_hasPush          := s2_hasPush
    s3_hasPop           := s2_hasPop
    s3_stackHead        := s2_stackHead
    s3_pushCountInStack := s2_pushCountInStack
  }.elsewhen(s3Clear) {
    // Clear S3 after it completes
    s3_hasPush          := false.B
    s3_hasPop           := false.B
    s3_stackHead        := ptrZero
    s3_pushCountInStack := 0.U
  }

  private val hasAnyInFlightRasAction = s3_hasPush || s2_hasPush // 发生旧值覆盖，在Override时无法恢复。

  when(io.hasRedirect) {
    stackHead        := ptrZero
    pushCountInStack := zeroPushCount
    // stackAddr
  }.elsewhen(hasOverride) {
    when(hasAnyInFlightRasAction) {
      when(s3_realPush) {
        stackHead        := 1.U.asTypeOf(new MicroRasPtr)
        pushCountInStack := onePushCount
        stackAddr(0)     := s3_realPushAddr
      }.otherwise {
        stackHead        := ptrZero
        pushCountInStack := zeroPushCount
      }
    }.otherwise {
      when(s3_realPush) {
        pushCountInStack := Mux(s3_pushCountInStack === MicroRasDepth.U, s3_pushCountInStack, s3_pushCountInStack + 1.U)
        stackAddr(s3_stackHead.value) := s3_realPushAddr
        stackHead                     := s3_stackHead + 1.U
      }.elsewhen(s3_realPop) {
        pushCountInStack := Mux(s3_pushCountInStack === 0.U, s3_pushCountInStack, s3_pushCountInStack - 1.U)
        // stackAddr(s3_stackHead.value)
        stackHead := s3_stackHead - 1.U
      }.otherwise {
        pushCountInStack := s3_pushCountInStack
        stackHead        := s3_stackHead
      }
    }
  }.elsewhen(s1SpecPush) {
    pushCountInStack           := Mux(pushCountInStack === MicroRasDepth.U, pushCountInStack, pushCountInStack + 1.U)
    stackAddr(stackHead.value) := specPushAddr
    stackHead                  := stackHead + 1.U
  }.elsewhen(s1SpecPop) {
    stackHead        := stackHead - 1.U
    pushCountInStack := Mux(pushCountInStack === 0.U, pushCountInStack, pushCountInStack - 1.U)
    // stackAddr
  }.otherwise {
    // stackHead := stackHead
    // pushCountInStack := pushCountInStack
    // stackAddr
  }

  // ------------------------------------------------------------
  // Main logic: compute the effective top-of-stack return address
  // that should be used by S1 in the next cycle.
  // ------------------------------------------------------------
  private val stackHasMoreThanOne   = pushCountInStack > 1.U
  private val stackHasAny           = pushCountInStack > 0.U
  private val inFlightNoRasAction   = !s2_hasPush && !s2_hasPop && !s3_hasPush && !s3_hasPop
  private val inFlightPushPopPair   = s3_hasPush && s2_hasPop
  private val canUseMainRasTop      = inFlightNoRasAction || inFlightPushPopPair
  private val stackTopRetAddr       = stackAddr((stackHead - 1.U).value)
  private val stackSecondTopRetAddr = stackAddr((stackHead - 2.U).value)

  when(io.hasRedirect) {
    // On redirect, the main RAS state is being restored,
    // and the URAS stack needs to be flushed, so the top address cannot be obtained.
    isCanUse := false.B
  }.elsewhen(hasOverride) {
    // When override occurs, the stack data needs to be flushed.
    // If the override itself is a push operation, the top stack data is the push address at override.
    // If the override itself is a pop operation, the top stack data cannot be obtained.
    // If the override is a normal operation, the top stack data can be fetched from mainRAS.
    isCanUse := !s3_realPop // Without popping, stack top data can be fetched from s3 or Main RAS.
    topRetAddr :=
      Mux(
        s3_realPop,
        pcZero,
        Mux(s3_realPush, s3_realPushAddr, io.fullRetAddr)
      )
  }.elsewhen(s1SpecPush) {
    // S1 sees a CALL → next cycle’s RAS top will be the return address of this CALL.
    isCanUse   := true.B
    topRetAddr := specPushAddr
  }.elsewhen(s1SpecPop) {
    // When s1 is a Pop operation:
    // If the number of data in the stack is greater than 1,
    // the next cycle's stack top is the next item of the current stack top,
    // because the current stack top data will be consumed.
    // Otherwise, the stack will be empty in the next cycle, so the next cycle's stack top item cannot be provided.
    // Also, because a Pop operation occurs, the MainRAS stack changes, so the stack top item cannot be provided either.
    when(stackHasMoreThanOne) {
      isCanUse   := true.B
      topRetAddr := stackSecondTopRetAddr
    }.otherwise {
      isCanUse   := false.B
      topRetAddr := pcZero
    }
  }.elsewhen(s1Normal) {
    // When s1 is a normal operation:
    // If the number of data in the stack is greater than 0, the next cycle's stack top is the current stack top item.
    // If the stack is empty, and the operations ready to be sent to MainRAS will not affect the MainRAS stack top,
    // then the next cycle's stack top item can be obtained from MainRAS.
    // When the above conditions are not met, the stack top item cannot be provided.
    when(stackHasAny) {
      isCanUse   := true.B
      topRetAddr := stackTopRetAddr
    }.elsewhen(canUseMainRasTop) {
      isCanUse   := !redirectDelay1
      topRetAddr := Mux(redirectDelay1, pcZero, io.fullRetAddr)
    }.otherwise {
      isCanUse   := false.B
      topRetAddr := pcZero
    }
  }

  io.specOut.isCanUse  := isCanUse
  io.specOut.retTarget := topRetAddr

  private val s3_overrideHasRasAction     = hasOverride && (s3_realPush || s3_realPop)
  private val s3_overrideHasRasActionNext = RegNext(s3_overrideHasRasAction, false.B)
  private val s2_canUse                   = RegEnable(isCanUse, io.stageCtrl.s1_fire)
  private val s3_canUse                   = RegEnable(s2_canUse, io.stageCtrl.s2_fire)
  private val s1MismatchS3Pop             = hasOverride && s3_hasPop && s3_realPop && s3_canUse
  private val needMicroRasTotalNum        = s3_hasPop && s3_realPop
  private val wrongNeedMicroRasTotalNum   = s3_hasPop && hasOverride && s3_realPop
  dontTouch(s1MismatchS3Pop)
  dontTouch(needMicroRasTotalNum)
  dontTouch(wrongNeedMicroRasTotalNum)
  XSPerfAccumulate("s3_override_has_rasAction", s3_overrideHasRasAction)
  XSPerfAccumulate("s1_pop_mismatch_s3_pop", s1MismatchS3Pop)
  XSPerfAccumulate(
    "s1_has_return_after_override_has_action",
    s3_overrideHasRasActionNext && io.stageCtrl.s1_fire && specPop
  )
  XSPerfAccumulate("need_micro_ras_total_num", needMicroRasTotalNum)
  XSPerfAccumulate("wrong_need_micro_ras_total_num", wrongNeedMicroRasTotalNum)
}
