from __future__ import annotations

from toffee import Bundle, Signal


class CSRControlBundle(Bundle):
    io_tlbCsr_priv_imode = Signal()
    io_tlbCsr_priv_virt = Signal()
    io_tlbCsr_priv_virt_changed = Signal()
    io_tlbCsr_satp_mode = Signal()
    io_tlbCsr_satp_asid = Signal()
    io_tlbCsr_satp_ppn = Signal()
    io_tlbCsr_satp_changed = Signal()
    io_tlbCsr_vsatp_mode = Signal()
    io_tlbCsr_vsatp_asid = Signal()
    io_tlbCsr_vsatp_ppn = Signal()
    io_tlbCsr_vsatp_changed = Signal()
    io_tlbCsr_hgatp_mode = Signal()
    io_tlbCsr_hgatp_vmid = Signal()
    io_tlbCsr_hgatp_ppn = Signal()
    io_tlbCsr_hgatp_changed = Signal()
    io_tlbCsr_mPBMTE = Signal()
    io_tlbCsr_hPBMTE = Signal()
    io_tlbCsr_mbmc_BCLEAR = Signal()
    io_tlbCsr_mbmc_BMA = Signal()
    io_tlbCsr_priv_mxr = Signal()
    io_tlbCsr_priv_sum = Signal()
    io_tlbCsr_priv_vmxr = Signal()
    io_tlbCsr_priv_vsum = Signal()
    io_tlbCsr_priv_spvp = Signal()
    io_tlbCsr_priv_dmode = Signal()
    io_tlbCsr_pmm_mseccfg = Signal()
    io_tlbCsr_pmm_menvcfg = Signal()
    io_tlbCsr_pmm_henvcfg = Signal()
    io_tlbCsr_pmm_hstatus = Signal()
    io_tlbCsr_pmm_senvcfg = Signal()
    io_csrCtrl_bp_ctrl_ubtbEnable = Signal()
    io_csrCtrl_bp_ctrl_abtbEnable = Signal()
    io_csrCtrl_bp_ctrl_mbtbEnable = Signal()
    io_csrCtrl_bp_ctrl_tageEnable = Signal()
    io_csrCtrl_bp_ctrl_scEnable = Signal()
    io_csrCtrl_bp_ctrl_ittageEnable = Signal()
    io_csrCtrl_pf_ctrl_l1I_pf_enable = Signal()
    io_csrCtrl_fsIsOff = Signal()
    io_csrCtrl_distribute_csr_w_valid = Signal()
    io_csrCtrl_distribute_csr_w_bits_addr = Signal()
    io_csrCtrl_distribute_csr_w_bits_data = Signal()
    io_csrCtrl_sbuffer_timeout = Signal()
    io_csrCtrl_ldld_vio_check_enable = Signal()
    io_csrCtrl_cache_error_enable = Signal()
    io_csrCtrl_mem_trigger_tUpdate_valid = Signal()
    io_csrCtrl_mem_trigger_tUpdate_bits_addr = Signal()
    io_csrCtrl_mem_trigger_tUpdate_bits_tdata_matchType = Signal()
    io_csrCtrl_mem_trigger_tUpdate_bits_tdata_select = Signal()
    io_csrCtrl_mem_trigger_tUpdate_bits_tdata_action = Signal()
    io_csrCtrl_mem_trigger_tUpdate_bits_tdata_chain = Signal()
    io_csrCtrl_mem_trigger_tUpdate_bits_tdata_store = Signal()
    io_csrCtrl_mem_trigger_tUpdate_bits_tdata_load = Signal()
    io_csrCtrl_mem_trigger_tUpdate_bits_tdata_tdata2 = Signal()
    io_csrCtrl_mem_trigger_tEnableVec_0 = Signal()
    io_csrCtrl_mem_trigger_tEnableVec_1 = Signal()
    io_csrCtrl_mem_trigger_tEnableVec_2 = Signal()
    io_csrCtrl_mem_trigger_tEnableVec_3 = Signal()
    io_csrCtrl_mem_trigger_debugMode = Signal()
    io_csrCtrl_mem_trigger_triggerCanRaiseBpExp = Signal()

    def drive_idle(
        self,
        ubtb_enable: int = 1,
        abtb_enable: int = 1,
        mbtb_enable: int = 1,
        tage_enable: int = 1,
        sc_enable: int = 1,
        ittage_enable: int = 1,
    ) -> None:
        self.io_tlbCsr_priv_imode.value = 3
        self.io_tlbCsr_priv_virt.value = 0
        self.io_tlbCsr_priv_virt_changed.value = 0
        self.io_tlbCsr_satp_mode.value = 0
        self.io_tlbCsr_satp_asid.value = 0
        self.io_tlbCsr_satp_ppn.value = 0
        self.io_tlbCsr_satp_changed.value = 0
        self.io_tlbCsr_vsatp_mode.value = 0
        self.io_tlbCsr_vsatp_asid.value = 0
        self.io_tlbCsr_vsatp_ppn.value = 0
        self.io_tlbCsr_vsatp_changed.value = 0
        self.io_tlbCsr_hgatp_mode.value = 0
        self.io_tlbCsr_hgatp_vmid.value = 0
        self.io_tlbCsr_hgatp_ppn.value = 0
        self.io_tlbCsr_hgatp_changed.value = 0
        self.io_tlbCsr_mPBMTE.value = 0
        self.io_tlbCsr_hPBMTE.value = 0
        self.io_tlbCsr_mbmc_BCLEAR.value = 0
        self.io_tlbCsr_mbmc_BMA.value = 0
        self.io_tlbCsr_priv_mxr.value = 0
        self.io_tlbCsr_priv_sum.value = 0
        self.io_tlbCsr_priv_vmxr.value = 0
        self.io_tlbCsr_priv_vsum.value = 0
        self.io_tlbCsr_priv_spvp.value = 0
        self.io_tlbCsr_priv_dmode.value = 0
        self.io_tlbCsr_pmm_mseccfg.value = 0
        self.io_tlbCsr_pmm_menvcfg.value = 0
        self.io_tlbCsr_pmm_henvcfg.value = 0
        self.io_tlbCsr_pmm_hstatus.value = 0
        self.io_tlbCsr_pmm_senvcfg.value = 0
        self.io_csrCtrl_bp_ctrl_ubtbEnable.value = int(ubtb_enable)
        self.io_csrCtrl_bp_ctrl_abtbEnable.value = int(abtb_enable)
        self.io_csrCtrl_bp_ctrl_mbtbEnable.value = int(mbtb_enable)
        self.io_csrCtrl_bp_ctrl_tageEnable.value = int(tage_enable)
        self.io_csrCtrl_bp_ctrl_scEnable.value = int(sc_enable)
        self.io_csrCtrl_bp_ctrl_ittageEnable.value = int(ittage_enable)
        self.io_csrCtrl_pf_ctrl_l1I_pf_enable.value = 1
        self.io_csrCtrl_fsIsOff.value = 0
        self.io_csrCtrl_distribute_csr_w_valid.value = 0
        self.io_csrCtrl_distribute_csr_w_bits_addr.value = 0
        self.io_csrCtrl_distribute_csr_w_bits_data.value = 0
        self.io_csrCtrl_sbuffer_timeout.value = 0
        self.io_csrCtrl_ldld_vio_check_enable.value = 0
        self.io_csrCtrl_cache_error_enable.value = 0
        self.io_csrCtrl_mem_trigger_tUpdate_valid.value = 0
        self.io_csrCtrl_mem_trigger_tUpdate_bits_addr.value = 0
        self.io_csrCtrl_mem_trigger_tUpdate_bits_tdata_matchType.value = 0
        self.io_csrCtrl_mem_trigger_tUpdate_bits_tdata_select.value = 0
        self.io_csrCtrl_mem_trigger_tUpdate_bits_tdata_action.value = 0
        self.io_csrCtrl_mem_trigger_tUpdate_bits_tdata_chain.value = 0
        self.io_csrCtrl_mem_trigger_tUpdate_bits_tdata_store.value = 0
        self.io_csrCtrl_mem_trigger_tUpdate_bits_tdata_load.value = 0
        self.io_csrCtrl_mem_trigger_tUpdate_bits_tdata_tdata2.value = 0
        self.io_csrCtrl_mem_trigger_tEnableVec_0.value = 0
        self.io_csrCtrl_mem_trigger_tEnableVec_1.value = 0
        self.io_csrCtrl_mem_trigger_tEnableVec_2.value = 0
        self.io_csrCtrl_mem_trigger_tEnableVec_3.value = 0
        self.io_csrCtrl_mem_trigger_debugMode.value = 0
        self.io_csrCtrl_mem_trigger_triggerCanRaiseBpExp.value = 0
