//=========================================================
//File name    : io_mem_to_ooo_int_wb_agent_agent_interface.sv
//Author       : OpenAI_Codex
//Module name  : io_mem_to_ooo_int_wb_agent_agent_interface
//Discribution : io_mem_to_ooo_int_wb_agent_agent_interface : signal interface
//Date         : 2026-04-12
//=========================================================
`ifndef IO_MEM_TO_OOO_INT_WB_AGENT_AGENT_INTERFACE__SV
`define IO_MEM_TO_OOO_INT_WB_AGENT_AGENT_INTERFACE__SV

`ifndef DEF_SETUP_TIME
    `define DEF_SETUP_TIME 1
`endif
`ifndef DEF_HOLD_TIME
    `define DEF_HOLD_TIME 1
`endif

interface io_mem_to_ooo_int_wb_agent_agent_interface  (input bit clk,input bit rst_n);

    logic io_mem_to_ooo_intWriteback_6_0_valid;
    logic io_mem_to_ooo_intWriteback_6_0_bits_toRob_valid;
    logic io_mem_to_ooo_intWriteback_6_0_bits_toRob_bits_robIdx_flag;
    logic [8:0] io_mem_to_ooo_intWriteback_6_0_bits_toRob_bits_robIdx_value;
    logic io_mem_to_ooo_intWriteback_6_0_bits_toRob_bits_sqIdx_flag;
    logic [5:0] io_mem_to_ooo_intWriteback_6_0_bits_toRob_bits_sqIdx_value;
    logic io_mem_to_ooo_intWriteback_5_0_valid;
    logic io_mem_to_ooo_intWriteback_5_0_bits_toRob_valid;
    logic io_mem_to_ooo_intWriteback_5_0_bits_toRob_bits_robIdx_flag;
    logic [8:0] io_mem_to_ooo_intWriteback_5_0_bits_toRob_bits_robIdx_value;
    logic io_mem_to_ooo_intWriteback_5_0_bits_toRob_bits_sqIdx_flag;
    logic [5:0] io_mem_to_ooo_intWriteback_5_0_bits_toRob_bits_sqIdx_value;
    logic io_mem_to_ooo_intWriteback_4_0_valid;
    logic io_mem_to_ooo_intWriteback_4_0_bits_toRob_valid;
    logic io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_robIdx_flag;
    logic [8:0] io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_robIdx_value;
    logic io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_exceptionVec_3;
    logic io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_exceptionVec_6;
    logic io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_exceptionVec_7;
    logic io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_exceptionVec_15;
    logic io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_exceptionVec_19;
    logic io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_exceptionVec_23;
    logic [3:0] io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_trigger;
    logic io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_isRVC;
    logic io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_sqIdx_flag;
    logic [5:0] io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_sqIdx_value;
    logic io_mem_to_ooo_intWriteback_3_0_ready;
    logic io_mem_to_ooo_intWriteback_3_0_valid;
    logic io_mem_to_ooo_intWriteback_3_0_bits_toRob_valid;
    logic io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_robIdx_flag;
    logic [8:0] io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_robIdx_value;
    logic io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_exceptionVec_3;
    logic io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_exceptionVec_6;
    logic io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_exceptionVec_7;
    logic io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_exceptionVec_15;
    logic io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_exceptionVec_19;
    logic io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_exceptionVec_23;
    logic [3:0] io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_trigger;
    logic io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_isRVC;
    logic io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_sqIdx_flag;
    logic [5:0] io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_sqIdx_value;
    logic [7:0] io_mem_to_ooo_intWriteback_3_0_bits_pdest;
    logic io_mem_to_ooo_intWriteback_2_0_valid;
    logic io_mem_to_ooo_intWriteback_2_0_bits_toRob_valid;
    logic io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_robIdx_flag;
    logic [8:0] io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_robIdx_value;
    logic io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_0;
    logic io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_1;
    logic io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_2;
    logic io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_3;
    logic io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_4;
    logic io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_5;
    logic io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_6;
    logic io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_7;
    logic io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_8;
    logic io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_9;
    logic io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_10;
    logic io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_11;
    logic io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_12;
    logic io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_13;
    logic io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_14;
    logic io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_15;
    logic io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_16;
    logic io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_17;
    logic io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_18;
    logic io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_19;
    logic io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_20;
    logic io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_21;
    logic io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_22;
    logic io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_23;
    logic [3:0] io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_trigger;
    logic io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_isRVC;
    logic io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_lqIdx_flag;
    logic [6:0] io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_lqIdx_value;
    logic [7:0] io_mem_to_ooo_intWriteback_2_0_bits_pdest;
    logic io_mem_to_ooo_intWriteback_2_0_bits_toIntRf_valid;
    logic [63:0] io_mem_to_ooo_intWriteback_2_0_bits_toIntRf_bits;
    logic io_mem_to_ooo_intWriteback_2_0_bits_toFpRf_valid;
    logic [63:0] io_mem_to_ooo_intWriteback_2_0_bits_toFpRf_bits;
    logic io_mem_to_ooo_intWriteback_1_0_valid;
    logic io_mem_to_ooo_intWriteback_1_0_bits_toRob_valid;
    logic io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_robIdx_flag;
    logic [8:0] io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_robIdx_value;
    logic io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_0;
    logic io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_1;
    logic io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_2;
    logic io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_3;
    logic io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_4;
    logic io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_5;
    logic io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_6;
    logic io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_7;
    logic io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_8;
    logic io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_9;
    logic io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_10;
    logic io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_11;
    logic io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_12;
    logic io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_13;
    logic io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_14;
    logic io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_15;
    logic io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_16;
    logic io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_17;
    logic io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_18;
    logic io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_19;
    logic io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_20;
    logic io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_21;
    logic io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_22;
    logic io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_23;
    logic [3:0] io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_trigger;
    logic io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_isRVC;
    logic io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_lqIdx_flag;
    logic [6:0] io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_lqIdx_value;
    logic [7:0] io_mem_to_ooo_intWriteback_1_0_bits_pdest;
    logic io_mem_to_ooo_intWriteback_1_0_bits_toIntRf_valid;
    logic [63:0] io_mem_to_ooo_intWriteback_1_0_bits_toIntRf_bits;
    logic io_mem_to_ooo_intWriteback_1_0_bits_toFpRf_valid;
    logic [63:0] io_mem_to_ooo_intWriteback_1_0_bits_toFpRf_bits;
    logic io_mem_to_ooo_intWriteback_0_0_valid;
    logic io_mem_to_ooo_intWriteback_0_0_bits_toRob_valid;
    logic io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_robIdx_flag;
    logic [8:0] io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_robIdx_value;
    logic io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_0;
    logic io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_1;
    logic io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_2;
    logic io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_3;
    logic io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_4;
    logic io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_5;
    logic io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_6;
    logic io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_7;
    logic io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_8;
    logic io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_9;
    logic io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_10;
    logic io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_11;
    logic io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_12;
    logic io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_13;
    logic io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_14;
    logic io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_15;
    logic io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_16;
    logic io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_17;
    logic io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_18;
    logic io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_19;
    logic io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_20;
    logic io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_21;
    logic io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_22;
    logic io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_23;
    logic [3:0] io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_trigger;
    logic io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_isRVC;
    logic io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_lqIdx_flag;
    logic [6:0] io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_lqIdx_value;
    logic [7:0] io_mem_to_ooo_intWriteback_0_0_bits_pdest;
    logic io_mem_to_ooo_intWriteback_0_0_bits_toIntRf_valid;
    logic [63:0] io_mem_to_ooo_intWriteback_0_0_bits_toIntRf_bits;
    logic io_mem_to_ooo_intWriteback_0_0_bits_toFpRf_valid;
    logic [63:0] io_mem_to_ooo_intWriteback_0_0_bits_toFpRf_bits;
    logic io_mem_to_ooo_intWriteback_0_0_bits_isFromLoadUnit;

    clocking drv_cb @(posedge clk);
        `ifdef INTERFACE_ADD_DELAY
            default input #`DEF_SETUP_TIME output #`DEF_HOLD_TIME;
        `endif
        input  io_mem_to_ooo_intWriteback_6_0_valid;
        input  io_mem_to_ooo_intWriteback_6_0_bits_toRob_valid;
        input  io_mem_to_ooo_intWriteback_6_0_bits_toRob_bits_robIdx_flag;
        input  io_mem_to_ooo_intWriteback_6_0_bits_toRob_bits_robIdx_value;
        input  io_mem_to_ooo_intWriteback_6_0_bits_toRob_bits_sqIdx_flag;
        input  io_mem_to_ooo_intWriteback_6_0_bits_toRob_bits_sqIdx_value;
        input  io_mem_to_ooo_intWriteback_5_0_valid;
        input  io_mem_to_ooo_intWriteback_5_0_bits_toRob_valid;
        input  io_mem_to_ooo_intWriteback_5_0_bits_toRob_bits_robIdx_flag;
        input  io_mem_to_ooo_intWriteback_5_0_bits_toRob_bits_robIdx_value;
        input  io_mem_to_ooo_intWriteback_5_0_bits_toRob_bits_sqIdx_flag;
        input  io_mem_to_ooo_intWriteback_5_0_bits_toRob_bits_sqIdx_value;
        input  io_mem_to_ooo_intWriteback_4_0_valid;
        input  io_mem_to_ooo_intWriteback_4_0_bits_toRob_valid;
        input  io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_robIdx_flag;
        input  io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_robIdx_value;
        input  io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_exceptionVec_3;
        input  io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_exceptionVec_6;
        input  io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_exceptionVec_7;
        input  io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_exceptionVec_15;
        input  io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_exceptionVec_19;
        input  io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_exceptionVec_23;
        input  io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_trigger;
        input  io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_isRVC;
        input  io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_sqIdx_flag;
        input  io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_sqIdx_value;
        output io_mem_to_ooo_intWriteback_3_0_ready;
        input  io_mem_to_ooo_intWriteback_3_0_valid;
        input  io_mem_to_ooo_intWriteback_3_0_bits_toRob_valid;
        input  io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_robIdx_flag;
        input  io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_robIdx_value;
        input  io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_exceptionVec_3;
        input  io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_exceptionVec_6;
        input  io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_exceptionVec_7;
        input  io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_exceptionVec_15;
        input  io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_exceptionVec_19;
        input  io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_exceptionVec_23;
        input  io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_trigger;
        input  io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_isRVC;
        input  io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_sqIdx_flag;
        input  io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_sqIdx_value;
        input  io_mem_to_ooo_intWriteback_3_0_bits_pdest;
        input  io_mem_to_ooo_intWriteback_2_0_valid;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_valid;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_robIdx_flag;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_robIdx_value;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_0;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_1;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_2;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_3;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_4;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_5;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_6;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_7;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_8;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_9;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_10;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_11;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_12;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_13;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_14;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_15;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_16;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_17;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_18;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_19;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_20;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_21;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_22;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_23;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_trigger;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_isRVC;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_lqIdx_flag;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_lqIdx_value;
        input  io_mem_to_ooo_intWriteback_2_0_bits_pdest;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toIntRf_valid;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toIntRf_bits;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toFpRf_valid;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toFpRf_bits;
        input  io_mem_to_ooo_intWriteback_1_0_valid;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_valid;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_robIdx_flag;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_robIdx_value;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_0;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_1;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_2;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_3;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_4;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_5;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_6;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_7;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_8;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_9;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_10;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_11;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_12;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_13;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_14;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_15;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_16;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_17;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_18;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_19;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_20;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_21;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_22;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_23;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_trigger;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_isRVC;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_lqIdx_flag;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_lqIdx_value;
        input  io_mem_to_ooo_intWriteback_1_0_bits_pdest;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toIntRf_valid;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toIntRf_bits;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toFpRf_valid;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toFpRf_bits;
        input  io_mem_to_ooo_intWriteback_0_0_valid;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_valid;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_robIdx_flag;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_robIdx_value;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_0;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_1;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_2;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_3;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_4;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_5;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_6;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_7;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_8;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_9;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_10;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_11;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_12;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_13;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_14;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_15;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_16;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_17;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_18;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_19;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_20;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_21;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_22;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_23;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_trigger;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_isRVC;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_lqIdx_flag;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_lqIdx_value;
        input  io_mem_to_ooo_intWriteback_0_0_bits_pdest;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toIntRf_valid;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toIntRf_bits;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toFpRf_valid;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toFpRf_bits;
        input  io_mem_to_ooo_intWriteback_0_0_bits_isFromLoadUnit;

    endclocking:drv_cb

    clocking mon_cb @(posedge clk);
        `ifdef INTERFACE_ADD_DELAY
            default input #`DEF_SETUP_TIME output #`DEF_HOLD_TIME;
        `endif
        input  io_mem_to_ooo_intWriteback_6_0_valid;
        input  io_mem_to_ooo_intWriteback_6_0_bits_toRob_valid;
        input  io_mem_to_ooo_intWriteback_6_0_bits_toRob_bits_robIdx_flag;
        input  io_mem_to_ooo_intWriteback_6_0_bits_toRob_bits_robIdx_value;
        input  io_mem_to_ooo_intWriteback_6_0_bits_toRob_bits_sqIdx_flag;
        input  io_mem_to_ooo_intWriteback_6_0_bits_toRob_bits_sqIdx_value;
        input  io_mem_to_ooo_intWriteback_5_0_valid;
        input  io_mem_to_ooo_intWriteback_5_0_bits_toRob_valid;
        input  io_mem_to_ooo_intWriteback_5_0_bits_toRob_bits_robIdx_flag;
        input  io_mem_to_ooo_intWriteback_5_0_bits_toRob_bits_robIdx_value;
        input  io_mem_to_ooo_intWriteback_5_0_bits_toRob_bits_sqIdx_flag;
        input  io_mem_to_ooo_intWriteback_5_0_bits_toRob_bits_sqIdx_value;
        input  io_mem_to_ooo_intWriteback_4_0_valid;
        input  io_mem_to_ooo_intWriteback_4_0_bits_toRob_valid;
        input  io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_robIdx_flag;
        input  io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_robIdx_value;
        input  io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_exceptionVec_3;
        input  io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_exceptionVec_6;
        input  io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_exceptionVec_7;
        input  io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_exceptionVec_15;
        input  io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_exceptionVec_19;
        input  io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_exceptionVec_23;
        input  io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_trigger;
        input  io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_isRVC;
        input  io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_sqIdx_flag;
        input  io_mem_to_ooo_intWriteback_4_0_bits_toRob_bits_sqIdx_value;
        input  io_mem_to_ooo_intWriteback_3_0_ready;
        input  io_mem_to_ooo_intWriteback_3_0_valid;
        input  io_mem_to_ooo_intWriteback_3_0_bits_toRob_valid;
        input  io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_robIdx_flag;
        input  io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_robIdx_value;
        input  io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_exceptionVec_3;
        input  io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_exceptionVec_6;
        input  io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_exceptionVec_7;
        input  io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_exceptionVec_15;
        input  io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_exceptionVec_19;
        input  io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_exceptionVec_23;
        input  io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_trigger;
        input  io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_isRVC;
        input  io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_sqIdx_flag;
        input  io_mem_to_ooo_intWriteback_3_0_bits_toRob_bits_sqIdx_value;
        input  io_mem_to_ooo_intWriteback_3_0_bits_pdest;
        input  io_mem_to_ooo_intWriteback_2_0_valid;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_valid;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_robIdx_flag;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_robIdx_value;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_0;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_1;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_2;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_3;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_4;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_5;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_6;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_7;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_8;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_9;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_10;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_11;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_12;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_13;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_14;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_15;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_16;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_17;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_18;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_19;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_20;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_21;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_22;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_exceptionVec_23;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_trigger;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_isRVC;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_lqIdx_flag;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toRob_bits_lqIdx_value;
        input  io_mem_to_ooo_intWriteback_2_0_bits_pdest;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toIntRf_valid;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toIntRf_bits;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toFpRf_valid;
        input  io_mem_to_ooo_intWriteback_2_0_bits_toFpRf_bits;
        input  io_mem_to_ooo_intWriteback_1_0_valid;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_valid;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_robIdx_flag;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_robIdx_value;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_0;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_1;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_2;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_3;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_4;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_5;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_6;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_7;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_8;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_9;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_10;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_11;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_12;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_13;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_14;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_15;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_16;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_17;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_18;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_19;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_20;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_21;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_22;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_exceptionVec_23;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_trigger;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_isRVC;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_lqIdx_flag;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toRob_bits_lqIdx_value;
        input  io_mem_to_ooo_intWriteback_1_0_bits_pdest;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toIntRf_valid;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toIntRf_bits;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toFpRf_valid;
        input  io_mem_to_ooo_intWriteback_1_0_bits_toFpRf_bits;
        input  io_mem_to_ooo_intWriteback_0_0_valid;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_valid;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_robIdx_flag;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_robIdx_value;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_0;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_1;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_2;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_3;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_4;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_5;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_6;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_7;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_8;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_9;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_10;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_11;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_12;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_13;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_14;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_15;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_16;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_17;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_18;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_19;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_20;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_21;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_22;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_exceptionVec_23;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_trigger;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_isRVC;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_lqIdx_flag;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toRob_bits_lqIdx_value;
        input  io_mem_to_ooo_intWriteback_0_0_bits_pdest;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toIntRf_valid;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toIntRf_bits;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toFpRf_valid;
        input  io_mem_to_ooo_intWriteback_0_0_bits_toFpRf_bits;
        input  io_mem_to_ooo_intWriteback_0_0_bits_isFromLoadUnit;

    endclocking:mon_cb

    modport drv_mp (clocking drv_cb);
    modport mon_mp (clocking mon_cb);

endinterface:io_mem_to_ooo_int_wb_agent_agent_interface

`endif
