//=========================================================
//File name    : io_mem_to_ooo_int_wb_agent_agent_interface.sv
//Author       : OpenAI_Codex
//Module name  : io_mem_to_ooo_int_wb_agent_agent_interface
//Discribution : io_mem_to_ooo_int_wb_agent_agent_interface : signal interface
//Date         : 2026-04-12
//=========================================================

`ifndef IO_MEM_TO_OOO_INT_WB_AGENT_AGENT_INTERFACE__SV
`define IO_MEM_TO_OOO_INT_WB_AGENT_AGENT_INTERFACE__SV

`ifndef DEF_SETUP_TIME
    `define DEF_SETUP_TIME 1
`endif
`ifndef DEF_HOLD_TIME
    `define DEF_HOLD_TIME 1
`endif

interface io_mem_to_ooo_int_wb_agent_agent_interface  (input bit clk,input bit rst_n);

    logic io_mem_to_ooo_writebackLda_0_valid;
    logic io_mem_to_ooo_writebackLda_0_bits_uop_exceptionVec_3;
    logic io_mem_to_ooo_writebackLda_0_bits_uop_exceptionVec_4;
    logic io_mem_to_ooo_writebackLda_0_bits_uop_exceptionVec_5;
    logic io_mem_to_ooo_writebackLda_0_bits_uop_exceptionVec_6;
    logic io_mem_to_ooo_writebackLda_0_bits_uop_exceptionVec_7;
    logic io_mem_to_ooo_writebackLda_0_bits_uop_exceptionVec_13;
    logic io_mem_to_ooo_writebackLda_0_bits_uop_exceptionVec_15;
    logic io_mem_to_ooo_writebackLda_0_bits_uop_exceptionVec_19;
    logic io_mem_to_ooo_writebackLda_0_bits_uop_exceptionVec_21;
    logic io_mem_to_ooo_writebackLda_0_bits_uop_exceptionVec_23;
    logic [3:0] io_mem_to_ooo_writebackLda_0_bits_uop_trigger;
    logic io_mem_to_ooo_writebackLda_0_bits_uop_rfWen;
    logic io_mem_to_ooo_writebackLda_0_bits_uop_fpWen;
    logic io_mem_to_ooo_writebackLda_0_bits_uop_flushPipe;
    logic [7:0] io_mem_to_ooo_writebackLda_0_bits_uop_pdest;
    logic io_mem_to_ooo_writebackLda_0_bits_uop_robIdx_flag;
    logic [`MEMBLOCK_DUT_ROB_VALUE_W-1:0] io_mem_to_ooo_writebackLda_0_bits_uop_robIdx_value;
    logic io_mem_to_ooo_writebackLda_0_bits_uop_replayInst;
    logic [63:0] io_mem_to_ooo_writebackLda_0_bits_data;
    logic io_mem_to_ooo_writebackLda_0_bits_isFromLoadUnit;
    logic io_mem_to_ooo_writebackLda_0_bits_debug_isMMIO;
    logic io_mem_to_ooo_writebackLda_0_bits_debug_isNCIO;
    logic io_mem_to_ooo_writebackLda_0_bits_debug_isPerfCnt;
    logic io_mem_to_ooo_writebackLda_1_valid;
    logic io_mem_to_ooo_writebackLda_1_bits_uop_exceptionVec_3;
    logic io_mem_to_ooo_writebackLda_1_bits_uop_exceptionVec_4;
    logic io_mem_to_ooo_writebackLda_1_bits_uop_exceptionVec_5;
    logic io_mem_to_ooo_writebackLda_1_bits_uop_exceptionVec_13;
    logic io_mem_to_ooo_writebackLda_1_bits_uop_exceptionVec_19;
    logic io_mem_to_ooo_writebackLda_1_bits_uop_exceptionVec_21;
    logic [3:0] io_mem_to_ooo_writebackLda_1_bits_uop_trigger;
    logic io_mem_to_ooo_writebackLda_1_bits_uop_rfWen;
    logic io_mem_to_ooo_writebackLda_1_bits_uop_fpWen;
    logic io_mem_to_ooo_writebackLda_1_bits_uop_flushPipe;
    logic [7:0] io_mem_to_ooo_writebackLda_1_bits_uop_pdest;
    logic io_mem_to_ooo_writebackLda_1_bits_uop_robIdx_flag;
    logic [`MEMBLOCK_DUT_ROB_VALUE_W-1:0] io_mem_to_ooo_writebackLda_1_bits_uop_robIdx_value;
    logic io_mem_to_ooo_writebackLda_1_bits_uop_replayInst;
    logic [63:0] io_mem_to_ooo_writebackLda_1_bits_data;
    logic io_mem_to_ooo_writebackLda_1_bits_debug_isMMIO;
    logic io_mem_to_ooo_writebackLda_1_bits_debug_isNCIO;
    logic io_mem_to_ooo_writebackLda_1_bits_debug_isPerfCnt;
    logic io_mem_to_ooo_writebackLda_2_valid;
    logic io_mem_to_ooo_writebackLda_2_bits_uop_exceptionVec_3;
    logic io_mem_to_ooo_writebackLda_2_bits_uop_exceptionVec_4;
    logic io_mem_to_ooo_writebackLda_2_bits_uop_exceptionVec_5;
    logic io_mem_to_ooo_writebackLda_2_bits_uop_exceptionVec_13;
    logic io_mem_to_ooo_writebackLda_2_bits_uop_exceptionVec_19;
    logic io_mem_to_ooo_writebackLda_2_bits_uop_exceptionVec_21;
    logic [3:0] io_mem_to_ooo_writebackLda_2_bits_uop_trigger;
    logic io_mem_to_ooo_writebackLda_2_bits_uop_rfWen;
    logic io_mem_to_ooo_writebackLda_2_bits_uop_fpWen;
    logic io_mem_to_ooo_writebackLda_2_bits_uop_flushPipe;
    logic [7:0] io_mem_to_ooo_writebackLda_2_bits_uop_pdest;
    logic io_mem_to_ooo_writebackLda_2_bits_uop_robIdx_flag;
    logic [`MEMBLOCK_DUT_ROB_VALUE_W-1:0] io_mem_to_ooo_writebackLda_2_bits_uop_robIdx_value;
    logic io_mem_to_ooo_writebackLda_2_bits_uop_replayInst;
    logic [63:0] io_mem_to_ooo_writebackLda_2_bits_data;
    logic io_mem_to_ooo_writebackLda_2_bits_debug_isMMIO;
    logic io_mem_to_ooo_writebackLda_2_bits_debug_isNCIO;
    logic io_mem_to_ooo_writebackLda_2_bits_debug_isPerfCnt;
    logic io_mem_to_ooo_writebackSta_0_valid;
    logic io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_0;
    logic io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_1;
    logic io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_2;
    logic io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_3;
    logic io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_4;
    logic io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_5;
    logic io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_6;
    logic io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_7;
    logic io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_8;
    logic io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_9;
    logic io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_10;
    logic io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_11;
    logic io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_12;
    logic io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_13;
    logic io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_14;
    logic io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_15;
    logic io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_16;
    logic io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_17;
    logic io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_18;
    logic io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_19;
    logic io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_20;
    logic io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_21;
    logic io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_22;
    logic io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_23;
    logic [3:0] io_mem_to_ooo_writebackSta_0_bits_uop_trigger;
    logic io_mem_to_ooo_writebackSta_0_bits_uop_flushPipe;
    logic io_mem_to_ooo_writebackSta_0_bits_uop_robIdx_flag;
    logic [`MEMBLOCK_DUT_ROB_VALUE_W-1:0] io_mem_to_ooo_writebackSta_0_bits_uop_robIdx_value;
    logic io_mem_to_ooo_writebackSta_0_bits_debug_isMMIO;
    logic io_mem_to_ooo_writebackSta_0_bits_debug_isNCIO;
    logic io_mem_to_ooo_writebackSta_1_valid;
    logic io_mem_to_ooo_writebackSta_1_bits_uop_exceptionVec_3;
    logic io_mem_to_ooo_writebackSta_1_bits_uop_exceptionVec_6;
    logic io_mem_to_ooo_writebackSta_1_bits_uop_exceptionVec_7;
    logic io_mem_to_ooo_writebackSta_1_bits_uop_exceptionVec_15;
    logic io_mem_to_ooo_writebackSta_1_bits_uop_exceptionVec_19;
    logic io_mem_to_ooo_writebackSta_1_bits_uop_exceptionVec_23;
    logic [3:0] io_mem_to_ooo_writebackSta_1_bits_uop_trigger;
    logic io_mem_to_ooo_writebackSta_1_bits_uop_robIdx_flag;
    logic [`MEMBLOCK_DUT_ROB_VALUE_W-1:0] io_mem_to_ooo_writebackSta_1_bits_uop_robIdx_value;
    logic io_mem_to_ooo_writebackSta_1_bits_debug_isMMIO;
    logic io_mem_to_ooo_writebackSta_1_bits_debug_isNCIO;
    logic io_mem_to_ooo_writebackStd_0_valid;
    logic [`MEMBLOCK_DUT_ROB_VALUE_W-1:0] io_mem_to_ooo_writebackStd_0_bits_uop_robIdx_value;
    logic io_mem_to_ooo_writebackStd_1_valid;
    logic [`MEMBLOCK_DUT_ROB_VALUE_W-1:0] io_mem_to_ooo_writebackStd_1_bits_uop_robIdx_value;

    clocking drv_cb @(posedge clk);
        `ifdef INTERFACE_ADD_DELAY
            default input #`DEF_SETUP_TIME output #`DEF_HOLD_TIME;
        `endif
        input  io_mem_to_ooo_writebackLda_0_valid;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_exceptionVec_3;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_exceptionVec_4;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_exceptionVec_5;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_exceptionVec_6;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_exceptionVec_7;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_exceptionVec_13;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_exceptionVec_15;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_exceptionVec_19;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_exceptionVec_21;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_exceptionVec_23;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_trigger;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_rfWen;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_fpWen;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_flushPipe;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_pdest;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_robIdx_flag;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_robIdx_value;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_replayInst;
        input  io_mem_to_ooo_writebackLda_0_bits_data;
        input  io_mem_to_ooo_writebackLda_0_bits_isFromLoadUnit;
        input  io_mem_to_ooo_writebackLda_0_bits_debug_isMMIO;
        input  io_mem_to_ooo_writebackLda_0_bits_debug_isNCIO;
        input  io_mem_to_ooo_writebackLda_0_bits_debug_isPerfCnt;
        input  io_mem_to_ooo_writebackLda_1_valid;
        input  io_mem_to_ooo_writebackLda_1_bits_uop_exceptionVec_3;
        input  io_mem_to_ooo_writebackLda_1_bits_uop_exceptionVec_4;
        input  io_mem_to_ooo_writebackLda_1_bits_uop_exceptionVec_5;
        input  io_mem_to_ooo_writebackLda_1_bits_uop_exceptionVec_13;
        input  io_mem_to_ooo_writebackLda_1_bits_uop_exceptionVec_19;
        input  io_mem_to_ooo_writebackLda_1_bits_uop_exceptionVec_21;
        input  io_mem_to_ooo_writebackLda_1_bits_uop_trigger;
        input  io_mem_to_ooo_writebackLda_1_bits_uop_rfWen;
        input  io_mem_to_ooo_writebackLda_1_bits_uop_fpWen;
        input  io_mem_to_ooo_writebackLda_1_bits_uop_flushPipe;
        input  io_mem_to_ooo_writebackLda_1_bits_uop_pdest;
        input  io_mem_to_ooo_writebackLda_1_bits_uop_robIdx_flag;
        input  io_mem_to_ooo_writebackLda_1_bits_uop_robIdx_value;
        input  io_mem_to_ooo_writebackLda_1_bits_uop_replayInst;
        input  io_mem_to_ooo_writebackLda_1_bits_data;
        input  io_mem_to_ooo_writebackLda_1_bits_debug_isMMIO;
        input  io_mem_to_ooo_writebackLda_1_bits_debug_isNCIO;
        input  io_mem_to_ooo_writebackLda_1_bits_debug_isPerfCnt;
        input  io_mem_to_ooo_writebackLda_2_valid;
        input  io_mem_to_ooo_writebackLda_2_bits_uop_exceptionVec_3;
        input  io_mem_to_ooo_writebackLda_2_bits_uop_exceptionVec_4;
        input  io_mem_to_ooo_writebackLda_2_bits_uop_exceptionVec_5;
        input  io_mem_to_ooo_writebackLda_2_bits_uop_exceptionVec_13;
        input  io_mem_to_ooo_writebackLda_2_bits_uop_exceptionVec_19;
        input  io_mem_to_ooo_writebackLda_2_bits_uop_exceptionVec_21;
        input  io_mem_to_ooo_writebackLda_2_bits_uop_trigger;
        input  io_mem_to_ooo_writebackLda_2_bits_uop_rfWen;
        input  io_mem_to_ooo_writebackLda_2_bits_uop_fpWen;
        input  io_mem_to_ooo_writebackLda_2_bits_uop_flushPipe;
        input  io_mem_to_ooo_writebackLda_2_bits_uop_pdest;
        input  io_mem_to_ooo_writebackLda_2_bits_uop_robIdx_flag;
        input  io_mem_to_ooo_writebackLda_2_bits_uop_robIdx_value;
        input  io_mem_to_ooo_writebackLda_2_bits_uop_replayInst;
        input  io_mem_to_ooo_writebackLda_2_bits_data;
        input  io_mem_to_ooo_writebackLda_2_bits_debug_isMMIO;
        input  io_mem_to_ooo_writebackLda_2_bits_debug_isNCIO;
        input  io_mem_to_ooo_writebackLda_2_bits_debug_isPerfCnt;
        input  io_mem_to_ooo_writebackSta_0_valid;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_0;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_1;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_2;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_3;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_4;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_5;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_6;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_7;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_8;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_9;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_10;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_11;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_12;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_13;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_14;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_15;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_16;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_17;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_18;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_19;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_20;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_21;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_22;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_23;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_trigger;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_flushPipe;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_robIdx_flag;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_robIdx_value;
        input  io_mem_to_ooo_writebackSta_0_bits_debug_isMMIO;
        input  io_mem_to_ooo_writebackSta_0_bits_debug_isNCIO;
        input  io_mem_to_ooo_writebackSta_1_valid;
        input  io_mem_to_ooo_writebackSta_1_bits_uop_exceptionVec_3;
        input  io_mem_to_ooo_writebackSta_1_bits_uop_exceptionVec_6;
        input  io_mem_to_ooo_writebackSta_1_bits_uop_exceptionVec_7;
        input  io_mem_to_ooo_writebackSta_1_bits_uop_exceptionVec_15;
        input  io_mem_to_ooo_writebackSta_1_bits_uop_exceptionVec_19;
        input  io_mem_to_ooo_writebackSta_1_bits_uop_exceptionVec_23;
        input  io_mem_to_ooo_writebackSta_1_bits_uop_trigger;
        input  io_mem_to_ooo_writebackSta_1_bits_uop_robIdx_flag;
        input  io_mem_to_ooo_writebackSta_1_bits_uop_robIdx_value;
        input  io_mem_to_ooo_writebackSta_1_bits_debug_isMMIO;
        input  io_mem_to_ooo_writebackSta_1_bits_debug_isNCIO;
        input  io_mem_to_ooo_writebackStd_0_valid;
        input  io_mem_to_ooo_writebackStd_0_bits_uop_robIdx_value;
        input  io_mem_to_ooo_writebackStd_1_valid;
        input  io_mem_to_ooo_writebackStd_1_bits_uop_robIdx_value;
    endclocking:drv_cb

    clocking mon_cb @(posedge clk);
        `ifdef INTERFACE_ADD_DELAY
            default input #`DEF_SETUP_TIME output #`DEF_HOLD_TIME;
        `endif
        input  io_mem_to_ooo_writebackLda_0_valid;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_exceptionVec_3;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_exceptionVec_4;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_exceptionVec_5;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_exceptionVec_6;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_exceptionVec_7;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_exceptionVec_13;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_exceptionVec_15;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_exceptionVec_19;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_exceptionVec_21;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_exceptionVec_23;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_trigger;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_rfWen;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_fpWen;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_flushPipe;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_pdest;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_robIdx_flag;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_robIdx_value;
        input  io_mem_to_ooo_writebackLda_0_bits_uop_replayInst;
        input  io_mem_to_ooo_writebackLda_0_bits_data;
        input  io_mem_to_ooo_writebackLda_0_bits_isFromLoadUnit;
        input  io_mem_to_ooo_writebackLda_0_bits_debug_isMMIO;
        input  io_mem_to_ooo_writebackLda_0_bits_debug_isNCIO;
        input  io_mem_to_ooo_writebackLda_0_bits_debug_isPerfCnt;
        input  io_mem_to_ooo_writebackLda_1_valid;
        input  io_mem_to_ooo_writebackLda_1_bits_uop_exceptionVec_3;
        input  io_mem_to_ooo_writebackLda_1_bits_uop_exceptionVec_4;
        input  io_mem_to_ooo_writebackLda_1_bits_uop_exceptionVec_5;
        input  io_mem_to_ooo_writebackLda_1_bits_uop_exceptionVec_13;
        input  io_mem_to_ooo_writebackLda_1_bits_uop_exceptionVec_19;
        input  io_mem_to_ooo_writebackLda_1_bits_uop_exceptionVec_21;
        input  io_mem_to_ooo_writebackLda_1_bits_uop_trigger;
        input  io_mem_to_ooo_writebackLda_1_bits_uop_rfWen;
        input  io_mem_to_ooo_writebackLda_1_bits_uop_fpWen;
        input  io_mem_to_ooo_writebackLda_1_bits_uop_flushPipe;
        input  io_mem_to_ooo_writebackLda_1_bits_uop_pdest;
        input  io_mem_to_ooo_writebackLda_1_bits_uop_robIdx_flag;
        input  io_mem_to_ooo_writebackLda_1_bits_uop_robIdx_value;
        input  io_mem_to_ooo_writebackLda_1_bits_uop_replayInst;
        input  io_mem_to_ooo_writebackLda_1_bits_data;
        input  io_mem_to_ooo_writebackLda_1_bits_debug_isMMIO;
        input  io_mem_to_ooo_writebackLda_1_bits_debug_isNCIO;
        input  io_mem_to_ooo_writebackLda_1_bits_debug_isPerfCnt;
        input  io_mem_to_ooo_writebackLda_2_valid;
        input  io_mem_to_ooo_writebackLda_2_bits_uop_exceptionVec_3;
        input  io_mem_to_ooo_writebackLda_2_bits_uop_exceptionVec_4;
        input  io_mem_to_ooo_writebackLda_2_bits_uop_exceptionVec_5;
        input  io_mem_to_ooo_writebackLda_2_bits_uop_exceptionVec_13;
        input  io_mem_to_ooo_writebackLda_2_bits_uop_exceptionVec_19;
        input  io_mem_to_ooo_writebackLda_2_bits_uop_exceptionVec_21;
        input  io_mem_to_ooo_writebackLda_2_bits_uop_trigger;
        input  io_mem_to_ooo_writebackLda_2_bits_uop_rfWen;
        input  io_mem_to_ooo_writebackLda_2_bits_uop_fpWen;
        input  io_mem_to_ooo_writebackLda_2_bits_uop_flushPipe;
        input  io_mem_to_ooo_writebackLda_2_bits_uop_pdest;
        input  io_mem_to_ooo_writebackLda_2_bits_uop_robIdx_flag;
        input  io_mem_to_ooo_writebackLda_2_bits_uop_robIdx_value;
        input  io_mem_to_ooo_writebackLda_2_bits_uop_replayInst;
        input  io_mem_to_ooo_writebackLda_2_bits_data;
        input  io_mem_to_ooo_writebackLda_2_bits_debug_isMMIO;
        input  io_mem_to_ooo_writebackLda_2_bits_debug_isNCIO;
        input  io_mem_to_ooo_writebackLda_2_bits_debug_isPerfCnt;
        input  io_mem_to_ooo_writebackSta_0_valid;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_0;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_1;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_2;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_3;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_4;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_5;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_6;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_7;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_8;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_9;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_10;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_11;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_12;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_13;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_14;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_15;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_16;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_17;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_18;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_19;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_20;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_21;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_22;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_exceptionVec_23;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_trigger;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_flushPipe;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_robIdx_flag;
        input  io_mem_to_ooo_writebackSta_0_bits_uop_robIdx_value;
        input  io_mem_to_ooo_writebackSta_0_bits_debug_isMMIO;
        input  io_mem_to_ooo_writebackSta_0_bits_debug_isNCIO;
        input  io_mem_to_ooo_writebackSta_1_valid;
        input  io_mem_to_ooo_writebackSta_1_bits_uop_exceptionVec_3;
        input  io_mem_to_ooo_writebackSta_1_bits_uop_exceptionVec_6;
        input  io_mem_to_ooo_writebackSta_1_bits_uop_exceptionVec_7;
        input  io_mem_to_ooo_writebackSta_1_bits_uop_exceptionVec_15;
        input  io_mem_to_ooo_writebackSta_1_bits_uop_exceptionVec_19;
        input  io_mem_to_ooo_writebackSta_1_bits_uop_exceptionVec_23;
        input  io_mem_to_ooo_writebackSta_1_bits_uop_trigger;
        input  io_mem_to_ooo_writebackSta_1_bits_uop_robIdx_flag;
        input  io_mem_to_ooo_writebackSta_1_bits_uop_robIdx_value;
        input  io_mem_to_ooo_writebackSta_1_bits_debug_isMMIO;
        input  io_mem_to_ooo_writebackSta_1_bits_debug_isNCIO;
        input  io_mem_to_ooo_writebackStd_0_valid;
        input  io_mem_to_ooo_writebackStd_0_bits_uop_robIdx_value;
        input  io_mem_to_ooo_writebackStd_1_valid;
        input  io_mem_to_ooo_writebackStd_1_bits_uop_robIdx_value;
    endclocking:mon_cb

    modport drv_mp (clocking drv_cb);
    modport mon_mp (clocking mon_cb);

endinterface:io_mem_to_ooo_int_wb_agent_agent_interface

`endif // IO_MEM_TO_OOO_INT_WB_AGENT_AGENT_INTERFACE__SV
