module frontend_funcov_hub (
  input logic clock,
  input logic reset,
  input logic        atp_io_tlbCsr_priv_virt,
  input logic [3:0]  atp_io_tlbCsr_satp_mode,
  input logic [3:0]  atp_io_tlbCsr_vsatp_mode,
  input logic [3:0]  atp_io_tlbCsr_hgatp_mode,
  input logic        atp_io_tlbCsr_satp_changed,
  input logic        atp_io_tlbCsr_vsatp_changed,
  input logic        atp_io_tlbCsr_hgatp_changed,
  input logic        atp_io_tlbCsr_priv_virt_changed,
  input logic        atp_itlb_req_valid,
  input logic [49:0] atp_itlb_req_vaddr,
  input logic        atp_itlb_resp_miss,
  input logic        atp_ptw_req_valid,
  input logic        atp_ptw_req_ready,
  input logic [37:0] atp_ptw_req_vpn,
  input logic [1:0]  atp_ptw_req_s2xlate,
  input logic        atp_ptw_resp_valid,
  input logic [1:0]  atp_ptw_resp_s2xlate,
  input logic        atp_ptw_resp_s1_entry_v,
  input logic [1:0]  atp_ptw_resp_s1_entry_level,
  input logic        atp_ptw_resp_s1_entry_n,
  input logic [7:0]  atp_ptw_resp_s1_valididx,
  input logic [7:0]  atp_ptw_resp_s1_pteidx,
  input logic        atp_ptw_resp_s2_gpf,
  input logic        atp_ptw_resp_s2_gaf,
  input logic        atp_sfence_valid,
  input logic        atp_sfence_rs1,
  input logic        atp_sfence_rs2,
  input logic        atp_sfence_hv,
  input logic        atp_sfence_hg,
  input logic        atp_flush_pipe,
  input logic          atpr_io_tlbCsr_priv_virt,
  input logic [1:0]    atpr_io_tlbCsr_priv_imode,
  input logic [3:0]    atpr_io_tlbCsr_satp_mode,
  input logic [3:0]    atpr_io_tlbCsr_vsatp_mode,
  input logic [3:0]    atpr_io_tlbCsr_hgatp_mode,
  input logic [15:0]   atpr_io_tlbCsr_satp_asid,
  input logic [15:0]   atpr_io_tlbCsr_vsatp_asid,
  input logic [15:0]   atpr_io_tlbCsr_hgatp_vmid,
  input logic          atpr_io_tlbCsr_satp_changed,
  input logic          atpr_io_tlbCsr_vsatp_changed,
  input logic          atpr_io_tlbCsr_hgatp_changed,
  input logic          atpr_io_tlbCsr_priv_virt_changed,
  input logic          atpr_itlb_req_valid,
  input logic [49:0]   atpr_itlb_req_vaddr,
  input logic          atpr_itlb_resp_miss,
  input logic [1:0]    atpr_itlb_resp_pbmt,
  input logic          atpr_itlb_resp_pf_instr,
  input logic          atpr_itlb_resp_af_instr,
  input logic          atpr_itlb_resp_gpf_instr,
  input logic          atpr_ptw_req_valid,
  input logic          atpr_ptw_req_ready,
  input logic [37:0]   atpr_ptw_req_vpn,
  input logic [1:0]    atpr_ptw_req_s2xlate,
  input logic          atpr_ptw_resp_valid,
  input logic [1:0]    atpr_ptw_resp_s2xlate,
  input logic [1:0]    atpr_ptw_resp_s1_pbmt,
  input logic [1:0]    atpr_ptw_resp_s2_pbmt,
  input logic          atpr_ptw_resp_s1_v,
  input logic          atpr_ptw_resp_s1_perm_a,
  input logic          atpr_ptw_resp_s1_perm_u,
  input logic          atpr_ptw_resp_s1_perm_x,
  input logic          atpr_ptw_resp_s1_perm_w,
  input logic          atpr_ptw_resp_s1_perm_r,
  input logic          atpr_ptw_resp_s2_perm_a,
  input logic          atpr_ptw_resp_s2_perm_x,
  input logic          atpr_ptw_resp_s1_pf,
  input logic          atpr_ptw_resp_s1_af,
  input logic          atpr_ptw_resp_s2_gpf,
  input logic          atpr_ptw_resp_s2_gaf,
  input logic          atpr_sfence_valid,
  input logic          atpr_sfence_rs1,
  input logic          atpr_sfence_rs2,
  input logic [49:0]   atpr_sfence_addr,
  input logic [15:0]   atpr_sfence_id,
  input logic          atpr_sfence_hv,
  input logic          atpr_sfence_hg,
  input logic          atpr_redirect_valid,
  input logic          atpr_backend_can_accept,
  input logic [47:0]   atpr_pmp_addr_0,
  input logic [47:0]   atpr_pmp_addr_1,
  input logic [31:0]   atpr_pmp_cfg_l,
  input logic [63:0]   atpr_pmp_cfg_a,
  input logic [31:0]   atpr_pmp_cfg_x,
  input logic [1471:0] atpr_pmp_addr,
  input logic [1535:0] atpr_pmp_mask,
  input logic [31:0]   atpr_pma_cfg_c,
  input logic [63:0]   atpr_pma_cfg_a,
  input logic [31:0]   atpr_pma_cfg_x,
  input logic [1471:0] atpr_pma_addr,
  input logic [1535:0] atpr_pma_mask,
  input logic          atpr_pmp_checker_0_x,
  input logic          atpr_pmp_checker_1_x,
  input logic             ibuf_in_ready,
  input logic             ibuf_in_valid,
  input logic [35:0]      ibuf_in_valid_lanes,
  input logic [35:0]      ibuf_in_enq_enable,
  input logic [35:0]      ibuf_in_is_rvc,
  input logic [2:0]       ibuf_in_exception_type,
  input logic             ibuf_in_backend_exception,
  input logic             ibuf_in_exception_cross_page,
  input logic             ibuf_ibuffer_empty,
  input logic             ibuf_flush,
  input logic             ibuf_backend_can_accept,
  input logic [7:0]       ibuf_cfvec_valid,
  input logic [7:0][49:0] ibuf_cfvec_pc,
  input logic             ifed_ptw_resp_valid,
  input logic [1:0]       ifed_ptw_resp_s2xlate,
  input logic             ifed_ptw_resp_s1_pf,
  input logic             ifed_ptw_resp_s1_af,
  input logic             ifed_ptw_resp_s2_gpf,
  input logic             ifed_ptw_resp_s2_gaf,
  input logic             ifed_ptw_req_valid,
  input logic             ifed_ptw_req_ready,
  input logic [37:0]      ifed_ptw_req_vpn,
  input logic [1:0]       ifed_ptw_req_s2xlate,
  input logic             ifed_icache_d_valid,
  input logic             ifed_icache_d_denied,
  input logic             ifed_icache_d_corrupt,
  input logic             ifed_icache_cross64_first_denied,
  input logic             ifed_icache_cross64_first_corrupt,
  input logic             ifed_icache_cross64_second_denied,
  input logic             ifed_icache_cross64_second_corrupt,
  input logic             ifed_icache_cross64_rvi,
  input logic             ifed_icache_ifu_req_valid,
  input logic [48:0]      ifed_icache_ifu_start_vaddr,
  input logic [31:0]      ifed_icache_ifu_maybe_rvc_map,
  input logic [1:0]       ifed_icache_ifu_pbmt,
  input logic             ifed_icache_ifu_pmp_mmio,
  input logic [2:0]       ifed_icache_ifu_exception,
  input logic             ifed_icache_meta_ecc_error,
  input logic             ifed_icache_data_ecc_error,
  input logic             ifed_backend_can_accept,
  input logic             ifed_uncache_d_valid,
  input logic             ifed_uncache_d_denied,
  input logic             ifed_uncache_d_corrupt,
  input logic             ifed_uncache_req_valid,
  input logic             ifed_uncache_req_ready,
  input logic [2:0]       ifed_uncache_req_addr_low,
  input logic             ifed_uncache_ifu_resp_valid,
  input logic             ifed_uncache_ifu_resp_denied,
  input logic             ifed_uncache_ifu_resp_corrupt,
  input logic             ifed_uncache_ifu_resp_need_resend,
  input logic [46:0]       ifed_uncache_entry_req_addr,
  input logic             ifed_ifu_to_ibuffer_valid,
  input logic             ifed_ifu_to_ibuffer_ready,
  input logic             ifed_ifu_to_ibuffer_ftq_flag,
  input logic [5:0]       ifed_ifu_to_ibuffer_ftq_value,
  input logic [2:0]       ifed_ifu_exception_type,
  input logic             ifed_ifu_exception_cross_page,
  input logic             ifed_ifu_s2_req_is_uncache,
  input logic             ifed_ifu_s2_prev_end_half_rvi,
  input logic             ifed_ifu_s2_ftq_flag,
  input logic [5:0]       ifed_ifu_s2_ftq_value,
  input logic [2:0]       ifed_ifu_s2_icache_exception,
  input logic [2:0]       ifed_ifu_uncache_exception,
  input logic             ifed_trigger_pc_match,
  input logic             ifed_ifu_s2_cacheable,
  input logic             ifed_uncache_response_valid,
  input logic [7:0]       ifed_cfvec_valid,
  input logic [7:0]       ifed_cfvec_is_rvc,
  input logic [7:0]       ifed_cfvec_illegal_instruction,
  input logic [7:0][3:0]  ifed_cfvec_trigger,
  input logic        mmio_s2_valid,
  input logic        mmio_s2_req_is_uncache,
  input logic        mmio_s2_use_uncache,
  input logic        mmio_s2_double_line,
  input logic        mmio_s2_pmp_mmio_0,
  input logic [1:0]  mmio_s2_pbmt_0,
  input logic [2:0]  mmio_s2_exception_0,
  input logic [48:0] mmio_s2_pc_0,
  input logic        mmio_is_first_instr,
  input logic        mmio_uncache_input_valid,
  input logic        mmio_uncache_input_ready,
  input logic [1:0]  mmio_uncache_state,
  input logic        mmio_uncache_busy,
  input logic        mmio_ifu_stall,
  input logic        mmio_empty_after,
  input logic        mmio_backend_commit,
  input logic        mmio_backend_empty,
  input logic        mmio_ibuffer_empty,
  input logic        mmio_backend_can_accept,
  input logic        mmio_tl_a_valid,
  input logic        mmio_tl_a_ready,
  input logic [47:0] mmio_tl_a_addr,
  input logic        mmio_tl_d_valid,
  input logic [255:0] mmio_tl_d_data,
  input logic        mmio_tl_d_corrupt,
  input logic        mmio_tl_d_denied,
  input logic [1:0]  mmio_entry_state,
  input logic        mmio_entry_resending,
  input logic [46:0] mmio_entry_req_addr,
  input logic        mmio_uncache_resp_valid,
  input logic [31:0] mmio_uncache_resp_data,
  input logic [2:0]  mmio_uncache_resp_exception,
  input logic        mmio_uncache_resp_need_resend,
  input logic        mmio_to_ibuffer_valid,
  input logic        mmio_to_ibuffer_ready,
  input logic [35:0] mmio_to_ibuffer_enq,
  input logic [35:0] mmio_to_ibuffer_is_rvc,
  input logic [48:0] mmio_to_ibuffer_pc_0,
  input logic [2:0]  mmio_to_ibuffer_exception,
  input logic        mmio_to_ibuffer_exception_cross_page,
  input logic        mmio_backend_redirect,
  input logic        mmio_ifu_flush,
  input logic        mmio_uncache_redirect,
  input logic        mmio_wb_redirect,
  input logic        mmio_wb_path_valid,
  input logic [1:0]  mmio_uncache_branch_type,
  input logic        mmio_prev_end_half_rvi,
  input logic [15:0] mmio_prev_half_data,
  input logic [48:0] mmio_prev_half_pc,
  input logic [48:0] mmio_uncache_pc,
  input logic        mmio_cfvec_valid,
  input logic        mmio_wfi_safe,
  input logic        wfi_backend_req,
  input logic        wfi_delayed_req,
  input logic        wfi_backend_safe,
  input logic        wfi_icache_safe,
  input logic        wfi_instr_uncache_safe,
  input logic        wfi_icache_tl_a_valid,
  input logic        wfi_icache_tl_a_ready,
  input logic        wfi_instr_uncache_tl_a_valid,
  input logic        wfi_instr_uncache_tl_a_ready,
  input logic [13:0] wfi_icache_mshr_valid,
  input logic [13:0] wfi_icache_mshr_issue,
  input logic [1:0]  wfi_instr_uncache_entry_state,
  input logic        wfi_frontend_flush,
  input logic        wfi_backend_redirect,
  input logic        nc_icache_waylookup_valid,
  input logic [3:0]  nc_icache_waymask_0,
  input logic [3:0]  nc_icache_waymask_1,
  input logic                 rfr_backend_redirect_valid,
  input logic [49:0]          rfr_backend_redirect_target,
  input logic                 rfr_backend_redirect_level,
  input logic                 rfr_backend_redirect_is_rvc,
  input logic                 rfr_backend_redirect_iaf,
  input logic                 rfr_backend_redirect_ipf,
  input logic                 rfr_backend_redirect_igpf,
  input logic                 rfr_backend_redirect_is_ctrl,
  input logic                 rfr_backend_redirect_is_mem_vio,
  input logic                 rfr_ftq_idx_ahead_valid,
  input logic                 rfr_ftq_idx_ahead_flag,
  input logic [5:0]           rfr_ftq_idx_ahead_value,
  input logic                 rfr_backend_redirect_ftq_idx_flag,
  input logic [5:0]           rfr_backend_redirect_ftq_idx_value,
  input logic [4:0]           rfr_backend_redirect_ftq_offset,
  input logic                 rfr_ftq_meta_valid,
  input logic                 rfr_ftq_meta_idx_flag,
  input logic [5:0]           rfr_ftq_meta_idx_value,
  input logic                 rfr_to_bpu_redirect_valid,
  input logic [48:0]          rfr_to_bpu_redirect_target,
  input logic                 rfr_icache_redirect_flush,
  input logic                 rfr_bpu_flush_valid,
  input logic                 rfr_ifu_wb_redirect_valid,
  input logic [49:0]          rfr_ifu_wb_redirect_target,
  input logic                 rfr_ifu_wb_redirect_taken,
  input logic                 rfr_ifu_wb_redirect_is_rvc,
  input logic                 rfr_ibuffer_empty,
  input logic                 rfr_ibuffer_ready,
  input logic                 rfr_icache_response_valid,
  input logic                 rfr_uncache_response_valid,
  input logic                 rfr_uncache_response_need_resend,
  input logic [46:0]          rfr_uncache_entry_req_addr,
  input logic                 rfr_icache_a_valid,
  input logic                 rfr_icache_a_ready,
  input logic [3:0]           rfr_icache_a_source,
  input logic [3:0]           rfr_icache_d_source,
  input logic                 rfr_uncache_a_valid,
  input logic                 rfr_uncache_a_ready,
  input logic                 rfr_ifu_to_ibuffer_valid,
  input logic                 rfr_icache_to_ifu_valid,
  input logic                 rfr_main_fetch_valid,
  input logic                 rfr_main_fetch_ready,
  input logic                 rfr_prefetch_valid,
  input logic                 rfr_ifu_s1_valid,
  input logic                 rfr_ifu_s2_valid,
  input logic                 rfr_backend_can_accept,
  input logic                 rfr_pred_checker_remask_fault,
  input logic                 rfr_pred_checker_not_cfi_taken,
  input logic                 rfr_pred_checker_invalid_taken,
  input logic                 rfr_itlb_flush_pipe,
  input logic                 rfr_fencei,
  input logic                 rfr_icache_cacheable_hit,
  input logic                 rfr_prefetch_s1_valid,
  input logic                 rfr_prefetch_wait_itlb,
  input logic                 rfr_prefetch_tlb_latch_valid,
  input logic                 rfr_sfence_valid,
  input logic                 rfr_satp_changed,
  input logic                 rfr_vsatp_changed,
  input logic                 rfr_hgatp_changed,
  input logic                 rfr_priv_virt_changed,
  input logic [7:0]           rfr_cfvec_valid,
  input logic [7:0][49:0]     rfr_cfvec_pc,
  input logic [7:0]           rfr_cfvec_iaf,
  input logic [7:0]           rfr_cfvec_ipf,
  input logic [7:0]           rfr_cfvec_igpf,
  input logic [7:0]           rfr_cfvec_backend_exception
);

  frontend_atp_funcov u_atp (
    .clock(clock),
    .reset(reset),
    .io_tlbCsr_priv_virt(atpr_io_tlbCsr_priv_virt),
    .io_tlbCsr_priv_imode(atpr_io_tlbCsr_priv_imode),
    .io_tlbCsr_satp_mode(atpr_io_tlbCsr_satp_mode),
    .io_tlbCsr_vsatp_mode(atpr_io_tlbCsr_vsatp_mode),
    .io_tlbCsr_hgatp_mode(atpr_io_tlbCsr_hgatp_mode),
    .io_tlbCsr_satp_asid(atpr_io_tlbCsr_satp_asid),
    .io_tlbCsr_vsatp_asid(atpr_io_tlbCsr_vsatp_asid),
    .io_tlbCsr_hgatp_vmid(atpr_io_tlbCsr_hgatp_vmid),
    .io_tlbCsr_satp_changed(atpr_io_tlbCsr_satp_changed),
    .io_tlbCsr_vsatp_changed(atpr_io_tlbCsr_vsatp_changed),
    .io_tlbCsr_hgatp_changed(atpr_io_tlbCsr_hgatp_changed),
    .io_tlbCsr_priv_virt_changed(atpr_io_tlbCsr_priv_virt_changed),
    .itlb_req_valid(atpr_itlb_req_valid),
    .itlb_req_vaddr(atpr_itlb_req_vaddr),
    .itlb_resp_miss(atpr_itlb_resp_miss),
    .itlb_resp_pbmt(atpr_itlb_resp_pbmt),
    .itlb_resp_pf_instr(atpr_itlb_resp_pf_instr),
    .itlb_resp_af_instr(atpr_itlb_resp_af_instr),
    .itlb_resp_gpf_instr(atpr_itlb_resp_gpf_instr),
    .ptw_req_valid(atpr_ptw_req_valid),
    .ptw_req_ready(atpr_ptw_req_ready),
    .ptw_req_vpn(atpr_ptw_req_vpn),
    .ptw_req_s2xlate(atpr_ptw_req_s2xlate),
    .ptw_resp_valid(atpr_ptw_resp_valid),
    .ptw_resp_s2xlate(atpr_ptw_resp_s2xlate),
    .ptw_resp_s1_pbmt(atpr_ptw_resp_s1_pbmt),
    .ptw_resp_s2_pbmt(atpr_ptw_resp_s2_pbmt),
    .ptw_resp_s1_v(atpr_ptw_resp_s1_v),
    .ptw_resp_s1_perm_a(atpr_ptw_resp_s1_perm_a),
    .ptw_resp_s1_perm_u(atpr_ptw_resp_s1_perm_u),
    .ptw_resp_s1_perm_x(atpr_ptw_resp_s1_perm_x),
    .ptw_resp_s1_perm_w(atpr_ptw_resp_s1_perm_w),
    .ptw_resp_s1_perm_r(atpr_ptw_resp_s1_perm_r),
    .ptw_resp_s2_perm_a(atpr_ptw_resp_s2_perm_a),
    .ptw_resp_s2_perm_x(atpr_ptw_resp_s2_perm_x),
    .ptw_resp_s1_pf(atpr_ptw_resp_s1_pf),
    .ptw_resp_s1_af(atpr_ptw_resp_s1_af),
    .ptw_resp_s2_gpf(atpr_ptw_resp_s2_gpf),
    .ptw_resp_s2_gaf(atpr_ptw_resp_s2_gaf),
    .ptw_resp_s1_entry_level(atp_ptw_resp_s1_entry_level),
    .ptw_resp_s1_entry_n(atp_ptw_resp_s1_entry_n),
    .ptw_resp_s1_valididx(atp_ptw_resp_s1_valididx),
    .ptw_resp_s1_pteidx(atp_ptw_resp_s1_pteidx),
    .flush_pipe(atp_flush_pipe),
    .sfence_valid(atpr_sfence_valid),
    .sfence_rs1(atpr_sfence_rs1),
    .sfence_rs2(atpr_sfence_rs2),
    .sfence_addr(atpr_sfence_addr),
    .sfence_id(atpr_sfence_id),
    .sfence_hv(atpr_sfence_hv),
    .sfence_hg(atpr_sfence_hg),
    .redirect_valid(atpr_redirect_valid),
    .backend_can_accept(atpr_backend_can_accept),
    .pmp_addr_0(atpr_pmp_addr_0),
    .pmp_addr_1(atpr_pmp_addr_1),
    .pmp_cfg_l(atpr_pmp_cfg_l),
    .pmp_cfg_a(atpr_pmp_cfg_a),
    .pmp_cfg_x(atpr_pmp_cfg_x),
    .pmp_addr(atpr_pmp_addr),
    .pmp_mask(atpr_pmp_mask),
    .pma_cfg_c(atpr_pma_cfg_c),
    .pma_cfg_a(atpr_pma_cfg_a),
    .pma_cfg_x(atpr_pma_cfg_x),
    .pma_addr(atpr_pma_addr),
    .pma_mask(atpr_pma_mask),
    .pmp_checker_0_x(atpr_pmp_checker_0_x),
    .pmp_checker_1_x(atpr_pmp_checker_1_x)
  );

  frontend_ibuffer_funcov u_ibuf (
    .clock(clock),
    .reset(reset),
    .in_ready(ibuf_in_ready),
    .in_valid(ibuf_in_valid),
    .in_valid_lanes(ibuf_in_valid_lanes),
    .in_enq_enable(ibuf_in_enq_enable),
    .in_is_rvc(ibuf_in_is_rvc),
    .in_exception_type(ibuf_in_exception_type),
    .in_backend_exception(ibuf_in_backend_exception),
    .in_exception_cross_page(ibuf_in_exception_cross_page),
    .ibuffer_empty(ibuf_ibuffer_empty),
    .flush(ibuf_flush),
    .backend_can_accept(ibuf_backend_can_accept),
    .cfvec_valid(ibuf_cfvec_valid),
    .cfvec_pc(ibuf_cfvec_pc)
  );

  frontend_ifu_exception_delivery_funcov u_ifed (
    .clock(clock),
    .reset(reset),
    .ptw_resp_valid(ifed_ptw_resp_valid),
    .ptw_resp_s2xlate(ifed_ptw_resp_s2xlate),
    .ptw_resp_s1_pf(ifed_ptw_resp_s1_pf),
    .ptw_resp_s1_af(ifed_ptw_resp_s1_af),
    .ptw_resp_s2_gpf(ifed_ptw_resp_s2_gpf),
    .ptw_resp_s2_gaf(ifed_ptw_resp_s2_gaf),
    .ptw_req_valid(ifed_ptw_req_valid),
    .ptw_req_ready(ifed_ptw_req_ready),
    .ptw_req_vpn(ifed_ptw_req_vpn),
    .ptw_req_s2xlate(ifed_ptw_req_s2xlate),
    .icache_d_valid(ifed_icache_d_valid),
    .icache_d_denied(ifed_icache_d_denied),
    .icache_d_corrupt(ifed_icache_d_corrupt),
    .icache_cross64_first_denied(ifed_icache_cross64_first_denied),
    .icache_cross64_first_corrupt(ifed_icache_cross64_first_corrupt),
    .icache_cross64_second_denied(ifed_icache_cross64_second_denied),
    .icache_cross64_second_corrupt(ifed_icache_cross64_second_corrupt),
    .icache_cross64_rvi(ifed_icache_cross64_rvi),
    .icache_ifu_req_valid(ifed_icache_ifu_req_valid),
    .icache_ifu_start_vaddr(ifed_icache_ifu_start_vaddr),
    .icache_ifu_maybe_rvc_map(ifed_icache_ifu_maybe_rvc_map),
    .icache_ifu_pbmt(ifed_icache_ifu_pbmt),
    .icache_ifu_pmp_mmio(ifed_icache_ifu_pmp_mmio),
    .icache_ifu_exception(ifed_icache_ifu_exception),
    .icache_meta_ecc_error(ifed_icache_meta_ecc_error),
    .icache_data_ecc_error(ifed_icache_data_ecc_error),
    .backend_can_accept(ifed_backend_can_accept),
    .uncache_d_valid(ifed_uncache_d_valid),
    .uncache_d_denied(ifed_uncache_d_denied),
    .uncache_d_corrupt(ifed_uncache_d_corrupt),
    .uncache_req_valid(ifed_uncache_req_valid),
    .uncache_req_ready(ifed_uncache_req_ready),
    .uncache_req_addr_low(ifed_uncache_req_addr_low),
    .uncache_ifu_resp_valid(ifed_uncache_ifu_resp_valid),
    .uncache_ifu_resp_denied(ifed_uncache_ifu_resp_denied),
    .uncache_ifu_resp_corrupt(ifed_uncache_ifu_resp_corrupt),
    .uncache_ifu_resp_need_resend(ifed_uncache_ifu_resp_need_resend),
    .uncache_entry_req_addr(ifed_uncache_entry_req_addr),
    .ifu_to_ibuffer_valid(ifed_ifu_to_ibuffer_valid),
    .ifu_to_ibuffer_ready(ifed_ifu_to_ibuffer_ready),
    .ifu_to_ibuffer_ftq_flag(ifed_ifu_to_ibuffer_ftq_flag),
    .ifu_to_ibuffer_ftq_value(ifed_ifu_to_ibuffer_ftq_value),
    .ifu_exception_type(ifed_ifu_exception_type),
    .ifu_exception_cross_page(ifed_ifu_exception_cross_page),
    .ifu_s2_req_is_uncache(ifed_ifu_s2_req_is_uncache),
    .ifu_s2_prev_end_half_rvi(ifed_ifu_s2_prev_end_half_rvi),
    .ifu_s2_ftq_flag(ifed_ifu_s2_ftq_flag),
    .ifu_s2_ftq_value(ifed_ifu_s2_ftq_value),
    .ifu_s2_icache_exception(ifed_ifu_s2_icache_exception),
    .ifu_uncache_exception(ifed_ifu_uncache_exception),
    .trigger_pc_match(ifed_trigger_pc_match),
    .ifu_s2_cacheable(ifed_ifu_s2_cacheable),
    .uncache_response_valid(ifed_uncache_response_valid),
    .cfvec_valid(ifed_cfvec_valid),
    .cfvec_is_rvc(ifed_cfvec_is_rvc),
    .cfvec_illegal_instruction(ifed_cfvec_illegal_instruction),
    .cfvec_trigger(ifed_cfvec_trigger)
  );

  frontend_mmio_fetch_funcov u_mmio (
    .clock(clock),
    .reset(reset),
    .s2_valid(mmio_s2_valid),
    .s2_req_is_uncache(mmio_s2_req_is_uncache),
    .s2_use_uncache(mmio_s2_use_uncache),
    .s2_double_line(mmio_s2_double_line),
    .s2_pmp_mmio_0(mmio_s2_pmp_mmio_0),
    .s2_pbmt_0(mmio_s2_pbmt_0),
    .s2_exception_0(mmio_s2_exception_0),
    .s2_pc_0(mmio_s2_pc_0),
    .is_first_instr(mmio_is_first_instr),
    .uncache_input_valid(mmio_uncache_input_valid),
    .uncache_input_ready(mmio_uncache_input_ready),
    .uncache_state(mmio_uncache_state),
    .uncache_busy(mmio_uncache_busy),
    .ifu_stall(mmio_ifu_stall),
    .empty_after(mmio_empty_after),
    .backend_commit(mmio_backend_commit),
    .backend_empty(mmio_backend_empty),
    .ibuffer_empty(mmio_ibuffer_empty),
    .backend_can_accept(mmio_backend_can_accept),
    .tl_a_valid(mmio_tl_a_valid),
    .tl_a_ready(mmio_tl_a_ready),
    .tl_a_addr(mmio_tl_a_addr),
    .tl_d_valid(mmio_tl_d_valid),
    .tl_d_data(mmio_tl_d_data),
    .tl_d_corrupt(mmio_tl_d_corrupt),
    .tl_d_denied(mmio_tl_d_denied),
    .entry_state(mmio_entry_state),
    .entry_resending(mmio_entry_resending),
    .entry_req_addr(mmio_entry_req_addr),
    .uncache_resp_valid(mmio_uncache_resp_valid),
    .uncache_resp_data(mmio_uncache_resp_data),
    .uncache_resp_exception(mmio_uncache_resp_exception),
    .uncache_resp_need_resend(mmio_uncache_resp_need_resend),
    .to_ibuffer_valid(mmio_to_ibuffer_valid),
    .to_ibuffer_ready(mmio_to_ibuffer_ready),
    .to_ibuffer_enq(mmio_to_ibuffer_enq),
    .to_ibuffer_is_rvc(mmio_to_ibuffer_is_rvc),
    .to_ibuffer_pc_0(mmio_to_ibuffer_pc_0),
    .to_ibuffer_exception(mmio_to_ibuffer_exception),
    .to_ibuffer_exception_cross_page(mmio_to_ibuffer_exception_cross_page),
    .backend_redirect(mmio_backend_redirect),
    .ifu_flush(mmio_ifu_flush),
    .uncache_redirect(mmio_uncache_redirect),
    .wb_redirect(mmio_wb_redirect),
    .wb_path_valid(mmio_wb_path_valid),
    .uncache_branch_type(mmio_uncache_branch_type),
    .prev_end_half_rvi(mmio_prev_end_half_rvi),
    .prev_half_data(mmio_prev_half_data),
    .prev_half_pc(mmio_prev_half_pc),
    .uncache_pc(mmio_uncache_pc),
    .cfvec_valid(mmio_cfvec_valid),
    .wfi_safe(mmio_wfi_safe)
  );

  frontend_nc_fetch_funcov u_nc (
    .clock(clock),
    .reset(reset),
    .s2_valid(mmio_s2_valid),
    .s2_req_is_uncache(mmio_s2_req_is_uncache),
    .s2_use_uncache(mmio_s2_use_uncache),
    .s2_pmp_mmio_0(mmio_s2_pmp_mmio_0),
    .s2_pbmt_0(mmio_s2_pbmt_0),
    .s2_exception_0(mmio_s2_exception_0),
    .uncache_input_valid(mmio_uncache_input_valid),
    .uncache_input_ready(mmio_uncache_input_ready),
    .uncache_state(mmio_uncache_state),
    .uncache_busy(mmio_uncache_busy),
    .ifu_stall(mmio_ifu_stall),
    .backend_empty(mmio_backend_empty),
    .ibuffer_empty(mmio_ibuffer_empty),
    .backend_can_accept(mmio_backend_can_accept),
    .tl_a_valid(mmio_tl_a_valid),
    .tl_a_ready(mmio_tl_a_ready),
    .tl_a_addr(mmio_tl_a_addr),
    .tl_d_valid(mmio_tl_d_valid),
    .tl_d_data(mmio_tl_d_data),
    .tl_d_corrupt(mmio_tl_d_corrupt),
    .tl_d_denied(mmio_tl_d_denied),
    .entry_state(mmio_entry_state),
    .entry_resending(mmio_entry_resending),
    .entry_req_addr(mmio_entry_req_addr),
    .uncache_resp_valid(mmio_uncache_resp_valid),
    .uncache_resp_data(mmio_uncache_resp_data),
    .uncache_resp_exception(mmio_uncache_resp_exception),
    .uncache_resp_need_resend(mmio_uncache_resp_need_resend),
    .to_ibuffer_valid(mmio_to_ibuffer_valid),
    .to_ibuffer_ready(mmio_to_ibuffer_ready),
    .to_ibuffer_enq(mmio_to_ibuffer_enq),
    .to_ibuffer_is_rvc(mmio_to_ibuffer_is_rvc),
    .to_ibuffer_pc_0(mmio_to_ibuffer_pc_0),
    .to_ibuffer_exception(mmio_to_ibuffer_exception),
    .to_ibuffer_exception_cross_page(mmio_to_ibuffer_exception_cross_page),
    .backend_redirect(mmio_backend_redirect),
    .ifu_flush(mmio_ifu_flush),
    .uncache_redirect(mmio_uncache_redirect),
    .wb_redirect(mmio_wb_redirect),
    .wb_path_valid(mmio_wb_path_valid),
    .uncache_branch_type(mmio_uncache_branch_type),
    .prev_end_half_rvi(mmio_prev_end_half_rvi),
    .prev_half_data(mmio_prev_half_data),
    .prev_half_pc(mmio_prev_half_pc),
    .uncache_pc(mmio_uncache_pc),
    .wfi_safe(mmio_wfi_safe),
    .icache_waylookup_valid(nc_icache_waylookup_valid),
    .icache_waymask_0(nc_icache_waymask_0),
    .icache_waymask_1(nc_icache_waymask_1)
  );

  frontend_wfi_funcov u_wfi (
    .clock(clock),
    .reset(reset),
    .backend_wfi_req(wfi_backend_req),
    .delayed_wfi_req(wfi_delayed_req),
    .backend_wfi_safe(wfi_backend_safe),
    .icache_wfi_safe(wfi_icache_safe),
    .instr_uncache_wfi_safe(wfi_instr_uncache_safe),
    .icache_tl_a_valid(wfi_icache_tl_a_valid),
    .icache_tl_a_ready(wfi_icache_tl_a_ready),
    .instr_uncache_tl_a_valid(wfi_instr_uncache_tl_a_valid),
    .instr_uncache_tl_a_ready(wfi_instr_uncache_tl_a_ready),
    .icache_mshr_valid(wfi_icache_mshr_valid),
    .icache_mshr_issue(wfi_icache_mshr_issue),
    .instr_uncache_entry_state(wfi_instr_uncache_entry_state),
    .frontend_flush(wfi_frontend_flush),
    .backend_redirect(wfi_backend_redirect)
  );

  frontend_redirect_flush_recovery_funcov u_rfr (
    .clock(clock),
    .reset(reset),
    .backend_redirect_valid(rfr_backend_redirect_valid),
    .backend_redirect_target(rfr_backend_redirect_target),
    .backend_redirect_level(rfr_backend_redirect_level),
    .backend_redirect_is_rvc(rfr_backend_redirect_is_rvc),
    .backend_redirect_iaf(rfr_backend_redirect_iaf),
    .backend_redirect_ipf(rfr_backend_redirect_ipf),
    .backend_redirect_igpf(rfr_backend_redirect_igpf),
    .backend_redirect_is_ctrl(rfr_backend_redirect_is_ctrl),
    .backend_redirect_is_mem_vio(rfr_backend_redirect_is_mem_vio),
    .ftq_idx_ahead_valid(rfr_ftq_idx_ahead_valid),
    .ftq_idx_ahead_flag(rfr_ftq_idx_ahead_flag),
    .ftq_idx_ahead_value(rfr_ftq_idx_ahead_value),
    .backend_redirect_ftq_idx_flag(rfr_backend_redirect_ftq_idx_flag),
    .backend_redirect_ftq_idx_value(rfr_backend_redirect_ftq_idx_value),
    .backend_redirect_ftq_offset(rfr_backend_redirect_ftq_offset),
    .ftq_meta_valid(rfr_ftq_meta_valid),
    .ftq_meta_idx_flag(rfr_ftq_meta_idx_flag),
    .ftq_meta_idx_value(rfr_ftq_meta_idx_value),
    .to_bpu_redirect_valid(rfr_to_bpu_redirect_valid),
    .to_bpu_redirect_target(rfr_to_bpu_redirect_target),
    .icache_redirect_flush(rfr_icache_redirect_flush),
    .bpu_flush_valid(rfr_bpu_flush_valid),
    .ifu_wb_redirect_valid(rfr_ifu_wb_redirect_valid),
    .ifu_wb_redirect_target(rfr_ifu_wb_redirect_target),
    .ifu_wb_redirect_taken(rfr_ifu_wb_redirect_taken),
    .ifu_wb_redirect_is_rvc(rfr_ifu_wb_redirect_is_rvc),
    .ibuffer_empty(rfr_ibuffer_empty),
    .ibuffer_ready(rfr_ibuffer_ready),
    .icache_response_valid(rfr_icache_response_valid),
    .uncache_response_valid(rfr_uncache_response_valid),
    .uncache_response_need_resend(rfr_uncache_response_need_resend),
    .uncache_entry_req_addr(rfr_uncache_entry_req_addr),
    .icache_a_valid(rfr_icache_a_valid),
    .icache_a_ready(rfr_icache_a_ready),
    .icache_a_source(rfr_icache_a_source),
    .icache_d_source(rfr_icache_d_source),
    .uncache_a_valid(rfr_uncache_a_valid),
    .uncache_a_ready(rfr_uncache_a_ready),
    .ifu_to_ibuffer_valid(rfr_ifu_to_ibuffer_valid),
    .icache_to_ifu_valid(rfr_icache_to_ifu_valid),
    .main_fetch_valid(rfr_main_fetch_valid),
    .main_fetch_ready(rfr_main_fetch_ready),
    .prefetch_valid(rfr_prefetch_valid),
    .ifu_s1_valid(rfr_ifu_s1_valid),
    .ifu_s2_valid(rfr_ifu_s2_valid),
    .backend_can_accept(rfr_backend_can_accept),
    .pred_checker_remask_fault(rfr_pred_checker_remask_fault),
    .pred_checker_not_cfi_taken(rfr_pred_checker_not_cfi_taken),
    .pred_checker_invalid_taken(rfr_pred_checker_invalid_taken),
    .itlb_flush_pipe(rfr_itlb_flush_pipe),
    .fencei(rfr_fencei),
    .icache_cacheable_hit(rfr_icache_cacheable_hit),
    .prefetch_s1_valid(rfr_prefetch_s1_valid),
    .prefetch_wait_itlb(rfr_prefetch_wait_itlb),
    .prefetch_tlb_latch_valid(rfr_prefetch_tlb_latch_valid),
    .sfence_valid(rfr_sfence_valid),
    .satp_changed(rfr_satp_changed),
    .vsatp_changed(rfr_vsatp_changed),
    .hgatp_changed(rfr_hgatp_changed),
    .priv_virt_changed(rfr_priv_virt_changed),
    .cfvec_valid(rfr_cfvec_valid),
    .cfvec_pc(rfr_cfvec_pc),
    .cfvec_iaf(rfr_cfvec_iaf),
    .cfvec_ipf(rfr_cfvec_ipf),
    .cfvec_igpf(rfr_cfvec_igpf),
    .cfvec_backend_exception(rfr_cfvec_backend_exception)
  );
endmodule

bind Frontend frontend_funcov_hub u_frontend_funcov_hub (
  .clock(clock),
  .reset(reset),
  .atp_io_tlbCsr_priv_virt(io_tlbCsr_priv_virt),
  .atp_io_tlbCsr_satp_mode(io_tlbCsr_satp_mode),
  .atp_io_tlbCsr_vsatp_mode(io_tlbCsr_vsatp_mode),
  .atp_io_tlbCsr_hgatp_mode(io_tlbCsr_hgatp_mode),
  .atp_io_tlbCsr_satp_changed(io_tlbCsr_satp_changed),
  .atp_io_tlbCsr_vsatp_changed(io_tlbCsr_vsatp_changed),
  .atp_io_tlbCsr_hgatp_changed(io_tlbCsr_hgatp_changed),
  .atp_io_tlbCsr_priv_virt_changed(io_tlbCsr_priv_virt_changed),
  .atp_itlb_req_valid(_inner_icache_io_itlb_req_valid),
  .atp_itlb_req_vaddr(_inner_icache_io_itlb_req_bits_vaddr),
  .atp_itlb_resp_miss(_inner_itlb_io_requestor_0_resp_bits_miss),
  .atp_ptw_req_valid(io_ptw_req_0_valid),
  .atp_ptw_req_ready(io_ptw_req_0_ready),
  .atp_ptw_req_vpn(io_ptw_req_0_bits_vpn),
  .atp_ptw_req_s2xlate(io_ptw_req_0_bits_s2xlate),
  .atp_ptw_resp_valid(io_ptw_resp_valid),
  .atp_ptw_resp_s2xlate(io_ptw_resp_bits_s2xlate),
  .atp_ptw_resp_s1_entry_v(io_ptw_resp_bits_s1_entry_v),
  .atp_ptw_resp_s1_entry_level(io_ptw_resp_bits_s1_entry_level),
  .atp_ptw_resp_s1_entry_n(io_ptw_resp_bits_s1_entry_n),
  .atp_ptw_resp_s1_valididx({
    io_ptw_resp_bits_s1_valididx_7,
    io_ptw_resp_bits_s1_valididx_6,
    io_ptw_resp_bits_s1_valididx_5,
    io_ptw_resp_bits_s1_valididx_4,
    io_ptw_resp_bits_s1_valididx_3,
    io_ptw_resp_bits_s1_valididx_2,
    io_ptw_resp_bits_s1_valididx_1,
    io_ptw_resp_bits_s1_valididx_0
  }),
  .atp_ptw_resp_s1_pteidx({
    io_ptw_resp_bits_s1_pteidx_7,
    io_ptw_resp_bits_s1_pteidx_6,
    io_ptw_resp_bits_s1_pteidx_5,
    io_ptw_resp_bits_s1_pteidx_4,
    io_ptw_resp_bits_s1_pteidx_3,
    io_ptw_resp_bits_s1_pteidx_2,
    io_ptw_resp_bits_s1_pteidx_1,
    io_ptw_resp_bits_s1_pteidx_0
  }),
  .atp_ptw_resp_s2_gpf(io_ptw_resp_bits_s2_gpf),
  .atp_ptw_resp_s2_gaf(io_ptw_resp_bits_s2_gaf),
  .atp_sfence_valid(_inner_sfence_delay_io_out_valid),
  .atp_sfence_rs1(_inner_sfence_delay_io_out_bits_rs1),
  .atp_sfence_rs2(_inner_sfence_delay_io_out_bits_rs2),
  .atp_sfence_hv(_inner_sfence_delay_io_out_bits_hv),
  .atp_sfence_hg(_inner_sfence_delay_io_out_bits_hg),
  .atp_flush_pipe(_inner_icache_io_itlbFlushPipe),
  .atpr_io_tlbCsr_priv_virt(io_tlbCsr_priv_virt),
  .atpr_io_tlbCsr_priv_imode(io_tlbCsr_priv_imode),
  .atpr_io_tlbCsr_satp_mode(io_tlbCsr_satp_mode),
  .atpr_io_tlbCsr_vsatp_mode(io_tlbCsr_vsatp_mode),
  .atpr_io_tlbCsr_hgatp_mode(io_tlbCsr_hgatp_mode),
  .atpr_io_tlbCsr_satp_asid(io_tlbCsr_satp_asid),
  .atpr_io_tlbCsr_vsatp_asid(io_tlbCsr_vsatp_asid),
  .atpr_io_tlbCsr_hgatp_vmid(io_tlbCsr_hgatp_vmid),
  .atpr_io_tlbCsr_satp_changed(io_tlbCsr_satp_changed),
  .atpr_io_tlbCsr_vsatp_changed(io_tlbCsr_vsatp_changed),
  .atpr_io_tlbCsr_hgatp_changed(io_tlbCsr_hgatp_changed),
  .atpr_io_tlbCsr_priv_virt_changed(io_tlbCsr_priv_virt_changed),
  .atpr_itlb_req_valid(_inner_icache_io_itlb_req_valid),
  .atpr_itlb_req_vaddr(_inner_icache_io_itlb_req_bits_vaddr),
  .atpr_itlb_resp_miss(_inner_itlb_io_requestor_0_resp_bits_miss),
  .atpr_itlb_resp_pbmt(_inner_itlb_io_requestor_0_resp_bits_pbmt_0),
  .atpr_itlb_resp_pf_instr(_inner_itlb_io_requestor_0_resp_bits_excp_0_pf_instr),
  .atpr_itlb_resp_af_instr(_inner_itlb_io_requestor_0_resp_bits_excp_0_af_instr),
  .atpr_itlb_resp_gpf_instr(_inner_itlb_io_requestor_0_resp_bits_excp_0_gpf_instr),
  .atpr_ptw_req_valid(io_ptw_req_0_valid),
  .atpr_ptw_req_ready(io_ptw_req_0_ready),
  .atpr_ptw_req_vpn(io_ptw_req_0_bits_vpn),
  .atpr_ptw_req_s2xlate(io_ptw_req_0_bits_s2xlate),
  .atpr_ptw_resp_valid(io_ptw_resp_valid),
  .atpr_ptw_resp_s2xlate(io_ptw_resp_bits_s2xlate),
  .atpr_ptw_resp_s1_pbmt(io_ptw_resp_bits_s1_entry_pbmt),
  .atpr_ptw_resp_s2_pbmt(io_ptw_resp_bits_s2_entry_pbmt),
  .atpr_ptw_resp_s1_v(io_ptw_resp_bits_s1_entry_v),
  .atpr_ptw_resp_s1_perm_a(io_ptw_resp_bits_s1_entry_perm_a),
  .atpr_ptw_resp_s1_perm_u(io_ptw_resp_bits_s1_entry_perm_u),
  .atpr_ptw_resp_s1_perm_x(io_ptw_resp_bits_s1_entry_perm_x),
  .atpr_ptw_resp_s1_perm_w(io_ptw_resp_bits_s1_entry_perm_w),
  .atpr_ptw_resp_s1_perm_r(io_ptw_resp_bits_s1_entry_perm_r),
  .atpr_ptw_resp_s2_perm_a(io_ptw_resp_bits_s2_entry_perm_a),
  .atpr_ptw_resp_s2_perm_x(io_ptw_resp_bits_s2_entry_perm_x),
  .atpr_ptw_resp_s1_pf(io_ptw_resp_bits_s1_pf),
  .atpr_ptw_resp_s1_af(io_ptw_resp_bits_s1_af),
  .atpr_ptw_resp_s2_gpf(io_ptw_resp_bits_s2_gpf),
  .atpr_ptw_resp_s2_gaf(io_ptw_resp_bits_s2_gaf),
  .atpr_sfence_valid(_inner_sfence_delay_io_out_valid),
  .atpr_sfence_rs1(_inner_sfence_delay_io_out_bits_rs1),
  .atpr_sfence_rs2(_inner_sfence_delay_io_out_bits_rs2),
  .atpr_sfence_addr(_inner_sfence_delay_io_out_bits_addr),
  .atpr_sfence_id(_inner_sfence_delay_io_out_bits_id),
  .atpr_sfence_hv(_inner_sfence_delay_io_out_bits_hv),
  .atpr_sfence_hg(_inner_sfence_delay_io_out_bits_hg),
  .atpr_redirect_valid(io_backend_toFtq_redirect_valid),
  .atpr_backend_can_accept(io_backend_canAccept),
  .atpr_pmp_addr_0(_inner_icache_io_pmp_0_req_bits_addr),
  .atpr_pmp_addr_1(_inner_icache_io_pmp_1_req_bits_addr),
  .atpr_pmp_cfg_l({_inner_pmp_io_pmp_31_cfg_l, _inner_pmp_io_pmp_30_cfg_l, _inner_pmp_io_pmp_29_cfg_l, _inner_pmp_io_pmp_28_cfg_l, _inner_pmp_io_pmp_27_cfg_l, _inner_pmp_io_pmp_26_cfg_l, _inner_pmp_io_pmp_25_cfg_l, _inner_pmp_io_pmp_24_cfg_l, _inner_pmp_io_pmp_23_cfg_l, _inner_pmp_io_pmp_22_cfg_l, _inner_pmp_io_pmp_21_cfg_l, _inner_pmp_io_pmp_20_cfg_l, _inner_pmp_io_pmp_19_cfg_l, _inner_pmp_io_pmp_18_cfg_l, _inner_pmp_io_pmp_17_cfg_l, _inner_pmp_io_pmp_16_cfg_l, _inner_pmp_io_pmp_15_cfg_l, _inner_pmp_io_pmp_14_cfg_l, _inner_pmp_io_pmp_13_cfg_l, _inner_pmp_io_pmp_12_cfg_l, _inner_pmp_io_pmp_11_cfg_l, _inner_pmp_io_pmp_10_cfg_l, _inner_pmp_io_pmp_9_cfg_l, _inner_pmp_io_pmp_8_cfg_l, _inner_pmp_io_pmp_7_cfg_l, _inner_pmp_io_pmp_6_cfg_l, _inner_pmp_io_pmp_5_cfg_l, _inner_pmp_io_pmp_4_cfg_l, _inner_pmp_io_pmp_3_cfg_l, _inner_pmp_io_pmp_2_cfg_l, _inner_pmp_io_pmp_1_cfg_l, _inner_pmp_io_pmp_0_cfg_l}),
  .atpr_pmp_cfg_a({_inner_pmp_io_pmp_31_cfg_a, _inner_pmp_io_pmp_30_cfg_a, _inner_pmp_io_pmp_29_cfg_a, _inner_pmp_io_pmp_28_cfg_a, _inner_pmp_io_pmp_27_cfg_a, _inner_pmp_io_pmp_26_cfg_a, _inner_pmp_io_pmp_25_cfg_a, _inner_pmp_io_pmp_24_cfg_a, _inner_pmp_io_pmp_23_cfg_a, _inner_pmp_io_pmp_22_cfg_a, _inner_pmp_io_pmp_21_cfg_a, _inner_pmp_io_pmp_20_cfg_a, _inner_pmp_io_pmp_19_cfg_a, _inner_pmp_io_pmp_18_cfg_a, _inner_pmp_io_pmp_17_cfg_a, _inner_pmp_io_pmp_16_cfg_a, _inner_pmp_io_pmp_15_cfg_a, _inner_pmp_io_pmp_14_cfg_a, _inner_pmp_io_pmp_13_cfg_a, _inner_pmp_io_pmp_12_cfg_a, _inner_pmp_io_pmp_11_cfg_a, _inner_pmp_io_pmp_10_cfg_a, _inner_pmp_io_pmp_9_cfg_a, _inner_pmp_io_pmp_8_cfg_a, _inner_pmp_io_pmp_7_cfg_a, _inner_pmp_io_pmp_6_cfg_a, _inner_pmp_io_pmp_5_cfg_a, _inner_pmp_io_pmp_4_cfg_a, _inner_pmp_io_pmp_3_cfg_a, _inner_pmp_io_pmp_2_cfg_a, _inner_pmp_io_pmp_1_cfg_a, _inner_pmp_io_pmp_0_cfg_a}),
  .atpr_pmp_cfg_x({_inner_pmp_io_pmp_31_cfg_x, _inner_pmp_io_pmp_30_cfg_x, _inner_pmp_io_pmp_29_cfg_x, _inner_pmp_io_pmp_28_cfg_x, _inner_pmp_io_pmp_27_cfg_x, _inner_pmp_io_pmp_26_cfg_x, _inner_pmp_io_pmp_25_cfg_x, _inner_pmp_io_pmp_24_cfg_x, _inner_pmp_io_pmp_23_cfg_x, _inner_pmp_io_pmp_22_cfg_x, _inner_pmp_io_pmp_21_cfg_x, _inner_pmp_io_pmp_20_cfg_x, _inner_pmp_io_pmp_19_cfg_x, _inner_pmp_io_pmp_18_cfg_x, _inner_pmp_io_pmp_17_cfg_x, _inner_pmp_io_pmp_16_cfg_x, _inner_pmp_io_pmp_15_cfg_x, _inner_pmp_io_pmp_14_cfg_x, _inner_pmp_io_pmp_13_cfg_x, _inner_pmp_io_pmp_12_cfg_x, _inner_pmp_io_pmp_11_cfg_x, _inner_pmp_io_pmp_10_cfg_x, _inner_pmp_io_pmp_9_cfg_x, _inner_pmp_io_pmp_8_cfg_x, _inner_pmp_io_pmp_7_cfg_x, _inner_pmp_io_pmp_6_cfg_x, _inner_pmp_io_pmp_5_cfg_x, _inner_pmp_io_pmp_4_cfg_x, _inner_pmp_io_pmp_3_cfg_x, _inner_pmp_io_pmp_2_cfg_x, _inner_pmp_io_pmp_1_cfg_x, _inner_pmp_io_pmp_0_cfg_x}),
  .atpr_pmp_addr({_inner_pmp_io_pmp_31_addr, _inner_pmp_io_pmp_30_addr, _inner_pmp_io_pmp_29_addr, _inner_pmp_io_pmp_28_addr, _inner_pmp_io_pmp_27_addr, _inner_pmp_io_pmp_26_addr, _inner_pmp_io_pmp_25_addr, _inner_pmp_io_pmp_24_addr, _inner_pmp_io_pmp_23_addr, _inner_pmp_io_pmp_22_addr, _inner_pmp_io_pmp_21_addr, _inner_pmp_io_pmp_20_addr, _inner_pmp_io_pmp_19_addr, _inner_pmp_io_pmp_18_addr, _inner_pmp_io_pmp_17_addr, _inner_pmp_io_pmp_16_addr, _inner_pmp_io_pmp_15_addr, _inner_pmp_io_pmp_14_addr, _inner_pmp_io_pmp_13_addr, _inner_pmp_io_pmp_12_addr, _inner_pmp_io_pmp_11_addr, _inner_pmp_io_pmp_10_addr, _inner_pmp_io_pmp_9_addr, _inner_pmp_io_pmp_8_addr, _inner_pmp_io_pmp_7_addr, _inner_pmp_io_pmp_6_addr, _inner_pmp_io_pmp_5_addr, _inner_pmp_io_pmp_4_addr, _inner_pmp_io_pmp_3_addr, _inner_pmp_io_pmp_2_addr, _inner_pmp_io_pmp_1_addr, _inner_pmp_io_pmp_0_addr}),
  .atpr_pmp_mask({_inner_pmp_io_pmp_31_mask, _inner_pmp_io_pmp_30_mask, _inner_pmp_io_pmp_29_mask, _inner_pmp_io_pmp_28_mask, _inner_pmp_io_pmp_27_mask, _inner_pmp_io_pmp_26_mask, _inner_pmp_io_pmp_25_mask, _inner_pmp_io_pmp_24_mask, _inner_pmp_io_pmp_23_mask, _inner_pmp_io_pmp_22_mask, _inner_pmp_io_pmp_21_mask, _inner_pmp_io_pmp_20_mask, _inner_pmp_io_pmp_19_mask, _inner_pmp_io_pmp_18_mask, _inner_pmp_io_pmp_17_mask, _inner_pmp_io_pmp_16_mask, _inner_pmp_io_pmp_15_mask, _inner_pmp_io_pmp_14_mask, _inner_pmp_io_pmp_13_mask, _inner_pmp_io_pmp_12_mask, _inner_pmp_io_pmp_11_mask, _inner_pmp_io_pmp_10_mask, _inner_pmp_io_pmp_9_mask, _inner_pmp_io_pmp_8_mask, _inner_pmp_io_pmp_7_mask, _inner_pmp_io_pmp_6_mask, _inner_pmp_io_pmp_5_mask, _inner_pmp_io_pmp_4_mask, _inner_pmp_io_pmp_3_mask, _inner_pmp_io_pmp_2_mask, _inner_pmp_io_pmp_1_mask, _inner_pmp_io_pmp_0_mask}),
  .atpr_pma_cfg_c({_inner_pmp_io_pma_31_cfg_c, _inner_pmp_io_pma_30_cfg_c, _inner_pmp_io_pma_29_cfg_c, _inner_pmp_io_pma_28_cfg_c, _inner_pmp_io_pma_27_cfg_c, _inner_pmp_io_pma_26_cfg_c, _inner_pmp_io_pma_25_cfg_c, _inner_pmp_io_pma_24_cfg_c, _inner_pmp_io_pma_23_cfg_c, _inner_pmp_io_pma_22_cfg_c, _inner_pmp_io_pma_21_cfg_c, _inner_pmp_io_pma_20_cfg_c, _inner_pmp_io_pma_19_cfg_c, _inner_pmp_io_pma_18_cfg_c, _inner_pmp_io_pma_17_cfg_c, _inner_pmp_io_pma_16_cfg_c, _inner_pmp_io_pma_15_cfg_c, _inner_pmp_io_pma_14_cfg_c, _inner_pmp_io_pma_13_cfg_c, _inner_pmp_io_pma_12_cfg_c, _inner_pmp_io_pma_11_cfg_c, _inner_pmp_io_pma_10_cfg_c, _inner_pmp_io_pma_9_cfg_c, _inner_pmp_io_pma_8_cfg_c, _inner_pmp_io_pma_7_cfg_c, _inner_pmp_io_pma_6_cfg_c, _inner_pmp_io_pma_5_cfg_c, _inner_pmp_io_pma_4_cfg_c, _inner_pmp_io_pma_3_cfg_c, _inner_pmp_io_pma_2_cfg_c, _inner_pmp_io_pma_1_cfg_c, _inner_pmp_io_pma_0_cfg_c}),
  .atpr_pma_cfg_a({_inner_pmp_io_pma_31_cfg_a, _inner_pmp_io_pma_30_cfg_a, _inner_pmp_io_pma_29_cfg_a, _inner_pmp_io_pma_28_cfg_a, _inner_pmp_io_pma_27_cfg_a, _inner_pmp_io_pma_26_cfg_a, _inner_pmp_io_pma_25_cfg_a, _inner_pmp_io_pma_24_cfg_a, _inner_pmp_io_pma_23_cfg_a, _inner_pmp_io_pma_22_cfg_a, _inner_pmp_io_pma_21_cfg_a, _inner_pmp_io_pma_20_cfg_a, _inner_pmp_io_pma_19_cfg_a, _inner_pmp_io_pma_18_cfg_a, _inner_pmp_io_pma_17_cfg_a, _inner_pmp_io_pma_16_cfg_a, _inner_pmp_io_pma_15_cfg_a, _inner_pmp_io_pma_14_cfg_a, _inner_pmp_io_pma_13_cfg_a, _inner_pmp_io_pma_12_cfg_a, _inner_pmp_io_pma_11_cfg_a, _inner_pmp_io_pma_10_cfg_a, _inner_pmp_io_pma_9_cfg_a, _inner_pmp_io_pma_8_cfg_a, _inner_pmp_io_pma_7_cfg_a, _inner_pmp_io_pma_6_cfg_a, _inner_pmp_io_pma_5_cfg_a, _inner_pmp_io_pma_4_cfg_a, _inner_pmp_io_pma_3_cfg_a, _inner_pmp_io_pma_2_cfg_a, _inner_pmp_io_pma_1_cfg_a, _inner_pmp_io_pma_0_cfg_a}),
  .atpr_pma_cfg_x({_inner_pmp_io_pma_31_cfg_x, _inner_pmp_io_pma_30_cfg_x, _inner_pmp_io_pma_29_cfg_x, _inner_pmp_io_pma_28_cfg_x, _inner_pmp_io_pma_27_cfg_x, _inner_pmp_io_pma_26_cfg_x, _inner_pmp_io_pma_25_cfg_x, _inner_pmp_io_pma_24_cfg_x, _inner_pmp_io_pma_23_cfg_x, _inner_pmp_io_pma_22_cfg_x, _inner_pmp_io_pma_21_cfg_x, _inner_pmp_io_pma_20_cfg_x, _inner_pmp_io_pma_19_cfg_x, _inner_pmp_io_pma_18_cfg_x, _inner_pmp_io_pma_17_cfg_x, _inner_pmp_io_pma_16_cfg_x, _inner_pmp_io_pma_15_cfg_x, _inner_pmp_io_pma_14_cfg_x, _inner_pmp_io_pma_13_cfg_x, _inner_pmp_io_pma_12_cfg_x, _inner_pmp_io_pma_11_cfg_x, _inner_pmp_io_pma_10_cfg_x, _inner_pmp_io_pma_9_cfg_x, _inner_pmp_io_pma_8_cfg_x, _inner_pmp_io_pma_7_cfg_x, _inner_pmp_io_pma_6_cfg_x, _inner_pmp_io_pma_5_cfg_x, _inner_pmp_io_pma_4_cfg_x, _inner_pmp_io_pma_3_cfg_x, _inner_pmp_io_pma_2_cfg_x, _inner_pmp_io_pma_1_cfg_x, _inner_pmp_io_pma_0_cfg_x}),
  .atpr_pma_addr({_inner_pmp_io_pma_31_addr, _inner_pmp_io_pma_30_addr, _inner_pmp_io_pma_29_addr, _inner_pmp_io_pma_28_addr, _inner_pmp_io_pma_27_addr, _inner_pmp_io_pma_26_addr, _inner_pmp_io_pma_25_addr, _inner_pmp_io_pma_24_addr, _inner_pmp_io_pma_23_addr, _inner_pmp_io_pma_22_addr, _inner_pmp_io_pma_21_addr, _inner_pmp_io_pma_20_addr, _inner_pmp_io_pma_19_addr, _inner_pmp_io_pma_18_addr, _inner_pmp_io_pma_17_addr, _inner_pmp_io_pma_16_addr, _inner_pmp_io_pma_15_addr, _inner_pmp_io_pma_14_addr, _inner_pmp_io_pma_13_addr, _inner_pmp_io_pma_12_addr, _inner_pmp_io_pma_11_addr, _inner_pmp_io_pma_10_addr, _inner_pmp_io_pma_9_addr, _inner_pmp_io_pma_8_addr, _inner_pmp_io_pma_7_addr, _inner_pmp_io_pma_6_addr, _inner_pmp_io_pma_5_addr, _inner_pmp_io_pma_4_addr, _inner_pmp_io_pma_3_addr, _inner_pmp_io_pma_2_addr, _inner_pmp_io_pma_1_addr, _inner_pmp_io_pma_0_addr}),
  .atpr_pma_mask({_inner_pmp_io_pma_31_mask, _inner_pmp_io_pma_30_mask, _inner_pmp_io_pma_29_mask, _inner_pmp_io_pma_28_mask, _inner_pmp_io_pma_27_mask, _inner_pmp_io_pma_26_mask, _inner_pmp_io_pma_25_mask, _inner_pmp_io_pma_24_mask, _inner_pmp_io_pma_23_mask, _inner_pmp_io_pma_22_mask, _inner_pmp_io_pma_21_mask, _inner_pmp_io_pma_20_mask, _inner_pmp_io_pma_19_mask, _inner_pmp_io_pma_18_mask, _inner_pmp_io_pma_17_mask, _inner_pmp_io_pma_16_mask, _inner_pmp_io_pma_15_mask, _inner_pmp_io_pma_14_mask, _inner_pmp_io_pma_13_mask, _inner_pmp_io_pma_12_mask, _inner_pmp_io_pma_11_mask, _inner_pmp_io_pma_10_mask, _inner_pmp_io_pma_9_mask, _inner_pmp_io_pma_8_mask, _inner_pmp_io_pma_7_mask, _inner_pmp_io_pma_6_mask, _inner_pmp_io_pma_5_mask, _inner_pmp_io_pma_4_mask, _inner_pmp_io_pma_3_mask, _inner_pmp_io_pma_2_mask, _inner_pmp_io_pma_1_mask, _inner_pmp_io_pma_0_mask}),
  .atpr_pmp_checker_0_x(inner_PMPChecker.res_pmp_cfg_x),
  .atpr_pmp_checker_1_x(inner_PMPChecker_1.res_pmp_cfg_x),
  .ibuf_in_ready(_inner_ibuffer_io_in_ready),
  .ibuf_in_valid(_inner_ifu_io_toIBuffer_valid),
  .ibuf_in_valid_lanes(_inner_ifu_io_toIBuffer_bits_valid),
  .ibuf_in_enq_enable(_inner_ifu_io_toIBuffer_bits_enqEnable),
  .ibuf_in_is_rvc({
    _inner_ifu_io_toIBuffer_bits_isRvc_35, _inner_ifu_io_toIBuffer_bits_isRvc_34,
    _inner_ifu_io_toIBuffer_bits_isRvc_33, _inner_ifu_io_toIBuffer_bits_isRvc_32,
    _inner_ifu_io_toIBuffer_bits_isRvc_31, _inner_ifu_io_toIBuffer_bits_isRvc_30,
    _inner_ifu_io_toIBuffer_bits_isRvc_29, _inner_ifu_io_toIBuffer_bits_isRvc_28,
    _inner_ifu_io_toIBuffer_bits_isRvc_27, _inner_ifu_io_toIBuffer_bits_isRvc_26,
    _inner_ifu_io_toIBuffer_bits_isRvc_25, _inner_ifu_io_toIBuffer_bits_isRvc_24,
    _inner_ifu_io_toIBuffer_bits_isRvc_23, _inner_ifu_io_toIBuffer_bits_isRvc_22,
    _inner_ifu_io_toIBuffer_bits_isRvc_21, _inner_ifu_io_toIBuffer_bits_isRvc_20,
    _inner_ifu_io_toIBuffer_bits_isRvc_19, _inner_ifu_io_toIBuffer_bits_isRvc_18,
    _inner_ifu_io_toIBuffer_bits_isRvc_17, _inner_ifu_io_toIBuffer_bits_isRvc_16,
    _inner_ifu_io_toIBuffer_bits_isRvc_15, _inner_ifu_io_toIBuffer_bits_isRvc_14,
    _inner_ifu_io_toIBuffer_bits_isRvc_13, _inner_ifu_io_toIBuffer_bits_isRvc_12,
    _inner_ifu_io_toIBuffer_bits_isRvc_11, _inner_ifu_io_toIBuffer_bits_isRvc_10,
    _inner_ifu_io_toIBuffer_bits_isRvc_9, _inner_ifu_io_toIBuffer_bits_isRvc_8,
    _inner_ifu_io_toIBuffer_bits_isRvc_7, _inner_ifu_io_toIBuffer_bits_isRvc_6,
    _inner_ifu_io_toIBuffer_bits_isRvc_5, _inner_ifu_io_toIBuffer_bits_isRvc_4,
    _inner_ifu_io_toIBuffer_bits_isRvc_3, _inner_ifu_io_toIBuffer_bits_isRvc_2,
    _inner_ifu_io_toIBuffer_bits_isRvc_1, _inner_ifu_io_toIBuffer_bits_isRvc_0
  }),
  .ibuf_in_exception_type(_inner_ifu_io_toIBuffer_bits_exceptionType_value),
  .ibuf_in_backend_exception(_inner_ifu_io_toIBuffer_bits_isBackendException),
  .ibuf_in_exception_cross_page(_inner_ifu_io_toIBuffer_bits_exceptionCrossPage),
  .ibuf_ibuffer_empty(_inner_ibuffer_io_empty),
  .ibuf_flush(inner_needFlush),
  .ibuf_backend_can_accept(io_backend_canAccept),
  .ibuf_cfvec_valid({io_backend_cfVec_7_valid, io_backend_cfVec_6_valid,
                io_backend_cfVec_5_valid, io_backend_cfVec_4_valid,
                io_backend_cfVec_3_valid, io_backend_cfVec_2_valid,
                io_backend_cfVec_1_valid, io_backend_cfVec_0_valid}),
  .ibuf_cfvec_pc({io_backend_cfVec_7_bits_pc, io_backend_cfVec_6_bits_pc,
             io_backend_cfVec_5_bits_pc, io_backend_cfVec_4_bits_pc,
             io_backend_cfVec_3_bits_pc, io_backend_cfVec_2_bits_pc,
             io_backend_cfVec_1_bits_pc, io_backend_cfVec_0_bits_pc}),
  .ifed_ptw_resp_valid(io_ptw_resp_valid),
  .ifed_ptw_resp_s2xlate(io_ptw_resp_bits_s2xlate),
  .ifed_ptw_resp_s1_pf(io_ptw_resp_bits_s1_pf),
  .ifed_ptw_resp_s1_af(io_ptw_resp_bits_s1_af),
  .ifed_ptw_resp_s2_gpf(io_ptw_resp_bits_s2_gpf),
  .ifed_ptw_resp_s2_gaf(io_ptw_resp_bits_s2_gaf),
  .ifed_ptw_req_valid(io_ptw_req_0_valid),
  .ifed_ptw_req_ready(io_ptw_req_0_ready),
  .ifed_ptw_req_vpn(io_ptw_req_0_bits_vpn),
  .ifed_ptw_req_s2xlate(io_ptw_req_0_bits_s2xlate),
  .ifed_icache_d_valid(auto_inner_icache_client_out_d_valid),
  .ifed_icache_d_denied(auto_inner_icache_client_out_d_bits_denied),
  .ifed_icache_d_corrupt(auto_inner_icache_client_out_d_bits_corrupt),
  .ifed_icache_cross64_first_denied(inner_icache.mainPipe.s1_valid &&
                                    inner_icache.mainPipe.accessTrace_crossLine &&
                                    inner_icache.mainPipe.s1_tlDenied_r),
  .ifed_icache_cross64_first_corrupt(inner_icache.mainPipe.s1_valid &&
                                     inner_icache.mainPipe.accessTrace_crossLine &&
                                     inner_icache.mainPipe.s1_tlCorrupt_r),
  .ifed_icache_cross64_second_denied(inner_icache.mainPipe.s1_valid &&
                                     inner_icache.mainPipe.accessTrace_crossLine &&
                                     inner_icache.mainPipe.s1_tlDenied_r_1),
  .ifed_icache_cross64_second_corrupt(inner_icache.mainPipe.s1_valid &&
                                      inner_icache.mainPipe.accessTrace_crossLine &&
                                      inner_icache.mainPipe.s1_tlCorrupt_r_1),
  .ifed_icache_cross64_rvi(
    !inner_icache.mainPipe.io_toIfu_req_bits_0_maybeRvcMap[5'd15]),
  .ifed_icache_ifu_req_valid(inner_icache.mainPipe.io_toIfu_req_valid),
  .ifed_icache_ifu_start_vaddr(inner_icache.mainPipe.io_toIfu_req_bits_0_startVAddr_addr),
  .ifed_icache_ifu_maybe_rvc_map(inner_icache.mainPipe.io_toIfu_req_bits_0_maybeRvcMap),
  .ifed_icache_ifu_pbmt(inner_icache.mainPipe.io_toIfu_req_bits_0_icacheMeta_itlbPbmt),
  .ifed_icache_ifu_pmp_mmio(inner_icache.mainPipe.io_toIfu_req_bits_0_icacheMeta_pmpMmio),
  .ifed_icache_ifu_exception(inner_icache.mainPipe.io_toIfu_req_bits_0_icacheMeta_exception_value),
  .ifed_icache_meta_ecc_error(inner_icache.mainPipe.s2_sramHits_0_0 &&
    ((^{inner_icache.mainPipe.s2_pTag,
        inner_icache.mainPipe.s2_wayLookupEntry_0_maybeRvcMap_0} !=
       inner_icache.mainPipe.s2_wayLookupEntry_0_metaCodes_0) &&
      (inner_icache.mainPipe.s2_corruptInfo_metaCorrupt_hitNum == 3'h1 ||
       |inner_icache.mainPipe.s2_corruptInfo_metaCorrupt_hitNum[2:1]))),
  .ifed_icache_data_ecc_error(inner_icache.mainPipe.s2_sramHits_0_0 &&
    inner_icache.mainPipe._s2_corruptInfo_dataCorrupt_bankCorrupt_T),
  .ifed_backend_can_accept(io_backend_canAccept),
  .ifed_uncache_d_valid(auto_inner_instrUncache_client_out_d_valid),
  .ifed_uncache_d_denied(auto_inner_instrUncache_client_out_d_bits_denied),
  .ifed_uncache_d_corrupt(auto_inner_instrUncache_client_out_d_bits_corrupt),
  .ifed_uncache_req_valid(_inner_ifu_io_toUncache_req_valid),
  .ifed_uncache_req_ready(_inner_instrUncache_io_fromIfu_req_ready),
  .ifed_uncache_req_addr_low(_inner_ifu_io_toUncache_req_bits_addr_addr[2:0]),
  .ifed_uncache_ifu_resp_valid(_inner_instrUncache_io_toIfu_resp_valid),
  .ifed_uncache_ifu_resp_denied(_inner_instrUncache_io_toIfu_resp_bits_denied),
  .ifed_uncache_ifu_resp_corrupt(_inner_instrUncache_io_toIfu_resp_bits_corrupt),
  .ifed_uncache_ifu_resp_need_resend(_inner_instrUncache_io_toIfu_resp_bits_needResend),
  .ifed_uncache_entry_req_addr(inner_instrUncache.entries_0.reqReg_addr_addr),
  .ifed_ifu_to_ibuffer_valid(_inner_ifu_io_toIBuffer_valid),
  .ifed_ifu_to_ibuffer_ready(_inner_ibuffer_io_in_ready),
  .ifed_ifu_to_ibuffer_ftq_flag(inner_ifu.io_toIBuffer_bits_ftqPtr_0_flag),
  .ifed_ifu_to_ibuffer_ftq_value(inner_ifu.io_toIBuffer_bits_ftqPtr_0_value),
  .ifed_ifu_exception_type(_inner_ifu_io_toIBuffer_bits_exceptionType_value),
  .ifed_ifu_exception_cross_page(_inner_ifu_io_toIBuffer_bits_exceptionCrossPage),
  .ifed_ifu_s2_req_is_uncache(inner_ifu.s2_reqIsUncache),
  .ifed_ifu_s2_prev_end_half_rvi(inner_ifu.s2_prevEndIsHalfRvi),
  .ifed_ifu_s2_ftq_flag(inner_ifu.s2_fetchBlock_0_ftqIdx_flag),
  .ifed_ifu_s2_ftq_value(inner_ifu.s2_fetchBlock_0_ftqIdx_value),
  .ifed_ifu_s2_icache_exception(inner_ifu.s2_icacheMeta_0_exception_value),
  .ifed_ifu_uncache_exception(inner_ifu._uncacheUnit_io_resp_bits_exception_value),
  .ifed_trigger_pc_match(|{
    inner_ifu.frontendTrigger.triggerHitVec_0_0, inner_ifu.frontendTrigger.triggerHitVec_0_1, inner_ifu.frontendTrigger.triggerHitVec_0_2,
    inner_ifu.frontendTrigger.triggerHitVec_1_0, inner_ifu.frontendTrigger.triggerHitVec_1_1, inner_ifu.frontendTrigger.triggerHitVec_1_2,
    inner_ifu.frontendTrigger.triggerHitVec_2_0, inner_ifu.frontendTrigger.triggerHitVec_2_1, inner_ifu.frontendTrigger.triggerHitVec_2_2,
    inner_ifu.frontendTrigger.triggerHitVec_3_0, inner_ifu.frontendTrigger.triggerHitVec_3_1, inner_ifu.frontendTrigger.triggerHitVec_3_2,
    inner_ifu.frontendTrigger.triggerHitVec_4_0, inner_ifu.frontendTrigger.triggerHitVec_4_1, inner_ifu.frontendTrigger.triggerHitVec_4_2,
    inner_ifu.frontendTrigger.triggerHitVec_5_0, inner_ifu.frontendTrigger.triggerHitVec_5_1, inner_ifu.frontendTrigger.triggerHitVec_5_2,
    inner_ifu.frontendTrigger.triggerHitVec_6_0, inner_ifu.frontendTrigger.triggerHitVec_6_1, inner_ifu.frontendTrigger.triggerHitVec_6_2,
    inner_ifu.frontendTrigger.triggerHitVec_7_0, inner_ifu.frontendTrigger.triggerHitVec_7_1, inner_ifu.frontendTrigger.triggerHitVec_7_2,
    inner_ifu.frontendTrigger.triggerHitVec_8_0, inner_ifu.frontendTrigger.triggerHitVec_8_1, inner_ifu.frontendTrigger.triggerHitVec_8_2,
    inner_ifu.frontendTrigger.triggerHitVec_9_0, inner_ifu.frontendTrigger.triggerHitVec_9_1, inner_ifu.frontendTrigger.triggerHitVec_9_2,
    inner_ifu.frontendTrigger.triggerHitVec_10_0, inner_ifu.frontendTrigger.triggerHitVec_10_1, inner_ifu.frontendTrigger.triggerHitVec_10_2,
    inner_ifu.frontendTrigger.triggerHitVec_11_0, inner_ifu.frontendTrigger.triggerHitVec_11_1, inner_ifu.frontendTrigger.triggerHitVec_11_2,
    inner_ifu.frontendTrigger.triggerHitVec_12_0, inner_ifu.frontendTrigger.triggerHitVec_12_1, inner_ifu.frontendTrigger.triggerHitVec_12_2,
    inner_ifu.frontendTrigger.triggerHitVec_13_0, inner_ifu.frontendTrigger.triggerHitVec_13_1, inner_ifu.frontendTrigger.triggerHitVec_13_2,
    inner_ifu.frontendTrigger.triggerHitVec_14_0, inner_ifu.frontendTrigger.triggerHitVec_14_1, inner_ifu.frontendTrigger.triggerHitVec_14_2,
    inner_ifu.frontendTrigger.triggerHitVec_15_0, inner_ifu.frontendTrigger.triggerHitVec_15_1, inner_ifu.frontendTrigger.triggerHitVec_15_2,
    inner_ifu.frontendTrigger.triggerHitVec_16_0, inner_ifu.frontendTrigger.triggerHitVec_16_1, inner_ifu.frontendTrigger.triggerHitVec_16_2,
    inner_ifu.frontendTrigger.triggerHitVec_17_0, inner_ifu.frontendTrigger.triggerHitVec_17_1, inner_ifu.frontendTrigger.triggerHitVec_17_2,
    inner_ifu.frontendTrigger.triggerHitVec_18_0, inner_ifu.frontendTrigger.triggerHitVec_18_1, inner_ifu.frontendTrigger.triggerHitVec_18_2,
    inner_ifu.frontendTrigger.triggerHitVec_19_0, inner_ifu.frontendTrigger.triggerHitVec_19_1, inner_ifu.frontendTrigger.triggerHitVec_19_2,
    inner_ifu.frontendTrigger.triggerHitVec_20_0, inner_ifu.frontendTrigger.triggerHitVec_20_1, inner_ifu.frontendTrigger.triggerHitVec_20_2,
    inner_ifu.frontendTrigger.triggerHitVec_21_0, inner_ifu.frontendTrigger.triggerHitVec_21_1, inner_ifu.frontendTrigger.triggerHitVec_21_2,
    inner_ifu.frontendTrigger.triggerHitVec_22_0, inner_ifu.frontendTrigger.triggerHitVec_22_1, inner_ifu.frontendTrigger.triggerHitVec_22_2,
    inner_ifu.frontendTrigger.triggerHitVec_23_0, inner_ifu.frontendTrigger.triggerHitVec_23_1, inner_ifu.frontendTrigger.triggerHitVec_23_2,
    inner_ifu.frontendTrigger.triggerHitVec_24_0, inner_ifu.frontendTrigger.triggerHitVec_24_1, inner_ifu.frontendTrigger.triggerHitVec_24_2,
    inner_ifu.frontendTrigger.triggerHitVec_25_0, inner_ifu.frontendTrigger.triggerHitVec_25_1, inner_ifu.frontendTrigger.triggerHitVec_25_2,
    inner_ifu.frontendTrigger.triggerHitVec_26_0, inner_ifu.frontendTrigger.triggerHitVec_26_1, inner_ifu.frontendTrigger.triggerHitVec_26_2,
    inner_ifu.frontendTrigger.triggerHitVec_27_0, inner_ifu.frontendTrigger.triggerHitVec_27_1, inner_ifu.frontendTrigger.triggerHitVec_27_2,
    inner_ifu.frontendTrigger.triggerHitVec_28_0, inner_ifu.frontendTrigger.triggerHitVec_28_1, inner_ifu.frontendTrigger.triggerHitVec_28_2,
    inner_ifu.frontendTrigger.triggerHitVec_29_0, inner_ifu.frontendTrigger.triggerHitVec_29_1, inner_ifu.frontendTrigger.triggerHitVec_29_2,
    inner_ifu.frontendTrigger.triggerHitVec_30_0, inner_ifu.frontendTrigger.triggerHitVec_30_1, inner_ifu.frontendTrigger.triggerHitVec_30_2,
    inner_ifu.frontendTrigger.triggerHitVec_31_0, inner_ifu.frontendTrigger.triggerHitVec_31_1, inner_ifu.frontendTrigger.triggerHitVec_31_2,
    inner_ifu.frontendTrigger.triggerHitVec_32_0, inner_ifu.frontendTrigger.triggerHitVec_32_1, inner_ifu.frontendTrigger.triggerHitVec_32_2,
    inner_ifu.frontendTrigger.triggerHitVec_33_0, inner_ifu.frontendTrigger.triggerHitVec_33_1, inner_ifu.frontendTrigger.triggerHitVec_33_2,
    inner_ifu.frontendTrigger.triggerHitVec_34_0, inner_ifu.frontendTrigger.triggerHitVec_34_1, inner_ifu.frontendTrigger.triggerHitVec_34_2,
    inner_ifu.frontendTrigger.triggerHitVec_35_0, inner_ifu.frontendTrigger.triggerHitVec_35_1, inner_ifu.frontendTrigger.triggerHitVec_35_2
  }),
  .ifed_ifu_s2_cacheable((inner_ifu.s2_fetchBlock_0_valid || inner_ifu.s2_fetchBlock_1_valid) &&
    inner_ifu.s2_icacheMeta_0_itlbPbmt == 2'b00 && !inner_ifu.s2_icacheMeta_0_pmpMmio &&
    inner_ifu.s2_icacheMeta_0_exception_value == 3'd0),
  .ifed_uncache_response_valid(auto_inner_instrUncache_client_out_d_valid),
  .ifed_cfvec_valid({io_backend_cfVec_7_valid, io_backend_cfVec_6_valid,
                io_backend_cfVec_5_valid, io_backend_cfVec_4_valid,
                io_backend_cfVec_3_valid, io_backend_cfVec_2_valid,
                io_backend_cfVec_1_valid, io_backend_cfVec_0_valid}),
  .ifed_cfvec_is_rvc({io_backend_cfVec_7_bits_isRvc, io_backend_cfVec_6_bits_isRvc,
                 io_backend_cfVec_5_bits_isRvc, io_backend_cfVec_4_bits_isRvc,
                 io_backend_cfVec_3_bits_isRvc, io_backend_cfVec_2_bits_isRvc,
                 io_backend_cfVec_1_bits_isRvc, io_backend_cfVec_0_bits_isRvc}),
  .ifed_cfvec_illegal_instruction({io_backend_cfVec_7_bits_exceptionVec_2,
                              io_backend_cfVec_6_bits_exceptionVec_2,
                              io_backend_cfVec_5_bits_exceptionVec_2,
                              io_backend_cfVec_4_bits_exceptionVec_2,
                              io_backend_cfVec_3_bits_exceptionVec_2,
                              io_backend_cfVec_2_bits_exceptionVec_2,
                              io_backend_cfVec_1_bits_exceptionVec_2,
                              io_backend_cfVec_0_bits_exceptionVec_2}),
  .ifed_cfvec_trigger({io_backend_cfVec_7_bits_trigger, io_backend_cfVec_6_bits_trigger,
                       io_backend_cfVec_5_bits_trigger, io_backend_cfVec_4_bits_trigger,
                       io_backend_cfVec_3_bits_trigger, io_backend_cfVec_2_bits_trigger,
                       io_backend_cfVec_1_bits_trigger, io_backend_cfVec_0_bits_trigger}),
  .mmio_s2_valid(inner_ifu.s2_valid_valid),
  .mmio_s2_req_is_uncache(inner_ifu.s2_reqIsUncache),
  .mmio_s2_use_uncache(inner_ifu.s2_useUncacheFetch),
  .mmio_s2_double_line(inner_ifu.s2_fetchBlock_1_valid),
  .mmio_s2_pmp_mmio_0(inner_ifu.s2_icacheMeta_0_pmpMmio),
  .mmio_s2_pbmt_0(inner_ifu.s2_icacheMeta_0_itlbPbmt),
  .mmio_s2_exception_0(inner_ifu.s2_icacheMeta_0_exception_value),
  .mmio_s2_pc_0(inner_ifu.s2_fetchBlock_0_startVAddr_addr),
  .mmio_is_first_instr(inner_ifu.isFirstInstr),
  .mmio_uncache_input_valid(inner_ifu.uncacheUnit_io_req_valid),
  .mmio_uncache_input_ready(inner_ifu._uncacheUnit_io_req_ready),
  .mmio_uncache_state(inner_ifu.uncacheUnit.uncacheState),
  .mmio_uncache_busy(inner_ifu.uncacheBusy),
  .mmio_ifu_stall(!_inner_ibuffer_io_in_ready),
  .mmio_empty_after(io_backend_backendEmpty && _inner_ibuffer_io_empty),
  .mmio_backend_commit(io_backend_toFtq_commit_valid),
  .mmio_backend_empty(io_backend_backendEmpty),
  .mmio_ibuffer_empty(_inner_ibuffer_io_empty),
  .mmio_backend_can_accept(io_backend_canAccept),
  .mmio_tl_a_valid(auto_inner_instrUncache_client_out_a_valid),
  .mmio_tl_a_ready(auto_inner_instrUncache_client_out_a_ready),
  .mmio_tl_a_addr(auto_inner_instrUncache_client_out_a_bits_address),
  .mmio_tl_d_valid(auto_inner_instrUncache_client_out_d_valid &&
                   !auto_inner_instrUncache_client_out_d_bits_source),
  .mmio_tl_d_data(auto_inner_instrUncache_client_out_d_bits_data),
  .mmio_tl_d_corrupt(auto_inner_instrUncache_client_out_d_bits_corrupt),
  .mmio_tl_d_denied(auto_inner_instrUncache_client_out_d_bits_denied),
  .mmio_entry_state(inner_instrUncache.entries_0.state),
  .mmio_entry_resending(inner_instrUncache.entries_0.resending),
  .mmio_entry_req_addr(inner_instrUncache.entries_0.reqReg_addr_addr),
  .mmio_uncache_resp_valid(inner_ifu._uncacheUnit_io_resp_valid),
  .mmio_uncache_resp_data(inner_ifu._uncacheUnit_io_resp_bits_uncacheData),
  .mmio_uncache_resp_exception(inner_ifu._uncacheUnit_io_resp_bits_exception_value),
  .mmio_uncache_resp_need_resend(inner_ifu._uncacheUnit_io_resp_bits_needResend),
  .mmio_to_ibuffer_valid(_inner_ifu_io_toIBuffer_valid),
  .mmio_to_ibuffer_ready(_inner_ibuffer_io_in_ready),
  .mmio_to_ibuffer_enq(_inner_ifu_io_toIBuffer_bits_enqEnable),
  .mmio_to_ibuffer_pc_0(_inner_ifu_io_toIBuffer_bits_pc_0_addr),
  .mmio_to_ibuffer_is_rvc({
    _inner_ifu_io_toIBuffer_bits_isRvc_35, _inner_ifu_io_toIBuffer_bits_isRvc_34,
    _inner_ifu_io_toIBuffer_bits_isRvc_33, _inner_ifu_io_toIBuffer_bits_isRvc_32,
    _inner_ifu_io_toIBuffer_bits_isRvc_31, _inner_ifu_io_toIBuffer_bits_isRvc_30,
    _inner_ifu_io_toIBuffer_bits_isRvc_29, _inner_ifu_io_toIBuffer_bits_isRvc_28,
    _inner_ifu_io_toIBuffer_bits_isRvc_27, _inner_ifu_io_toIBuffer_bits_isRvc_26,
    _inner_ifu_io_toIBuffer_bits_isRvc_25, _inner_ifu_io_toIBuffer_bits_isRvc_24,
    _inner_ifu_io_toIBuffer_bits_isRvc_23, _inner_ifu_io_toIBuffer_bits_isRvc_22,
    _inner_ifu_io_toIBuffer_bits_isRvc_21, _inner_ifu_io_toIBuffer_bits_isRvc_20,
    _inner_ifu_io_toIBuffer_bits_isRvc_19, _inner_ifu_io_toIBuffer_bits_isRvc_18,
    _inner_ifu_io_toIBuffer_bits_isRvc_17, _inner_ifu_io_toIBuffer_bits_isRvc_16,
    _inner_ifu_io_toIBuffer_bits_isRvc_15, _inner_ifu_io_toIBuffer_bits_isRvc_14,
    _inner_ifu_io_toIBuffer_bits_isRvc_13, _inner_ifu_io_toIBuffer_bits_isRvc_12,
    _inner_ifu_io_toIBuffer_bits_isRvc_11, _inner_ifu_io_toIBuffer_bits_isRvc_10,
    _inner_ifu_io_toIBuffer_bits_isRvc_9, _inner_ifu_io_toIBuffer_bits_isRvc_8,
    _inner_ifu_io_toIBuffer_bits_isRvc_7, _inner_ifu_io_toIBuffer_bits_isRvc_6,
    _inner_ifu_io_toIBuffer_bits_isRvc_5, _inner_ifu_io_toIBuffer_bits_isRvc_4,
    _inner_ifu_io_toIBuffer_bits_isRvc_3, _inner_ifu_io_toIBuffer_bits_isRvc_2,
    _inner_ifu_io_toIBuffer_bits_isRvc_1, _inner_ifu_io_toIBuffer_bits_isRvc_0}),
  .mmio_to_ibuffer_exception(_inner_ifu_io_toIBuffer_bits_exceptionType_value),
  .mmio_to_ibuffer_exception_cross_page(_inner_ifu_io_toIBuffer_bits_exceptionCrossPage),
  .mmio_backend_redirect(io_backend_toFtq_redirect_valid),
  .mmio_ifu_flush(inner_ifu.s2_flush),
  .mmio_uncache_redirect(inner_ifu.uncacheRedirect_valid),
  .mmio_wb_redirect(_inner_ifu_io_toFtq_wbRedirect_valid),
  .mmio_wb_path_valid(inner_ifu.wbValid),
  .mmio_uncache_branch_type(inner_ifu.brAttribute_branchType),
  .mmio_prev_end_half_rvi(inner_ifu.s2_prevEndIsHalfRvi),
  .mmio_prev_half_data(inner_ifu.s2_prevEndHalfRviData),
  .mmio_prev_half_pc(inner_ifu.s2_prevEndHalfPc_addr),
  .mmio_uncache_pc(inner_ifu.uncachePc_addr),
  .mmio_cfvec_valid(|{io_backend_cfVec_7_valid, io_backend_cfVec_6_valid,
                       io_backend_cfVec_5_valid, io_backend_cfVec_4_valid,
                       io_backend_cfVec_3_valid, io_backend_cfVec_2_valid,
                       io_backend_cfVec_1_valid, io_backend_cfVec_0_valid}),
  .mmio_wfi_safe(io_backend_wfi_wfiSafe),
  .wfi_backend_req(io_backend_wfi_wfiReq),
  .wfi_delayed_req(_inner_wfiReq_delay_io_out),
  .wfi_backend_safe(io_backend_wfi_wfiSafe),
  .wfi_icache_safe(_inner_icache_io_wfi_wfiSafe),
  .wfi_instr_uncache_safe(_inner_instrUncache_io_wfi_wfiSafe),
  .wfi_icache_tl_a_valid(auto_inner_icache_client_out_a_valid),
  .wfi_icache_tl_a_ready(auto_inner_icache_client_out_a_ready),
  .wfi_instr_uncache_tl_a_valid(auto_inner_instrUncache_client_out_a_valid),
  .wfi_instr_uncache_tl_a_ready(auto_inner_instrUncache_client_out_a_ready),
  .wfi_icache_mshr_valid({
    inner_icache.missUnit.allMshr_13.valid, inner_icache.missUnit.allMshr_12.valid,
    inner_icache.missUnit.allMshr_11.valid, inner_icache.missUnit.allMshr_10.valid,
    inner_icache.missUnit.allMshr_9.valid, inner_icache.missUnit.allMshr_8.valid,
    inner_icache.missUnit.allMshr_7.valid, inner_icache.missUnit.allMshr_6.valid,
    inner_icache.missUnit.allMshr_5.valid, inner_icache.missUnit.allMshr_4.valid,
    inner_icache.missUnit.allMshr_3.valid, inner_icache.missUnit.allMshr_2.valid,
    inner_icache.missUnit.allMshr_1.valid, inner_icache.missUnit.allMshr_0.valid
  }),
  .wfi_icache_mshr_issue({
    inner_icache.missUnit.allMshr_13.issue, inner_icache.missUnit.allMshr_12.issue,
    inner_icache.missUnit.allMshr_11.issue, inner_icache.missUnit.allMshr_10.issue,
    inner_icache.missUnit.allMshr_9.issue, inner_icache.missUnit.allMshr_8.issue,
    inner_icache.missUnit.allMshr_7.issue, inner_icache.missUnit.allMshr_6.issue,
    inner_icache.missUnit.allMshr_5.issue, inner_icache.missUnit.allMshr_4.issue,
    inner_icache.missUnit.allMshr_3.issue, inner_icache.missUnit.allMshr_2.issue,
    inner_icache.missUnit.allMshr_1.issue, inner_icache.missUnit.allMshr_0.issue
  }),
  .wfi_instr_uncache_entry_state(inner_instrUncache.entries_0.state),
  .wfi_frontend_flush(inner_ifu.s2_flush),
  .wfi_backend_redirect(io_backend_toFtq_redirect_valid),
  .nc_icache_waylookup_valid(inner_icache.mainPipe.s1_valid),
  .nc_icache_waymask_0(inner_icache.mainPipe.s1_wayLookupEntry_0_waymask_0),
  .nc_icache_waymask_1(inner_icache.mainPipe.s1_wayLookupEntry_0_waymask_1),
  .rfr_backend_redirect_valid(io_backend_toFtq_redirect_valid),
  .rfr_backend_redirect_target(io_backend_toFtq_redirect_bits_target),
  .rfr_backend_redirect_level(io_backend_toFtq_redirect_bits_level),
  .rfr_backend_redirect_is_rvc(io_backend_toFtq_redirect_bits_isRVC),
  .rfr_backend_redirect_iaf(io_backend_toFtq_redirect_bits_backendIAF),
  .rfr_backend_redirect_ipf(io_backend_toFtq_redirect_bits_backendIPF),
  .rfr_backend_redirect_igpf(io_backend_toFtq_redirect_bits_backendIGPF),
  .rfr_backend_redirect_is_ctrl(io_backend_toFtq_redirect_bits_debugIsCtrl),
  .rfr_backend_redirect_is_mem_vio(io_backend_toFtq_redirect_bits_debugIsMemVio),
  .rfr_ftq_idx_ahead_valid(io_backend_toFtq_ftqIdxAhead_valid),
  .rfr_ftq_idx_ahead_flag(io_backend_toFtq_ftqIdxAhead_bits_flag),
  .rfr_ftq_idx_ahead_value(io_backend_toFtq_ftqIdxAhead_bits_value),
  .rfr_backend_redirect_ftq_idx_flag(io_backend_toFtq_redirect_bits_ftqIdx_flag),
  .rfr_backend_redirect_ftq_idx_value(io_backend_toFtq_redirect_bits_ftqIdx_value),
  .rfr_backend_redirect_ftq_offset(io_backend_toFtq_redirect_bits_ftqOffset),
  .rfr_ftq_meta_valid(_inner_bpu_io_toFtq_meta_valid),
  .rfr_ftq_meta_idx_flag(_inner_bpu_io_toFtq_s3FtqPtr_flag),
  .rfr_ftq_meta_idx_value(_inner_bpu_io_toFtq_s3FtqPtr_value),
  .rfr_to_bpu_redirect_valid(_inner_ftq_io_toBpu_redirect_valid),
  .rfr_to_bpu_redirect_target(_inner_ftq_io_toBpu_redirect_bits_target_addr),
  .rfr_icache_redirect_flush(_inner_ftq_io_toICache_redirectFlush),
  .rfr_bpu_flush_valid(_inner_ftq_io_toICache_flushFromBpu_s3_valid),
  .rfr_ifu_wb_redirect_valid(_inner_ifu_io_toFtq_wbRedirect_valid),
  .rfr_ifu_wb_redirect_target(_inner_ifu_io_toFtq_wbRedirect_bits_target),
  .rfr_ifu_wb_redirect_taken(_inner_ifu_io_toFtq_wbRedirect_bits_taken),
  .rfr_ifu_wb_redirect_is_rvc(_inner_ifu_io_toFtq_wbRedirect_bits_isRVC),
  .rfr_ibuffer_empty(_inner_ibuffer_io_empty),
  .rfr_ibuffer_ready(_inner_ibuffer_io_in_ready),
  .rfr_icache_response_valid(auto_inner_icache_client_out_d_valid),
  .rfr_uncache_response_valid(auto_inner_instrUncache_client_out_d_valid),
  .rfr_uncache_response_need_resend(_inner_instrUncache_io_toIfu_resp_bits_needResend),
  .rfr_uncache_entry_req_addr(inner_instrUncache.entries_0.reqReg_addr_addr),
  .rfr_icache_a_valid(auto_inner_icache_client_out_a_valid),
  .rfr_icache_a_ready(auto_inner_icache_client_out_a_ready),
  .rfr_icache_a_source(auto_inner_icache_client_out_a_bits_source),
  .rfr_icache_d_source(auto_inner_icache_client_out_d_bits_source),
  .rfr_uncache_a_valid(auto_inner_instrUncache_client_out_a_valid),
  .rfr_uncache_a_ready(auto_inner_instrUncache_client_out_a_ready),
  .rfr_ifu_to_ibuffer_valid(_inner_ifu_io_toIBuffer_valid),
  .rfr_icache_to_ifu_valid(_inner_icache_io_toIfu_req_valid),
  .rfr_main_fetch_valid(_inner_ftq_io_toICache_toMainPipe_valid),
  .rfr_main_fetch_ready(_inner_icache_io_fromFtq_toMainPipe_ready),
  .rfr_prefetch_valid(_inner_ftq_io_toICache_toPrefetch_valid),
  .rfr_ifu_s1_valid(|inner_ifu.s1_valid),
  .rfr_ifu_s2_valid(inner_ifu.s2_fetchBlock_0_valid || inner_ifu.s2_fetchBlock_1_valid),
  .rfr_backend_can_accept(io_backend_canAccept),
  .rfr_pred_checker_remask_fault(|{
    inner_ifu.predChecker._stage1Fault_T, inner_ifu.predChecker._stage1Fault_T_4,
    inner_ifu.predChecker._stage1Fault_T_8, inner_ifu.predChecker._stage1Fault_T_12,
    inner_ifu.predChecker._stage1Fault_T_16, inner_ifu.predChecker._stage1Fault_T_20,
    inner_ifu.predChecker._stage1Fault_T_24, inner_ifu.predChecker._stage1Fault_T_28,
    inner_ifu.predChecker._stage1Fault_T_32, inner_ifu.predChecker._stage1Fault_T_36,
    inner_ifu.predChecker._stage1Fault_T_40, inner_ifu.predChecker._stage1Fault_T_44,
    inner_ifu.predChecker._stage1Fault_T_48, inner_ifu.predChecker._stage1Fault_T_52,
    inner_ifu.predChecker._stage1Fault_T_56, inner_ifu.predChecker._stage1Fault_T_60,
    inner_ifu.predChecker._stage1Fault_T_64, inner_ifu.predChecker._stage1Fault_T_68,
    inner_ifu.predChecker._stage1Fault_T_72, inner_ifu.predChecker._stage1Fault_T_76,
    inner_ifu.predChecker._stage1Fault_T_80, inner_ifu.predChecker._stage1Fault_T_84,
    inner_ifu.predChecker._stage1Fault_T_88, inner_ifu.predChecker._stage1Fault_T_92,
    inner_ifu.predChecker._stage1Fault_T_96, inner_ifu.predChecker._stage1Fault_T_100,
    inner_ifu.predChecker._stage1Fault_T_104, inner_ifu.predChecker._stage1Fault_T_108,
    inner_ifu.predChecker._stage1Fault_T_112, inner_ifu.predChecker._stage1Fault_T_116,
    inner_ifu.predChecker._stage1Fault_T_120, inner_ifu.predChecker._stage1Fault_T_124,
    inner_ifu.predChecker._stage1Fault_T_128, inner_ifu.predChecker._stage1Fault_T_132,
    inner_ifu.predChecker._stage1Fault_T_136,
    inner_ifu.predChecker.retFaultVec_0, inner_ifu.predChecker.retFaultVec_1,
    inner_ifu.predChecker.retFaultVec_2, inner_ifu.predChecker.retFaultVec_3,
    inner_ifu.predChecker.retFaultVec_4, inner_ifu.predChecker.retFaultVec_5,
    inner_ifu.predChecker.retFaultVec_6, inner_ifu.predChecker.retFaultVec_7,
    inner_ifu.predChecker.retFaultVec_8, inner_ifu.predChecker.retFaultVec_9,
    inner_ifu.predChecker.retFaultVec_10, inner_ifu.predChecker.retFaultVec_11,
    inner_ifu.predChecker.retFaultVec_12, inner_ifu.predChecker.retFaultVec_13,
    inner_ifu.predChecker.retFaultVec_14, inner_ifu.predChecker.retFaultVec_15,
    inner_ifu.predChecker.retFaultVec_16, inner_ifu.predChecker.retFaultVec_17,
    inner_ifu.predChecker.retFaultVec_18, inner_ifu.predChecker.retFaultVec_19,
    inner_ifu.predChecker.retFaultVec_20, inner_ifu.predChecker.retFaultVec_21,
    inner_ifu.predChecker.retFaultVec_22, inner_ifu.predChecker.retFaultVec_23,
    inner_ifu.predChecker.retFaultVec_24, inner_ifu.predChecker.retFaultVec_25,
    inner_ifu.predChecker.retFaultVec_26, inner_ifu.predChecker.retFaultVec_27,
    inner_ifu.predChecker.retFaultVec_28, inner_ifu.predChecker.retFaultVec_29,
    inner_ifu.predChecker.retFaultVec_30, inner_ifu.predChecker.retFaultVec_31,
    inner_ifu.predChecker.retFaultVec_32, inner_ifu.predChecker.retFaultVec_33,
    inner_ifu.predChecker.retFaultVec_34}),
  .rfr_pred_checker_not_cfi_taken(|{
    inner_ifu.predChecker.notCfiTaken_0, inner_ifu.predChecker.notCfiTaken_1,
    inner_ifu.predChecker.notCfiTaken_2, inner_ifu.predChecker.notCfiTaken_3,
    inner_ifu.predChecker.notCfiTaken_4, inner_ifu.predChecker.notCfiTaken_5,
    inner_ifu.predChecker.notCfiTaken_6, inner_ifu.predChecker.notCfiTaken_7,
    inner_ifu.predChecker.notCfiTaken_8, inner_ifu.predChecker.notCfiTaken_9,
    inner_ifu.predChecker.notCfiTaken_10, inner_ifu.predChecker.notCfiTaken_11,
    inner_ifu.predChecker.notCfiTaken_12, inner_ifu.predChecker.notCfiTaken_13,
    inner_ifu.predChecker.notCfiTaken_14, inner_ifu.predChecker.notCfiTaken_15,
    inner_ifu.predChecker.notCfiTaken_16, inner_ifu.predChecker.notCfiTaken_17,
    inner_ifu.predChecker.notCfiTaken_18, inner_ifu.predChecker.notCfiTaken_19,
    inner_ifu.predChecker.notCfiTaken_20, inner_ifu.predChecker.notCfiTaken_21,
    inner_ifu.predChecker.notCfiTaken_22, inner_ifu.predChecker.notCfiTaken_23,
    inner_ifu.predChecker.notCfiTaken_24, inner_ifu.predChecker.notCfiTaken_25,
    inner_ifu.predChecker.notCfiTaken_26, inner_ifu.predChecker.notCfiTaken_27,
    inner_ifu.predChecker.notCfiTaken_28, inner_ifu.predChecker.notCfiTaken_29,
    inner_ifu.predChecker.notCfiTaken_30, inner_ifu.predChecker.notCfiTaken_31,
    inner_ifu.predChecker.notCfiTaken_32, inner_ifu.predChecker.notCfiTaken_33,
    inner_ifu.predChecker.notCfiTaken_34}),
  .rfr_pred_checker_invalid_taken(inner_ifu.predChecker.invalidTakenNext),
  .rfr_itlb_flush_pipe(_inner_icache_io_itlbFlushPipe),
  .rfr_fencei(io_fencei),
  .rfr_icache_cacheable_hit(inner_icache.mainPipe.s2_sramHits_0_0),
  .rfr_prefetch_s1_valid(inner_icache.prefetcher.s1_valid),
  .rfr_prefetch_wait_itlb(inner_icache.prefetcher.s1_waitItlb),
  .rfr_prefetch_tlb_latch_valid(inner_icache.prefetcher.tlbValidLatch_valid),
  .rfr_sfence_valid(io_sfence_valid),
  .rfr_satp_changed(io_tlbCsr_satp_changed),
  .rfr_vsatp_changed(io_tlbCsr_vsatp_changed),
  .rfr_hgatp_changed(io_tlbCsr_hgatp_changed),
  .rfr_priv_virt_changed(io_tlbCsr_priv_virt_changed),
  .rfr_cfvec_valid({io_backend_cfVec_7_valid, io_backend_cfVec_6_valid,
                io_backend_cfVec_5_valid, io_backend_cfVec_4_valid,
                io_backend_cfVec_3_valid, io_backend_cfVec_2_valid,
                io_backend_cfVec_1_valid, io_backend_cfVec_0_valid}),
  .rfr_cfvec_pc({io_backend_cfVec_7_bits_pc, io_backend_cfVec_6_bits_pc,
             io_backend_cfVec_5_bits_pc, io_backend_cfVec_4_bits_pc,
             io_backend_cfVec_3_bits_pc, io_backend_cfVec_2_bits_pc,
             io_backend_cfVec_1_bits_pc, io_backend_cfVec_0_bits_pc}),
  .rfr_cfvec_iaf({io_backend_cfVec_7_bits_exceptionVec_1, io_backend_cfVec_6_bits_exceptionVec_1,
              io_backend_cfVec_5_bits_exceptionVec_1, io_backend_cfVec_4_bits_exceptionVec_1,
              io_backend_cfVec_3_bits_exceptionVec_1, io_backend_cfVec_2_bits_exceptionVec_1,
              io_backend_cfVec_1_bits_exceptionVec_1, io_backend_cfVec_0_bits_exceptionVec_1}),
  .rfr_cfvec_ipf({io_backend_cfVec_7_bits_exceptionVec_12, io_backend_cfVec_6_bits_exceptionVec_12,
              io_backend_cfVec_5_bits_exceptionVec_12, io_backend_cfVec_4_bits_exceptionVec_12,
              io_backend_cfVec_3_bits_exceptionVec_12, io_backend_cfVec_2_bits_exceptionVec_12,
              io_backend_cfVec_1_bits_exceptionVec_12, io_backend_cfVec_0_bits_exceptionVec_12}),
  .rfr_cfvec_igpf({io_backend_cfVec_7_bits_exceptionVec_20, io_backend_cfVec_6_bits_exceptionVec_20,
               io_backend_cfVec_5_bits_exceptionVec_20, io_backend_cfVec_4_bits_exceptionVec_20,
               io_backend_cfVec_3_bits_exceptionVec_20, io_backend_cfVec_2_bits_exceptionVec_20,
               io_backend_cfVec_1_bits_exceptionVec_20, io_backend_cfVec_0_bits_exceptionVec_20}),
  .rfr_cfvec_backend_exception({io_backend_cfVec_7_bits_backendException, io_backend_cfVec_6_bits_backendException,
                            io_backend_cfVec_5_bits_backendException, io_backend_cfVec_4_bits_backendException,
                            io_backend_cfVec_3_bits_backendException, io_backend_cfVec_2_bits_backendException,
                            io_backend_cfVec_1_bits_backendException, io_backend_cfVec_0_bits_backendException})
);
