# OpenIOMMU RTL sources for Verilator/VCS.
# IOMMU_ROOT may be overridden by the including Makefile.
IOMMU_ROOT ?= $(patsubst %/,%,$(dir $(lastword $(MAKEFILE_LIST))))

# Keep this order synchronized with iommu_wrap.f; package/module order matters.
IOMMU_VSRC := \
  $(IOMMU_ROOT)/axi4_traffic.sv \
  $(IOMMU_ROOT)/iommu_axi_mon.sv \
  $(IOMMU_ROOT)/iommu_wrap.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/iommu_atd_cache_pkg.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_wrap/iommu_atd.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_sw/iommu_sw_apb.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_sw/iommu_atd_pq.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_sw/iommu_atd_sw.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_sw/iommu_atd_cq.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_sw/iommu_atd_fq.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_sw/iommu_atd_msi.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_tw/iommu_tw_apb.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_tw/iommu_atd_tw.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_tw/iommu_atd_cdw.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_tw/iommu_atd_ptw.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_tw/iommu_atd_hpm.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_tc/iommu_tc_apb.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_tc/iommu_atd_tc.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_tc/iommu_atd_t2c.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_tc/iommu_atd_c2t.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_tr/iommu_atd_tr.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_tr/iommu_atd_t2r.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_tr/iommu_atd_r2t.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_ds/iommu_atd_ds.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_ds/atd_arb_a.v \
  $(IOMMU_ROOT)/rtl_atd/atd_ds/atd_arb_d.v \
  $(IOMMU_ROOT)/rtl_atd/atd_ds/atd_rou_ad.v \
  $(IOMMU_ROOT)/rtl_atd/atd_cbb/atd_sync2_rstn.v \
  $(IOMMU_ROOT)/rtl_atd/atd_cbb/atd_reg_slice.v \
  $(IOMMU_ROOT)/rtl_atd/atd_cbb/atd_sync_fifo.v \
  $(IOMMU_ROOT)/rtl_atd/atd_cbb/atd_sync_fifo_wrap.v \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/iommu_atd_inv.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/iommu_atd_ddtc_wrap.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/iommu_atd_pdtc_wrap.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/iommu_atd_s1ptc_wrap.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/iommu_atd_s2ptc_wrap.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/iommu_atd_ptc_multiupdate.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/iommu_atd_cache_ram_generic.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/atd_cache/iommu_atd_dtc_main_tlb.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/atd_cache/iommu_atd_dtc_micro_tlb_entry_update.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/atd_cache/iommu_atd_dtc_micro_tlb_inv_hit.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/atd_cache/iommu_atd_dtc_micro_tlb.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/atd_cache/iommu_atd_dtc_micro_tlb_tag_hit.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/atd_cache/iommu_atd_dtc_mtlb_bank.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/atd_cache/iommu_atd_dtc_mtlb_idx.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/atd_cache/iommu_atd_dtc_mtlb_inv_cabin_wrap.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/atd_cache/iommu_atd_dtc_mtlb_lkp_cabin_wrap.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/atd_cache/iommu_atd_dtc_mtlb_ram_wrap.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/atd_cache/iommu_atd_dtc_mtlb_tag_hit.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/atd_cache/iommu_atd_dtc_mtlb_upd_cabin_wrap.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/atd_cache/iommu_atd_dtc_top.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/atd_cache/iommu_atd_ptc_main_tlb.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/atd_cache/iommu_atd_ptc_micro_tlb_entry_update.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/atd_cache/iommu_atd_ptc_micro_tlb_inv_hit.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/atd_cache/iommu_atd_ptc_micro_tlb.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/atd_cache/iommu_atd_ptc_micro_tlb_tag_hit.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/atd_cache/iommu_atd_ptc_mtlb_bank.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/atd_cache/iommu_atd_ptc_mtlb_idx.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/atd_cache/iommu_atd_ptc_mtlb_inv_cabin_wrap.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/atd_cache/iommu_atd_ptc_mtlb_lkp_cabin_wrap.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/atd_cache/iommu_atd_ptc_mtlb_ram_wrap.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/atd_cache/iommu_atd_ptc_mtlb_tag_hit.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/atd_cache/iommu_atd_ptc_mtlb_upd_cabin_wrap.sv \
  $(IOMMU_ROOT)/rtl_atd/atd_cache/atd_cache/iommu_atd_ptc_top.sv \
  $(IOMMU_ROOT)/rtl_acd/iommu_acd_pkg.sv \
  $(IOMMU_ROOT)/rtl_acd/iommu_acd.sv \
  $(IOMMU_ROOT)/rtl_acd/iommu_acd_generate.sv \
  $(IOMMU_ROOT)/rtl_acd/iommu_acd_ram_generic.sv \
  $(IOMMU_ROOT)/rtl_acd/bus_handler/iommu_acd_bus_handler_w_buf.sv \
  $(IOMMU_ROOT)/rtl_acd/bus_handler/iommu_acd_bus_handler_trans_arb.sv \
  $(IOMMU_ROOT)/rtl_acd/bus_handler/iommu_acd_bus_handler_queue_entry_update.sv \
  $(IOMMU_ROOT)/rtl_acd/bus_handler/iommu_acd_bus_handler_mst_intf.sv \
  $(IOMMU_ROOT)/rtl_acd/bus_handler/iommu_acd_bus_handler_top.sv \
  $(IOMMU_ROOT)/rtl_acd/bus_handler/iommu_acd_bus_handler_trans_queue.sv \
  $(IOMMU_ROOT)/rtl_acd/bus_handler/iommu_acd_bus_handler_trans_queue_entry.sv \
  $(IOMMU_ROOT)/rtl_acd/bus_handler/iommu_acd_bus_handler_idx_fifo.sv \
  $(IOMMU_ROOT)/rtl_acd/bus_handler/iommu_acd_bus_handler_mrif_agent.sv \
  $(IOMMU_ROOT)/rtl_acd/bus_handler/iommu_acd_bus_handler_4k_boundary_check.sv \
  $(IOMMU_ROOT)/rtl_acd/bus_handler/iommu_acd_bus_handler_r_buf.sv \
  $(IOMMU_ROOT)/rtl_acd/bus_handler/iommu_acd_bus_handler_b_buf.sv \
  $(IOMMU_ROOT)/rtl_acd/bus_handler/iommu_acd_bus_handler_bar_queue_entry.sv \
  $(IOMMU_ROOT)/rtl_acd/bus_handler/iommu_acd_bus_handler_slv_err.sv \
  $(IOMMU_ROOT)/rtl_acd/bus_handler/iommu_acd_bus_handler_slv_intf.sv \
  $(IOMMU_ROOT)/rtl_acd/bus_handler/iommu_acd_bus_handler_regslice.sv \
  $(IOMMU_ROOT)/rtl_acd/tc_if/iommu_acd_tc_if.sv \
  $(IOMMU_ROOT)/rtl_acd/tc_if/iommu_acd_c2t_if.sv \
  $(IOMMU_ROOT)/rtl_acd/tc_if/iommu_acd_t2c_if.sv \
  $(IOMMU_ROOT)/rtl_acd/translate_unit/iommu_acd_mtlb_lkp_cabin_wrap.sv \
  $(IOMMU_ROOT)/rtl_acd/translate_unit/iommu_acd_mtlb_tag_hit.sv \
  $(IOMMU_ROOT)/rtl_acd/translate_unit/iommu_acd_mtlb_plru.sv \
  $(IOMMU_ROOT)/rtl_acd/translate_unit/iommu_multi_bit_1_check.sv \
  $(IOMMU_ROOT)/rtl_acd/translate_unit/iommu_acd_translate_unit.sv \
  $(IOMMU_ROOT)/rtl_acd/translate_unit/iommu_acd_mtlb_inv_cabin_wrap.sv \
  $(IOMMU_ROOT)/rtl_acd/translate_unit/iommu_acd_main_tlb.sv \
  $(IOMMU_ROOT)/rtl_acd/translate_unit/iommu_acd_mtlb_bank.sv \
  $(IOMMU_ROOT)/rtl_acd/translate_unit/iommu_acd_mtlb_bank_top.sv \
  $(IOMMU_ROOT)/rtl_acd/translate_unit/iommu_acd_mtlb_ecc.sv \
  $(IOMMU_ROOT)/rtl_acd/translate_unit/iommu_acd_tlb_wrap.sv \
  $(IOMMU_ROOT)/rtl_acd/translate_unit/iommu_acd_micro_tlb_tag_hit.sv \
  $(IOMMU_ROOT)/rtl_acd/translate_unit/iommu_acd_mtlb_upd_cabin_wrap.sv \
  $(IOMMU_ROOT)/rtl_acd/translate_unit/iommu_acd_mtlb_idx.sv \
  $(IOMMU_ROOT)/rtl_acd/translate_unit/iommu_acd_mtlb_ready_mux.sv \
  $(IOMMU_ROOT)/rtl_acd/translate_unit/iommu_acd_mtlb_ram_wrap.sv \
  $(IOMMU_ROOT)/rtl_acd/translate_unit/iommu_acd_micro_tlb.sv \
  $(IOMMU_ROOT)/rtl_acd/translate_unit/iommu_acd_tlb_queue.sv \
  $(IOMMU_ROOT)/rtl_acd/translate_unit/iommu_acd_tlb_queue_entry.sv \
  $(IOMMU_ROOT)/rtl_acd/translate_unit/iommu_acd_micro_tlb_entry_update.sv \
  $(IOMMU_ROOT)/rtl_acd/translate_unit/iommu_acd_micro_tlb_inv_hit.sv \
  $(IOMMU_ROOT)/rtl_acd/translate_unit/iommu_acd_micro_tlb_plru.sv \
  $(IOMMU_ROOT)/rtl_acd/cfg_ctrl_wrap/iommu_acd_ptw.sv \
  $(IOMMU_ROOT)/rtl_acd/cfg_ctrl_wrap/iommu_acd_cfg.sv \
  $(IOMMU_ROOT)/rtl_acd/cfg_ctrl_wrap/iommu_acd_int.sv \
  $(IOMMU_ROOT)/rtl_acd/cfg_ctrl_wrap/iommu_acd_inv.sv \
  $(IOMMU_ROOT)/rtl_acd/cfg_ctrl_wrap/iommu_acd_cfg_ctrl_wrap.sv \
  $(IOMMU_ROOT)/rtl_acd/cfg_ctrl_wrap/iommu_acd_ptwackfilter.sv \
  $(IOMMU_ROOT)/rtl_acd/cfg_ctrl_wrap/iommu_acd_fault.sv \
  $(IOMMU_ROOT)/rtl_acd/dbg_trace/iommu_acd_dbg.sv \
  $(IOMMU_ROOT)/rtl_acd/dbg_trace/iommu_acd_mon_unit.sv \
  $(IOMMU_ROOT)/rtl_acd/hpm_ctl/iommu_acd_hpm_bus_handler.sv \
  $(IOMMU_ROOT)/rtl_acd/hpm_ctl/iommu_acd_hpm_tlbqueue.sv \
  $(IOMMU_ROOT)/rtl_acd/hpm_ctl/iommu_acd_hpm_tlbwrap.sv \
  $(IOMMU_ROOT)/rtl_acd/hpm_ctl/iommu_acd_hpm_top.sv \
  $(IOMMU_ROOT)/rtl_acd/hpm_ctl/iommu_acd_hpm_translate_unit.sv \
  $(IOMMU_ROOT)/rtl_acd/hpm_ctl/iommu_acd_riscv_hpm_cnt.sv

IOMMU_VFLAGS := \
  +incdir+$(IOMMU_ROOT)/rtl_acd \
  +incdir+$(IOMMU_ROOT)/rtl_atd/atd_cache

