sed -i 's/parameter int unsigned/parameter/g' axi4_traffic.sv
sed -i 's/parameter int unsigned/parameter/g' iommu_axi_mon.sv
sed -i 's/parameter int unsigned/parameter/g' iommu_wrap.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/iommu_atd_cache_pkg.sv 
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_wrap/iommu_atd.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_sw/iommu_sw_apb.sv 
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_sw/iommu_atd_pq.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_sw/iommu_atd_sw.sv 
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_sw/iommu_atd_cq.sv 
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_sw/iommu_atd_fq.sv   
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_sw/iommu_atd_msi.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_tw/iommu_tw_apb.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_tw/iommu_atd_tw.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_tw/iommu_atd_cdw.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_tw/iommu_atd_ptw.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_tw/iommu_atd_hpm.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_tc/iommu_tc_apb.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_tc/iommu_atd_tc.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_tc/iommu_atd_t2c.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_tc/iommu_atd_c2t.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_tr/iommu_atd_tr.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_tr/iommu_atd_t2r.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_tr/iommu_atd_r2t.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_ds/iommu_atd_ds.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_ds/atd_arb_a.v
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_ds/atd_arb_d.v
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_ds/atd_rou_ad.v 
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cbb/atd_sync2_rstn.v
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cbb/atd_reg_slice.v
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cbb/atd_sync_fifo.v
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cbb/atd_sync_fifo_wrap.v
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/iommu_atd_inv.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/iommu_atd_ddtc_wrap.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/iommu_atd_pdtc_wrap.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/iommu_atd_s1ptc_wrap.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/iommu_atd_s2ptc_wrap.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/iommu_atd_ptc_multiupdate.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/iommu_atd_cache_ram_generic.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/atd_cache/iommu_atd_dtc_main_tlb.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/atd_cache/iommu_atd_dtc_micro_tlb_entry_update.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/atd_cache/iommu_atd_dtc_micro_tlb_inv_hit.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/atd_cache/iommu_atd_dtc_micro_tlb.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/atd_cache/iommu_atd_dtc_micro_tlb_tag_hit.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/atd_cache/iommu_atd_dtc_mtlb_bank.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/atd_cache/iommu_atd_dtc_mtlb_idx.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/atd_cache/iommu_atd_dtc_mtlb_inv_cabin_wrap.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/atd_cache/iommu_atd_dtc_mtlb_lkp_cabin_wrap.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/atd_cache/iommu_atd_dtc_mtlb_ram_wrap.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/atd_cache/iommu_atd_dtc_mtlb_tag_hit.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/atd_cache/iommu_atd_dtc_mtlb_upd_cabin_wrap.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/atd_cache/iommu_atd_dtc_top.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/atd_cache/iommu_atd_ptc_main_tlb.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/atd_cache/iommu_atd_ptc_micro_tlb_entry_update.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/atd_cache/iommu_atd_ptc_micro_tlb_inv_hit.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/atd_cache/iommu_atd_ptc_micro_tlb.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/atd_cache/iommu_atd_ptc_micro_tlb_tag_hit.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/atd_cache/iommu_atd_ptc_mtlb_bank.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/atd_cache/iommu_atd_ptc_mtlb_idx.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/atd_cache/iommu_atd_ptc_mtlb_inv_cabin_wrap.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/atd_cache/iommu_atd_ptc_mtlb_lkp_cabin_wrap.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/atd_cache/iommu_atd_ptc_mtlb_ram_wrap.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/atd_cache/iommu_atd_ptc_mtlb_tag_hit.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/atd_cache/iommu_atd_ptc_mtlb_upd_cabin_wrap.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_atd/atd_cache/atd_cache/iommu_atd_ptc_top.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/iommu_acd_pkg.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/iommu_acd.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/iommu_acd_generate.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/iommu_acd_ram_generic.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/bus_handler/iommu_acd_bus_handler_w_buf.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/bus_handler/iommu_acd_bus_handler_trans_arb.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/bus_handler/iommu_acd_bus_handler_queue_entry_update.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/bus_handler/iommu_acd_bus_handler_mst_intf.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/bus_handler/iommu_acd_bus_handler_top.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/bus_handler/iommu_acd_bus_handler_trans_queue.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/bus_handler/iommu_acd_bus_handler_trans_queue_entry.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/bus_handler/iommu_acd_bus_handler_idx_fifo.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/bus_handler/iommu_acd_bus_handler_mrif_agent.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/bus_handler/iommu_acd_bus_handler_4k_boundary_check.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/bus_handler/iommu_acd_bus_handler_r_buf.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/bus_handler/iommu_acd_bus_handler_b_buf.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/bus_handler/iommu_acd_bus_handler_bar_queue_entry.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/bus_handler/iommu_acd_bus_handler_slv_err.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/bus_handler/iommu_acd_bus_handler_slv_intf.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/bus_handler/iommu_acd_bus_handler_regslice.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/tc_if/iommu_acd_tc_if.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/tc_if/iommu_acd_c2t_if.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/tc_if/iommu_acd_t2c_if.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/translate_unit/iommu_acd_mtlb_lkp_cabin_wrap.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/translate_unit/iommu_acd_mtlb_tag_hit.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/translate_unit/iommu_acd_mtlb_plru.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/translate_unit/iommu_multi_bit_1_check.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/translate_unit/iommu_acd_translate_unit.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/translate_unit/iommu_acd_mtlb_inv_cabin_wrap.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/translate_unit/iommu_acd_main_tlb.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/translate_unit/iommu_acd_mtlb_bank.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/translate_unit/iommu_acd_mtlb_bank_top.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/translate_unit/iommu_acd_mtlb_ecc.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/translate_unit/iommu_acd_tlb_wrap.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/translate_unit/iommu_acd_micro_tlb_tag_hit.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/translate_unit/iommu_acd_mtlb_upd_cabin_wrap.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/translate_unit/iommu_acd_mtlb_idx.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/translate_unit/iommu_acd_mtlb_ready_mux.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/translate_unit/iommu_acd_mtlb_ram_wrap.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/translate_unit/iommu_acd_micro_tlb.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/translate_unit/iommu_acd_tlb_queue.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/translate_unit/iommu_acd_tlb_queue_entry.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/translate_unit/iommu_acd_micro_tlb_entry_update.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/translate_unit/iommu_acd_micro_tlb_inv_hit.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/translate_unit/iommu_acd_micro_tlb_plru.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/cfg_ctrl_wrap/iommu_acd_ptw.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/cfg_ctrl_wrap/iommu_acd_cfg.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/cfg_ctrl_wrap/iommu_acd_int.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/cfg_ctrl_wrap/iommu_acd_inv.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/cfg_ctrl_wrap/iommu_acd_cfg_ctrl_wrap.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/cfg_ctrl_wrap/iommu_acd_ptwackfilter.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/cfg_ctrl_wrap/iommu_acd_fault.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/dbg_trace/iommu_acd_dbg.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/dbg_trace/iommu_acd_mon_unit.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/hpm_ctl/iommu_acd_hpm_bus_handler.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/hpm_ctl/iommu_acd_hpm_tlbqueue.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/hpm_ctl/iommu_acd_hpm_tlbwrap.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/hpm_ctl/iommu_acd_hpm_top.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/hpm_ctl/iommu_acd_hpm_translate_unit.sv
sed -i 's/parameter int unsigned/parameter/g' rtl_acd/hpm_ctl/iommu_acd_riscv_hpm_cnt.sv
