# This workflow is for misc non-parallelizable tests / checks related to EMU
name: EMU Misc Test

on:
  push:
    branches: [ kunminghu-v3 ]
  pull_request:
    branches: [ kunminghu-v3 ]

env:
  # Set common environment variables for all jobs
  NOOP_HOME: ${{ github.workspace }}
  NEMU_HOME: /nfs/home/share/ci-workloads/NEMU
  AM_HOME: /nfs/home/share/ci-workloads/nexus-am
  WAVE_HOME: /nfs/home/ci-runner/xs-wave/${{ github.run_number }}
  PERF_HOME: /nfs/home/ci-runner/xs-perf/${{ github.run_number }}
  GCPT_RESTORE_BIN: /nfs/home/share/ci-workloads/fix-gcpt/gcpt.bin

jobs:
  changes:
    name: Changes Detection
    permissions:
      pull-requests: read
    runs-on: ubuntu-latest
    outputs:
      core: ${{ steps.filter.outputs.core }}
    steps:
      - uses: actions/checkout@v6
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          predicate-quantifier: 'every'
          filters: .github/filters.yaml

  ### Misc Tests
  # NOTE: These tests may be built and ran both on 'builder' machines, this might be confusing.
  #       The reason is that we dont want a complex builder-runner workflow like EMU Performance Test,
  #       and these tests may consume ~16 threads verlator, while 'runner' label is designed to be used with single-thread gsim,
  #       so we just run them on 'builder' to ensure enough resource.

  # GSIM functional test
  # TODO: maybe didn't need this as we're using gsim for EMU Performance Test
  # TODO: maybe move to gsim repo?
  emu-gsim:
    name: EMU - GSIM
    needs: changes
    if: ${{ needs.changes.outputs.core == 'true' }}
    runs-on:
      - builder
      - node # Run on node servers for the moment, as gsim is having performance issue on open servers
    timeout-minutes: 900
    continue-on-error: false
    steps:
      - name: Cleanup orphan EMU
        run: |
          pkill -9 -e -f ${GITHUB_WORKSPACE}/build/emu || true
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true
      - name: Init
        run: |
          mkdir -p ${WAVE_HOME} ${PERF_HOME}
          make init-force
          python3 ${GITHUB_WORKSPACE}/scripts/xiangshan.py --clean
      - name: Build GSIM emu
        run: |
          python3 ${GITHUB_WORKSPACE}/scripts/xiangshan.py --build \
            --emulator gsim \
            --yaml-config ${GITHUB_WORKSPACE}/src/main/resources/config/Default.yml \
            --with-dramsim3 --dramsim3 /nfs/home/share/ci-workloads/DRAMsim3 \
            --pgo ${GITHUB_WORKSPACE}/ready-to-run/coremark-2-iteration.bin --llvm-profdata llvm-profdata \
            --trace-fst
      - name: GSIM Test - Linux
        run: |
          python3 ${GITHUB_WORKSPACE}/scripts/xiangshan.py \
            --wave-dump ${WAVE_HOME} \
            --numa --threads 1 \
            --ci linux-hello-opensbi \
            2> stderr.log
          cat stderr.log | sort

  # CHI Release config test
  emu-chi:
    name: EMU - CHI
    needs: changes
    if: ${{ needs.changes.outputs.core == 'true' }}
    runs-on: builder
    timeout-minutes: 900
    continue-on-error: false
    steps:
      - name: Cleanup orphan EMU
        run: |
          pkill -9 -e -f ${GITHUB_WORKSPACE}/build/emu || true
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true
      - name: Init
        run: |
          mkdir -p ${WAVE_HOME} ${PERF_HOME}
          make init-force
          python3 ${GITHUB_WORKSPACE}/scripts/xiangshan.py --clean
      - name: Build CHIConfig Release EMU
        run: |
          python3 ${GITHUB_WORKSPACE}/scripts/xiangshan.py --build \
            --emulator verilator --threads 8 \
            --config CHIConfig --release \
            --trace-fst
      - name: CHIConfig Test - Linux
        run: |
          python3 ${GITHUB_WORKSPACE}/scripts/xiangshan.py \
            --wave-dump ${WAVE_HOME} \
            --threads 8 --numa \
            --ci linux-hello-opensbi \
            2> stderr.log
          cat stderr.log | sort
      - name: CHIConfig Test - Iopmp
        run: |
          python3 ${GITHUB_WORKSPACE}/scripts/xiangshan.py \
            --wave-dump ${WAVE_HOME} \
            --threads 8 --numa \
            --no-diff \
            --ci iopmp-test \
          2> stderr.log
          cat stderr.log | sort

  # Simfrontend test
  emu-simfrontend:
    name: EMU - SimFrontend
    needs: changes
    if: ${{ needs.changes.outputs.core == 'true' }}
    runs-on: builder
    timeout-minutes: 900
    continue-on-error: false
    steps:
      - name: Cleanup orphan EMU
        run: |
          pkill -9 -e -f ${GITHUB_WORKSPACE}/build/emu || true
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true
      - name: Init
        run: |
          mkdir -p ${WAVE_HOME} ${PERF_HOME}
          make init-force
          python3 ${GITHUB_WORKSPACE}/scripts/xiangshan.py --clean
      - name: Build Simfrontend EMU
        run: |
          python3 ${GITHUB_WORKSPACE}/scripts/xiangshan.py --build \
            --emulator verilator --threads 8 \
            --yaml-config ${GITHUB_WORKSPACE}/src/main/resources/config/Default.yml \
            --with-dramsim3 --dramsim3 /nfs/home/share/ci-workloads/DRAMsim3 \
            --simfrontend \
            --trace-fst
      - name: Simfrontend Test - SPEC06 astar
        id: astar_simfrontend
        shell: bash
        run: |
          python3 ${GITHUB_WORKSPACE}/scripts/xiangshan.py \
            --wave-dump ${WAVE_HOME} \
            --numa --threads 8 \
            --max-instr 5000000 \
            --ci astar \
            --instr-trace astar \
            --gcpt-restore-bin ${GCPT_RESTORE_BIN} \
            2> stderr.log | tee stdout.log
          cat stderr.log | sort | tee ${PERF_HOME}/astar_simfrontend.log
          echo "IPC=$(grep -oP 'IPC = \K\d+\.\d+' stdout.log)" >> $GITHUB_OUTPUT
      - name: Simfrontend Test - SPEC06 milc
        id: milc_simfrontend
        shell: bash
        run: |
          python3 ${GITHUB_WORKSPACE}/scripts/xiangshan.py \
            --wave-dump ${WAVE_HOME} \
            --numa --threads 8 \
            --max-instr 5000000 \
            --ci milc \
            --instr-trace milc \
            --gcpt-restore-bin ${GCPT_RESTORE_BIN} \
            2> stderr.log | tee stdout.log
          cat stderr.log | sort | tee ${PERF_HOME}/milc_simfrontend.log
          echo "IPC=$(grep -oP 'IPC = \K\d+\.\d+' stdout.log)" >> $GITHUB_OUTPUT
      - name: Simfrontend Test - SPEC06 xalancbmk
        id: xalancbmk_simfrontend
        shell: bash
        run: |
          python3 ${GITHUB_WORKSPACE}/scripts/xiangshan.py \
            --wave-dump ${WAVE_HOME} \
            --numa --threads 8 \
            --max-instr 5000000 \
            --ci xalancbmk \
            --instr-trace xalancbmk \
            --gcpt-restore-bin ${GCPT_RESTORE_BIN} \
            2> stderr.log | tee stdout.log
          cat stderr.log | sort | tee ${PERF_HOME}/xalancbmk_simfrontend.log
          echo "IPC=$(grep -oP 'IPC = \K\d+\.\d+' stdout.log)" >> $GITHUB_OUTPUT
      - name: Generate summary
        if: always()
        run: |
          echo "## Emu - SimFrontend summary" >> $GITHUB_STEP_SUMMARY
          echo "| Testcase  | IPC |" >> $GITHUB_STEP_SUMMARY
          echo "| --------- | --- |" >> $GITHUB_STEP_SUMMARY
          echo "| astar     | ${{ steps.astar_simfrontend.outputs.IPC }} |" >> $GITHUB_STEP_SUMMARY
          echo "| milc      | ${{ steps.milc_simfrontend.outputs.IPC }} |" >> $GITHUB_STEP_SUMMARY
          echo "| xalancbmk | ${{ steps.xalancbmk_simfrontend.outputs.IPC }} |" >> $GITHUB_STEP_SUMMARY

  # Multi-core test
  emu-mc:
    name: EMU - MC
    needs: changes
    if: ${{ needs.changes.outputs.core == 'true' }}
    runs-on: builder
    timeout-minutes: 900
    continue-on-error: false
    steps:
      - name: Cleanup orphan EMU
        run: |
          pkill -9 -e -f ${GITHUB_WORKSPACE}/build/emu || true
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true
      - name: Init
        run: |
          mkdir -p ${WAVE_HOME} ${PERF_HOME}
          make init-force
          python3 ${GITHUB_WORKSPACE}/scripts/xiangshan.py --clean
      - name: Build MC EMU
        run: |
          python3 ${GITHUB_WORKSPACE}/scripts/xiangshan.py --build \
            --emulator verilator --threads 16 \
             --num-cores 2 --emu-optimize "" \
             --with-dramsim3 --dramsim3 /nfs/home/share/ci-workloads/DRAMsim3 \
             --pgo /nfs/home/share/ci-workloads/linux-hello-smp-new/bbl.bin --llvm-profdata llvm-profdata \
             --trace-fst --trace-all
      - name: MC Test - Basics
        run: |
          python3 ${GITHUB_WORKSPACE}/scripts/xiangshan.py \
            --wave-dump ${WAVE_HOME} \
            --numa --threads 16 \
            --diff ./ready-to-run/riscv64-nemu-interpreter-dual-so \
            --ci mc-tests 2> /dev/zero
      - name: MC Test - SMP Linux
        run: |
          python3 ${GITHUB_WORKSPACE}/scripts/xiangshan.py \
            --wave-dump ${WAVE_HOME} \
            --numa --threads 16 \
            --diff ./ready-to-run/riscv64-nemu-interpreter-dual-so \
            --ci linux-hello-smp-new 2> /dev/null

  # SIMV basics test
  simv-basics:
    name: SIMV - Basics
    needs: changes
    if: ${{ needs.changes.outputs.core == 'true' }}
    runs-on: eda
    continue-on-error: false
    timeout-minutes: 900
    steps:
      - name: Remote Connection Test
        run: |
          ssh -tt eda01 "echo test-ok"
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true
      - name: Init
        run: |
          mkdir -p ${WAVE_HOME} ${PERF_HOME}
          make init-force
          python3 ${GITHUB_WORKSPACE}/scripts/xiangshan.py --clean
      - name: Generate Verilog for VCS
        run: |
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --vcs-gen --xprop
      - name: Build SIMV on Remote
        run: |
          ssh -tt eda01 "python3 `echo $GITHUB_WORKSPACE`/scripts/xiangshan.py --vcs-build --xprop"
      - name: V Extension Test - rvv-test
        run: |
          ssh -tt eda01 "python3 `echo $GITHUB_WORKSPACE`/scripts/xiangshan.py --wave-dump `echo $WAVE_HOME` --ci-vcs rvv-test"
      - name: Simple Test - CoreMark 1 iteration
        run: |
          ssh -tt eda01 "python3 `echo $GITHUB_WORKSPACE`/scripts/xiangshan.py --wave-dump `echo $WAVE_HOME` --ci-vcs coremark-1-iteration"
      # - name: Simple Test - MicroBench
      #   run: |
      #     ssh -tt eda01 "python3 `echo $GITHUB_WORKSPACE`/scripts/xiangshan.py --wave-dump `echo $WAVE_HOME` --ci-vcs microbench --am=/nfs/home/share/ci-workloads/nexus-am/"
      # - name: Basic Test - cputest
      #   run: |
      #     ssh -tt eda01 "python3 `echo $GITHUB_WORKSPACE`/scripts/xiangshan.py --ci-vcs cputest --am=/nfs/home/share/ci-workloads/nexus-am/" 2> /dev/zero
      # - name: Simple Test - CoreMark
      #   run: |
      #     ssh -tt eda01 "python3 `echo $GITHUB_WORKSPACE`/scripts/xiangshan.py --ci-vcs coremark --am=/nfs/home/share/ci-workloads/nexus-am/ --timeout 1800" 2> /dev/zero
      # - name: System Test - Linux
      #   run: |
      #     ssh -tt eda01 "python3 `echo $GITHUB_WORKSPACE`/scripts/xiangshan.py --ci-vcs linux-hello-opensbi --timeout 7200" 2> /dev/zero

  ### Code quality checks
  # Check if docker image can be built
  check-docker:
    name: Check Docker
    needs: changes
    if: ${{ needs.changes.outputs.core == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    continue-on-error: true
    steps:
      - uses: actions/checkout@v6
      - name: Build docker image
        run: make image
      - name: Compile generator JAR
        run: make test-jar

  # Check verilog generation and check wiring/interface
  check-verilog:
    name: Check Verilog
    needs: changes
    if: ${{ needs.changes.outputs.core == 'true' }}
    runs-on: builder
    timeout-minutes: 900
    continue-on-error: false
    steps:
      - name: Cleanup orphan EMU
        run: |
          pkill -9 -e -f ${GITHUB_WORKSPACE}/build/emu || true
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          submodules: true
      - name: Init
        run: |
          mkdir -p ${WAVE_HOME} ${PERF_HOME}
          make init-force
          python3 ${GITHUB_WORKSPACE}/scripts/xiangshan.py --clean
      - name: Check top wiring
        run:
          bash .github/workflows/check-usage.sh "BoringUtils" $GITHUB_WORKSPACE
      - name: Generate standalone devices for TL
        run: |
          make StandAloneCLINT DEVICE_BASE_ADDR=0x38000000 DEVICE_ADDR_WIDTH=32 DEVICE_DATA_WIDTH=64 DEVICE_TL=1 DEVICE_PREFIX=CLINT_
          make StandAloneSYSCNT DEVICE_BASE_ADDR=0x38040000 DEVICE_ADDR_WIDTH=32 DEVICE_DATA_WIDTH=64 DEVICE_TL=1 DEVICE_PREFIX=CLINT_
          make StandAloneDebugModule DEVICE_BASE_ADDR=0x38020000 DEVICE_ADDR_WIDTH=32 DEVICE_DATA_WIDTH=64 DEVICE_TL=1 DEVICE_PREFIX=DM_
          make StandAlonePLIC DEVICE_BASE_ADDR=0x3C000000 DEVICE_ADDR_WIDTH=32 DEVICE_DATA_WIDTH=64 DEVICE_TL=1 DEVICE_PREFIX=PLIC_
          make clean
      - name: Generate standalone devices for AXI4
        run: |
          make StandAloneCLINT DEVICE_BASE_ADDR=0x38000000 DEVICE_ADDR_WIDTH=32 DEVICE_DATA_WIDTH=64 DEVICE_TL=0 DEVICE_PREFIX=CLINT_
          make StandAloneSYSCNT DEVICE_BASE_ADDR=0x38040000 DEVICE_ADDR_WIDTH=32 DEVICE_DATA_WIDTH=64 DEVICE_TL=0 DEVICE_PREFIX=CLINT_
          make StandAloneDebugModule DEVICE_BASE_ADDR=0x38020000 DEVICE_ADDR_WIDTH=32 DEVICE_DATA_WIDTH=64 DEVICE_TL=0 DEVICE_PREFIX=DM_
          make StandAlonePLIC DEVICE_BASE_ADDR=0x3C000000 DEVICE_ADDR_WIDTH=32 DEVICE_DATA_WIDTH=64 DEVICE_TL=0 DEVICE_PREFIX=PLIC_
          make clean
      - name: Generate XSNoCTop verilog file
        run: |
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --generate --config XSNoCTopConfig
      - name: Check XSNoCTop verilog
        run: |
          python3 $GITHUB_WORKSPACE/.github/workflows/check_verilog.py build/rtl
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --clean
      - name: Generate verilog file
        run:
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --generate --num-cores 2
      - name: Check verilog
        run: |
          python3 $GITHUB_WORKSPACE/.github/workflows/check_verilog.py build/rtl
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --clean
      - name: Generate chirrtl only
        run: |
          make sim-verilog CHISEL_TARGET=chirrtl
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --clean
      - name: Build TLMinimalConfig Release EMU
        run: |
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --build \
            --threads 8 --config TLMinimalConfig --release --trace-fst
      - name: Run TLMinimalConfig - Linux
        run: |
          python3 $GITHUB_WORKSPACE/scripts/xiangshan.py --wave-dump $WAVE_HOME --threads 8 --numa --ci linux-hello-opensbi 2> perf.log
          cat perf.log | sort
      - name: Generate NOC XiangShan
        run: |
          make clean
          make verilog CONFIG=XSNoCDiffTopConfig
      - name: Generate NOC Difftest
        run: |
          export NOOP_HOME=$GITHUB_WORKSPACE/difftest
          cd difftest && make difftest_verilog PROFILE=../build/generated-src/difftest_profile.json NUM_CORES=2 CONFIG=ZESNH
      - name: Check interface between XSNoCDiffTop and Difftest
        run: |
          cd $GITHUB_WORKSPACE
          python3 difftest/scripts/st_tools/interface.py build/rtl/SimTop.sv --interface build/difftest-interface.sv --path_level 4
          sed 's|^|build/rtl/|' difftest/build/rtl/filelist.f | xargs -d '\n' rm -f
          rm -rf build/rtl/DiffExt*
          verilator --lint-only -Wno-fatal -Wno-MODDUP -Wno-lint --top-module XSDiffTopChecker \
            build/XSDiffTopChecker.sv build/difftest-interface.sv build/rtl/*.sv build/rtl/*.v difftest/build/rtl/*.sv difftest/build/rtl/*.v\
            -Idifftest/build/generated-src/ -LDFLAGS -"lreadline"

  # Check submodules must be merged to its default branch
  check-submodules:
    name: Check Submodules
    needs: changes
    if: ${{ needs.changes.outputs.core == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    continue-on-error: false
    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'true'
          fetch-depth: '0'
      - name: Check rocket-chip
        run: cd rocket-chip && git fetch --all && git merge-base --is-ancestor `git rev-parse HEAD` origin/master
      - name: Check difftest
        run: cd difftest && git fetch --all && git merge-base --is-ancestor `git rev-parse HEAD` origin/master
      - name: Check ready-to-run
        run: cd ready-to-run && git fetch --all && git merge-base --is-ancestor `git rev-parse HEAD` origin/master
      - name: Check huancun
        run: cd huancun && git fetch --all && git merge-base --is-ancestor `git rev-parse HEAD` origin/master
      - name: Check utility
        run: cd utility && git fetch --all && git merge-base --is-ancestor `git rev-parse HEAD` origin/master
      - name: Check yunsuan
        run: cd yunsuan && git fetch --all && git merge-base --is-ancestor `git rev-parse HEAD` origin/kunminghu-v3
      - name: Check coupledL2
        run: cd coupledL2 && git fetch --all && git merge-base --is-ancestor `git rev-parse HEAD` origin/master
      - name: Check openLLC
        run: cd openLLC && git fetch --all && git merge-base --is-ancestor `git rev-parse HEAD` origin/master
      - name: Check ChiselAIA
        run: cd ChiselAIA && git fetch --all && git merge-base --is-ancestor `git rev-parse HEAD` origin/kunminghu-v3

  # Check format
  check-format:
    name: Check Format
    needs: changes
    if: ${{ needs.changes.outputs.core == 'true' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    continue-on-error: false
    steps:
      - uses: actions/checkout@v6
      - name: Install Java
        uses: actions/setup-java@v5
        with:
          distribution: 'graalvm'
          java-version: '21'
      - name: Install mill
        env:
          MILL_VERSION: 1.0.4
        run: |
          mkdir -p ~/.local/bin
          curl -L https://repo1.maven.org/maven2/com/lihaoyi/mill-dist/${MILL_VERSION}/mill-dist-${MILL_VERSION}-mill.sh -o ~/.local/bin/mill
          chmod +x ~/.local/bin/mill
      - name: Run check-format
        run: |
          export PATH=~/.local/bin:$PATH
          make check-format
