# This file describes the GitHub Actions workflow for continuous integration of XS Core.
name: XS Core CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Verilog
    steps:
       - uses: actions/checkout@v2
        
       - name: Set Up Mill
         uses: jodersky/setup-mill@master
         with:
           mill-version: 0.7.3
         
       - name: Complile
         run: make verilog
