# This file describes the GitHub Actions workflow for continuous integration of XS Core.
name: XS Core CI

on:
  push:
    branches: []
  pull_request:
    branches: []

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate Verilog
    steps:
       - run: echo "Do nothing!"
