name: Performance Regression V3

on:
  schedule:
    #run at 4:00 UTC (12:00 UTC+8) on Friday
    - cron: '0 4 * * 5'
  workflow_dispatch:
    inputs:
      test_branch:
        description: Only fill this option when retrying with the same branch/commit as previous attempts
        required: false
        type: string
        default: kunminghu-v3

jobs:
  run:
    name: Run Performance Test
    uses: ./.github/workflows/perf-template.yml
    with:
      test_branch: ${{ github.event.inputs.test_branch }}
      perf_report_dir: /nfs/home/cirunner/perf-report-kmhv3
      servers: all

  report:
    name: Generate Report
    needs: run
    runs-on: perf
    steps:
      - uses: actions/checkout@v6
      - name: Upload report
        uses: actions/upload-artifact@v7
        with:
          name: score
          path: ${{ needs.run.outputs.SCORE_FILE }}
